cmake_minimum_required(VERSION 3.20)
foreach(required APP FIXTURE WORK)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} required")
  endif()
endforeach()
find_program(SQLITE sqlite3 REQUIRED)
file(MAKE_DIRECTORY "${WORK}")
file(READ "${FIXTURE}" config)
get_filename_component(config_dir "${FIXTURE}" DIRECTORY)
string(REPLACE "source.architecture-docs.root = ./source-docs" "source.architecture-docs.root = ${config_dir}/source-docs" config "${config}")
file(WRITE "${WORK}/original.conf" "${config}")
file(WRITE "${WORK}/prospective.conf" "${config}\nsource.smoke.connector = folder\nsource.smoke.root = ${config_dir}/source-docs\nsource.smoke.include = **/*.txt\nsource.smoke.stable_key = relative-path\nsource.smoke.privacy = public\nsource.smoke.retain_raw_artifact = true\n")
string(REPLACE "worker.processes = 1" "worker.processes = 2" operational "${config}")
file(WRITE "${WORK}/operational.conf" "${operational}")
function(sql query output)
  execute_process(COMMAND "${SQLITE}" -bail "${db}" "${query}" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Fixture SQL: ${err}")
  endif()
  set(${output} "${out}" PARENT_SCOPE)
endfunction()
function(cli policy access output)
  execute_process(COMMAND "${APP}" --library "${library}" --config-file "${WORK}/${policy}.conf" --profile it-architecture-profile --format json --access "${access}" ${ARGN} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
  file(APPEND "${WORK}/commands.log" "${case}: ${policy} ${ARGN}\nexit=${rc}\n${out}${err}\n")
  set(${output} "${out}" PARENT_SCOPE)
  set(last_rc "${rc}" PARENT_SCOPE)
endfunction()
# No provider command runs. Synthetic old state is confined to fresh tiny fixtures.
foreach(case complete stale_deadline unknown_terminal unknown_paused queued reserved live terminal_reserved terminal_live intentional_pause)
  set(library "${WORK}/${case}")
  set(db "${library}/library.sqlite")
  cli(original admin out library init)
  if(NOT last_rc EQUAL 0)
    message(FATAL_ERROR "Init failed: ${out}")
  endif()
  set(parent paused)
  set(item dead_letter)
  if(case MATCHES "^(complete|terminal_reserved|terminal_live)$")
    set(parent completed_with_errors)
  elseif(case STREQUAL unknown_terminal)
    set(parent completed_with_errors)
  elseif(case STREQUAL queued)
    set(parent queued)
    set(item queued)
  endif()
  sql("PRAGMA foreign_keys=ON; INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at) SELECT 'target','probe','{}',config_snapshot_id,'${parent}',10,0,0,0,0,'fixture','fixture' FROM config_snapshots; INSERT INTO job_items(item_id,job_id,item_type,state,priority,idempotency_key,input_hash,input_json,created_at,updated_at) VALUES('item','target','embedding','${item}',1,'item','input','{}','fixture','fixture');" ignored)
  if(case MATCHES "^(stale_deadline|unknown_terminal|unknown_paused)$")
    sql("INSERT INTO maintenance_runs(run_id,expected_generation,config_snapshot_id,mode,state,plan_digest,canonical_plan,created_at) SELECT 'target',g.published_generation,j.config_snapshot_id,'automatic','incomplete','probe','{}','fixture' FROM jobs j CROSS JOIN library_meta g; INSERT INTO maintenance_windows(window_id,run_id,job_id,state,deadline_epoch,policy_json,policy_fingerprint,created_epoch,closed_epoch) VALUES('target','target','target','deadline',1,'{}','policy',1,2);" ignored)
  endif()
  if(case MATCHES "^unknown")
    sql("INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,started_at,completed_at) VALUES('attempt','item','old-worker',1,'input','cannot begin provider receipt','dead_letter','fixture','fixture'); INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at) VALUES('target','item','attempt','provider-intent','{}','fixture');" ignored)
  elseif(case MATCHES "^(reserved|terminal_reserved)$")
    sql("UPDATE jobs SET reserved_calls=1;" ignored)
  elseif(case MATCHES "^(live|terminal_live)$")
    sql("INSERT INTO runtime_instances(instance_id,kind,parent_instance_id,host_id,pid,process_start_token,executable_identity,mode,job_filter,state,started_at,heartbeat_at) VALUES('live','worker',NULL,'fixture',0,'','fixture','follow','target','starting',unixepoch(),unixepoch());" ignored)
  endif()
  sql("PRAGMA integrity_check; SELECT count(*) FROM pragma_foreign_key_check;" integrity)
  if(NOT integrity STREQUAL "ok\n0")
    message(FATAL_ERROR "Bad fixture ${case}: ${integrity}")
  endif()
  cli(original diagnose status job status target)
  string(JSON projected GET "${status}" records 0 fields state)
  foreach(policy operational prospective)
    cli(${policy} plan plan config plan --reason "Configuration barrier investigation")
    string(JSON payload GET "${plan}" records 0 fields canonical_plan)
    string(JSON digest GET "${plan}" records 0 fields digest)
    string(JSON active GET "${payload}" active_jobs)
    set(last_rc "not-applied")
    # Exercise prospective transitions and blocked operational controls.
    if(active GREATER 0 OR policy STREQUAL prospective)
      cli(${policy} admin applied config apply --plan-json "${payload}" --expect-digest "${digest}")

    endif()
    message(STATUS "${case} ${policy}: raw=${parent}; projected=${projected}; active=${active}; apply_exit=${last_rc}")
    if(policy STREQUAL prospective AND last_rc EQUAL 0)
      sql("SELECT (SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM jobs)||':'||(SELECT count(*) FROM job_items)||':'||(SELECT config_snapshot_id=(SELECT current_config_snapshot_id FROM library_config_state) FROM jobs)||':'||(SELECT published_generation FROM library_meta);" preserved)
      if(NOT preserved STREQUAL "0:1:1:0:1")
        message(FATAL_ERROR "Prospective apply rewrote old provenance or queued work: ${preserved}")
      endif()
    endif()
  endforeach()
  if(case MATCHES "^unknown")
    foreach(repeat RANGE 1 3)
      cli(original control cancel job cancel target --reason "Fixture cancellation retains unknown history")
      sql("SELECT state FROM jobs;" raw)
      cli(original diagnose status job status target)
      string(JSON state GET "${status}" records 0 fields state)
      message(STATUS "${case} cancel ${repeat}: raw=${raw}; projected=${state}")
    endforeach()
    sql("SELECT count(*) FROM attempts; SELECT count(*) FROM job_events WHERE event_type='provider-intent'; SELECT count(*) FROM job_events WHERE event_type='provider-response'; SELECT count(*) FROM provider_runs;" history)
    if(NOT history STREQUAL "1\n1\n0\n0")
      message(FATAL_ERROR "Unknown history changed: ${history}")
    endif()
  endif()
endforeach()
