#!/usr/bin/env python3
"""Build/release tooling, never product orchestration. Uses installed RAG bytes."""
import argparse
import base64
import hashlib
import json
import os
from pathlib import Path, PurePosixPath, PureWindowsPath
import re
import shlex
import shutil
import subprocess
import tempfile
import zipfile

ROOT = Path(__file__).resolve().parents[2]
APPLE_SECRETS = (
    "APPLE_DEVELOPER_ID_CERTIFICATE_BASE64", "APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD",
    "APPLE_DEVELOPER_ID_IDENTITY", "APPLE_DEVELOPER_ID_INSTALLER_CERTIFICATE_BASE64",
    "APPLE_DEVELOPER_ID_INSTALLER_CERTIFICATE_PASSWORD", "APPLE_DEVELOPER_ID_INSTALLER_IDENTITY",
    "APPLE_ID", "APPLE_APP_SPECIFIC_PASSWORD", "APPLE_TEAM_ID",
)


def run(*args, **kwargs):
    try:
        return subprocess.run([str(a) for a in args], check=True, **kwargs)
    except subprocess.CalledProcessError as error:
        # Signing commands contain credentials: never echo their argument list.
        raise RuntimeError(f"{args[0]} failed (exit {error.returncode})") from None


def digest(path):
    with Path(path).open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def apple_credentials(env):
    missing = [key for key in APPLE_SECRETS if not env.get(key, "").strip()]
    return not missing, missing


def local_file(root, name):
    relative = PurePosixPath(name)
    path = root / name
    if relative.is_absolute() or ".." in relative.parts or "\\" in name or not path.is_file() or path.is_symlink() or not path.resolve().is_relative_to(root.resolve()):
        raise ValueError(f"Missing/nonlocal declared file: {name}")
    return path


def provider_manifests(directory, refresh=False):
    native_path = directory / "rxllama.native.json"
    runtime_path = directory / "rxllama.runtime.json"
    native, runtime = (json.loads(p.read_text()) for p in (native_path, runtime_path))
    for key in ("version", "provider", "platform", "arch", "engine"):
        if native[key] != runtime[key]:
            raise ValueError(f"Provider identity mismatch: {key}")
    def hashes(entries):
        for row in entries:
            actual = digest(local_file(directory, row["path"]))
            if not refresh and row["sha256"] != actual:
                raise ValueError(f"Provider hash mismatch: {row['path']}")
            row["sha256"] = actual
    # Validate the complete declared file set before changing a manifest.
    hashes(native["link_libraries"] + native["runtime_files"])
    hashes(runtime["backends"])
    if refresh:
        runtime_path.write_text(json.dumps(runtime, separators=(",", ":")) + "\n")
        hashes(native["runtime_files"])
        native_path.write_text(json.dumps(native, separators=(",", ":")) + "\n")


def write_inventory(prefix, version, commit, crexx_commit, platform, signing):
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:[-+][A-Za-z0-9.-]+)?", version):
        raise ValueError("Invalid release version")
    if not all(re.fullmatch(r"[a-f0-9]{40}", c) for c in (commit, crexx_commit)):
        raise ValueError("Release inputs must use full commit identities")
    if platform not in ("windows-x64", "macos-arm64", "macos-x86_64"):
        raise ValueError("Unknown release platform")
    files = {}
    for path in sorted(prefix.rglob("*")):
        if path.is_symlink():
            raise ValueError(f"Payload must contain complete local files: {path}")
        if path.is_file() and path != prefix / "release.json":
            files[path.relative_to(prefix).as_posix()] = digest(path)
    (prefix / "release.json").write_text(json.dumps(dict(
        product="crexxrag", version=version, source_commit=commit,
        crexx_commit=crexx_commit, platform=platform, signing=signing, files=files,
    ), indent=2) + "\n")


def verify_inventory(prefix, installed=False):
    doc = json.loads((prefix / "release.json").read_text())
    actual = {p.relative_to(prefix).as_posix() for p in prefix.rglob("*") if p.is_file() and p != prefix / "release.json"}
    if installed and doc["platform"] == "windows-x64":
        actual.discard("Uninstall.exe")  # Generated by NSIS, not part of its input ZIP.
    if actual != set(doc["files"]):
        raise ValueError("Release file set differs from inventory")
    for name, expected in doc["files"].items():
        if digest(local_file(prefix, name)) != expected:
            raise ValueError(f"Release hash mismatch: {name}")
    provider_manifests(prefix / "bin")
    return doc


def archive(prefix, output):
    verify_inventory(prefix)
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as z:
        for path in sorted(prefix.rglob("*")):
            if path.is_file():
                z.write(path, path.relative_to(prefix))


def unpack(archive_path, destination):
    with zipfile.ZipFile(archive_path) as z:
        names = set()
        for row in z.infolist():
            path = PurePosixPath(row.filename)
            if row.filename in names or PureWindowsPath(row.filename).drive or path.is_absolute() or ".." in path.parts or "\\" in row.filename or (row.external_attr >> 16) & 0o170000 == 0o120000:
                raise ValueError("Nonlocal ZIP member")
            names.add(row.filename)
        z.extractall(destination)
        for row in z.infolist():
            mode = (row.external_attr >> 16) & 0o777
            if mode:
                (destination / row.filename).chmod(mode)
    return verify_inventory(destination)


def checksums(output):
    for path in sorted(output.iterdir()):
        if path.suffix in (".zip", ".pkg", ".exe"):
            path.with_name(path.name + ".sha256").write_text(f"{digest(path)}  {path.name}\n")


def apple_sign_payload(prefix, keychain):
    env = os.environ
    password = os.urandom(24).hex()
    run("security", "create-keychain", "-p", password, keychain)
    run("security", "set-keychain-settings", "-lut", "21600", keychain)
    run("security", "unlock-keychain", "-p", password, keychain)
    for kind in ("", "INSTALLER_"):
        cert = keychain.parent / (kind + "certificate.p12")
        cert.write_bytes(base64.b64decode(env[f"APPLE_DEVELOPER_ID_{kind}CERTIFICATE_BASE64"], validate=True))
        cert.chmod(0o600)
        run("security", "import", cert, "-k", keychain, "-P", env[f"APPLE_DEVELOPER_ID_{kind}CERTIFICATE_PASSWORD"], "-T", "/usr/bin/codesign", "-T", "/usr/bin/productbuild")
        cert.unlink()
    run("security", "set-key-partition-list", "-S", "apple-tool:,apple:", "-s", "-k", password, keychain, stdout=subprocess.DEVNULL)
    for path in sorted((prefix / "bin").iterdir()):
        if path.is_file() and "Mach-O" in subprocess.check_output(["file", "-b", str(path)], text=True):
            run("codesign", "--force", "--timestamp", "--options", "runtime", "--keychain", keychain, "--sign", env["APPLE_DEVELOPER_ID_IDENTITY"], path)
            run("codesign", "--verify", "--strict", path)
    provider_manifests(prefix / "bin", refresh=True)


def macos_installer(prefix, output, version, keychain=None):
    with tempfile.TemporaryDirectory(prefix="rag-pkg-") as temp:
        work = Path(temp)
        destination = work / "root/usr/local/lib/crexxrag"
        shutil.copytree(prefix, destination)
        links = work / "root/usr/local/bin"
        links.mkdir(parents=True)
        (links / "crexxrag").symlink_to("../lib/crexxrag/bin/crexxrag")
        component = work / "component.pkg"
        run("pkgbuild", "--root", work / "root", "--identifier", "org.crexx.crexxrag", "--version", re.split("[-+]", version)[0], "--install-location", "/", component)
        command = ["productbuild", "--package", component]
        if keychain:
            command += ["--sign", os.environ["APPLE_DEVELOPER_ID_INSTALLER_IDENTITY"], "--keychain", keychain, "--timestamp"]
        run(*command, output)
        if keychain:
            run("pkgutil", "--check-signature", output)
            run("xcrun", "notarytool", "submit", output, "--apple-id", os.environ["APPLE_ID"], "--password", os.environ["APPLE_APP_SPECIFIC_PASSWORD"], "--team-id", os.environ["APPLE_TEAM_ID"], "--wait", "--timeout", "30m")
            run("xcrun", "stapler", "staple", output)
            run("xcrun", "stapler", "validate", output)


def windows_installer(prefix, output, version, helper=None):
    exe = shutil.which("makensis") or shutil.which("makensis.exe")
    if not exe:
        raise ValueError("Install NSIS and add makensis to PATH")
    define = "/D" if os.name == "nt" else "-D"
    args = [exe, define + "RAG_PAYLOAD=" + str(prefix.resolve()), define + "RAG_OUTPUT=" + str(output.resolve()),
            define + "RAG_VERSION=" + version, define + "RAG_FILE_VERSION=" + re.split("[-+]", version)[0] + ".0"]
    if helper:
        args += [define + "RAG_SIGN_HELPER=" + str(helper), define + "RAG_SIGNED_PLUGINS=" + str(helper.parent / "plugins")]
    # Delete only packaged files; user libraries/configuration are never swept.
    with tempfile.TemporaryDirectory(prefix="rag-nsis-") as temp:
        uninstall = Path(temp) / "owned-files.nsh"
        def nsis(value):
            return value.replace("$", "$$").replace('"', '$\\"')
        files = sorted(p.relative_to(prefix) for p in prefix.rglob("*") if p.is_file())
        lines = ['Delete "$INSTDIR\\' + nsis(str(p).replace("/", "\\")) + '"' for p in files]
        directories = sorted({d for p in files for d in p.parents if d != Path(".")}, key=lambda p: len(p.parts), reverse=True)
        lines += ['RMDir "$INSTDIR\\' + nsis(str(p).replace("/", "\\")) + '"' for p in directories]
        uninstall.write_text("\n".join(lines) + "\n")
        run(*args, define + "RAG_UNINSTALL_FILES=" + str(uninstall), ROOT / "packaging/windows/crexxrag.nsi")


def package(args):
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="rag-release-") as temp:
        prefix = Path(temp) / "payload"
        shutil.copytree(args.prefix, prefix)
        if args.platform == "windows-x64":
            helper_dir = prefix / "share/crexxrag/installer"
            helper_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / "packaging/windows/update-user-path.ps1", helper_dir)
        provider_manifests(prefix / "bin")
        enabled, missing = apple_credentials(os.environ)
        enabled = enabled and args.platform.startswith("macos")
        state = "signed" if enabled else "unsigned"
        keychain = Path(temp) / "signing.keychain-db"
        try:
            if enabled:
                apple_sign_payload(prefix, keychain)
            elif args.platform.startswith("macos"):
                print("macOS signing/notarization skipped; missing: " + ", ".join(missing))
            write_inventory(prefix, args.version, args.commit, args.crexx_commit, args.platform, state)
            stem = f"crexxrag-{args.version}-{args.platform}-{state}"
            if args.platform.startswith("macos"):
                macos_installer(prefix, output / (stem + ".pkg"), args.version, keychain if enabled else None)
            else:
                windows_installer(prefix, output / (stem + "-setup.exe"), args.version)
            archive(prefix, output / (stem + ".zip"))
            checksums(output)
            if os.environ.get("GITHUB_STEP_SUMMARY"):
                with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as summary:
                    summary.write(f"### {args.platform}\n\nInstaller and ZIP: **{state}**. Source `{args.commit}`.\n")
                    if enabled:
                        summary.write("The macOS PKG is notarized and stapled; the ZIP contains the same signed payload.\n")
                    if missing and args.platform.startswith("macos"):
                        summary.write("Missing Apple settings: " + ", ".join(f"`{name}`" for name in missing) + ".\n")
        finally:
            if keychain.exists():
                run("security", "delete-keychain", keychain)


def sign_file(path):
    # Keep valid vendor signatures on the bundled Microsoft runtime DLLs.
    if subprocess.run(["osslsigncode", "verify", "-in", str(path)],
                      stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0:
        return
    run("jsign", "--storetype", "PKCS11", "--keystore", os.environ["PROVIDER"], "--alias", os.environ["CERTUM_ALIAS"], "--alg", "SHA-256", "--tsaurl", os.environ.get("TSA_URL", "http://time.certum.pl"), path)
    run("osslsigncode", "verify", "-in", path, stdout=subprocess.DEVNULL)


def windows_sign(args):
    for variable in ("PROVIDER", "CERTUM_ALIAS"):
        if not os.environ.get(variable):
            raise ValueError(f"Set {variable} for local Windows signing")
    if args.upload and not (args.repo and args.tag):
        raise ValueError("--upload requires --repo and --tag")
    args.output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="rag-windows-sign-") as temp:
        prefix = Path(temp) / "payload"
        meta = unpack(args.zip, prefix)
        if meta["product"] != "crexxrag" or meta["platform"] != "windows-x64" or meta["signing"] != "unsigned":
            raise ValueError("Expected the unsigned RAG Windows release ZIP")
        if args.upload:
            target = subprocess.check_output(["gh", "api", f"repos/{args.repo}/commits/{args.tag}", "--jq", ".sha"], text=True).strip()
            if target != meta["source_commit"]:
                raise ValueError("Release tag differs from payload source")
        for path in sorted(prefix.rglob("*")):
            if path.is_file():
                with path.open("rb") as stream:
                    if stream.read(2) == b"MZ" or path.suffix.lower() == ".ps1":
                        sign_file(path)
        provider_manifests(prefix / "bin", refresh=True)
        write_inventory(prefix, meta["version"], meta["source_commit"], meta["crexx_commit"], meta["platform"], "signed")
        helper = Path(temp) / "sign-helper.sh"
        helper.write_text("#!/bin/sh\nexec python3 " + shlex.quote(str(Path(__file__).resolve())) + ' sign-file "$@"\n')
        helper.chmod(0o700)
        stem = f"crexxrag-{meta['version']}-windows-x64-signed"
        installer = args.output / (stem + "-setup.exe")
        windows_installer(prefix, installer, meta["version"], helper)
        sign_file(installer)
        zip_path = args.output / (stem + ".zip")
        archive(prefix, zip_path)
        checksums(args.output)
        if args.upload:
            run("gh", "release", "upload", args.tag, "--repo", args.repo, installer, zip_path,
                installer.with_name(installer.name + ".sha256"), zip_path.with_name(zip_path.name + ".sha256"))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    build = sub.add_parser("package")
    for option in ("prefix", "output"):
        build.add_argument("--" + option, type=Path, required=True)
    for option in ("version", "commit", "crexx-commit", "platform"):
        build.add_argument("--" + option, required=True)
    check = sub.add_parser("verify")
    check.add_argument("prefix", type=Path)
    signing = sub.add_parser("windows-sign")
    signing.add_argument("--zip", type=Path, required=True)
    signing.add_argument("--output", type=Path, required=True)
    signing.add_argument("--upload", action="store_true")
    signing.add_argument("--repo")
    signing.add_argument("--tag")
    helper = sub.add_parser("sign-file")
    helper.add_argument("paths", nargs="+")
    helper.add_argument("--nsis-plugins", action="store_true")
    args = parser.parse_args()
    if args.command == "package":
        package(args)
    elif args.command == "verify":
        verify_inventory(args.prefix)
    elif args.command == "windows-sign":
        windows_sign(args)
    elif args.nsis_plugins:
        source, target = map(Path, args.paths)
        target.mkdir(parents=True)
        for name in ("System.dll", "nsExec.dll"):
            shutil.copy2(source / name, target / name)
            sign_file(target / name)
    else:
        if len(args.paths) != 1:
            parser.error("sign-file requires one file")
        sign_file(Path(args.paths[0]))


if __name__ == "__main__":
    main()
