set(CPRAG_RXC /Users/adrian/.local/bin/rxc)
set(CPRAG_RXAS /Users/adrian/.local/bin/rxas)
set(CPRAG_RXVME /Users/adrian/.local/bin/rxvme)
set(CPRAG_RXBVM /Users/adrian/.local/bin/rxbvm)
set(CPRAG_CREXX_BIN_DIR /Users/adrian/.local/bin)
set(CPRAG_PLUGIN_DIR /Users/adrian/.local/bin/providers)
set(CPRAG_APPLICATION_DIR /Users/adrian/CLionProjects/crexx-rag-review/cmake-build-debug/crexx-application)
set(CPRAG_SCENARIO /private/tmp/supervision-race-diagnostic.crexx)
foreach(iteration RANGE 1 30)
    set(CPRAG_WORK_DIR /private/tmp/crexx-supervision-race-repro-${iteration})
    message(STATUS "Reproduction iteration ${iteration}")
    include(/Users/adrian/CLionProjects/crexx-rag-review/cmake/SupervisionRegression.cmake)
endforeach()
