foreach(required CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(sqlite sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
file(WRITE "${CPRAG_WORK_DIR}/source/architecture.txt"
    "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase.\n")
file(WRITE "${CPRAG_WORK_DIR}/glossary.tsv"
    "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\tBilling Service\nconcept\tCustomerDatabase\tdata-store\tCustomer DB\n")
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
set(CPRAG_FIXTURE_PORT 0)
execute_process(COMMAND /bin/sh -c
    "( \"$1\" 0 5 product-first-pass; printf '%s' $? >\"$4\" ) >\"$2\" 2>\"$3\" &"
    first-pass-test "${CPRAG_LOOPBACK}" "${CPRAG_WORK_DIR}/server.out"
    "${CPRAG_WORK_DIR}/server.err" "${CPRAG_WORK_DIR}/server.status"
    COMMAND_ERROR_IS_FATAL ANY)
set(ready FALSE)
foreach(poll RANGE 1 200)
    if(EXISTS "${CPRAG_WORK_DIR}/server.out")
        file(READ "${CPRAG_WORK_DIR}/server.out" server)
        if(server MATCHES "READY ([0-9]+)")
            set(CPRAG_FIXTURE_PORT "${CMAKE_MATCH_1}")
            set(ready TRUE)
            break()
        endif()
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
endforeach()
if(NOT ready)
    message(FATAL_ERROR "First-pass provider fixture did not become ready")
endif()
configure_file("${CPRAG_CONFIG_TEMPLATE}" "${CPRAG_WORK_DIR}/crexxrag.conf" @ONLY)
file(READ "${CPRAG_WORK_DIR}/crexxrag.conf" config)
string(REPLACE "discovery.mode = all" "discovery.mode = maintenance" config "${config}")
string(REPLACE "worker.processes = 2" "worker.processes = 4" config "${config}")
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 10" config "${config}")
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 10" config "${config}")
string(REPLACE "budget.input_tokens = 8192" "budget.input_tokens = 65536" config "${config}")
string(REPLACE "budget.output_tokens = 1024" "budget.output_tokens = 8192" config "${config}")
file(WRITE "${CPRAG_WORK_DIR}/crexxrag.conf" "${config}\nmaintenance.mode = automatic\nmaintenance.batch_items = 1\nmaintenance.maximum_attempts = 3\nmaintenance.advanced_attempts = 3\nrole.advanced-resolver = gemini-generate\nrole.advanced-resolver.max_input_tokens = 8192\n")
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
function(cli output)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
        "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}"
        --config-file "${CPRAG_WORK_DIR}/crexxrag.conf" --library "${CPRAG_WORK_DIR}/library"
        --profile it-architecture-profile --format json ${ARGN}
        WORKING_DIRECTORY "${CPRAG_WORK_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE result
        ERROR_VARIABLE detail TIMEOUT 60)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\n${status}\n${result}${detail}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "First-pass command failed: ${ARGN}\n${result}${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${sqlite}" -bail "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "First-pass query failed: ${query}\n${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
function(window output)
    cli(plan --access plan maintain plan --source "${source}" --initial-extraction-only --minutes 5)
    string(JSON canonical GET "${plan}" records 0 fields canonical_plan)
    string(JSON digest GET "${plan}" records 0 fields digest)
    cli(applied --access curate maintain apply --plan-json "${canonical}" --expect-digest "${digest}")
    string(JSON job GET "${applied}" records 0 fields job_id)
    set(${output} "${job}" PARENT_SCOPE)
endfunction()

cli(init --access admin library init)
cli(ingest_plan --access plan ingest plan --source-set architecture-docs)
string(JSON ingest_canonical GET "${ingest_plan}" records 0 fields canonical_plan)
string(JSON ingest_digest GET "${ingest_plan}" records 0 fields digest)
cli(ingest_apply --access ingest ingest apply --plan-json "${ingest_canonical}" --expect-digest "${ingest_digest}")
string(JSON ingest_job GET "${ingest_apply}" records 0 fields job_id)
cli(ingest_work --access control worker start --count 1 --poll-ms 20 --max-polls 10 --job "${ingest_job}")
sql(source "SELECT source_id FROM sources WHERE stable_key='architecture.txt';")
sql(chunks "SELECT count(*) FROM revision_chunks WHERE revision_id=(SELECT current_revision_id FROM sources WHERE source_id='${source}');")
if(chunks LESS 1)
    message(FATAL_ERROR "Synthetic source did not produce a current chunk")
endif()
window(ordinary_job)
sql(ordinary "SELECT count(*) FROM job_items WHERE job_id='${ordinary_job}' AND item_type='improve-extraction';")
if(NOT ordinary STREQUAL "1")
    message(FATAL_ERROR "Initial-only window did not select one typed extraction: ${ordinary}")
endif()
cli(first --access control worker start --count 4 --poll-ms 20 --max-polls 10 --job "${ordinary_job}")
string(JSON requested GET "${first}" records 0 fields workers_requested)
string(JSON completed GET "${first}" records 0 fields workers_completed)
if(NOT requested EQUAL 4 OR NOT completed EQUAL 4)
    message(FATAL_ERROR "The first-pass window lost its four-worker ownership: ${first}")
endif()
sql(escalated "SELECT count(*) FROM maintenance_tasks WHERE subject_type='chunk' AND required_capability='advanced-reasoning' AND escalation_origin='validation-failures';")
sql(corrections "SELECT count(*) FROM job_events WHERE event_type='citation-correction-requested';")
if(NOT escalated STREQUAL "1" OR NOT corrections STREQUAL "1")
    message(FATAL_ERROR "Ordinary validation/correction did not escalate exactly one chunk: ${escalated}, ${corrections}")
endif()
sql(advanced "SELECT count(*) FROM job_items WHERE job_id='${ordinary_job}' AND item_type='maintenance-resolution' AND state='processed' AND json_extract(input_json,'$.role')='advanced-resolver';")
if(NOT advanced STREQUAL "1")
    message(FATAL_ERROR "Advanced route did not select the escalated chunk: ${advanced}")
endif()
sql(decisions "SELECT count(*) FROM maintenance_decisions WHERE disposition='extract:pending';")
if(NOT decisions STREQUAL "1")
    message(FATAL_ERROR "Advanced route did not retain one typed follow-on decision: ${decisions}")
endif()
sql(typed "SELECT count(*) FROM job_items WHERE job_id='${ordinary_job}' AND item_type='improve-extraction' AND json_extract(input_json,'$.required_capability')='advanced-reasoning';")
if(NOT typed STREQUAL "1")
    message(FATAL_ERROR "Follow-on typed extraction was not selected: ${typed}")
endif()
sql(accepted "SELECT count(*) FROM attempts a JOIN job_items i USING(item_id) WHERE i.job_id='${ordinary_job}' AND i.item_type='improve-extraction' AND a.outcome='succeeded' AND a.validation_state='validated-discovery-batch';")
if(NOT accepted STREQUAL "1")
    message(FATAL_ERROR "Typed follow-on did not produce an accepted extraction receipt: ${accepted}")
endif()
cli(restarted --access control worker start --count 4 --poll-ms 20 --max-polls 1 --job "${ordinary_job}")
cli(tasks --access read maintain tasks --source "${source}")
string(JSON detail GET "${tasks}" records 0 fields detail)
string(JSON missing GET "${detail}" incomplete_first_pass_chunks)
if(NOT missing EQUAL 0)
    message(FATAL_ERROR "Accepted receipt did not complete initial-only coverage: ${detail}")
endif()
window(replay_job)
sql(replay "SELECT count(*) FROM job_items WHERE job_id='${replay_job}';")
if(NOT replay STREQUAL "0")
    message(FATAL_ERROR "Unchanged replay selected already accepted first-pass work: ${replay}")
endif()
sql(accounting "SELECT (SELECT count(*) FROM job_events WHERE event_type='provider-response')||':'||(SELECT count(*) FROM maintenance_decisions WHERE disposition='extract:pending')||':'||(SELECT count(*) FROM job_items WHERE item_type='improve-extraction' AND state='processed');")
if(NOT accounting STREQUAL "5:1:1")
    message(FATAL_ERROR "First-pass attempts, decision or accepted work changed on replay: ${accounting}")
endif()
if(NOT EXISTS "${CPRAG_WORK_DIR}/server.status")
    message(FATAL_ERROR "Synthetic provider fixture did not receive its bounded requests")
endif()
file(READ "${CPRAG_WORK_DIR}/server.status" server_status)
if(NOT server_status STREQUAL "0")
    message(FATAL_ERROR "Synthetic provider fixture failed")
endif()
message(STATUS "Native first-pass failure, correction, advanced decision, typed extraction and replay passed")
