foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_FIXTURE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
file(READ "${CPRAG_CONFIG_FIXTURE}" config)
string(APPEND config "\nmaintenance.mode = automatic\n")
file(WRITE "${CPRAG_WORK_DIR}/policy.conf" "${config}")
set(base "${CPRAG_NATIVE_APPLICATION}" --config-file "${CPRAG_WORK_DIR}/policy.conf"
    --profile it-architecture-profile --library "${CPRAG_WORK_DIR}/library" --format json)
execute_process(COMMAND ${base} --access admin library init RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Command fixture init failed: ${out}${err}")
endif()
find_program(CREXXRAG_SQLITE3 sqlite3 REQUIRED)
execute_process(COMMAND "${CREXXRAG_SQLITE3}" -readonly "${CPRAG_WORK_DIR}/library/library.sqlite" .dump OUTPUT_VARIABLE before)
function(tool_call tool arguments expected)
    file(WRITE "${CPRAG_WORK_DIR}/request.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"${tool}\",\"arguments\":${arguments}}}\n")
    execute_process(COMMAND ${base} --access read,plan,control,ingest,curate,diagnose,admin serve mcp
        INPUT_FILE "${CPRAG_WORK_DIR}/request.jsonl" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "MCP process failed: ${out}${err}")
    endif()
    if(expected STREQUAL "invalid")
        string(JSON code ERROR_VARIABLE failure GET "${out}" error code)
        if(failure OR NOT code EQUAL -32602)
            message(FATAL_ERROR "Invalid argument accepted (${tool} ${arguments}): ${out}")
        endif()
    else()
        string(JSON code ERROR_VARIABLE failure GET "${out}" result structuredContent exit_code)
        if(failure OR NOT code EQUAL expected)
            message(FATAL_ERROR "Advertised argument did not reach product semantics (${tool} ${arguments}): ${out}")
        endif()
    endif()
    set(response "${out}" PARENT_SCOPE)
endfunction()
# Positive control before the advertised boolean regression.
tool_call(rag_maintain_plan "{}" 0)
foreach(value true false)
    tool_call(rag_maintain_plan "{\"embeddings_only\":${value},\"enrich_provenance\":false}" 0)
    string(JSON actual GET "${response}" result structuredContent records 1 fields embeddings_only)
    if(value AND NOT actual OR NOT value AND actual)
        message(FATAL_ERROR "Boolean forwarding lost its value: ${response}")
    endif()
    tool_call(rag_vector_rebuild "{\"reconcile\":${value}}" 6)
endforeach()
tool_call(rag_maintain_plan "{\"embeddings_only\":\"true\"}" invalid)
tool_call(rag_vector_rebuild "{\"reconcile\":\"true\"}" invalid)
foreach(args IN ITEMS "{\"limit\":0}" "{\"limit\":101}" "{\"limit\":1.5}" "{\"limit\":\"1\"}" "{\"limit\":1,\"limit\":2}" "{\"unexpected\":\"x\"}")
    tool_call(rag_job_list "${args}" invalid)
endforeach()
tool_call(rag_job_list "{\"limit\":1}" 0)
tool_call(rag_job_list "{\"limit\":100}" 0)
tool_call(rag_job_status "{}" invalid)
tool_call(rag_job_status "{\"id\":\"\"}" invalid)
tool_call(rag_job_items "{\"id\":\"missing\",\"state\":\"invented\"}" invalid)
tool_call(rag_query_inspect "{\"question\":\"synthetic\",\"mode\":\"hybrid\"}" invalid)
tool_call(rag_proposal_plan "{}" invalid)
tool_call(rag_proposal_plan "{\"input\":\"x\",\"proposals_ndjson\":\"x\"}" invalid)
tool_call(rag_proposal_plan "{\"input\":\"\"}" invalid)
tool_call(rag_proposal_plan "{\"input\":\"x\",\"proposals_ndjson\":\"\"}" invalid)
string(REPEAT "a" 513 too_long)
tool_call(rag_task_list "{\"concept\":\"${too_long}\"}" invalid)
tool_call(rag_unknown "{}" invalid)
execute_process(COMMAND "${CREXXRAG_SQLITE3}" -readonly "${CPRAG_WORK_DIR}/library/library.sqlite" .dump OUTPUT_VARIABLE after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Read-only plans or rejected argument checks changed library state")
endif()
message(STATUS "Declared boolean, enum, integer, length, required, oneOf and duplicate argument contracts hold without writes")
