foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_FIXTURE CPRAG_EXPECTED_CONTRACTS CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
file(WRITE "${CPRAG_WORK_DIR}/request.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\"}\n")
set(observed "")
foreach(lane read all)
    set(access read)
    if(lane STREQUAL all)
        set(access read,plan,control,ingest,curate,diagnose,admin)
    endif()
    execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --config-file "${CPRAG_CONFIG_FIXTURE}"
        --profile it-architecture-profile --library "${CPRAG_WORK_DIR}/unopened-library"
        --access "${access}" --format json serve mcp
        INPUT_FILE "${CPRAG_WORK_DIR}/request.jsonl" OUTPUT_VARIABLE out ERROR_VARIABLE err RESULT_VARIABLE result TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot capture tool metadata: ${out}${err}")
    endif()
    string(JSON metadata GET "${out}" result tools)
    string(JSON count LENGTH "${metadata}")
    if(count LESS 1)
        message(FATAL_ERROR "No tool metadata captured")
    endif()
    file(WRITE "${CPRAG_WORK_DIR}/${lane}.json" "${metadata}\n")
    string(SHA256 digest "${metadata}")
    string(APPEND observed "${lane} ${count} ${digest}\n")
endforeach()
file(WRITE "${CPRAG_WORK_DIR}/observed.sha256" "${observed}")
file(READ "${CPRAG_EXPECTED_CONTRACTS}" expected)
if(NOT observed STREQUAL expected)
    message(FATAL_ERROR "Advertised command contracts changed; review ${CPRAG_WORK_DIR}/observed.sha256 and captured metadata")
endif()
if(EXISTS "${CPRAG_WORK_DIR}/unopened-library")
    message(FATAL_ERROR "Tool metadata inspection created a library")
endif()
message(STATUS "Advertised command schemas, required fields and access annotations match the captured baseline")
