# Exercise recovery inside one eight-worker command; no operator restart.
foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_CODEX_FIXTURE CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(sqlite_cli sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
function(run_cli)
    execute_process(COMMAND ${cli} ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 90)
    file(APPEND "${cell}/commands.log" "${ARGN}\nstatus=${status}\n${output}${errors}\n")
    set(last_status "${status}" PARENT_SCOPE)
    set(last_output "${output}" PARENT_SCOPE)
    if((NOT expect_failure AND NOT status EQUAL 0) OR (expect_failure AND NOT status EQUAL 8))
        message(FATAL_ERROR "Controller command failed: ${ARGN}\n${output}${errors}")
    endif()
endfunction()
function(sql query expected)
    execute_process(COMMAND "${sqlite_cli}" -cmd ".timeout 5000" "${library}/library.sqlite" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0 OR NOT output STREQUAL "${expected}")
        message(FATAL_ERROR "Controller assertion: ${query}\nExpected ${expected}, got ${output}\n${errors}")
    endif()
endfunction()
if(NOT DEFINED CPRAG_CASES)
    set(CPRAG_CASES interrupted completed cleanup unavailable exhausted unavailable-only)
endif()
foreach(case IN LISTS CPRAG_CASES)
    set(cell "${CPRAG_WORK_DIR}/${case}")
    set(library "${cell}/library")
    set(CPRAG_FIXTURE_SOURCE "${cell}/source")
    set(CPRAG_FIXTURE_GLOSSARY "${cell}/glossary.tsv")
    set(CPRAG_FIXTURE_PORT 1)
    file(MAKE_DIRECTORY "${CPRAG_FIXTURE_SOURCE}" "${cell}/sync")
    file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\nconcept\tCustomerDatabase\tdata-store\n")
    foreach(n RANGE 1 16)
        file(WRITE "${CPRAG_FIXTURE_SOURCE}/${n}.txt" "BillingService depends on CustomerDatabase. Source ${n}.\n")
    endforeach()
    file(READ "${CPRAG_CONFIG_TEMPLATE}" config)
    string(CONFIGURE "${config}" config @ONLY)
    string(REPLACE "worker.processes = 1" "worker.processes = 8" config "${config}")
    string(REPLACE "budget.item_limit = 2" "budget.item_limit = 32" config "${config}")
    string(REPLACE "budget.model_calls = 2" "budget.model_calls = 40" config "${config}")
    string(REPLACE "budget.codex_turns = 1" "budget.codex_turns = 20" config "${config}")
    string(REPLACE "budget.input_tokens = 65536" "budget.input_tokens = 1000000" config "${config}")
    string(REPLACE "budget.output_tokens = 1024" "budget.output_tokens = 100000" config "${config}")
    set(restart_limit 2)
    if(case STREQUAL "unavailable-only")
        set(restart_limit 0)
    endif()
    string(APPEND config "\nworker.max_restarts = ${restart_limit}\nworker.restart_backoff_ms = 10\n")
    file(WRITE "${cell}/recovery.conf" "${config}")
    set(observed "${case}")
    if(case STREQUAL "exhausted")
        set(observed interrupted)
    elseif(case STREQUAL "unavailable-only")
        set(observed unavailable)
    endif()
    file(WRITE "${cell}/external-state" "${observed}\n")
    file(WRITE "${cell}/codex-fixture.sh" "#!/bin/sh\nexec /bin/sh '${CPRAG_CODEX_FIXTURE}' \"\$@\"\n")
    file(CHMOD "${cell}/codex-fixture.sh" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    set(cli "${CMAKE_COMMAND}" -E env "CREXXRAG_CODEX=${cell}/codex-fixture.sh"
        "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "CREXXRAG_CODEX_FIXTURE_MODE=extraction"
        "CREXXRAG_CODEX_FIXTURE_FAILURE=controller-${case}"
        "CREXXRAG_CODEX_FIXTURE_ONCE=${cell}/failed-once" "CREXXRAG_CODEX_FIXTURE_SYNC=${cell}/sync"
        "CREXXRAG_CODEX_FIXTURE_STATE_FILE=${cell}/external-state" "CREXXRAG_CODEX_FIXTURE_LOG=${cell}/methods.log"
        "${CPRAG_NATIVE_APPLICATION}" --library "${library}" --config-file "${cell}/recovery.conf"
        --profile it-architecture-profile --format json --progress plain)
    run_cli(--access admin library init)
    run_cli(--access plan ingest plan --source-set architecture-docs)
    string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
    string(JSON digest GET "${last_output}" records 0 fields digest)
    run_cli(--access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
    string(JSON job GET "${last_output}" records 0 fields job_id)
    # Keep this test focused on extraction; preserve queued embedding work.
    if(case STREQUAL "unavailable-only")
        sql("UPDATE job_items SET state='cancelled' WHERE item_type='embedding';" "")
    else()
        sql("UPDATE job_items SET retry_at=unixepoch()+3600 WHERE item_type='embedding';" "")
    endif()
    set(expect_failure FALSE)
    if(case STREQUAL "exhausted" OR case STREQUAL "unavailable-only")
        set(expect_failure TRUE)
    endif()
    run_cli(--access control job run "${job}" --count 8 --poll-ms 20 --max-polls 150)
    set(expect_failure FALSE)
    set(expected_observations 1)
    set(expected_replacements 1)
    if(case STREQUAL "cleanup")
        set(expected_replacements 0)
    endif()
    if(case STREQUAL "unavailable-only")
        set(expected_replacements 0)
    endif()
    if(case STREQUAL "exhausted")
        set(expected_observations 3)
        set(expected_replacements 2)
        sql("SELECT count(*) FROM runtime_instances WHERE kind='worker' AND requested_state='drain';" "0")
    endif()
    set(expected_completed 16)
    set(expected_unsettled 0)
    if(case MATCHES "^unavailable")
        set(expected_completed 15)
        set(expected_unsettled 1)
        sql("SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state='dead_letter';" "1")
        sql("SELECT count(DISTINCT attempt_id) FROM job_events WHERE event_type='provider-outcome-uncertain';" "1")
    elseif(NOT case STREQUAL "cleanup")
        sql("SELECT count(*) FROM job_events WHERE event_type='provider-observed' AND json_extract(message,'$.usage_complete')=0;" "${expected_observations}")
        sql("SELECT count(*) FROM provider_runs p JOIN attempts a ON a.provider_run_id=p.provider_run_id JOIN job_events e ON e.attempt_id=a.attempt_id WHERE e.event_type='provider-observed' AND p.input_tokens=7 AND p.output_tokens=2;" "${expected_observations}")
    endif()
    sql("SELECT count(*) FROM jobs WHERE state='paused';" "0")
    sql("SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state IN('processed','skipped');" "${expected_completed}")
    sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "${expected_replacements}")
    sql("SELECT count(*) FROM runtime_instances WHERE kind='controller';" "1")
    sql("SELECT reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns FROM jobs;" "0")
    sql("SELECT count(*) FROM attempts WHERE outcome='running';" "0")
    sql("SELECT count(*) FROM provider_runs WHERE outcome IN('starting','running','completed-unsettled');" "${expected_unsettled}")
    sql("SELECT model_call_budget||':'||codex_turn_budget||':'||input_token_budget||':'||output_token_budget FROM jobs;" "40:20:1000000:100000")
    set(expected_calls 16)
    if(case STREQUAL "interrupted")
        set(expected_calls 17)
    elseif(case STREQUAL "exhausted")
        set(expected_calls 19)
    endif()
    sql("SELECT count(*) FROM provider_runs;" "${expected_calls}")
    file(READ "${cell}/methods.log" methods)
    string(REGEX MATCHALL "turn/start" calls "${methods}")
    list(LENGTH calls call_count)
    if(NOT call_count EQUAL expected_calls)
        message(FATAL_ERROR "Unexpected generation count: ${call_count}, expected ${expected_calls}")
    endif()
    if(case STREQUAL "unavailable-only")
        # Drained work has finished with errors; a launch alone does not redo it.
        execute_process(COMMAND ${cli} --access control job run "${job}" --count 8 --poll-ms 20 --max-polls 5
            RESULT_VARIABLE terminal_status OUTPUT_VARIABLE terminal_output ERROR_VARIABLE terminal_error TIMEOUT 30)
        if(NOT terminal_status EQUAL 0)
            message(FATAL_ERROR "Completed job index retry failed: ${terminal_output}${terminal_error}")
        endif()
        sql("SELECT state FROM jobs;" "completed_with_errors")
        sql("SELECT count(*) FROM provider_runs;" "16")
        execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite"
            "SELECT item_id FROM job_items WHERE item_type='claim-extraction' AND state='dead_letter';"
            OUTPUT_VARIABLE held_item OUTPUT_STRIP_TRAILING_WHITESPACE)
        file(WRITE "${cell}/external-state" "interrupted\n")
        run_cli(--access diagnose job reconcile "${job}" --item "${held_item}")
        string(JSON reconcile_digest GET "${last_output}" records 0 fields digest)
        run_cli(--access control job reconcile "${job}" --item "${held_item}" --apply --expect-digest "${reconcile_digest}")
        sql("SELECT count(*) FROM job_items WHERE item_id='${held_item}' AND state='queued';" "1")
        sql("SELECT state FROM jobs;" "running")
        run_cli(--access control job continue "${job}" --prepare)
        sql("SELECT count(*) FROM provider_runs;" "16")
    endif()
    file(WRITE "${cell}/result.txt" "Eight overlapping workers recovered ${case} within one controller, completed ${expected_completed} extraction items, preserved budgets and made exactly ${expected_calls} generation calls.\n")
endforeach()
