# Test infrastructure only. CTest owns scheduling; each case owns its files and
# children. Fixed endpoint fixtures declare narrow port locks, never RUN_SERIAL.
find_package(Python3 REQUIRED COMPONENTS Interpreter)

function(crexxrag_add_test)
    set(name "${ARGV1}")
    set(command)
    set(scenario_sources)
    set(inputs "${CMAKE_CURRENT_SOURCE_DIR}/tests/qa/run_case.py")
    set(artifacts "${CREXXRAG_NATIVE_APPLICATION}" "${CREXXRAG_APPLICATION_RXBIN}" "${CREXX_BUILDINFO_FILE}" "${CREXXRAG_SQLITE_PROVIDER_DIR}" "${CREXX_INSTALL_BIN_DIR}/providers")
    math(EXPR last "${ARGC}-1")
    foreach(index RANGE 3 ${last})
        set(value "${ARGV${index}}")
        string(REGEX REPLACE "^-D[^=]+=" "" path "${value}")
        if(path MATCHES "\\.crexx$")
            list(APPEND scenario_sources "${path}")
        endif()
        if(path MATCHES "^\\$<TARGET_FILE:")
            list(APPEND artifacts "${path}")
        endif()
        if(EXISTS "${path}" AND NOT IS_DIRECTORY "${path}")
            if(path MATCHES "\\.(cmake|crexx|in|conf|tsv|json|sha256|sh|py|txt)$")
                list(APPEND inputs "${path}")
            else()
                list(APPEND artifacts "${path}")
            endif()
        endif()
        string(REPLACE ";" "\\;" value "${value}")
        list(APPEND command "${value}")
    endforeach()
    set(driver "${ARGV${last}}")
    get_filename_component(driver_name "${driver}" NAME_WE)
    # Explicit helper dependencies; no inferred module graph or scheduler.
    if(driver_name MATCHES "^(GeminiQuery|PromptContract)$")
        set(profile "${CREXXRAG_APP_DIR}/config/profiles/it-architecture.profile.tsv")
        list(INSERT command 1 "-DCPRAG_ARCHITECTURE_PROFILE=${profile}")
        list(APPEND inputs "${profile}")
    elseif(driver_name STREQUAL "TaskReset")
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/task-reset.py")
    elseif(driver_name STREQUAL "ProcessWorkers")
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/providers/gemini-ingestion.conf.in")
    elseif(driver_name STREQUAL "NativeSupervision")
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/worker-exit.py")
    endif()
    if(driver_name STREQUAL "SourceMaintenance")
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/cmake/JobDeadline.cmake")
    elseif(driver_name STREQUAL "PromptInspection")
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/cmake/ProjectContract.cmake")
    elseif(driver_name STREQUAL "PublicRegression")
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/cmake/JobRetryReset.cmake" "${CMAKE_CURRENT_SOURCE_DIR}/cmake/LexicalRegression.cmake")
    endif()
    if(driver_name MATCHES "^(InstalledProduct|PromptContract)$")
        foreach(helper GeminiProviderSmoke GeminiImprovement GeminiIngestion GeminiQuery DurableBacklogProvider PublicRegression JobRetryReset LexicalRegression)
            if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/cmake/${helper}.cmake")
                list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/cmake/${helper}.cmake")
            endif()
        endforeach()
    endif()
    if(driver_name MATCHES "^(ControllerClosure|LauncherExit)$")
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/launcher-exit.py" "${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/providers/codex-application.conf.in")
    endif()
    if(driver_name STREQUAL "InstalledProduct")
        file(GLOB_RECURSE package_inputs CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/skills/*" "${CREXXRAG_APP_DIR}/config/*" "${CMAKE_CURRENT_SOURCE_DIR}/docs/tutorial/*")
        list(APPEND inputs "${CMAKE_BINARY_DIR}/cmake_install.cmake" "${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/retrieval/regression.json" ${package_inputs})
    endif()
    if(name STREQUAL "linked_application")
        list(APPEND artifacts "${CREXXRAG_APPLICATION_DIR}/crexxrag.rxproviders")
    endif()
    if(name STREQUAL "documentation_contract")
        file(GLOB_RECURSE docs CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/docs/*.md" "${CMAKE_CURRENT_SOURCE_DIR}/skills/*")
        list(APPEND inputs ${docs} "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
    endif()
    if(driver_name MATCHES "^(ProjectContract|PromptInspection|DurableBacklog|ConfigContract|CodexProtocol)$")
        set(build_driver "${driver}")
        set(build_name "${name}")
        set(output_file contract_linked.rxbin)
        if(driver_name STREQUAL "PromptInspection")
            set(build_driver "${CMAKE_CURRENT_SOURCE_DIR}/cmake/ProjectContract.cmake")
        elseif(driver_name STREQUAL "DurableBacklog")
            set(build_name durable_backlog)
            set(output_file backlog_scenario.rxbin)
        elseif(driver_name MATCHES "^(ConfigContract|CodexProtocol)$")
            set(build_name "${driver_name}")
            set(output_file compiled.stamp)
        endif()
        set(prebuilt "${CMAKE_BINARY_DIR}/qa-programs/${build_name}")
        if(NOT TARGET qa_${build_name})
            set(build_command)
            foreach(arg IN LISTS command)
                if(arg MATCHES "^-DCPRAG_WORK_DIR=")
                    set(arg "-DCPRAG_WORK_DIR=${prebuilt}")
                elseif(arg STREQUAL "${driver}")
                    set(arg "${build_driver}")
                endif()
                string(REPLACE ";" "\\;" arg "${arg}")
                list(APPEND build_command "${arg}")
            endforeach()
            list(INSERT build_command 1 -DCPRAG_COMPILE_ONLY=ON)
            add_custom_command(OUTPUT "${prebuilt}/${output_file}"
                COMMAND ${build_command}
                DEPENDS ${scenario_sources} "${build_driver}" "${CREXXRAG_APPLICATION_PROJECT_RXBIN}" "${CREXX_RXC_EXECUTABLE}" "${CREXX_RXAS_EXECUTABLE}"
                VERBATIM COMMENT "Building test scenario ${build_name}")
            add_custom_target(qa_${build_name} ALL DEPENDS "${prebuilt}/${output_file}")
        endif()
        list(INSERT command 1 "-DCPRAG_PREBUILT=${prebuilt}")
        list(APPEND artifacts "${prebuilt}")
    endif()
    set(ports)
    # These cases intentionally retain one endpoint across frozen plans or
    # protocol variants. Locks isolate the actual shared resource, not a suite.
    if(driver_name MATCHES "^(GeminiQuery|PromptContract)$")
        set(ports 18999)
    elseif(driver_name STREQUAL "LocalEmbeddingProtocol")
        set(ports 19020)
    elseif(driver_name STREQUAL "GeminiExtractionValidation")
        set(ports 19021 19022 19023 19024)
    elseif(driver_name STREQUAL "EmbeddingRecovery")
        set(ports 19031 19032)
    elseif(driver_name STREQUAL "NativeAdmission")
        set(ports 19045)
    elseif(driver_name STREQUAL "NativeLifecycle")
        set(ports 19046 19047)
    elseif(driver_name STREQUAL "EmbeddingPublication")
        set(ports 19051)
    elseif(driver_name STREQUAL "Test2Completion")
        set(ports 19053)
    endif()
    if(driver_name MATCHES "^(NativeSurfaces|GeminiIngestion|GeminiImprovement|CodexApplication|NativeReceipts|NativeReceiptFailure|NativePublication|NativeInterruption|GeminiProviderSmoke)$")
        set(ports)
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/cmake/FixtureEndpoint.cmake")
    elseif(driver_name STREQUAL "InstalledProduct")
        set(ports)
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/cmake/FixtureEndpoint.cmake")
    elseif(driver_name STREQUAL "PromptContract")
        set(ports 18999)
        list(APPEND inputs "${CMAKE_CURRENT_SOURCE_DIR}/cmake/FixtureEndpoint.cmake")
    endif()
    set(arguments --root "${CMAKE_BINARY_DIR}/qa" --name "${name}")
    foreach(input IN LISTS inputs)
        if(EXISTS "${input}" AND NOT IS_DIRECTORY "${input}")
            list(APPEND arguments --input "${input}")
        endif()
    endforeach()
    foreach(artifact IN LISTS artifacts)
        if(NOT artifact STREQUAL "")
            list(APPEND arguments --artifact "${artifact}")
        endif()
    endforeach()
    if(driver_name MATCHES "(Gemini|Native|Embedding|DurableBacklogProvider|Test2Completion|PromptContract|InstalledProduct)")
        list(APPEND arguments --artifact "$<TARGET_FILE:crexxrag_provider_fixture>")
    endif()
    set(locks)
    foreach(port IN LISTS ports)
        list(APPEND arguments --port "${port}")
        list(APPEND locks "loopback-${port}")
    endforeach()
    add_test(NAME "${name}" COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/qa/run_case.py" ${arguments} -- ${command})
    set_tests_properties("${name}" PROPERTIES SKIP_RETURN_CODE 125 RESOURCE_LOCK "${locks}" TIMEOUT 330)
endfunction()
