foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(CPRAG_SQLITE sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")

function(run_cli output)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
        "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}" ${ARGN}
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail TIMEOUT 60)
    file(APPEND "${work}/commands.log" "${ARGN}\n${result}${detail}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "durable maintenance command failed: ${ARGN}\n${result}${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

foreach(case IN ITEMS valid malformed rejected manual)
    set(work "${CPRAG_WORK_DIR}/${case}")
    file(MAKE_DIRECTORY "${work}/source")
    file(WRITE "${work}/source/architecture.txt" "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase.\n")
    set(CPRAG_FIXTURE_SOURCE "${work}/source")
    set(CPRAG_FIXTURE_GLOSSARY "${work}/glossary.tsv")
    file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\tBilling Service\nconcept\tCustomerDatabase\tdata-store\tCustomer DB\n")
    set(request_count 3)
    set(maintenance_calls 1)
    set(maintenance_mode automatic)
    set(CPRAG_FIXTURE_PORT 19013)
    if(case STREQUAL "malformed")
        set(CPRAG_FIXTURE_PORT 19014)
    elseif(case STREQUAL "rejected")
        set(CPRAG_FIXTURE_PORT 19015)
    elseif(case STREQUAL "manual")
        set(CPRAG_FIXTURE_PORT 19016)
        set(request_count 2)
        set(maintenance_calls 0)
        set(maintenance_mode manual)
    endif()
    configure_file("${CPRAG_CONFIG_TEMPLATE}" "${work}/crexxrag.conf" @ONLY)
    execute_process(COMMAND /bin/sh -c
        "( \"$1\" \"$2\" \"$7\" \"$3\"; printf '%s' $? >\"$6\" ) >\"$4\" 2>\"$5\" &"
        backlog-test "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}" "product-backlog-${case}"
        "${work}/server.out" "${work}/server.err" "${work}/server.status" "${request_count}"
        COMMAND_ERROR_IS_FATAL ANY)
    set(ready FALSE)
    foreach(poll RANGE 1 200)
        if(EXISTS "${work}/server.out")
            file(READ "${work}/server.out" server)
            if(server MATCHES "READY ${CPRAG_FIXTURE_PORT}")
                set(ready TRUE)
                break()
            endif()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
    endforeach()
    if(NOT ready)
        message(FATAL_ERROR "durable backlog loopback did not become ready")
    endif()
    run_cli(init init)
    run_cli(ingest ingest --yes --workers 1)
    set(database "${work}/library/library.sqlite")
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "SELECT count(*) FROM provider_runs WHERE outcome='failed';"
        OUTPUT_VARIABLE ingestion_failures OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT ingestion_failures STREQUAL "0")
        message(FATAL_ERROR "backlog fixture ingestion failed before maintenance")
    endif()
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "INSERT INTO analysis_notes(note_id,note_kind,text,importance,uncertainty,next_action,state,grounding_json,author,created_generation,created_at,updated_at) SELECT 'fixture-note','lead','Resolve the dependency question',900000,100000,'Investigate','active','{}','fixture',published_generation,'fixture','fixture' FROM library_meta; INSERT INTO analysis_note_links(link_id,note_id,object_type,object_id,revision_chunk_id,span_start,span_end) SELECT 'fixture-note-link','fixture-note','chunk',revision_chunk_id,revision_chunk_id,0,43 FROM revision_chunks WHERE visible_to_generation IS NULL LIMIT 1;"
        COMMAND_ERROR_IS_FATAL ANY)
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "SELECT (SELECT count(*) FROM revision_chunks)||':'||(SELECT group_concat(hex(vector)) FROM embeddings)||':'||(SELECT count(*) FROM revision_chunk_embeddings)||':'||(SELECT count(*) FROM provider_runs);"
        OUTPUT_VARIABLE before OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    file(READ "${work}/crexxrag.conf" config)
    string(REPLACE "budget.model_calls = 2" "budget.model_calls = 1" config "${config}")
    string(REPLACE "budget.item_limit = 2" "budget.item_limit = 1" config "${config}")
    string(APPEND config "\nmaintenance.mode = ${maintenance_mode}\nmaintenance.batch_items = 1\nmaintenance.maximum_attempts = 1\nmaintenance.resolution_prompt = fixture-resolution-prompt\n")
    file(WRITE "${work}/crexxrag.conf" "${config}")
    run_cli(config_plan --format json --access plan config plan --reason "bounded durable backlog fixture")
    string(JSON configuration_plan GET "${config_plan}" records 0 fields canonical_plan)
    string(JSON configuration_digest GET "${config_plan}" records 0 fields digest)
    run_cli(config_apply --access admin config apply --plan-json "${configuration_plan}" --expect-digest "${configuration_digest}")
    run_cli(explain --format json config explain)
    if(NOT explain MATCHES "resolution_prompt_sha256" OR NOT explain MATCHES "automatic_actions")
        message(FATAL_ERROR "configuration explanation omitted durable maintenance policy")
    endif()
    run_cli(maintain maintain --yes --workers 1)
    run_cli(status --format json maintain status)
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "SELECT (SELECT count(*) FROM revision_chunks)||':'||(SELECT group_concat(hex(vector)) FROM embeddings)||':'||(SELECT count(*) FROM revision_chunk_embeddings)||':'||((SELECT count(*) FROM provider_runs)-${maintenance_calls});"
        OUTPUT_VARIABLE after OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "maintenance changed source/vector state or made an unexpected number of calls")
    endif()
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "SELECT state FROM maintenance_tasks WHERE kind='analysis-lead' AND subject_id='fixture-note';"
        OUTPUT_VARIABLE task_state OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(case STREQUAL "manual")
        if(NOT task_state STREQUAL "review")
            message(FATAL_ERROR "manual window did not collect its note question: ${task_state}")
        endif()
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}" "SELECT count(*) FROM maintenance_windows WHERE state='active';"
            OUTPUT_VARIABLE active_windows OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        if(NOT active_windows STREQUAL "0")
            message(FATAL_ERROR "guided manual census left a window active with no queued provider work")
        endif()
    elseif(case STREQUAL "valid")
        if(NOT task_state STREQUAL "resolved")
            message(FATAL_ERROR "valid Gemini resolution was not applied: ${task_state}\n${maintain}${status}")
        endif()
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT task_id FROM maintenance_tasks WHERE subject_id='fixture-note';"
            OUTPUT_VARIABLE task_id OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        run_cli(inspect --format json maintain inspect "${task_id}")
        if(NOT inspect MATCHES "fixture-note-link" OR NOT inspect MATCHES "retain:resolved")
            message(FATAL_ERROR "durable task inspection omitted evidence or decision")
        endif()
    else()
        if(NOT task_state STREQUAL "failed")
            message(FATAL_ERROR "malformed response did not reach bounded failure: ${task_state}")
        endif()
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT recovery_json FROM provider_runs WHERE outcome='failed';"
            OUTPUT_VARIABLE diagnostic COMMAND_ERROR_IS_FATAL ANY)
        if(diagnostic MATCHES "synthetic-product-gemini-key")
            message(FATAL_ERROR "resolution failure diagnostic exposed a fixture credential")
        endif()
        if(case STREQUAL "rejected" AND (NOT diagnostic MATCHES "REDACTED" OR NOT diagnostic MATCHES "resolution quotation"))
            message(FATAL_ERROR "resolution failure diagnostic did not retain redacted evidence")
        endif()
    endif()
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}" "PRAGMA integrity_check; SELECT count(*) FROM pragma_foreign_key_check;"
        OUTPUT_VARIABLE integrity OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT integrity STREQUAL "ok\n0")
        message(FATAL_ERROR "durable backlog database integrity failure: ${integrity}")
    endif()
    if(NOT EXISTS "${work}/server.status")
        message(FATAL_ERROR "loopback did not finish its exact bounded requests")
    endif()
    file(READ "${work}/server.status" server_status)
    if(NOT server_status STREQUAL "0")
        message(FATAL_ERROR "durable backlog loopback failed")
    endif()
endforeach()
file(WRITE "${CPRAG_WORK_DIR}/result.txt" "Public automatic maintenance: Gemini typed resolution, quotation grounding, bounded malformed output, secret redaction, task inspection, source/vector preservation, exactly one maintenance request per automatic case and zero for manual collection.\n")
