foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(CPRAG_SQLITE sqlite3 REQUIRED)
if(NOT DEFINED CPRAG_CONCURRENT_ITEMS)
    set(CPRAG_CONCURRENT_ITEMS 40)
endif()
math(EXPR concurrent_remainder "${CPRAG_CONCURRENT_ITEMS} % 2")
if(CPRAG_CONCURRENT_ITEMS LESS 2 OR CPRAG_CONCURRENT_ITEMS GREATER 10000 OR NOT concurrent_remainder EQUAL 0)
    message(FATAL_ERROR "CPRAG_CONCURRENT_ITEMS must be even and between 2 and 10000")
endif()
math(EXPR concurrent_extra "${CPRAG_CONCURRENT_ITEMS} - 1")
math(EXPR concurrent_pairs "${CPRAG_CONCURRENT_ITEMS} / 2")
if(NOT DEFINED CPRAG_CASES)
    set(CPRAG_CASES valid malformed rejected manual concurrent budget continuation item-limit correction correction-failed correction-budget)
endif()
if(NOT DEFINED CPRAG_COMMAND_TIMEOUT)
    set(CPRAG_COMMAND_TIMEOUT 60)
endif()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")

function(run_cli output)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
        "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}" ${ARGN}
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail TIMEOUT ${CPRAG_COMMAND_TIMEOUT})
    file(APPEND "${work}/commands.log" "${ARGN}\n${result}${detail}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "durable maintenance command failed: ${ARGN}\n${result}${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

foreach(case IN LISTS CPRAG_CASES)
    set(work "${CPRAG_WORK_DIR}/${case}")
    file(MAKE_DIRECTORY "${work}/source")
    file(WRITE "${work}/source/architecture.txt" "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase.\n")
    set(CPRAG_FIXTURE_SOURCE "${work}/source")
    set(CPRAG_FIXTURE_GLOSSARY "${work}/glossary.tsv")
    file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\tBilling Service\nconcept\tCustomerDatabase\tdata-store\tCustomer DB\n")
    set(request_count 3)
    set(maintenance_calls 1)
    set(maintenance_mode automatic)
    set(maintenance_workers 1)
    set(fixture_scenario "product-backlog-${case}")
    set(CPRAG_FIXTURE_PORT 19013)
    if(case STREQUAL "malformed")
        set(CPRAG_FIXTURE_PORT 19014)
    elseif(case STREQUAL "rejected")
        set(CPRAG_FIXTURE_PORT 19015)
    elseif(case STREQUAL "manual")
        set(CPRAG_FIXTURE_PORT 19016)
        set(request_count 2)
        set(maintenance_calls 0)
        set(maintenance_mode manual)
    elseif(case STREQUAL "concurrent")
        set(CPRAG_FIXTURE_PORT 19017)
        if(DEFINED CPRAG_CONCURRENT_PORT)
            set(CPRAG_FIXTURE_PORT ${CPRAG_CONCURRENT_PORT})
        endif()
        math(EXPR request_count "${CPRAG_CONCURRENT_ITEMS} + 2")
        set(maintenance_calls ${CPRAG_CONCURRENT_ITEMS})
        set(maintenance_workers 2)
        set(fixture_scenario product-concurrent)
    elseif(case STREQUAL "budget" OR case STREQUAL "continuation" OR case STREQUAL "item-limit")
        set(CPRAG_FIXTURE_PORT 19018)
        set(request_count 6)
        set(maintenance_calls 4)
        set(maintenance_workers 2)
        set(fixture_scenario product-concurrent)
    endif()
    if(case MATCHES "^correction")
        set(CPRAG_FIXTURE_PORT 19019)
        if(NOT case STREQUAL "correction-budget")
            set(request_count 4)
            set(maintenance_calls 2)
        endif()
    endif()
    configure_file("${CPRAG_CONFIG_TEMPLATE}" "${work}/crexxrag.conf" @ONLY)
    execute_process(COMMAND /bin/sh -c
        "( \"$1\" \"$2\" \"$7\" \"$3\"; printf '%s' $? >\"$6\" ) >\"$4\" 2>\"$5\" &"
        backlog-test "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}" "${fixture_scenario}"
        "${work}/server.out" "${work}/server.err" "${work}/server.status" "${request_count}"
        COMMAND_ERROR_IS_FATAL ANY)
    set(ready FALSE)
    foreach(poll RANGE 1 200)
        if(EXISTS "${work}/server.out")
            file(READ "${work}/server.out" server)
            if(server MATCHES "READY ${CPRAG_FIXTURE_PORT}")
                set(ready TRUE)
                break()
            endif()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
    endforeach()
    if(NOT ready)
        message(FATAL_ERROR "durable backlog loopback did not become ready")
    endif()
    run_cli(init init)
    run_cli(ingest ingest --yes --workers 1)
    set(database "${work}/library/library.sqlite")
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "SELECT (SELECT count(*) FROM provider_runs WHERE outcome='failed')+(SELECT count(*) FROM job_items WHERE state NOT IN('processed','skipped'));"
        OUTPUT_VARIABLE ingestion_failures OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT ingestion_failures STREQUAL "0")
        message(FATAL_ERROR "backlog fixture ingestion failed before maintenance")
    endif()
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "INSERT INTO analysis_notes(note_id,note_kind,text,importance,uncertainty,next_action,state,grounding_json,author,created_generation,created_at,updated_at) SELECT 'fixture-note','lead','Resolve the dependency question',900000,100000,'Investigate','active','{}','fixture',published_generation,'fixture','fixture' FROM library_meta; INSERT INTO analysis_note_links(link_id,note_id,object_type,object_id,revision_chunk_id,span_start,span_end) SELECT 'fixture-note-link','fixture-note','chunk',revision_chunk_id,revision_chunk_id,0,43 FROM revision_chunks WHERE visible_to_generation IS NULL LIMIT 1;"
        COMMAND_ERROR_IS_FATAL ANY)
    if(case STREQUAL "concurrent" OR case STREQUAL "budget" OR case STREQUAL "continuation" OR case STREQUAL "item-limit")
        set(note_extra ${concurrent_extra})
        if(case STREQUAL "budget" OR case STREQUAL "continuation" OR case STREQUAL "item-limit")
            set(note_extra 3)
        endif()
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "WITH RECURSIVE n(x) AS(SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<${note_extra}) INSERT INTO analysis_notes(note_id,note_kind,text,importance,uncertainty,next_action,state,grounding_json,author,created_generation,created_at,updated_at) SELECT 'fixture-note-'||x,'lead','Resolve dependency question '||x,900000,100000,'Investigate','active','{}','fixture',published_generation,'fixture','fixture' FROM n,library_meta; INSERT INTO analysis_note_links(link_id,note_id,object_type,object_id,revision_chunk_id,span_start,span_end) SELECT 'fixture-note-link-'||n.note_id,n.note_id,'chunk',r.revision_chunk_id,r.revision_chunk_id,0,43 FROM analysis_notes n,revision_chunks r WHERE n.note_id LIKE 'fixture-note-%' AND r.visible_to_generation IS NULL;"
            COMMAND_ERROR_IS_FATAL ANY)
    endif()
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "SELECT (SELECT count(*) FROM revision_chunks)||':'||(SELECT group_concat(hex(vector)) FROM embeddings)||':'||(SELECT count(*) FROM revision_chunk_embeddings)||':'||(SELECT count(*) FROM provider_runs);"
        OUTPUT_VARIABLE before OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    file(READ "${work}/crexxrag.conf" config)
    set(window_items 1)
    set(batch_items 1)
    if(case STREQUAL "concurrent" OR case STREQUAL "budget" OR case STREQUAL "continuation" OR case STREQUAL "item-limit")
        set(window_items ${CPRAG_CONCURRENT_ITEMS})
        set(batch_items 10)
        if(case STREQUAL "budget" OR case STREQUAL "continuation" OR case STREQUAL "item-limit")
            set(window_items 4)
            set(batch_items 4)
        endif()
        math(EXPR input_ceiling "8192 * ${window_items}")
        math(EXPR output_ceiling "1024 * ${window_items}")
        if(case STREQUAL "continuation" OR case STREQUAL "item-limit")
            set(output_ceiling 16384)
        endif()
        string(REPLACE "budget.input_tokens = 8192" "budget.input_tokens = ${input_ceiling}" config "${config}")
        string(REPLACE "budget.output_tokens = 1024" "budget.output_tokens = ${output_ceiling}" config "${config}")
        string(APPEND config "\nprovider.gemini-generate.concurrent_requests = 2\n")
        if(CPRAG_CONCURRENT_ITEMS GREATER 40)
            # Explicit offline scale lane: no hosted credential or route.
            string(REPLACE "budget.minutes = 2" "budget.minutes = 60" config "${config}")
            string(APPEND config "\nprovider.gemini-generate.requests_per_minute = 60000\nprovider.gemini-generate.tokens_per_minute = 2000000000\n")
        endif()
    endif()
    set(window_calls ${window_items})
    if(case STREQUAL "budget")
        set(window_calls 2)
    endif()
    if(case STREQUAL "correction" OR case STREQUAL "correction-failed")
        set(window_calls 2)
        string(REPLACE "budget.input_tokens = 8192" "budget.input_tokens = 16384" config "${config}")
        string(REPLACE "budget.output_tokens = 1024" "budget.output_tokens = 2048" config "${config}")
    endif()
    string(REPLACE "budget.model_calls = 2" "budget.model_calls = ${window_calls}" config "${config}")
    string(REPLACE "budget.item_limit = 2" "budget.item_limit = ${window_items}" config "${config}")
    string(APPEND config "\nmaintenance.mode = ${maintenance_mode}\nmaintenance.batch_items = ${batch_items}\nmaintenance.maximum_attempts = 1\nmaintenance.resolution_prompt = fixture-resolution-prompt\n")
    file(WRITE "${work}/crexxrag.conf" "${config}")
    run_cli(config_plan --format json --access plan config plan --reason "bounded durable backlog fixture")
    string(JSON configuration_plan GET "${config_plan}" records 0 fields canonical_plan)
    string(JSON configuration_digest GET "${config_plan}" records 0 fields digest)
    run_cli(config_apply --access admin config apply --plan-json "${configuration_plan}" --expect-digest "${configuration_digest}")
    run_cli(explain --format json config explain)
    if(NOT explain MATCHES "resolution_prompt_sha256" OR NOT explain MATCHES "automatic_actions")
        message(FATAL_ERROR "configuration explanation omitted durable maintenance policy")
    endif()
    if(case STREQUAL "valid")
        # Timing controls are read-only until the reviewed plan is applied.
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT (SELECT count(*) FROM jobs)||':'||(SELECT count(*) FROM provider_runs);"
            OUTPUT_VARIABLE timing_before OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        run_cli(past --format json --access plan maintain plan --until 2000-01-01T06:00:00Z)
        run_cli(past_guided maintain --until=2000-01-01T06:00:00Z --yes)
        if(NOT past MATCHES "skipped" OR NOT past_guided MATCHES "skipped")
            message(FATAL_ERROR "past deadline did not skip cleanly: ${past}${past_guided}")
        endif()
        file(WRITE "${work}/timing-mcp.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_maintain_plan\",\"arguments\":{\"until\":\"2000-01-01T06:00:00Z\"}}}\n")
        execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --access plan serve mcp
            WORKING_DIRECTORY "${work}" INPUT_FILE "${work}/timing-mcp.jsonl"
            OUTPUT_VARIABLE timing_mcp ERROR_VARIABLE timing_mcp_err RESULT_VARIABLE timing_mcp_rc TIMEOUT 30)
        if(NOT timing_mcp_rc EQUAL 0 OR NOT timing_mcp MATCHES "skipped")
            message(FATAL_ERROR "MCP timing control failed: ${timing_mcp}${timing_mcp_err}")
        endif()
        run_cli(timing_plan --format json --access plan maintain plan --minutes 120)
        string(JSON resolved_timing GET "${timing_plan}" records 1 fields timing)
        string(JSON resolved_start GET "${resolved_timing}" started_epoch)
        string(JSON resolved_end GET "${resolved_timing}" deadline_epoch)
        math(EXPR elapsed_window "${resolved_end} - ${resolved_start}")
        string(JSON timed_plan GET "${timing_plan}" records 0 fields canonical_plan)
        string(JSON timed_policy GET "${timed_plan}" action window_policy)
        string(JSON saved_window GET "${timed_policy}" window_seconds)
        if(NOT saved_window EQUAL 7200)
            message(FATAL_ERROR "saved policy retained the configured duration instead of the requested duration")
        endif()
        if(NOT elapsed_window EQUAL 7200)
            message(FATAL_ERROR "duration was reduced by configured aggregate budget")
        endif()
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT (SELECT count(*) FROM jobs)||':'||(SELECT count(*) FROM provider_runs);"
            OUTPUT_VARIABLE timing_after OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        if(NOT timing_after STREQUAL timing_before)
            message(FATAL_ERROR "timing preview or skipped run mutated work")
        endif()
    endif()
    if(case STREQUAL "continuation" OR case STREQUAL "item-limit")
        run_cli(plan --format json --access plan maintain plan)
        string(JSON maintenance_plan GET "${plan}" records 0 fields canonical_plan)
        string(JSON maintenance_digest GET "${plan}" records 0 fields digest)
        run_cli(applied --format json --access curate maintain apply --plan-json "${maintenance_plan}" --expect-digest "${maintenance_digest}")
        string(JSON continuing_job GET "${applied}" records 0 fields job_id)
        set(batch_limit --max-polls)
        if(case STREQUAL "item-limit")
            set(batch_limit --max-items)
            # Hold real queued work until both workers have survived three
            # empty polls with an item allowance of one. Release by observed
            # state, not by guessing a provider delay or process startup time.
            execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
                "UPDATE job_items SET retry_at=2147483647 WHERE job_id='${continuing_job}' AND state='queued'; CREATE TABLE qa_idle_polls(instance_id TEXT PRIMARY KEY,polls INTEGER); CREATE TRIGGER qa_count_idle AFTER UPDATE ON runtime_instances WHEN NEW.kind='worker' AND NEW.state='idle' BEGIN INSERT INTO qa_idle_polls VALUES(NEW.instance_id,1) ON CONFLICT(instance_id) DO UPDATE SET polls=polls+1; END;"
                COMMAND_ERROR_IS_FATAL ANY)
            execute_process(COMMAND /bin/sh -c
                "( CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key CREXXRAG_SELF=\"$1\" \"$1\" --format json --access control worker start --poll-ms 20 --max-items 1 --job \"$2\"; printf '%s' $? >\"$5\" ) >\"$3\" 2>\"$4\" &"
                item-limit-test "${CPRAG_NATIVE_APPLICATION}" "${continuing_job}" "${work}/first.out" "${work}/first.err" "${work}/first.status"
                WORKING_DIRECTORY "${work}" COMMAND_ERROR_IS_FATAL ANY)
            set(waited FALSE)
            foreach(poll RANGE 1 400)
                execute_process(COMMAND "${CPRAG_SQLITE}" -cmd ".timeout 5000" "${database}"
                    "SELECT count(*) FROM qa_idle_polls WHERE polls>=3;"
                    OUTPUT_VARIABLE waiting OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
                if(waiting STREQUAL "2")
                    set(waited TRUE)
                    break()
                endif()
                execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
            endforeach()
            # Always release the test gate so a failed assertion cannot strand workers.
            execute_process(COMMAND "${CPRAG_SQLITE}" -cmd ".timeout 5000" "${database}"
                "UPDATE job_items SET retry_at=0 WHERE job_id='${continuing_job}' AND state='queued';"
                COMMAND_ERROR_IS_FATAL ANY)
            if(NOT waited)
                message(FATAL_ERROR "item-limited workers stopped during empty polls")
            endif()
            foreach(poll RANGE 1 400)
                if(EXISTS "${work}/first.status")
                    break()
                endif()
                execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
            endforeach()
            file(READ "${work}/first.status" first_status)
            file(READ "${work}/first.out" first)
            if(NOT first_status STREQUAL "0")
                message(FATAL_ERROR "item-limited worker group failed: ${first}")
            endif()
            execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
                "SELECT (SELECT count(*) FROM maintenance_decisions)||':'||(SELECT count(*) FROM runtime_instances r WHERE job_filter='${continuing_job}' AND kind='worker' AND state='stopped' AND exit_code=0 AND (SELECT count(*) FROM attempts a WHERE a.worker_id=r.instance_id AND a.outcome<>'cancelled')=1); DROP TRIGGER qa_count_idle; DROP TABLE qa_idle_polls;"
                OUTPUT_VARIABLE item_result OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
            if(NOT item_result STREQUAL "2:2")
                message(FATAL_ERROR "empty polls consumed the work allowance or workers exceeded it: ${item_result}")
            endif()
        else()
            run_cli(first --format json --access control worker start --max-polls 1 --job "${continuing_job}")
        endif()
        if(NOT first MATCHES "identical-no-op" OR NOT first MATCHES "\"vector_generations\":1")
            message(FATAL_ERROR "bounded worker group lost existing vector availability: ${first}")
        endif()
        run_cli(second --format json --access control worker start ${batch_limit} 1 --job "${continuing_job}")
        run_cli(finish --format json --access control worker start --max-polls 1 --job "${continuing_job}")
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT (SELECT count(*) FROM maintenance_windows)||':'||(SELECT count(*) FROM maintenance_decisions WHERE disposition='retain:resolved')||':'||(SELECT count(*) FROM job_items WHERE state IN('queued','running','cancel_requested','dead_letter'));"
            OUTPUT_VARIABLE continuation_result OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        if(NOT continuation_result STREQUAL "1:4:0")
            message(FATAL_ERROR "bounded worker groups did not continue one plan: ${continuation_result}")
        endif()
    elseif(case STREQUAL "budget")
        # Use the configured two-worker group, exactly as the nightly wrapper does.
        run_cli(maintain maintain --yes)
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT (SELECT count(*) FROM maintenance_windows WHERE state='budget-exhausted')||':'||(SELECT count(*) FROM maintenance_decisions WHERE disposition='retain:resolved')||':'||(SELECT count(*) FROM maintenance_tasks WHERE subject_id LIKE 'fixture-note%' AND state='pending')||':'||(SELECT count(*) FROM job_items WHERE state IN('queued','running','cancel_requested','dead_letter'))||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs);"
            OUTPUT_VARIABLE bounded_result OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        if(NOT bounded_result STREQUAL "1:2:2:0:0")
            message(FATAL_ERROR "budget boundary lost unfinished work or reported a failure: ${bounded_result}")
        endif()
        run_cli(resume maintain --yes)
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT (SELECT count(*) FROM maintenance_windows WHERE state='budget-exhausted')||':'||(SELECT count(*) FROM maintenance_decisions WHERE disposition='retain:resolved')||':'||(SELECT count(*) FROM job_items WHERE state IN('queued','running','cancel_requested','dead_letter'))||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs);"
            OUTPUT_VARIABLE resumed_result OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        file(READ "${work}/server.out" budget_server)
        if(NOT resumed_result STREQUAL "2:4:0:0" OR NOT budget_server MATCHES "barrier_pairs=2")
            message(FATAL_ERROR "fresh plan did not resume remaining work with two workers: ${resumed_result}\n${budget_server}")
        endif()
    else()
        run_cli(maintain maintain --yes --workers ${maintenance_workers})
    endif()
    run_cli(status --format json maintain status)
    run_cli(report --format json library report)
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "SELECT count(*) FROM maintenance_tasks WHERE state NOT IN('resolved','superseded');"
        OUTPUT_VARIABLE expected_open OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT report MATCHES "\"kind\":\"durable-maintenance-backlog\"" OR
       NOT report MATCHES "\"open_tasks\":${expected_open}[,}]")
        message(FATAL_ERROR "report omitted or miscounted durable tasks: ${report}")
    endif()
    if(case STREQUAL "manual")
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT count(*) FROM maintenance_tasks WHERE state='review';"
            OUTPUT_VARIABLE expected_review OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        if(expected_review LESS 1 OR NOT report MATCHES "\"review_tasks\":${expected_review}[,}]" OR
           NOT report MATCHES "\"dimension\":\"review\",\"state\":\"attention\"")
            message(FATAL_ERROR "manual review questions were reported healthy or omitted: ${report}")
        endif()
        run_cli(snapshot --format json --access read,control library snapshot --trigger maintenance --reason "Durable review census regression")
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT work_backlog||':'||pending_reviews FROM observation_snapshots ORDER BY sequence_number DESC LIMIT 1;"
            OUTPUT_VARIABLE observed_backlog OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        if(NOT observed_backlog STREQUAL "${expected_open}:${expected_review}")
            message(FATAL_ERROR "snapshot omitted durable work/reviews: ${observed_backlog}")
        endif()
    endif()
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "SELECT (SELECT count(*) FROM revision_chunks)||':'||(SELECT group_concat(hex(vector)) FROM embeddings)||':'||(SELECT count(*) FROM revision_chunk_embeddings)||':'||((SELECT count(*) FROM provider_runs)-${maintenance_calls});"
        OUTPUT_VARIABLE after OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "maintenance changed source/vector state or made an unexpected number of calls")
    endif()
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
        "SELECT state FROM maintenance_tasks WHERE kind='analysis-lead' AND subject_id='fixture-note';"
        OUTPUT_VARIABLE task_state OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(case MATCHES "^correction")
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT (SELECT count(*) FROM job_events WHERE event_type='citation-correction-requested')||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-response')||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs)||':'||(SELECT count(*) FROM job_items WHERE state='dead_letter');"
            OUTPUT_VARIABLE correction_result OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        set(expected_correction "1:4:0:0")
        set(expected_task resolved)
        if(case STREQUAL "correction-failed")
            set(expected_correction "1:4:0:1")
            set(expected_task unresolved)
            execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
                "SELECT semantic_failures||':'||required_capability||':'||escalation_origin FROM maintenance_tasks WHERE kind='analysis-lead' AND subject_id='fixture-note';"
                OUTPUT_VARIABLE escalation OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
            if(NOT escalation STREQUAL "2:advanced-reasoning:validation-failures")
                message(FATAL_ERROR "repeated invalid provider content did not flag advanced reasoning: ${escalation}")
            endif()
        elseif(case STREQUAL "correction-budget")
            set(expected_correction "1:3:0:0")
            set(expected_task pending)
        endif()
        if(NOT correction_result STREQUAL expected_correction OR NOT task_state STREQUAL expected_task)
            message(FATAL_ERROR "citation correction lost its one-call bound, receipt or outcome: ${correction_result}, task=${task_state}\n${maintain}${status}")
        endif()
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT job_id FROM job_events WHERE event_type='citation-correction-requested' LIMIT 1;"
            OUTPUT_VARIABLE correction_job OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        run_cli(correction_status --format json --access read job status "${correction_job}" --seconds 3600)
        string(JSON requested ERROR_VARIABLE missing_requested GET "${correction_status}" records 0 fields correction_requested_items)
        string(JSON corrected ERROR_VARIABLE missing_corrected GET "${correction_status}" records 0 fields correction_processed_items)
        set(expected_corrected 0)
        if(case STREQUAL "correction")
            set(expected_corrected 1)
        endif()
        if(missing_requested OR missing_corrected OR NOT requested EQUAL 1 OR NOT corrected EQUAL expected_corrected)
            message(FATAL_ERROR "Public correction status cannot distinguish requested and accepted corrections: ${correction_status}")
        endif()
    elseif(case STREQUAL "manual")
        if(NOT task_state STREQUAL "review")
            message(FATAL_ERROR "manual window did not collect its note question: ${task_state}")
        endif()
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}" "SELECT count(*) FROM maintenance_windows WHERE state='active';"
            OUTPUT_VARIABLE active_windows OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        if(NOT active_windows STREQUAL "0")
            message(FATAL_ERROR "guided manual census left a window active with no queued provider work")
        endif()
    elseif(case STREQUAL "valid" OR case STREQUAL "concurrent" OR case STREQUAL "budget" OR case STREQUAL "continuation" OR case STREQUAL "item-limit")
        if(NOT task_state STREQUAL "resolved")
            message(FATAL_ERROR "valid Gemini resolution was not applied: ${task_state}\n${maintain}${status}")
        endif()
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT task_id FROM maintenance_tasks WHERE subject_id='fixture-note';"
            OUTPUT_VARIABLE task_id OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        run_cli(inspect --format json maintain inspect "${task_id}")
        run_cli(task_evidence --format json maintain evidence "${task_id}" --limit 1)
        if(NOT inspect MATCHES "rag_task_evidence" OR NOT inspect MATCHES "retain:resolved" OR NOT task_evidence MATCHES "fixture-note-link" OR NOT task_evidence MATCHES "crexx-rag:.*:utf8-")
            message(FATAL_ERROR "durable task inspection or paged source evidence omitted evidence, citation or decision")
        endif()
        if(case STREQUAL "concurrent")
            execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
                "SELECT (SELECT count(*) FROM maintenance_decisions WHERE disposition='retain:resolved')||':'||(SELECT count(*) FROM job_items WHERE state NOT IN('processed','skipped'))||':'||(SELECT count(DISTINCT a.worker_id) FROM attempts a JOIN job_items i USING(item_id) WHERE i.item_type='maintenance-resolution')||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs);"
                OUTPUT_VARIABLE concurrent_result OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
            file(READ "${work}/server.out" concurrent_server)
            if(NOT concurrent_result STREQUAL "${CPRAG_CONCURRENT_ITEMS}:0:2:0" OR NOT concurrent_server MATCHES "barrier_pairs=${concurrent_pairs}")
                message(FATAL_ERROR "native concurrency/publication/accounting proof failed: ${concurrent_result}\n${concurrent_server}")
            endif()
            run_cli(verify --access diagnose library verify)
        endif()
    else()
        if(NOT task_state STREQUAL "failed")
            message(FATAL_ERROR "malformed response did not reach bounded failure: ${task_state}")
        endif()
        execute_process(COMMAND "${CPRAG_SQLITE}" "${database}"
            "SELECT recovery_json FROM provider_runs WHERE outcome='failed';"
            OUTPUT_VARIABLE diagnostic COMMAND_ERROR_IS_FATAL ANY)
        if(diagnostic MATCHES "synthetic-product-gemini-key")
            message(FATAL_ERROR "resolution failure diagnostic exposed a fixture credential")
        endif()
        if(case STREQUAL "rejected" AND (NOT diagnostic MATCHES "REDACTED" OR NOT diagnostic MATCHES "credential-redacted"))
            message(FATAL_ERROR "resolution failure diagnostic did not retain redacted evidence")
        endif()
    endif()
    execute_process(COMMAND "${CPRAG_SQLITE}" "${database}" "PRAGMA integrity_check; SELECT count(*) FROM pragma_foreign_key_check;"
        OUTPUT_VARIABLE integrity OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT integrity STREQUAL "ok\n0")
        message(FATAL_ERROR "durable backlog database integrity failure: ${integrity}")
    endif()
    if(NOT EXISTS "${work}/server.status")
        message(FATAL_ERROR "loopback did not finish its exact bounded requests")
    endif()
    file(READ "${work}/server.status" server_status)
    if(NOT server_status STREQUAL "0")
        message(FATAL_ERROR "durable backlog loopback failed")
    endif()
endforeach()
file(WRITE "${CPRAG_WORK_DIR}/result.txt" "Cases: ${CPRAG_CASES}. Concurrent gate: ${CPRAG_CONCURRENT_ITEMS} decisions, two actual workers, ${concurrent_pairs} forced overlapping request pairs, zero failed/unfinished items and zero outstanding reservations, preserved source/vector state and exact call accounting.\n")
