# Product recovery through the public native CLI and local Gemini protocol.
foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var})
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(sqlite_cli sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
set(documents 32)
set(requests 34)
set(scenario embedding-recovery)
if(CPRAG_EXHAUSTION)
    set(documents 2)
    set(requests 7)
    set(scenario embedding-exhaustion)
endif()
foreach(item RANGE 1 ${documents})
    file(WRITE "${CPRAG_WORK_DIR}/source/${item}.txt"
        "Document ${item}. BillingService depends on CustomerDatabase.\n")
endforeach()
set(CPRAG_FIXTURE_PORT 19031)
if(CPRAG_EXHAUSTION)
    set(CPRAG_FIXTURE_PORT 19032)
endif()
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
file(READ "${CPRAG_CONFIG_TEMPLATE}" config)
string(CONFIGURE "${config}" config @ONLY)
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 1000" config "${config}")
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 1000" config "${config}")
string(REPLACE "worker.processes = 2" "worker.processes = 8" config "${config}")
string(REPLACE "provider.gemini-embed.max_attempts = 1" "provider.gemini-embed.max_attempts = 6" config "${config}")
string(APPEND config "\nmaintenance.mode = automatic\nmaintenance.window_seconds = 180\nmaintenance.maximum_attempts = 6\nmaintenance.batch_items = 8\nprovider.gemini-embed.initial_backoff_ms = 1000\nprovider.gemini-embed.maximum_backoff_ms = 60000\nprovider.gemini-embed.jitter_ms = 0\nprovider.gemini-embed.concurrent_requests = 1\nprovider.gemini-embed.requests_per_minute = 1000\nprovider.gemini-embed.tokens_per_minute = 1000000\n")
file(WRITE "${CPRAG_WORK_DIR}/recovery.conf" "${config}")
set(library "${CPRAG_WORK_DIR}/library")
set(cli "${CMAKE_COMMAND}" -E env "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
    "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}"
    --library "${library}" --config-file "${CPRAG_WORK_DIR}/recovery.conf"
    --profile it-architecture-profile --format json --progress plain)
function(run_cli)
    execute_process(COMMAND ${cli} ${ARGN} RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 120)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\nstatus=${status}\n${output}${errors}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Embedding recovery command failed: ${ARGN}\n${output}${errors}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()
function(sql query expected)
    execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0 OR NOT output STREQUAL "${expected}")
        message(FATAL_ERROR "Embedding assertion: ${query}\nExpected ${expected}; got ${output}\n${errors}")
    endif()
endfunction()
run_cli(--access admin library init)
run_cli(--access plan ingest plan --source-set architecture-docs)
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
run_cli(--access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON ingestion GET "${last_output}" records 0 fields job_id)
run_cli(--access control job pause "${ingestion}")
run_cli(--access plan maintain plan --embeddings-only --minutes 3)
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
run_cli(--access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON job GET "${last_output}" records 0 fields job_id)
set(server_out "${CPRAG_WORK_DIR}/server.out")
set(server_err "${CPRAG_WORK_DIR}/server.err")
set(server_status "${CPRAG_WORK_DIR}/server.status")
execute_process(COMMAND /bin/sh -c
    "( \"$1\" \"$2\" ${requests} ${scenario}; printf '%s' $? >\"$5\" ) >\"$3\" 2>\"$4\" &"
    embedding-recovery "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}" "${server_out}" "${server_err}" "${server_status}")
foreach(poll RANGE 1 200)
    if(EXISTS "${server_out}")
        file(READ "${server_out}" output)
        if(output MATCHES "READY ${CPRAG_FIXTURE_PORT}")
            break()
        endif()
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
endforeach()
run_cli(--access control worker start --count 8 --job "${job}" --poll-ms 20)
file(STRINGS "${server_out}" observed_calls REGEX "^EMBEDDING_CALL ")
foreach(observed IN LISTS observed_calls)
    if(observed MATCHES "identity=([^ ]+) attempt=([0-9]+) status=([0-9]+) epoch_ms=([0-9]+)")
        string(SHA256 identity_key "${CMAKE_MATCH_1}")
        set(ordinal "${CMAKE_MATCH_2}")
        set(timestamp "${CMAKE_MATCH_4}")
        if(ordinal GREATER 1)
            math(EXPR spacing "${timestamp}-${last_${identity_key}}")
            math(EXPR required_spacing "1000 * (1 << (${ordinal}-2))")
            if(spacing LESS required_spacing)
                message(FATAL_ERROR "Retry ${ordinal} arrived early: ${spacing}ms < ${required_spacing}ms")
            endif()
        endif()
        set(last_${identity_key} "${timestamp}")
    endif()
endforeach()
if(CPRAG_EXHAUSTION)
    sql("SELECT count(*) FROM provider_runs WHERE outcome='failed';" "6")
    sql("SELECT count(*) FROM provider_runs WHERE outcome='succeeded';" "1")
    sql("SELECT count(*) FROM job_items WHERE job_id='${job}' AND state='dead_letter';" "1")
    sql("SELECT state FROM jobs WHERE job_id='${job}';" "completed_with_errors")
    sql("SELECT sum(reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns) FROM jobs;" "0")
    sql("SELECT count(*) FROM attempts WHERE outcome='running';" "0")
    # Represent a held phase-two task carrying prior provider history. The
    # next embedding window must preserve it and enforce the call ceiling
    # through a newly discovered embedding task, not the old failed task.
    sql("UPDATE maintenance_tasks SET kind='phase-two-held',state='pending' WHERE task_id IN(SELECT m.task_id FROM maintenance_task_items m JOIN job_items i USING(item_id) WHERE i.job_id='${job}' AND i.state='dead_letter');" "")
    # A fresh controller and a fresh maintenance window cannot reset six calls.
    run_cli(--access control worker start --count 8 --job "${job}" --poll-ms 20)
    run_cli(--access plan maintain plan --embeddings-only --minutes 3)
    string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
    string(JSON digest GET "${last_output}" records 0 fields digest)
    run_cli(--access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
    string(JSON second_job GET "${last_output}" records 0 fields job_id)
    run_cli(--access control worker start --count 8 --job "${second_job}" --poll-ms 20)
    sql("SELECT count(*) FROM provider_runs;" "7")
    sql("SELECT count(*) FROM maintenance_tasks WHERE kind='phase-two-held' AND state='pending';" "1")
    sql("SELECT count(*) FROM revision_chunks r WHERE NOT EXISTS(SELECT 1 FROM revision_chunk_embeddings e WHERE e.revision_chunk_id=r.revision_chunk_id AND e.visible_to_generation IS NULL);" "1")
    sql("SELECT state FROM jobs WHERE job_id='${ingestion}';" "paused")
    file(READ "${server_status}" server_exit)
    if(NOT server_exit STREQUAL "0")
        message(FATAL_ERROR "Exhaustion fixture did not observe exactly seven calls")
    endif()
    message(STATUS "EMBEDDING_EXHAUSTION_OK workers=8 calls=7 ceiling=6 restarts=preserved incomplete=reported")
    return()
endif()
sql("SELECT count(*) FROM job_items WHERE job_id='${job}' AND item_type='embedding' AND state='processed';" "32")
sql("SELECT count(*) FROM job_items WHERE job_id='${job}' AND item_type<>'embedding';" "0")
sql("SELECT count(*) FROM provider_runs WHERE outcome='succeeded';" "32")
sql("SELECT count(*) FROM provider_runs WHERE outcome='failed';" "2")
sql("SELECT count(*) FROM (SELECT item_id FROM attempts WHERE provider_run_id IS NOT NULL GROUP BY item_id HAVING count(DISTINCT provider_run_id)=3);" "1")
sql("SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state='queued';" "32")
sql("SELECT state FROM jobs WHERE job_id='${ingestion}';" "paused")
sql("SELECT count(*) FROM runtime_instances WHERE kind='worker' AND job_filter='${job}' AND state='stopped' AND exit_code=0;" "8")
sql("SELECT sum(reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns) FROM jobs;" "0")
sql("SELECT count(*) FROM attempts WHERE outcome='running';" "0")
sql("SELECT count(DISTINCT revision_chunk_id) FROM revision_chunk_embeddings WHERE visible_to_generation IS NULL;" "32")
# Run an independently queued stale embedding through the actual worker cache.
sql("INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,codex_turn_budget,created_at,updated_at) SELECT 'cache-job','cache-plan','{}',config_snapshot_id,'queued',1,1,input_token_budget,output_token_budget,cost_budget,codex_turn_budget,created_at,updated_at FROM jobs WHERE job_id='${ingestion}'; INSERT INTO job_items(item_id,job_id,item_type,state,priority,idempotency_key,input_hash,input_json,created_at,updated_at) SELECT 'cache-item','cache-job','embedding','queued',100,'cache-key',input_hash,input_json,created_at,updated_at FROM job_items WHERE job_id='${ingestion}' AND item_type='embedding' ORDER BY item_id LIMIT 1;" "")
sql("INSERT INTO job_events(job_id,event_type,message,occurred_at) SELECT 'cache-job',event_type,message,occurred_at FROM job_events WHERE job_id='${ingestion}' AND event_type='budget-policy';" "")
run_cli(--access control worker start --count 1 --job cache-job --max-items 1 --poll-ms 20)
sql("SELECT state FROM job_items WHERE item_id='cache-item';" "processed")
sql("SELECT count(*) FROM provider_runs;" "34")
sql("SELECT count(*) FROM revision_chunk_embeddings WHERE visible_to_generation IS NULL;" "32")
run_cli(--access control vector rebuild --reconcile)
sql("SELECT count(*) FROM job_items WHERE job_id='${ingestion}' AND item_type='embedding' AND state='skipped';" "32")
sql("SELECT count(*) FROM job_events WHERE event_type='embedding-reconciled';" "32")
run_cli(--access control vector rebuild --reconcile)
sql("SELECT count(*) FROM job_events WHERE event_type='embedding-reconciled';" "32")
sql("SELECT count(*) FROM provider_runs;" "34")
# Reproduce the historic duplicate shape in a new, retained generation.
sql("BEGIN IMMEDIATE; INSERT INTO published_generations(generation,parent_generation,state,config_snapshot_id,summary,created_at,published_at) SELECT m.next_generation,m.published_generation,'published',g.config_snapshot_id,'duplicate-membership fixture',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM library_meta m JOIN published_generations g ON g.generation=m.published_generation; INSERT INTO publication_events(generation,previous_generation,event_type,reason,occurred_at) SELECT next_generation,published_generation,'publish','duplicate fixture',strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM library_meta; UPDATE library_meta SET published_generation=next_generation,next_generation=next_generation+1; INSERT INTO revision_chunk_embeddings(revision_chunk_id,embedding_id,visible_from_generation) SELECT revision_chunk_id,embedding_id,(SELECT published_generation FROM library_meta) FROM revision_chunk_embeddings WHERE visible_to_generation IS NULL ORDER BY revision_chunk_id LIMIT 1; COMMIT;" "")
execute_process(COMMAND ${cli} --access diagnose library verify
    RESULT_VARIABLE verify_status OUTPUT_VARIABLE verify_output ERROR_VARIABLE verify_errors TIMEOUT 30)
if(verify_status EQUAL 0 OR NOT verify_output MATCHES "embedding-membership-duplicates")
    message(FATAL_ERROR "Verifier did not detect duplicate memberships: ${verify_output}${verify_errors}")
endif()
run_cli(--access control vector rebuild --reconcile)
sql("SELECT count(*) FROM revision_chunk_embeddings;" "33")
sql("SELECT count(*) FROM revision_chunk_embeddings WHERE visible_to_generation IS NULL;" "32")
sql("SELECT count(*) FROM revision_chunk_embeddings WHERE visible_to_generation IS NOT NULL;" "1")
sql("SELECT count(*) FROM provider_runs;" "34")
run_cli(--access diagnose library verify)
file(READ "${server_status}" server_exit)
if(NOT server_exit STREQUAL "0")
    message(FATAL_ERROR "Embedding fixture did not observe exactly 34 calls")
endif()
message(STATUS "EMBEDDING_RECOVERY_OK workers=8 batches=4 covered=32 calls=34 retries=2 extraction=held reconcile=idempotent")
