# RAG-SMK-006: finish missing embeddings while a partial ancestral index exists.
# Only the retained graph-only generation is seeded by SQL; embedding work,
# process ownership, publication and recovery use the public native commands.
foreach(required CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(sqlite_cli sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
foreach(item RANGE 1 2)
    file(WRITE "${CPRAG_WORK_DIR}/source/${item}.txt"
        "Document ${item}. BillingService depends on CustomerDatabase.\n")
endforeach()
set(CPRAG_FIXTURE_PORT 19051)
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
file(READ "${CPRAG_CONFIG_TEMPLATE}" config)
string(CONFIGURE "${config}" config @ONLY)
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 10" config "${config}")
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 10" config "${config}")
string(APPEND config "\nmaintenance.mode = automatic\nmaintenance.window_seconds = 180\nmaintenance.batch_items = 2\n")
file(WRITE "${CPRAG_WORK_DIR}/publication.conf" "${config}")
set(library "${CPRAG_WORK_DIR}/library")
set(cli "${CMAKE_COMMAND}" -E env "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
    "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}"
    --library "${library}" --config-file "${CPRAG_WORK_DIR}/publication.conf"
    --profile it-architecture-profile --format json --progress plain)
function(call_cli)
    execute_process(COMMAND ${cli} ${ARGN} RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\nstatus=${status}\n${output}${errors}\n")
    set(last_status "${status}" PARENT_SCOPE)
    set(last_output "${output}" PARENT_SCOPE)
endfunction()
function(run_cli)
    call_cli(${ARGN})
    if(NOT last_status EQUAL 0)
        message(FATAL_ERROR "Publication command failed: ${ARGN}\n${last_output}")
    endif()
    set(last_output "${last_output}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${sqlite_cli}" -cmd ".timeout 5000" "${library}/library.sqlite" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE errors OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Publication fixture SQL failed: ${errors}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
function(expect actual expected label)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(SEND_ERROR "${label}: expected '${expected}', got '${actual}'")
    endif()
endfunction()
run_cli(--access admin library init)
run_cli(--access plan ingest plan --source-set architecture-docs)
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
run_cli(--access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON ingestion GET "${last_output}" records 0 fields job_id)
run_cli(--access control job pause "${ingestion}")
run_cli(--access plan maintain plan --embeddings-only --minutes 3)
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
run_cli(--access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON job GET "${last_output}" records 0 fields job_id)
execute_process(COMMAND /bin/sh -c
    "( \"$1\" \"$2\" 2 product; printf '%s' $? >\"$5\" ) >\"$3\" 2>\"$4\" &"
    embedding-publication "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}"
    "${CPRAG_WORK_DIR}/server.out" "${CPRAG_WORK_DIR}/server.err" "${CPRAG_WORK_DIR}/server.status")
set(ready FALSE)
foreach(poll RANGE 1 200)
    if(EXISTS "${CPRAG_WORK_DIR}/server.out")
        file(READ "${CPRAG_WORK_DIR}/server.out" output)
        if(output MATCHES "READY ${CPRAG_FIXTURE_PORT}")
            set(ready TRUE)
            break()
        endif()
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
endforeach()
if(NOT ready)
    message(FATAL_ERROR "Publication loopback provider did not start")
endif()
run_cli(--access control worker run --once --job "${job}")
run_cli(--access control job pause "${job}")
run_cli(--access control vector rebuild)
string(JSON partial GET "${last_output}" records 0 fields rows)
expect("${partial}" "1" "partial publication positive control")
sql(ignored "BEGIN IMMEDIATE; INSERT INTO published_generations(generation,parent_generation,state,config_snapshot_id,summary,created_at,published_at) SELECT m.next_generation,m.published_generation,'published',g.config_snapshot_id,'graph-only fixture',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM library_meta m JOIN published_generations g ON g.generation=m.published_generation; INSERT INTO publication_events(generation,previous_generation,event_type,reason,occurred_at) SELECT next_generation,published_generation,'publish','graph-only fixture',strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM library_meta; UPDATE library_meta SET published_generation=next_generation,next_generation=next_generation+1; COMMIT;")
run_cli(--access admin library migrate)
run_cli(--access diagnose library verify)
sql(before "SELECT (SELECT count(*) FROM revision_chunk_embeddings)||':'||(SELECT count(*) FROM provider_runs)||':'||(SELECT row_count FROM vector_generations WHERE state='published')||':'||(SELECT count(*) FROM vector_generations v JOIN library_meta m ON v.semantic_generation<m.published_generation WHERE v.state='published');")
expect("${before}" "1:1:1:1" "aligned partial ancestral index positive control")
message(STATUS "PARTIAL_ANCESTRAL_CONTROL_OK")
call_cli(--access control job run "${job}" --count 1 --poll-ms 20)
file(WRITE "${CPRAG_WORK_DIR}/automatic-result.json" "${last_output}")
expect("${last_status}" "0" "RAG-SMK-006 automatic publication after repair")
call_cli(--access diagnose library verify)
expect("${last_status}" "0" "RAG-SMK-006 automatic manifest integrity")
sql(after "SELECT (SELECT count(*) FROM revision_chunk_embeddings)||':'||(SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM job_items WHERE job_id='${job}' AND state='processed')||':'||(SELECT count(*) FROM vector_generations WHERE state='published' AND row_count=2)||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns) FROM jobs);")
expect("${after}" "2:2:2:1:0" "RAG-SMK-006 coverage publication receipts reservations")
# Always complete scratch recovery before returning accumulated failures.
run_cli(--access control vector rebuild)
run_cli(--access diagnose library verify)
set(history_sql "SELECT * FROM attempts ORDER BY attempt_id; SELECT * FROM provider_runs ORDER BY provider_run_id; SELECT * FROM revision_chunk_embeddings ORDER BY 1,2,3;")
sql(history_before "${history_sql}")
# A repeat completes finalization without redoing completed provider work.
call_cli(--access control job run "${job}" --count 1 --max-polls 1)
expect("${last_status}" "0" "terminal job run is an idempotent completion retry")
# Remove the derived projection and reject its replacement after work commits.
file(REMOVE "${library}/manifest.json")
file(MAKE_DIRECTORY "${library}/manifest.json.new")
call_cli(--access control job run "${job}" --count 1 --poll-ms 20 --max-polls 1)
expect("${last_status}" "8" "rejected manifest publication remains an error")
sql(history_rejected "${history_sql}")
expect("${history_rejected}" "${history_before}" "rejected publication preserves committed work and receipts")
file(REMOVE_RECURSE "${library}/manifest.json.new")
run_cli(--access control job run "${job}" --count 1 --poll-ms 20 --max-polls 1)
run_cli(--access diagnose library verify)
sql(history_after "${history_sql}")
expect("${history_after}" "${history_before}" "repeated completed job makes no provider call or work change")
sql(cleanup "SELECT (SELECT count(*) FROM runtime_instances WHERE state NOT IN('stopped','failed'))||':'||(SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state='queued')||':'||(SELECT state FROM jobs WHERE job_id='${ingestion}');")
expect("${cleanup}" "0:2:paused" "workers drained and extraction stays paused")
file(READ "${CPRAG_WORK_DIR}/server.status" server_status)
expect("${server_status}" "0" "exactly two loopback provider calls")
message(STATUS "PUBLICATION_RECOVERY_CONTROLS_CHECKED calls=2 history=preserved; errors above remain failures")
