foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(CPRAG_SQLITE sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source/nested/deep")
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
set(CPRAG_FIXTURE_PORT 1)
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
foreach(path IN ITEMS wanted.txt extra.txt note.md nested/wanted.txt nested/extra.md nested/deep/last.txt ignored.pdf)
    file(WRITE "${CPRAG_FIXTURE_SOURCE}/${path}" "Historical evidence from ${path}.\n")
endforeach()
configure_file("${CPRAG_CONFIG_TEMPLATE}" "${CPRAG_WORK_DIR}/template.conf" @ONLY)
file(READ "${CPRAG_WORK_DIR}/template.conf" template)
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 100" template "${template}")
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 100" template "${template}")
string(REPLACE "budget.input_tokens = 8192" "budget.input_tokens = 1000000" template "${template}")
string(REPLACE "budget.output_tokens = 1024" "budget.output_tokens = 1000000" template "${template}")

function(cli output)
    execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --config-file "${config}"
        --library "${library}" --format json ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail TIMEOUT 30)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\n${result}${detail}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "folder include command failed (see commands.log):\n${result}${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(check_selection name patterns expected)
    set(config "${CPRAG_WORK_DIR}/${name}.conf")
    set(library "${CPRAG_WORK_DIR}/${name}-library")
    string(REPLACE "source.architecture-docs.include = **/*.txt"
        "source.architecture-docs.include = ${patterns}" candidate "${template}")
    file(WRITE "${config}" "${candidate}")
    cli(initialized init)
    cli(planned --access plan ingest plan --source-set architecture-docs)
    string(JSON plan GET "${planned}" records 0 fields canonical_plan)
    string(JSON digest GET "${planned}" records 0 fields digest)
    string(JSON domain GET "${plan}" action ingest_plan)
    string(JSON count LENGTH "${domain}" observations)
    set(keys)
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON key GET "${domain}" observations ${index} stable_key)
            list(APPEND keys "${key}")
        endforeach()
    endif()
    list(JOIN keys "|" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "${name}: include=${patterns}; expected [${expected}], observed [${actual}]")
    endif()
    # Apply must use the same filter. Excluded changes must not stale the plan.
    file(WRITE "${CPRAG_FIXTURE_SOURCE}/ignored.pdf" "Excluded bytes changed after planning.\n")
    if(name STREQUAL "exact")
        file(WRITE "${CPRAG_FIXTURE_SOURCE}/extra.txt" "Excluded supported bytes changed after planning.\n")
    endif()
    cli(applied --access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
    execute_process(COMMAND "${CPRAG_SQLITE}" "${library}/library.sqlite"
        "SELECT coalesce(group_concat(stable_key,'|'),'') FROM (SELECT stable_key FROM sources WHERE visible_to_generation IS NULL ORDER BY stable_key); SELECT count(*) FROM provider_runs;"
        RESULT_VARIABLE sql_status OUTPUT_VARIABLE stored ERROR_VARIABLE sql_error OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT sql_status EQUAL 0 OR NOT stored STREQUAL "${expected}\n0")
        message(FATAL_ERROR "${name}: stored selection or zero-provider-call assertion failed: ${stored} ${sql_error}")
    endif()
    file(APPEND "${CPRAG_WORK_DIR}/result.txt" "PASS ${name}: ${patterns} => ${actual}; apply matched; provider_calls=0\n")
endfunction()

# Passing positive control comes first, including nested supported files and
# an unsupported extension. Exact selection is the original Test 7 defect.
check_selection(all "**/*" "extra.txt|nested/deep/last.txt|nested/extra.md|nested/wanted.txt|note.md|wanted.txt")
check_selection(exact "wanted.txt" "wanted.txt")
check_selection(root "*.txt" "extra.txt|wanted.txt")
check_selection(recursive "**/*.txt" "extra.txt|nested/deep/last.txt|nested/wanted.txt|wanted.txt")
check_selection(nested "nested/*.txt" "nested/wanted.txt")
check_selection(nested_recursive "nested/**/*.txt" "nested/deep/last.txt|nested/wanted.txt")
check_selection(question "?anted.txt" "wanted.txt")
check_selection(multiple "wanted.txt,nested/*.md,wanted.*" "nested/extra.md|wanted.txt")
check_selection(case_sensitive "WANTED.txt" "")
check_selection(unsupported "ignored.pdf" "")
file(WRITE "${CPRAG_FIXTURE_SOURCE}/*wanted.txt" "A legal filename containing a wildcard character.\n")
check_selection(wildcard_filename "*ted.txt" "*wanted.txt|wanted.txt")
