# Included after real source-scoped maintenance planning/apply. No provider runs.
sql(ignored "UPDATE maintenance_windows SET policy_json=json_set(policy_json,'$.timing',json_set(json_extract(policy_json,'$.timing'),'$.started_epoch',unixepoch()-600)||'') WHERE job_id='${job}';")
set(unchanged_sql "SELECT json_object('job',json((SELECT json_object('state',state,'plan',canonical_plan,'config',config_snapshot_id,'items',item_budget,'calls',model_call_budget,'input',input_token_budget,'output',output_token_budget,'cost',cost_budget,'turns',codex_turn_budget) FROM jobs WHERE job_id='${job}')),'started_epoch',json_extract(json_extract(policy_json,'$.timing'),'$.started_epoch'),'policy',json(json_remove(policy_json,'$.timing')),'items',json((SELECT json_group_array(json_object('id',item_id,'input',input_json,'state',state,'fence',fence)) FROM job_items WHERE job_id='${job}'))) FROM maintenance_windows WHERE job_id='${job}';")
sql(before "${unchanged_sql}")
sql(until "SELECT strftime('%Y-%m-%dT%H:%M:%SZ','now','+4 hours');")
cli(4 --access read job deadline "${job}" --until "${until}")
cli(2 --access control job deadline "${job}" --until tomorrow)
cli(0 --access control job deadline "${job}" --until "${until}")
sql(after "${unchanged_sql}")
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Deadline-only update changed job, limits, scope or work")
endif()
sql(first "SELECT deadline_epoch||':'||policy_json FROM maintenance_windows WHERE job_id='${job}';")
file(WRITE "${CPRAG_WORK_DIR}/deadline.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{}}\n{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_job_deadline\",\"arguments\":{\"id\":\"${job}\",\"until\":\"${until}\"}}}\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --access control serve mcp WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/deadline.jsonl" OUTPUT_VARIABLE response ERROR_VARIABLE errors RESULT_VARIABLE status TIMEOUT 30)
if(NOT status EQUAL 0 OR NOT response MATCHES "deadline_epoch" OR response MATCHES "isError.:true")
    message(FATAL_ERROR "MCP deadline update failed: ${response}${errors}")
endif()
sql(second "SELECT deadline_epoch||':'||policy_json FROM maintenance_windows WHERE job_id='${job}';")
sql(events "SELECT count(*) FROM job_events WHERE job_id='${job}' AND event_type='deadline-update';")
if(NOT first STREQUAL second OR NOT events EQUAL 1)
    message(FATAL_ERROR "Repeated absolute deadline moved or duplicated update")
endif()
# An expired paused window can receive more time without another allowance.
sql(ignored "UPDATE jobs SET state='paused' WHERE job_id='${job}'; UPDATE maintenance_windows SET deadline_epoch=1,state='complete' WHERE job_id='${job}';")
cli(0 --access control job deadline "${job}" --until "${until}")
cli(0 --access control job continue "${job}" --prepare)
sql(result "SELECT (deadline_epoch=unixepoch('${until}'))||':'||json_extract(policy_json,'$.item_limit')||':'||(SELECT count(*) FROM job_events WHERE event_type='allowance-period')||':'||(SELECT count(*) FROM provider_runs) FROM maintenance_windows WHERE job_id='${job}';")
if(NOT result STREQUAL "1:100:0:0")
    message(FATAL_ERROR "Explicit deadline continuation changed scope/allowance: ${result}")
endif()
cli(0 --access control job cancel "${job}")
cli(6 --access control job continue "${job}" --prepare)
cli(6 --access control job deadline "${job}" --until "${until}")
message(STATUS "JOB_DEADLINE_CHECKED: CLI/MCP; no renewal; stable repeat; unchanged scope/history; cancelled control")
