# Public reset controls, ordinary retry selection and preserved durable history.
foreach(parent IN ITEMS first second)
    sql("INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at) SELECT '${parent}','${parent}-plan','{}',config_snapshot_id,'paused',10,20,8192,1024,1000000,'fixture','fixture' FROM config_snapshots LIMIT 1; INSERT INTO job_items(item_id,job_id,item_type,state,priority,fence,idempotency_key,input_hash,input_json,created_at,updated_at) VALUES('${parent}-item','${parent}','claim-extraction','dead_letter',1,3,'${parent}-key','hash','{}','fixture','fixture'); WITH RECURSIVE n(i) AS(VALUES(1) UNION ALL SELECT i+1 FROM n WHERE i<3) INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,started_at,completed_at) SELECT '${parent}-attempt-'||i,'${parent}-item','historic',i,'hash','transport timeout','failed','fixture','fixture' FROM n; INSERT INTO job_events(job_id,event_type,message,occurred_at) VALUES('${parent}','budget-policy','{\"maximum_attempts\":3}','fixture');" "")
    call_cli(json --access control job retry "${parent}" --item "${parent}-item")
    require_status(0)
    sql("SELECT disposition FROM retry_requests WHERE item_id='${parent}-item';" "attempt-limit")
endforeach()
execute_process(COMMAND "${sqlite_cli}" "${database}" "SELECT * FROM attempts ORDER BY attempt_id; SELECT job_id,canonical_plan,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget FROM jobs ORDER BY job_id;" OUTPUT_VARIABLE before)
call_cli(json --access read job reset-retries first)
require_status(4)
call_cli(json --access control job reset-retries)
require_status(2)
call_cli(json --access control job reset-retries first --all)
require_status(2)
call_cli(json --access control job reset-retries missing)
require_status(5)
call_cli(json --access control job reset-retries first)
require_status(0)
require_json(1 records 0 fields jobs_reset)
call_cli(json --access control job reset-retries first)
require_status(0)
require_json(0 records 0 fields jobs_reset)
call_mcp(rag_job_reset_retries "{\"id\":\"first\"}" control)
require_status(0)
require_json(0 records 0 fields jobs_reset)
call_cli(json --access control job retry first --item first-item)
require_status(0)
sql("SELECT disposition FROM retry_requests WHERE item_id='first-item';" "job-paused")
sql("SELECT disposition FROM retry_requests WHERE item_id='second-item';" "attempt-limit")
sql("SELECT count(*) FROM job_items WHERE state='dead_letter';" "2")
call_mcp(rag_job_reset_retries "{\"all\":true}" control)
require_status(0)
call_cli(json --access control job reset-retries --all)
require_status(0)
require_json(0 records 0 fields jobs_reset)
call_cli(json --access control job retry second --item second-item)
require_status(0)
sql("SELECT disposition FROM retry_requests WHERE item_id='second-item';" "job-paused")
execute_process(COMMAND "${sqlite_cli}" "${database}" "SELECT * FROM attempts ORDER BY attempt_id; SELECT job_id,canonical_plan,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget FROM jobs ORDER BY job_id;" OUTPUT_VARIABLE after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Retry reset erased history or changed budgets/inputs")
endif()
# A fresh failed attempt consumes the new allowance; reset did not disable it.
sql("WITH RECURSIVE n(i) AS(VALUES(4) UNION ALL SELECT i+1 FROM n WHERE i<6) INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,started_at,completed_at) SELECT 'new-attempt-'||i,'first-item','new-worker',i,'hash','transport timeout','failed','later','later' FROM n; UPDATE job_items SET fence=6 WHERE item_id='first-item';" "")
call_cli(json --access control job retry first --item first-item)
require_status(0)
sql("SELECT disposition FROM retry_requests WHERE item_id='first-item' AND state='pending';" "attempt-limit")
sql("SELECT count(*) FROM attempts;" "9")
sql("SELECT count(*) FROM provider_runs;" "0")
message(STATUS "JOB_RETRY_RESET_CHECKED: single/all; CLI/MCP; history and limits retained; renewed count exhausts normally")
