# Included by PublicRegression.cmake with its native/scratch fixture helpers.
file(READ "${CPRAG_CORPUS}" corpus)
string(JSON count LENGTH "${corpus}" documents)
math(EXPR last "${count}-1")
foreach(index RANGE 0 ${last})
    string(JSON name GET "${corpus}" documents ${index} name)
    string(JSON body GET "${corpus}" documents ${index} text)
    file(WRITE "${CPRAG_WORK_DIR}/source/${name}" "${body}")
endforeach()
call_cli(json --access plan ingest plan --source-set architecture-docs)
require_status(0)
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
call_cli(json --access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
require_status(0)
sql("SELECT count(*) FROM sources;" "6")
sql("SELECT count(*) FROM provider_runs;" "0")
sql("SELECT count(*) FROM concepts;" "0")
sql("SELECT count(*) FROM chunks_fts WHERE chunks_fts MATCH '\"Élodie\"';" "1")
sql("SELECT count(*) FROM chunks_fts WHERE chunks_fts MATCH '\"東京\"';" "1")
execute_process(COMMAND "${sqlite_cli}" "${database}" .dump
    OUTPUT_FILE "${CPRAG_WORK_DIR}/before.sql" RESULT_VARIABLE dump_status)
if(NOT dump_status EQUAL 0)
    message(FATAL_ERROR "Cannot snapshot query fixture")
endif()
file(SHA256 "${CPRAG_WORK_DIR}/before.sql" before_hash)

string(JSON count LENGTH "${corpus}" questions)
math(EXPR last "${count}-1")
foreach(index RANGE 0 ${last})
    string(JSON id GET "${corpus}" questions ${index} id)
    string(JSON question GET "${corpus}" questions ${index} question)
    string(JSON document GET "${corpus}" questions ${index} document)
    string(JSON known_issue ERROR_VARIABLE lookup GET "${corpus}" questions ${index} known_issue)
    if(lookup)
        set(known_issue "")
    elseif(CPRAG_CASE STREQUAL "retrieval")
        continue()
    endif()
    set(cli_citations)
    foreach(surface IN ITEMS json mcp)
        if(surface STREQUAL "mcp")
            # Take the JSON string from the frozen fixture without re-escaping it.
            string(JSON arguments GET "${corpus}" questions ${index})
            string(JSON arguments REMOVE "${arguments}" id)
            string(JSON arguments REMOVE "${arguments}" document)
            if(NOT known_issue STREQUAL "")
                string(JSON arguments REMOVE "${arguments}" known_issue)
            endif()
            call_mcp(rag_query_inspect "${arguments}" read)
        else()
            call_cli(json --access read query inspect "${question}")
        endif()
        require_status(0)
        require_json(0 records 0 fields provider_calls)
        string(JSON evidence GET "${last_output}" records 0 fields evidence_json)
        string(JSON claims LENGTH "${evidence}" claims)
        string(JSON passages LENGTH "${evidence}" passages)
        if(NOT claims EQUAL 0)
            message(FATAL_ERROR "${id}/${surface}: unextracted text became an accepted graph claim")
        endif()
        if(document STREQUAL "")
            if(NOT passages EQUAL 0)
                message(FATAL_ERROR "${id}/${surface}: absent term returned unrelated evidence")
            endif()
            continue()
        endif()
        if(passages LESS 1)
            if(NOT known_issue STREQUAL "")
                list(APPEND defects "${known_issue}: ${id}/${surface}: indexed literal name returns no passage")
                continue()
            endif()
            message(FATAL_ERROR "${id}/${surface}: missing independently specified passage ${document}")
        endif()
        file(READ "${CPRAG_WORK_DIR}/source/${document}" source_text)
        string(STRIP "${source_text}" expected_passage)
        set(found 0)
        set(citations)
        math(EXPR end "${passages}-1")
        foreach(row RANGE 0 ${end})
            string(JSON passage GET "${evidence}" passages ${row} text)
            string(FIND "${source_text}" "${passage}" start)
            if(passage STREQUAL expected_passage AND NOT start EQUAL -1)
                set(found 1)
                string(JSON citation GET "${evidence}" passages ${row} citation id)
                list(APPEND citations "${citation}")
                call_cli(json --access read citation show "${citation}")
                require_status(0)
                require_json("${passage}" records 0 fields text)
                require_json(utf8 records 0 fields span_unit)
                require_json("${start}" records 0 fields span_start)
                string(LENGTH "${passage}" bytes)
                math(EXPR span_end "${start}+${bytes}")
                require_json("${span_end}" records 0 fields span_end)
            endif()
        endforeach()
        if(NOT found)
            message(FATAL_ERROR "${id}/${surface}: returned evidence does not contain the expected source text")
        endif()
        if(surface STREQUAL "json")
            set(cli_citations "${citations}")
        elseif(NOT "${citations}" STREQUAL "${cli_citations}")
            message(FATAL_ERROR "${id}: CLI and MCP disagree on stable evidence identities")
        endif()
    endforeach()
endforeach()
execute_process(COMMAND "${sqlite_cli}" "${database}" .dump
    OUTPUT_FILE "${CPRAG_WORK_DIR}/after.sql" RESULT_VARIABLE dump_status)
file(SHA256 "${CPRAG_WORK_DIR}/after.sql" after_hash)
if(NOT dump_status EQUAL 0 OR NOT before_hash STREQUAL after_hash)
    message(FATAL_ERROR "Read-only inspection changed authoritative SQLite state")
endif()
message(STATUS "LEXICAL_REGRESSION_CHECKED case=${CPRAG_CASE} surfaces=2 provider_calls=0 writes=0 citation_offsets=utf8")
