foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(CPRAG_SQLITE sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
function(cli output expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
        "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}" ${ARGN}
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail TIMEOUT 60)
    file(APPEND "${work}/commands.log" "${ARGN}\n${result}${detail}\n")
    if(expected STREQUAL "success" AND NOT status EQUAL 0)
        message(FATAL_ERROR "receipt command failed: ${ARGN}\n${result}${detail}")
    endif()
    set(last_status "${status}" PARENT_SCOPE)
    set(${output} "${result}${detail}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${CPRAG_SQLITE}" -cmd ".timeout 5000" "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "receipt SQL failed: ${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
foreach(kind IN ITEMS embedding extraction)
    set(work "${CPRAG_WORK_DIR}/${kind}")
    file(MAKE_DIRECTORY "${work}/source")
    file(WRITE "${work}/source/architecture.txt" "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase.\n")
    set(CPRAG_FIXTURE_SOURCE "${work}/source")
    set(CPRAG_FIXTURE_GLOSSARY "${work}/glossary.tsv")
    file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\nconcept\tCustomerDatabase\tdata-store\n")
    set(CPRAG_FIXTURE_PORT 19049)
    set(fault_model gemini-embedding-2)
    if(kind STREQUAL "extraction")
        set(CPRAG_FIXTURE_PORT 19050)
        set(fault_model gemini-3.5-flash-lite)
    endif()
    configure_file("${CPRAG_CONFIG_TEMPLATE}" "${work}/crexxrag.conf" @ONLY)
    file(READ "${work}/crexxrag.conf" config)
    string(REPLACE "max_attempts = 1" "max_attempts = 3" config "${config}")
    file(WRITE "${work}/crexxrag.conf" "${config}")
    execute_process(COMMAND /bin/sh -c
        "( \"$1\" \"$2\" 2 product-ingestion; printf '%s' $? >\"$5\" ) >\"$3\" 2>\"$4\" &"
        receipt-test "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}"
        "${work}/server.out" "${work}/server.err" "${work}/server.status"
        COMMAND_ERROR_IS_FATAL ANY)
    set(ready FALSE)
    foreach(poll RANGE 1 200)
        if(EXISTS "${work}/server.out")
            file(READ "${work}/server.out" server)
            if(server MATCHES "READY ${CPRAG_FIXTURE_PORT}")
                set(ready TRUE)
                break()
            endif()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
    endforeach()
    if(NOT ready)
        message(FATAL_ERROR "receipt fixture did not become ready")
    endif()
    cli(init success init)
    set(database "${work}/library/library.sqlite")
    # Fail the receipt INSERT itself, after the provider has returned. This
    # cannot become an ordinary validation failure or lose incurred usage.
    sql(ignore "CREATE TRIGGER receipt_fault BEFORE INSERT ON job_events WHEN NEW.event_type='provider-response' AND json_extract(NEW.message,'$.model')='${fault_model}' BEGIN SELECT RAISE(ABORT,'injected receipt write failure'); END;")
    cli(interrupted any ingest --yes --workers 2)
    sql(job "SELECT job_id FROM jobs LIMIT 1;")
    sql(item "SELECT item_id FROM job_items WHERE item_type='${kind}';")
    if(kind STREQUAL "extraction")
        sql(item "SELECT item_id FROM job_items WHERE item_type='claim-extraction';")
    endif()
    sql(before "SELECT json_group_array(json_object('event',event_id,'attempt',attempt_id,'type',event_type,'body',message)) FROM job_events WHERE event_type='provider-intent';")
    sql(ignore "DROP TRIGGER receipt_fault;")
    cli(retry success --access control --format json job retry "${job}" --item "${item}" --reason "receipt storage repaired")
    if(NOT retry MATCHES "provider-outcome-uncertain")
        list(APPEND failures "${kind}: retry did not report an uncertain receipt: ${retry}")
    endif()
    # New controllers must hold the original item and finish its healthy peer.
    cli(restarted success --access control --format json job run "${job}" --count 2 --poll-ms 20 --max-polls 5)
    cli(again success --access control --format json job run "${job}" --count 2 --poll-ms 20 --max-polls 1)
    sql(after "SELECT json_group_array(json_object('event',event_id,'attempt',attempt_id,'type',event_type,'body',message)) FROM job_events WHERE event_type='provider-intent';")
    sql(state "SELECT (SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM job_items WHERE state IN('processed','skipped'))||':'||(SELECT count(*) FROM job_items WHERE state='dead_letter')||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns) FROM jobs)||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-response')||':'||(SELECT count(DISTINCT attempt_id) FROM job_events WHERE event_type='provider-outcome-uncertain')||':'||(SELECT count(*) FROM attempts WHERE item_id='${item}')||':'||(SELECT count(*) FROM provider_runs WHERE outcome='succeeded');")
    if(NOT state STREQUAL "2:1:1:0:1:1:1:1" OR NOT before STREQUAL after)
        list(APPEND failures "${kind}: receipt loss not held with original identity and healthy peer: ${state}")
    endif()
    sql(usage "SELECT sum(input_tokens)||':'||sum(output_tokens) FROM provider_runs;")
    if(NOT usage STREQUAL "204:60")
        list(APPEND failures "${kind}: original provider usage lost or doubled: ${usage}")
    endif()
    cli(status success --format json job status "${job}")
    if(NOT status MATCHES "provider outcome uncertain")
        list(APPEND failures "${kind}: public status concealed receipt loss: ${status}")
    endif()
    sql(integrity "PRAGMA integrity_check; SELECT count(*) FROM pragma_foreign_key_check;")
    if(NOT integrity STREQUAL "ok\n0")
        message(FATAL_ERROR "receipt library integrity failed: ${integrity}")
    endif()
    file(READ "${work}/server.out" server)
    if(NOT server MATCHES "connections=2")
        message(FATAL_ERROR "receipt fixture did not receive exactly two total calls: ${server}")
    endif()
endforeach()
if(failures)
    list(JOIN failures "\n" details)
    message(FATAL_ERROR "Receipt-write regression failures:\n${details}")
endif()
file(WRITE "${CPRAG_WORK_DIR}/result.txt" "Extraction and embedding receipt write failures preserve original usage, hold missing output across retry/controller restart, finish the healthy peer and make exactly two calls.\n")
