foreach(required CPRAG_NATIVE_APPLICATION CPRAG_PROBE CPRAG_MODEL CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
find_program(sqlite_cli sqlite3 REQUIRED)
set(offline)
if(APPLE)
    find_program(sandbox_exec sandbox-exec REQUIRED)
    set(offline "${sandbox_exec}" -p "(version 1) (allow default) (deny network*)")
endif()
execute_process(COMMAND ${offline} "${CPRAG_PROBE}" "${CPRAG_MODEL}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
file(WRITE "${CPRAG_WORK_DIR}/probe.log" "${output}${error}")
if(NOT result EQUAL 0 OR NOT output MATCHES "EMBEDDING_WINDOWS_OK")
    message(FATAL_ERROR "Native window contract failed: ${output}${error}")
endif()

set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
set(CPRAG_FIXTURE_PORT 1)
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
file(WRITE "${CPRAG_WORK_DIR}/window.profile.tsv"
    "format\tcrexx-rag.profile/1\nprofile\twindow-profile\t1\nconcept\tperson\nconcept\tplace\nrelationship\trelated-to\trelated-to\tfalse\nchunk\t6000\t180\tplain,markdown\nweight\tlexical\t1000000\nprompt\tadvisory\t1\twindow-advisory\nprompt\textractor\t1\twindow-extractor\nvalidator\tdirection-required\n")
string(REPEAT "The travellers sailed among the Hebrides and discussed the island's history. " 55 long_text)
file(WRITE "${CPRAG_WORK_DIR}/source/islands.txt" "${long_text}At the end of their voyage they visited the abbey on Iona.\n")
file(WRITE "${CPRAG_WORK_DIR}/source/edinburgh.txt" "Edinburgh Castle stands on Castle Rock above the city of Edinburgh.\n")
file(READ "${CPRAG_CONFIG_TEMPLATE}" config)
string(CONFIGURE "${config}" config @ONLY)
string(REPLACE "profiles = it-architecture-profile" "profiles = window-profile\nprofile.window-profile.file = ./window.profile.tsv" config "${config}")
string(REPLACE "discovery.mode = all" "discovery.mode = maintenance" config "${config}")
string(REPLACE "provider.gemini-embed.kind = gemini" "provider.gemini-embed.kind = llama" config "${config}")
string(REPLACE "provider.gemini-embed.base_url = http://127.0.0.1:1/gemini/v1beta" "provider.gemini-embed.base_url = llama://local" config "${config}")
string(REPLACE "provider.gemini-embed.model = gemini-embedding-2" "provider.gemini-embed.model = bge-small-en-v1.5\nprovider.gemini-embed.model_path = ${CPRAG_MODEL}" config "${config}")
string(REPLACE "provider.gemini-embed.credential = env:CPRAG_FIXTURE_GEMINI_KEY" "provider.gemini-embed.credential = none" config "${config}")
string(REPLACE "gemini-embed" "local-bge" config "${config}")
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 20" config "${config}")
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 20" config "${config}")
string(REPLACE "budget.input_tokens = 8192" "budget.input_tokens = 65536" config "${config}")
string(APPEND config "\nmaintenance.mode = automatic\nmaintenance.batch_items = 4\nmaintenance.window_seconds = 60\nvector.centroids = 1\nvector.probes = 1\n")
set(config_file "${CPRAG_WORK_DIR}/local.conf")
file(WRITE "${config_file}" "${config}")
set(library "${CPRAG_WORK_DIR}/library")
set(cli "${CMAKE_COMMAND}" -E env "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}"
    ${offline} "${CPRAG_NATIVE_APPLICATION}" --library "${library}"
    --config-file "${config_file}" --profile window-profile --format json --progress plain)
function(run_cli)
    execute_process(COMMAND ${cli} ${ARGN} RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\nstatus=${status}\n${output}${error}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Native embedding command failed: ${ARGN}\n${output}${error}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()
function(sql query expected)
    execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0 OR NOT output STREQUAL "${expected}")
        message(FATAL_ERROR "Native embedding assertion: ${query}\nexpected=${expected}; actual=${output}\n${error}")
    endif()
endfunction()
run_cli(config check)
# Native route validation must fail before a model can be called.
foreach(bad IN ITEMS model credential)
    if(bad STREQUAL "model")
        string(REPLACE "provider.local-bge.model = bge-small-en-v1.5" "provider.local-bge.model = unqualified-model" bad_config "${config}")
    else()
        string(REPLACE "provider.local-bge.credential = none" "provider.local-bge.credential = env:SHOULD_NOT_BE_USED" bad_config "${config}")
    endif()
    file(WRITE "${config_file}" "${bad_config}")
    execute_process(COMMAND ${cli} config check RESULT_VARIABLE status OUTPUT_VARIABLE rejected ERROR_VARIABLE error TIMEOUT 10)
    if(NOT "${status}" MATCHES "^[0-9]+$" OR status EQUAL 0)
        message(FATAL_ERROR "Native invalid ${bad} accepted: ${rejected}${error}")
    endif()
endforeach()
file(WRITE "${config_file}" "${config}")
run_cli(--access admin library init)
run_cli(--access plan ingest plan --source-set architecture-docs)
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
run_cli(--access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON job GET "${last_output}" records 0 fields job_id)
# Interrupt after the whole multi-vector response is durable but before its
# second link can commit. The same task must recover the saved complete list.
sql("UPDATE job_items SET priority=CASE WHEN json_extract(input_json,'$.text') LIKE 'The travellers%' THEN 1000 ELSE 0 END;CREATE TRIGGER window_link_fault BEFORE INSERT ON revision_chunk_embeddings WHEN (SELECT count(*) FROM revision_chunk_embeddings WHERE revision_chunk_id=NEW.revision_chunk_id)=1 BEGIN SELECT RAISE(ABORT,'injected second window link failure'); END;" "")
execute_process(COMMAND ${cli} --access control worker run --once --job "${job}"
    RESULT_VARIABLE status OUTPUT_VARIABLE interrupted ERROR_VARIABLE error TIMEOUT 30)
file(APPEND "${CPRAG_WORK_DIR}/commands.log" "receipt fault\nstatus=${status}\n${interrupted}${error}\n")
if(NOT "${status}" MATCHES "^[0-9]+$" OR status EQUAL 0)
    message(FATAL_ERROR "Second window link fault did not interrupt publication: ${interrupted}${error}")
endif()
sql("SELECT count(*) FROM embeddings" "0")
sql("SELECT count(*) FROM revision_chunk_embeddings" "0")
sql("SELECT count(*) FROM job_items WHERE state='processed'" "0")
sql("SELECT count(*) FROM job_events WHERE event_type='provider-response'" "1")
sql("DROP TRIGGER window_link_fault;UPDATE job_items SET lease_until=unixepoch()-1 WHERE state='running';" "")
run_cli(--access control job run "${job}")
sql("SELECT count(*) FROM provider_runs" "2")
sql("SELECT count(*) FROM job_events WHERE event_type='provider-response'" "2")
sql("SELECT count(*) FROM job_events WHERE event_type='provider-receipt-reused'" "1")
sql("SELECT count(*) FROM job_items WHERE state='processed' AND item_type='embedding'" "2")
sql("SELECT count(*) FROM revision_chunk_embeddings WHERE revision_chunk_id IN(SELECT revision_chunk_id FROM revision_chunks JOIN chunk_contents USING(content_id) WHERE text LIKE 'Edinburgh Castle%')" "1")
sql("SELECT count(*)>2 FROM embeddings" "1")
sql("SELECT count(*) FROM job_items WHERE item_type<>'embedding'" "0")
sql("SELECT count(*) FROM provider_runs WHERE charging_basis<>'local-compute'" "0")
run_cli(--access control vector rebuild)
run_cli(--access diagnose library verify)
run_cli(query evidence "Where is Edinburgh Castle?" --mode hybrid)
if(NOT last_output MATCHES "Edinburgh Castle stands on Castle Rock")
    message(FATAL_ERROR "Native query did not retrieve the castle source: ${last_output}")
endif()
# Seed one source-backed graph fact in this test-only library so replacement
# proves preservation of nonempty graph rows, not only zero counts.
sql("INSERT INTO concepts(concept_id,canonical_label,concept_type,lifecycle_state,visible_from_generation) VALUES('castle','Edinburgh Castle','place','active',1),('rock','Castle Rock','place','active',1);INSERT INTO claims(claim_id,source_concept_id,relationship_type,target_concept_id,direction,qualifiers_json,policy_version,visible_from_generation) VALUES('castle-rock','castle','related-to','rock','forward','{}','window-fixture',1);INSERT INTO claim_support(support_id,claim_id,revision_chunk_id,span_start,span_end,polarity,stance,directness,attribution,lineage_group,extractor_identity,visible_from_generation) SELECT 'castle-support','castle-rock',revision_chunk_id,0,length(CAST(text AS BLOB)),'positive','asserted','direct','','castle-lineage','window-fixture',1 FROM revision_chunks JOIN chunk_contents USING(content_id) WHERE text LIKE 'Edinburgh Castle%';" "")
execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite"
    "SELECT * FROM concepts ORDER BY concept_id;SELECT * FROM claims ORDER BY claim_id;SELECT * FROM claim_support ORDER BY support_id;"
    OUTPUT_VARIABLE before_graph OUTPUT_STRIP_TRAILING_WHITESPACE)
run_cli(--access diagnose library verify)
execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite"
    "SELECT group_concat(revision_chunk_id||':'||content_id||':'||normalized_start||':'||normalized_end,'|') FROM revision_chunks;SELECT count(*) FROM source_revisions;SELECT count(*) FROM claims;SELECT count(*) FROM claim_support;SELECT count(*) FROM embeddings;"
    OUTPUT_VARIABLE before OUTPUT_STRIP_TRAILING_WHITESPACE)

# A second profile exercises the exact public replacement workflow without a
# hosted model call. Old vectors/links remain; source and graph rows do not move.
string(REPLACE "local-bge" "replacement-bge" replacement_config "${config}")
file(WRITE "${config_file}" "${replacement_config}")
run_cli(--access plan config plan --reason "qualify embedding-only replacement")
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
run_cli(--access admin config apply --plan-json "${plan}" --expect-digest "${digest}")
run_cli(--access plan maintain plan --embeddings-only --minutes 1)
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
run_cli(--access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON replacement_job GET "${last_output}" records 0 fields job_id)
run_cli(--access control job run "${replacement_job}")
run_cli(--access control vector rebuild)
run_cli(--access diagnose library verify)
sql("SELECT count(*) FROM embedding_profiles" "2")
sql("SELECT count(*) FROM revision_chunks r WHERE (SELECT count(DISTINCT e.embedding_profile_id) FROM revision_chunk_embeddings l JOIN embeddings e USING(embedding_id) WHERE l.revision_chunk_id=r.revision_chunk_id)=2" "2")
execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite"
    "SELECT group_concat(revision_chunk_id||':'||content_id||':'||normalized_start||':'||normalized_end,'|') FROM revision_chunks;SELECT count(*) FROM source_revisions;SELECT count(*) FROM claims;SELECT count(*) FROM claim_support;SELECT count(*) FROM embeddings WHERE embedding_profile_id IN(SELECT embedding_profile_id FROM embedding_profiles WHERE provider_id='local-bge');"
    OUTPUT_VARIABLE after OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite"
    "SELECT * FROM concepts ORDER BY concept_id;SELECT * FROM claims ORDER BY claim_id;SELECT * FROM claim_support ORDER BY support_id;"
    OUTPUT_VARIABLE after_graph OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT before_graph STREQUAL after_graph)
    message(FATAL_ERROR "Replacement modified existing graph rows")
endif()
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Replacement changed source, graph or old vectors: ${before} / ${after}")
endif()
run_cli(query evidence "Where is Edinburgh Castle?" --mode hybrid)
# Repeating the same embedding-only maintenance is a no-op: no inference,
# duplicate links or lost state once the representation is complete.
run_cli(--access plan maintain plan --embeddings-only --minutes 1)
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
run_cli(--access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON noop_job GET "${last_output}" records 0 fields job_id)
run_cli(--access control job run "${noop_job}")
sql("SELECT count(*) FROM provider_runs WHERE provider_run_id IN(SELECT provider_run_id FROM attempts)" "4")
sql("SELECT count(*) FROM provider_runs" "6")
sql("SELECT count(*) FROM revision_chunk_embeddings GROUP BY revision_chunk_id,embedding_id HAVING count(*)>1" "")
sql("SELECT count(*) FROM pragma_foreign_key_check" "0")
file(WRITE "${CPRAG_WORK_DIR}/result.txt" "NATIVE_EMBEDDING_WINDOWS_OK offline=passed parents=2 windows=multiple replacement=complete sources=unchanged graph=unchanged old-vectors=retained\n")
message(STATUS "NATIVE_EMBEDDING_WINDOWS_OK")
