include("${CMAKE_CURRENT_LIST_DIR}/FixtureEndpoint.cmake")
foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(CPRAG_SQLITE sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
function(cli output expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
        "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}" ${ARGN}
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail TIMEOUT 60)
    file(APPEND "${work}/commands.log" "${ARGN}\nstatus=${status}\n${result}${detail}\n")
    if(expected STREQUAL "success" AND NOT status EQUAL 0)
        message(FATAL_ERROR "receipt command failed: ${ARGN}\n${result}${detail}")
    endif()
    if(expected STREQUAL "failure" AND (NOT "${status}" MATCHES "^[0-9]+$" OR status EQUAL 0))
        message(FATAL_ERROR "receipt fault did not produce a failure exit (${status}): ${ARGN}\n${result}${detail}")
    endif()
    set(${output} "${result}${detail}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${CPRAG_SQLITE}" -cmd ".timeout 5000" "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "receipt SQL failed: ${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
foreach(kind IN ITEMS embedding extraction)
    set(work "${CPRAG_WORK_DIR}/${kind}")
    file(MAKE_DIRECTORY "${work}/source")
    file(WRITE "${work}/source/architecture.txt" "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase.\n")
    set(CPRAG_FIXTURE_SOURCE "${work}/source")
    set(CPRAG_FIXTURE_GLOSSARY "${work}/glossary.tsv")
    file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\nconcept\tCustomerDatabase\tdata-store\n")
    set(CPRAG_FIXTURE_PORT 19040)
    set(fault_model gemini-embedding-2)
    if(kind STREQUAL "extraction")
        set(CPRAG_FIXTURE_PORT 19041)
        set(fault_model gemini-3.5-flash-lite)
    endif()
    set(CPRAG_FIXTURE_PORT 0)
configure_file("${CPRAG_CONFIG_TEMPLATE}" "${work}/crexxrag.conf" @ONLY)
    file(READ "${work}/crexxrag.conf" config)
    string(REPLACE "max_attempts = 1" "max_attempts = 3" config "${config}")
    # Repair the injected fault before explicitly restarting recovery workers.
    string(APPEND config "\nworker.max_restarts = 0\n")
    file(WRITE "${work}/crexxrag.conf" "${config}")
    execute_process(COMMAND /bin/sh -c
        "( \"$1\" \"$2\" 2 product-ingestion; printf '%s' $? >\"$5\" ) >\"$3\" 2>\"$4\" &"
        receipt-test "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}"
        "${work}/server.out" "${work}/server.err" "${work}/server.status"
        COMMAND_ERROR_IS_FATAL ANY)
    set(ready FALSE)
    foreach(poll RANGE 1 200)
        if(EXISTS "${work}/server.out")
            file(READ "${work}/server.out" server)
            if(server MATCHES "READY [0-9]+")
                set(ready TRUE)
                break()
            endif()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
    endforeach()
    if(NOT ready)
        message(FATAL_ERROR "receipt fixture did not become ready")
    endif()
crexxrag_fixture_endpoint("${work}/server.out" "${work}/crexxrag.conf")
    cli(init success init)
    set(database "${work}/library/library.sqlite")
    # Fault strictly after the raw response commit and before usage settlement.
    # The native worker exits, leaving its durable receipt and expired ownership.
    sql(ignore "CREATE TRIGGER receipt_fault BEFORE INSERT ON provider_runs WHEN NEW.model='${fault_model}' BEGIN SELECT RAISE(ABORT,'injected receipt settlement failure'); END;")
    cli(interrupted failure ingest --yes --workers 1)
    sql(receipts "SELECT count(*) FROM job_events WHERE event_type='provider-response' AND json_extract(message,'$.model')='${fault_model}';")
    sql(unsettled "SELECT count(*) FROM attempts a JOIN job_events e USING(attempt_id) WHERE e.event_type='provider-response' AND json_extract(e.message,'$.model')='${fault_model}' AND a.provider_run_id IS NULL;")
    if(NOT receipts STREQUAL "1" OR NOT unsettled STREQUAL "1")
        message(FATAL_ERROR "fault did not leave exactly one received, unsettled response: ${receipts}:${unsettled}\n${interrupted}")
    endif()
    sql(ignore "DROP TRIGGER receipt_fault; UPDATE job_items SET lease_until=unixepoch()-1 WHERE state='running';")
    cli(restarted success --access control --format json worker start --count 2 --poll-ms 20 --max-polls 10)
    sql(state "SELECT (SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM job_items WHERE state NOT IN('processed','skipped'))||':'||(SELECT count(*) FROM revision_chunk_embeddings)||':'||(SELECT count(*) FROM claims)||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs)||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-response')||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-receipt-reused');")
    if(NOT state STREQUAL "2:0:1:1:0:2:1")
        message(FATAL_ERROR "receipt recovery repeated paid work or lost publication/accounting: ${state}\n${restarted}")
    endif()
    sql(original "SELECT count(*) FROM attempts a JOIN job_events e USING(attempt_id) WHERE e.event_type='provider-response' AND json_extract(e.message,'$.model')='${fault_model}' AND a.outcome='expired' AND a.provider_run_id IS NOT NULL;")
    if(NOT original STREQUAL "1")
        message(FATAL_ERROR "recovered usage lost its original expired attempt")
    endif()
    sql(captured "SELECT count(*) FROM job_events WHERE event_type='provider-request' AND json_extract(message,'$.model') IN('gemini-embedding-2','gemini-3.5-flash-lite') AND json_extract(message,'$.availability')='retained' AND length(json_extract(message,'$.prompt_sha256'))=64;")
    if(NOT captured STREQUAL "2")
        message(FATAL_ERROR "original requests were not retained exactly once across receipt recovery: ${captured}")
    endif()
    sql(original_item "SELECT item_id FROM job_events WHERE event_type='provider-request' AND json_extract(message,'$.model')='gemini-3.5-flash-lite';")
    sql(original_attempt "SELECT attempt_id FROM job_events WHERE event_type='provider-request' AND item_id='${original_item}';")
    cli(request success --access read --format json job inspect "${original_item}" --attempt "${original_attempt}" --section request)
    if(NOT request MATCHES "BillingService" OR NOT request MATCHES "generate_structured" OR request MATCHES "synthetic-product-gemini-key")
        message(FATAL_ERROR "request inspection lost original evidence or exposed credentials: ${request}")
    endif()
    string(JSON original_digest GET "${request}" records 0 fields sha256)
    file(APPEND "${work}/crexxrag.conf" "\nrole.extractor.system_prompt = Changed current prompt after the completed call\n")
    cli(changed success --access read --format json job inspect "${original_item}" --attempt "${original_attempt}" --section request)
    string(JSON unchanged_digest GET "${changed}" records 0 fields sha256)
    if(NOT original_digest STREQUAL unchanged_digest OR changed MATCHES "Changed current prompt")
        message(FATAL_ERROR "Inspection reconstructed historical input from today's prompt")
    endif()
    # Recovery retains exactly the original measured receipt time. An ordinary
    # settled call now measures its whole provider step, so it may exceed the
    # transport envelope latency; it must never lose that time or admission wait.
    sql(time_errors "SELECT count(*) FROM attempts a JOIN provider_runs p USING(provider_run_id) JOIN job_events e ON e.attempt_id=a.attempt_id AND e.event_type='provider-response' JOIN provider_admissions d ON d.attempt_id=a.attempt_id WHERE (a.outcome='expired' AND p.duration_ms<>CAST(json_extract(e.message,'$.latency_us') AS INTEGER)/1000+d.wait_ms) OR p.duration_ms<CAST(json_extract(e.message,'$.latency_us') AS INTEGER)/1000+d.wait_ms OR p.duration_ms>15000 OR d.lease_until_epoch-d.admitted_epoch<>40;")
    if(NOT time_errors STREQUAL "0")
        message(FATAL_ERROR "receipt duration, full provider-step timing or lease conversion is incorrect: ${time_errors}")
    endif()
    cli(rebuild success --access control --format json vector rebuild)
    cli(verify success --access diagnose library verify)
    file(READ "${work}/server.out" server)
    if(NOT server MATCHES "connections=2")
        message(FATAL_ERROR "receipt fixture did not receive exactly two total network calls: ${server}")
    endif()
    file(WRITE "${work}/result.txt" "Native ${kind} response survived worker exit before settlement; two replacement workers recovered it without another outbound call, linked usage to the expired attempt, published valid knowledge, and released all reservations.\n")
endforeach()
