foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(CPRAG_SQLITE sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
function(cli output)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
        "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}" ${ARGN}
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail TIMEOUT 30)
    file(APPEND "${work}/commands.log" "${ARGN}\n${result}${detail}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "interruption command failed: ${ARGN}\n${result}${detail}")
    endif()
    set(${output} "${result}${detail}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${CPRAG_SQLITE}" -cmd ".timeout 5000" "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "interruption SQL failed: ${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
function(await_file file pattern)
    foreach(poll RANGE 1 400)
        if(EXISTS "${file}")
            file(READ "${file}" contents)
            if(contents MATCHES "${pattern}")
                return()
            endif()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
    endforeach()
    message(FATAL_ERROR "interruption rendezvous missing: ${file} ${pattern}")
endfunction()
foreach(kind IN ITEMS killed_intent cancellation manifest_failure)
    set(work "${CPRAG_WORK_DIR}/${kind}")
    file(MAKE_DIRECTORY "${work}/source")
    file(WRITE "${work}/source/architecture.txt" "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase.\n")
    set(CPRAG_FIXTURE_SOURCE "${work}/source")
    set(CPRAG_FIXTURE_GLOSSARY "${work}/glossary.tsv")
    file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\nconcept\tCustomerDatabase\tdata-store\n")
    set(CPRAG_FIXTURE_PORT 19042)
    set(scenario product-hold-response)
    set(requests 1)
    set(control "${work}/release.fifo")
    if(kind STREQUAL "cancellation")
        set(CPRAG_FIXTURE_PORT 19043)
    elseif(kind STREQUAL "manifest_failure")
        set(CPRAG_FIXTURE_PORT 19044)
        set(scenario product-manifest-fault)
        set(requests 2)
        set(control "${work}/library/manifest.json.new")
    endif()
    if(NOT kind STREQUAL "manifest_failure")
        execute_process(COMMAND mkfifo "${control}" COMMAND_ERROR_IS_FATAL ANY)
    endif()
    configure_file("${CPRAG_CONFIG_TEMPLATE}" "${work}/crexxrag.conf" @ONLY)
    file(READ "${work}/crexxrag.conf" config)
    string(REPLACE "max_attempts = 1" "max_attempts = 3" config "${config}")
    file(WRITE "${work}/crexxrag.conf" "${config}")
    execute_process(COMMAND /bin/sh -c
        "( \"$1\" \"$2\" \"$3\" \"$4\" \"$5\"; printf '%s' $? >\"$8\" ) >\"$6\" 2>\"$7\" &"
        interruption-test "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}" "${requests}" "${scenario}" "${control}"
        "${work}/server.out" "${work}/server.err" "${work}/server.status" COMMAND_ERROR_IS_FATAL ANY)
    await_file("${work}/server.out" "READY ${CPRAG_FIXTURE_PORT}")
    cli(init init)
    set(database "${work}/library/library.sqlite")
    execute_process(COMMAND /bin/sh -c
        "( CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key CREXXRAG_SELF=\"$1\" \"$1\" ingest --yes --workers 1; printf '%s' $? >\"$4\" ) >\"$2\" 2>\"$3\" &"
        interruption-test "${CPRAG_NATIVE_APPLICATION}" "${work}/ingest.out" "${work}/ingest.err" "${work}/ingest.status"
        WORKING_DIRECTORY "${work}" COMMAND_ERROR_IS_FATAL ANY)
    if(kind STREQUAL "manifest_failure")
        await_file("${work}/server.out" "MANIFEST_FAULT_READY")
        await_file("${work}/ingest.status" "[0-9]")
        sql(state "SELECT (SELECT count(*) FROM claims)||':'||(SELECT count(*) FROM job_items WHERE state='processed')||':'||(SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM job_items WHERE state='dead_letter');")
        if(NOT state STREQUAL "1:1:1:0")
            message(FATAL_ERROR "post-commit projection failure retried or discarded committed work: ${state}")
        endif()
        file(REMOVE_RECURSE "${control}")
        cli(complete --access control --format json worker start --count 2 --poll-ms 20 --max-polls 10)
        cli(recovery --access control --format json vector rebuild)
        cli(verify --access diagnose library verify)
        cli(query --format json query evidence "BillingService depends on CustomerDatabase" --mode lexical)
        if(NOT query MATCHES "BillingService" OR NOT query MATCHES "\"provider_calls\":0")
            message(FATAL_ERROR "post-commit recovery did not retain source evidence")
        endif()
    else()
        await_file("${work}/server.out" "RESPONSE_HELD")
        sql(job "SELECT job_id FROM jobs LIMIT 1;")
        if(kind STREQUAL "cancellation")
            cli(cancel --access control job cancel "${job}" --reason "cancel during admitted native provider call")
        else()
            # Kill only PIDs registered by this newly created test library.
            sql(pids "SELECT group_concat(pid,';') FROM (SELECT pid FROM runtime_instances WHERE state IN('idle','running','starting') ORDER BY CASE kind WHEN 'controller' THEN 0 ELSE 1 END);")
            foreach(pid IN LISTS pids)
                execute_process(COMMAND /bin/kill -KILL "${pid}" RESULT_VARIABLE killed ERROR_QUIET)
            endforeach()
        endif()
        execute_process(COMMAND /bin/sh -c "printf R >\"$1\"" interruption-release "${control}" TIMEOUT 5 COMMAND_ERROR_IS_FATAL ANY)
        await_file("${work}/ingest.status" "[0-9]")
        if(kind STREQUAL "cancellation")
            sql(state "SELECT (SELECT state FROM jobs)||':'||(SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM revision_chunk_embeddings)||':'||(SELECT count(*) FROM job_items WHERE state='cancelled')||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs);")
            if(NOT state STREQUAL "cancelled:1:0:2:0")
                message(FATAL_ERROR "native cancellation lost usage, published a result or leaked ownership: ${state}")
            endif()
        else()
            sql(ignore "UPDATE job_items SET lease_until=unixepoch()-1 WHERE state='running';")
            cli(restart --access control --format json worker start --count 2 --poll-ms 20 --max-polls 5)
            sql(state "SELECT (SELECT state FROM jobs)||':'||(SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-intent')||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-response')||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-outcome-uncertain')||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs);")
            if(NOT state STREQUAL "paused:0:1:0:1:0")
                message(FATAL_ERROR "killed request was silently repeated or uncertainty lost: ${state}")
            endif()
            cli(events --format json job events "${job}")
            if(NOT events MATCHES "provider-outcome-uncertain")
                message(FATAL_ERROR "uncertain external result is not operator-visible")
            endif()
        endif()
    endif()
    await_file("${work}/server.status" "0")
    sql(integrity "PRAGMA integrity_check; SELECT count(*) FROM pragma_foreign_key_check;")
    if(NOT integrity STREQUAL "ok\n0")
        message(FATAL_ERROR "interrupted library failed integrity: ${integrity}")
    endif()
    file(WRITE "${work}/result.txt" "Native ${kind} reached its deterministic provider/commit boundary and preserved accounting, fencing, source data and inspectable recovery state.\n")
endforeach()
