foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(CPRAG_SQLITE sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
function(cli output)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
        "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}" ${ARGN}
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail TIMEOUT 30)
    file(APPEND "${work}/commands.log" "${ARGN}\n${result}${detail}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "interruption command failed: ${ARGN}\n${result}${detail}")
    endif()
    set(${output} "${result}${detail}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${CPRAG_SQLITE}" -cmd ".timeout 5000" "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "interruption SQL failed: ${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
function(await_file file pattern)
    foreach(poll RANGE 1 400)
        if(EXISTS "${file}")
            file(READ "${file}" contents)
            if(contents MATCHES "${pattern}")
                return()
            endif()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
    endforeach()
    message(FATAL_ERROR "interruption rendezvous missing: ${file} ${pattern}")
endfunction()
# New controller/restart cases reuse the same real-process/provider rendezvous.
# The original interruption gate keeps its original three cases.
if(NOT DEFINED CPRAG_CASES)
    set(CPRAG_CASES killed_intent cancellation manifest_failure)
endif()
function(process_exited output pid)
    execute_process(COMMAND ps -p "${pid}" -o stat= OUTPUT_VARIABLE state ERROR_QUIET)
    string(STRIP "${state}" state)
    if(state STREQUAL "" OR state MATCHES "^Z")
        set(${output} TRUE PARENT_SCOPE)
    else()
        set(${output} FALSE PARENT_SCOPE)
    endif()
endfunction()
function(await_exit output pid)
    foreach(poll RANGE 1 400)
        process_exited(exited "${pid}")
        if(exited)
            set(${output} TRUE PARENT_SCOPE)
            return()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.025)
    endforeach()
    set(${output} FALSE PARENT_SCOPE)
endfunction()
function(expect actual expected label)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(SEND_ERROR "${label}: expected '${expected}', got '${actual}'")
    endif()
endfunction()
foreach(kind IN LISTS CPRAG_CASES)
    if(NOT kind MATCHES "^(killed_intent|cancellation|manifest_failure|controller_loss|restart_live)$")
        message(FATAL_ERROR "Unknown interruption case: ${kind}")
    endif()
    set(work "${CPRAG_WORK_DIR}/${kind}")
    file(MAKE_DIRECTORY "${work}/source")
    file(WRITE "${work}/source/architecture.txt" "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase.\n")
    set(CPRAG_FIXTURE_SOURCE "${work}/source")
    set(CPRAG_FIXTURE_GLOSSARY "${work}/glossary.tsv")
    file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\nconcept\tCustomerDatabase\tdata-store\n")
    set(CPRAG_FIXTURE_PORT 19042)
    set(scenario product-hold-response)
    set(requests 1)
    if(kind STREQUAL "killed_intent" OR kind STREQUAL "restart_live")
        set(requests 2)
    endif()
    set(control "${work}/release.fifo")
    if(kind STREQUAL "cancellation")
        set(CPRAG_FIXTURE_PORT 19043)
    elseif(kind STREQUAL "manifest_failure")
        set(CPRAG_FIXTURE_PORT 19044)
        set(scenario product-manifest-fault)
        set(requests 2)
        set(control "${work}/library/manifest.json.new")
    endif()
    if(kind STREQUAL "controller_loss")
        set(CPRAG_FIXTURE_PORT 19180)
    elseif(kind STREQUAL "restart_live")
        set(CPRAG_FIXTURE_PORT 19181)
    endif()
    if(NOT kind STREQUAL "manifest_failure")
        execute_process(COMMAND mkfifo "${control}" COMMAND_ERROR_IS_FATAL ANY)
    endif()
    configure_file("${CPRAG_CONFIG_TEMPLATE}" "${work}/crexxrag.conf" @ONLY)
    file(READ "${work}/crexxrag.conf" config)
    string(REPLACE "max_attempts = 1" "max_attempts = 3" config "${config}")
    file(WRITE "${work}/crexxrag.conf" "${config}")
    execute_process(COMMAND /bin/sh -c
        "( \"$1\" \"$2\" \"$3\" \"$4\" \"$5\"; printf '%s' $? >\"$8\" ) >\"$6\" 2>\"$7\" &"
        interruption-test "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}" "${requests}" "${scenario}" "${control}"
        "${work}/server.out" "${work}/server.err" "${work}/server.status" COMMAND_ERROR_IS_FATAL ANY)
    await_file("${work}/server.out" "READY ${CPRAG_FIXTURE_PORT}")
    cli(init init)
    set(database "${work}/library/library.sqlite")
    if(NOT kind STREQUAL "cancellation")
        # Inject the first fault on extraction. Equal-priority item
        # IDs depend on the configuration digest and do not guarantee this order.
        sql(ordered "CREATE TRIGGER qa_extraction_first AFTER INSERT ON job_items WHEN NEW.item_type='claim-extraction' BEGIN UPDATE job_items SET priority=1000001 WHERE item_id=NEW.item_id; END;")
    endif()
    execute_process(COMMAND /bin/sh -c
        "( CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key CREXXRAG_SELF=\"$1\" \"$1\" ingest --yes --workers 1; printf '%s' $? >\"$4\" ) >\"$2\" 2>\"$3\" &"
        interruption-test "${CPRAG_NATIVE_APPLICATION}" "${work}/ingest.out" "${work}/ingest.err" "${work}/ingest.status"
        WORKING_DIRECTORY "${work}" COMMAND_ERROR_IS_FATAL ANY)
    if(kind STREQUAL "manifest_failure")
        await_file("${work}/server.out" "MANIFEST_FAULT_READY")
        await_file("${work}/ingest.status" "[0-9]")
        sql(state "SELECT (SELECT count(*) FROM claims)||':'||(SELECT count(*) FROM job_items WHERE state='processed')||':'||(SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM job_items WHERE state='dead_letter');")
        if(NOT state STREQUAL "1:1:1:0")
            message(FATAL_ERROR "post-commit projection failure retried or discarded committed work: ${state}")
        endif()
        sql(ordered "DROP TRIGGER qa_extraction_first;")
        file(REMOVE_RECURSE "${control}")
        cli(complete --access control --format json worker start --count 2 --poll-ms 20 --max-polls 10)
        cli(recovery --access control --format json vector rebuild)
        cli(verify --access diagnose library verify)
        cli(query --format json query evidence "BillingService depends on CustomerDatabase" --mode lexical)
        if(NOT query MATCHES "BillingService" OR NOT query MATCHES "\"provider_calls\":0")
            message(FATAL_ERROR "post-commit recovery did not retain source evidence")
        endif()
    else()
        await_file("${work}/server.out" "RESPONSE_HELD")
        sql(job "SELECT job_id FROM jobs LIMIT 1;")
        if(kind STREQUAL "controller_loss" OR kind STREQUAL "restart_live")
            sql(controller "SELECT pid FROM runtime_instances WHERE kind='controller';")
            sql(worker "SELECT pid FROM runtime_instances WHERE kind='worker';")
            sql(original_controller "SELECT instance_id FROM runtime_instances WHERE kind='controller';")
            sql(initial "SELECT (SELECT count(*) FROM attempts)||':'||(SELECT count(*) FROM job_items WHERE state='queued')||':'||(SELECT count(*) FROM runtime_instances WHERE kind='controller' AND state='running');")
            process_exited(controller_gone "${controller}")
            process_exited(worker_gone "${worker}")
            if(NOT initial STREQUAL "1:1:1" OR controller_gone OR worker_gone)
                message(FATAL_ERROR "RESTART_CONTROL_FAILED: held call, queued peer and live owned group required: ${initial}")
            endif()
            message(STATUS "RESTART_CONTROLS_OK: one held call, one queued peer, live controller and child")
            if(kind STREQUAL "restart_live")
                execute_process(COMMAND /bin/sh -c "echo \"$PPID\"" OUTPUT_VARIABLE observer_pid OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
                # Real live observer PID and a terminal row belong to another job.
                # Neither may be signalled, drained or globally pruned by restart.
                sql(ignored "INSERT INTO runtime_instances(instance_id,kind,parent_instance_id,host_id,pid,process_start_token,executable_identity,mode,job_filter,state,requested_state,started_at,heartbeat_at) SELECT 'other-live','controller',NULL,host_id,${observer_pid},'other','fixture','wait','other-job','running','none',1,1 FROM runtime_instances WHERE instance_id='${original_controller}'; INSERT INTO runtime_instances(instance_id,kind,parent_instance_id,host_id,pid,process_start_token,executable_identity,mode,job_filter,state,requested_state,started_at,heartbeat_at) SELECT 'other-terminal','worker','other-live',host_id,0,'other','fixture','follow','other-job','stopped','none',1,1 FROM runtime_instances WHERE instance_id='${original_controller}'; INSERT INTO runtime_instances(instance_id,kind,parent_instance_id,host_id,pid,process_start_token,executable_identity,mode,job_filter,state,requested_state,started_at,heartbeat_at) SELECT 'old-reservation','worker',instance_id,host_id,0,'','fixture','follow',job_filter,'starting','none',1,1 FROM runtime_instances WHERE instance_id='${original_controller}';")
                sql(other_before "SELECT * FROM runtime_instances WHERE job_filter='other-job' ORDER BY instance_id;")
            endif()
            if(kind STREQUAL "controller_loss")
                # Deliberately leave the child alive. The old test killed both
                # generations and could not observe an orphan claiming work.
                execute_process(COMMAND /bin/kill -KILL "${controller}" COMMAND_ERROR_IS_FATAL ANY)
                await_file("${work}/ingest.status" "[0-9]")
            else()
                execute_process(COMMAND /bin/sh -c
                    "( CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key CREXXRAG_SELF=\"$1\" \"$1\" --access control --format json job run \"$2\" --count 1 --poll-ms 20 --max-polls 20; printf '%s' $? >\"$5\" ) >\"$3\" 2>\"$4\" &"
                    restart-test "${CPRAG_NATIVE_APPLICATION}" "${job}" "${work}/restart.out" "${work}/restart.err" "${work}/restart.status"
                    WORKING_DIRECTORY "${work}" COMMAND_ERROR_IS_FATAL ANY)
                # Release as soon as the new command has rejected ownership,
                # requested cleanup, or stopped the old controller. No fixed
                # race against the provider's response delay is needed.
                set(restart_seen FALSE)
                foreach(poll RANGE 1 200)
                    sql(cleanup "SELECT count(*) FROM runtime_instances WHERE (instance_id='${original_controller}' OR parent_instance_id='${original_controller}') AND requested_state IN('drain','stop');")
                    process_exited(controller_gone "${controller}")
                    if(EXISTS "${work}/restart.status" OR cleanup GREATER 0 OR controller_gone)
                        set(restart_seen TRUE)
                        break()
                    endif()
                    execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
                endforeach()
            endif()
            execute_process(COMMAND /bin/sh -c "printf R >\"$1\"" interruption-release "${control}" TIMEOUT 5 COMMAND_ERROR_IS_FATAL ANY)
            await_exit(child_exited "${worker}")
            # Always clean this scratch-owned group before reporting failures.
            if(NOT child_exited)
                execute_process(COMMAND /bin/kill -TERM "${worker}" ERROR_QUIET)
                await_exit(ignored "${worker}")
            endif()
            await_file("${work}/ingest.status" "[0-9]")
            if(kind STREQUAL "controller_loss")
                sql(claims_after_loss "SELECT count(*) FROM attempts;")
                expect("${claims_after_loss}" "1" "OPS-001 controller loss must prevent a new item claim")
                expect("${child_exited}" "TRUE" "OPS-001 orphan child must exit")
                # Controller death before group admission must also end a child.
                sql(ignored "UPDATE runtime_instances SET state='idle' WHERE instance_id='${original_controller}';")
                execute_process(COMMAND ${CMAKE_COMMAND} -E env "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key" "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}" --access control --format json worker run --id startup-orphan --parent "${original_controller}" --job "${job}" --follow --max-polls 1 WORKING_DIRECTORY "${work}" RESULT_VARIABLE startup_code OUTPUT_VARIABLE startup_out ERROR_VARIABLE startup_err TIMEOUT 5)
                expect("${startup_code}" "0" "orphan exits cleanly during group admission")
                sql(startup_attempts "SELECT count(*) FROM attempts;")
                expect("${startup_attempts}" "${claims_after_loss}" "startup orphan makes no new claim")
            else()
                await_file("${work}/restart.status" "[0-9]")
                file(READ "${work}/ingest.status" old_controller_status)
                if(old_controller_status STREQUAL "137")
                    message(SEND_ERROR "OPS-001 ordinary restart must politely stop the old controller, not SIGKILL it")
                endif()
                file(READ "${work}/restart.status" restart_status)
                file(READ "${work}/restart.out" restart_output)
                file(READ "${work}/restart.err" restart_error)
                file(APPEND "${work}/commands.log" "job run ${job} with live group\n${restart_output}${restart_error}\n")
                expect("${restart_seen}" "TRUE" "OPS-001 ordinary restart begins cleanup")
                expect("${restart_status}" "0" "OPS-001 ordinary restart must clean old ownership and run")
                sql(fresh "SELECT count(*) FROM runtime_instances WHERE kind='controller' AND job_filter='${job}' AND instance_id<>'${original_controller}';")
                expect("${fresh}" "1" "OPS-001 restart creates a fresh controller")
                expect("${child_exited}" "TRUE" "OPS-001 old child exits during restart")
                sql(reservations "SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs;")
                expect("${reservations}" "0" "OPS-001 restart releases abandoned reservations")
                # Repeating the ordinary continuation with an already drained
                # group must keep completed work, receipts and attempts intact.
                set(history_query "SELECT * FROM attempts ORDER BY attempt_id; SELECT * FROM provider_runs ORDER BY provider_run_id; SELECT * FROM claims ORDER BY claim_id; SELECT * FROM revision_chunk_embeddings ORDER BY 1,2;")
                sql(before_repeat "${history_query}")
                sql(first_restart_id "SELECT instance_id FROM runtime_instances WHERE kind='controller' AND job_filter='${job}' AND instance_id<>'${original_controller}';")
                sql(first_restart_children "SELECT count(*) FROM runtime_instances WHERE kind='worker' AND parent_instance_id='${first_restart_id}';")
                expect("${first_restart_children}" "1" "OPS-001 first restart creates fresh children")
                cli(repeat --access control --format json job continue "${job}" --count 1 --poll-ms 20 --max-polls 5)
                sql(after_repeat "${history_query}")
                expect("${after_repeat}" "${before_repeat}" "OPS-001 repeated cleanup preserves completed work and accounting")
                # Runtime cleanup may remove old registrations. Compare the
                # returned identity, not the number of retained runtime rows.
                string(JSON repeat_id GET "${repeat}" records 0 fields controller_id)
                if(repeat_id STREQUAL original_controller OR repeat_id STREQUAL first_restart_id)
                    message(SEND_ERROR "OPS-001 repeated continuation reused an old controller: ${repeat_id}")
                endif()
                sql(repeat_children "SELECT count(*) FROM runtime_instances WHERE kind='worker' AND parent_instance_id='${repeat_id}';")
                expect("${repeat_children}" "1" "OPS-001 repeated continuation creates fresh children")
                message(STATUS "RESTART_REPEAT_CHECKED: no repeated work or provider receipt")
                sql(other_after "SELECT * FROM runtime_instances WHERE job_filter='other-job' ORDER BY instance_id;")
                expect("${other_after}" "${other_before}" "restart preserves unrelated live and terminal ownership")
                process_exited(observer_gone "${observer_pid}")
                expect("${observer_gone}" "FALSE" "restart leaves the other live process alone")
                sql(pending_old "SELECT count(*) FROM runtime_instances WHERE instance_id='old-reservation' AND state NOT IN('stopped','failed');")
                expect("${pending_old}" "0" "restart cleans old PID-zero reservations")
                # An inaccessible remote group must be retained without a new launch.
                sql(ignored "INSERT INTO runtime_instances(instance_id,kind,host_id,pid,process_start_token,executable_identity,mode,job_filter,state,started_at,heartbeat_at) VALUES('remote-owner','controller','another-host',${observer_pid},'remote','fixture','wait','${job}','running',1,1);")
                sql(remote_before "SELECT * FROM runtime_instances ORDER BY instance_id;")
                execute_process(COMMAND ${CMAKE_COMMAND} -E env "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key" "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}" --access control --format json job continue "${job}" --count 1 --max-polls 1 WORKING_DIRECTORY "${work}" RESULT_VARIABLE remote_code OUTPUT_VARIABLE remote_out ERROR_VARIABLE remote_err TIMEOUT 10)
                expect("${remote_code}" "6" "remote ownership blocks automatic restart")
                sql(remote_after "SELECT * FROM runtime_instances ORDER BY instance_id;")
                expect("${remote_after}" "${remote_before}" "remote denial preserves runtime ownership")
                sql(ignored "DELETE FROM runtime_instances WHERE instance_id IN('remote-owner','other-terminal','other-live');")
            endif()
            await_file("${work}/server.status" "0")
            sql(integrity "PRAGMA integrity_check; SELECT count(*) FROM pragma_foreign_key_check;")
            expect("${integrity}" "ok\n0" "restart fixture integrity")
            message(STATUS "RESTART_CLEANUP_CHECKED: ${kind}; errors above remain failures")
            continue()
        endif()
        if(kind STREQUAL "cancellation")
            cli(cancel --access control job cancel "${job}" --reason "cancel during admitted native provider call")
        else()
            # Kill only PIDs registered by this newly created test library.
            sql(pids "SELECT group_concat(pid,';') FROM (SELECT pid FROM runtime_instances WHERE state IN('idle','running','starting') ORDER BY CASE kind WHEN 'controller' THEN 0 ELSE 1 END);")
            foreach(pid IN LISTS pids)
                execute_process(COMMAND /bin/kill -KILL "${pid}" RESULT_VARIABLE killed ERROR_QUIET)
            endforeach()
        endif()
        execute_process(COMMAND /bin/sh -c "printf R >\"$1\"" interruption-release "${control}" TIMEOUT 5 COMMAND_ERROR_IS_FATAL ANY)
        await_file("${work}/ingest.status" "[0-9]")
        if(kind STREQUAL "cancellation")
            sql(state "SELECT (SELECT state FROM jobs)||':'||(SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM revision_chunk_embeddings)||':'||(SELECT count(*) FROM job_items WHERE state='cancelled')||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs);")
            if(NOT state STREQUAL "cancelled:1:0:2:0")
                message(FATAL_ERROR "native cancellation lost usage, published a result or leaked ownership: ${state}")
            endif()
        else()
            # Advance the fixture's expired-lease and stale-heartbeat clocks;
            # the product must confirm dead PIDs through its public restart.
            sql(ignore "UPDATE job_items SET lease_until=unixepoch()-1 WHERE state='running'; UPDATE runtime_instances SET heartbeat_at=unixepoch()-2;")
            cli(restart --access control --format json job run "${job}" --count 2 --poll-ms 20 --max-polls 5)
            sql(state "SELECT (SELECT state FROM jobs)||':'||(SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-intent')||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-response')||':'||(SELECT count(*) FROM job_events WHERE event_type='provider-outcome-uncertain')||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs);")
            if(NOT state STREQUAL "completed_with_errors:1:2:1:1:0")
                message(FATAL_ERROR "killed request was silently repeated or uncertainty lost: ${state}")
            endif()
            sql(peer "SELECT (SELECT count(*) FROM job_items WHERE item_type='embedding' AND state='processed')||':'||(SELECT count(*) FROM attempts a JOIN job_items i ON i.item_id=a.item_id WHERE i.item_type='claim-extraction')||':'||(SELECT count(*) FROM provider_runs WHERE outcome='succeeded');")
            if(NOT peer STREQUAL "1:1:1")
                message(FATAL_ERROR "healthy embedding did not finish, or killed extraction was retried: ${peer}")
            endif()
            cli(events --format json job events "${job}")
            if(NOT events MATCHES "provider-outcome-uncertain")
                message(FATAL_ERROR "uncertain external result is not operator-visible")
            endif()
        endif()
    endif()
    await_file("${work}/server.status" "0")
    sql(integrity "PRAGMA integrity_check; SELECT count(*) FROM pragma_foreign_key_check;")
    if(NOT integrity STREQUAL "ok\n0")
        message(FATAL_ERROR "interrupted library failed integrity: ${integrity}")
    endif()
    file(WRITE "${work}/result.txt" "Native ${kind} reached its deterministic provider/commit boundary and preserved accounting, fencing, source data and inspectable recovery state.\n")
endforeach()
