foreach(required CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(CPRAG_SQLITE sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
set(work "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${work}/source")
function(cli output)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env
        "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
        "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}" ${ARGN}
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail TIMEOUT 30)
    file(APPEND "${work}/commands.log" "${ARGN}\n${result}${detail}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "admission command failed: ${ARGN}\n${result}${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${CPRAG_SQLITE}" -cmd ".timeout 5000" "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE detail OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "admission SQL failed: ${detail}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
function(await_file file pattern)
    foreach(poll RANGE 1 500)
        if(EXISTS "${file}")
            file(READ "${file}" content)
            if(content MATCHES "${pattern}")
                return()
            endif()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
    endforeach()
    message(FATAL_ERROR "admission rendezvous missing: ${file} ${pattern}")
endfunction()
foreach(source RANGE 1 2)
    file(WRITE "${work}/source/architecture-${source}.txt"
        "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase.\nSource ${source}.\n")
endforeach()
set(CPRAG_FIXTURE_SOURCE "${work}/source")
set(CPRAG_FIXTURE_GLOSSARY "${work}/glossary.tsv")
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\nconcept\tCustomerDatabase\tdata-store\n")
set(CPRAG_FIXTURE_PORT 19045)
configure_file("${CPRAG_CONFIG_TEMPLATE}" "${work}/crexxrag.conf" @ONLY)
file(READ "${work}/crexxrag.conf" config)
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 4" config "${config}")
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 4" config "${config}")
string(REPLACE "budget.input_tokens = 8192" "budget.input_tokens = 65536" config "${config}")
string(REPLACE "budget.output_tokens = 1024" "budget.output_tokens = 65536" config "${config}")
file(WRITE "${work}/crexxrag.conf" "${config}")
cli(init init)
set(database "${work}/library/library.sqlite")
cli(planned --format json --access plan ingest plan --source-set architecture-docs)
string(JSON plan GET "${planned}" records 0 fields canonical_plan)
string(JSON digest GET "${planned}" records 0 fields digest)
cli(applied --format json --access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
sql(job "SELECT job_id FROM jobs;")
# Constrain this scratch fixture to one reservation before launching workers.
# The public planner normally scales the ceiling with worker count. Keeping a
# smaller stored ceiling makes the held-peer boundary deterministic, without
# modifying any policy once execution begins.
sql(seeded "UPDATE job_events SET message=json_set(message,'$.maximum_inflight_calls',1) WHERE event_type='budget-policy';")
sql(policy_before "SELECT message FROM job_events WHERE event_type='budget-policy';")
# Two supported worker processes share that unchanged allowance.
execute_process(COMMAND mkfifo "${work}/release.fifo" COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND /bin/sh -c
    "( \"$1\" \"$2\" 4 product-hold-response \"$3\" & fixture_pid=$!; printf '%s' \"$fixture_pid\" >\"$7\"; wait \"$fixture_pid\"; printf '%s' $? >\"$6\" ) >\"$4\" 2>\"$5\" &"
    admission-test "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}" "${work}/release.fifo"
    "${work}/server.out" "${work}/server.err" "${work}/server.status" "${work}/server.pid" COMMAND_ERROR_IS_FATAL ANY)
await_file("${work}/server.out" "READY ${CPRAG_FIXTURE_PORT}")
execute_process(COMMAND /bin/sh -c
    "( CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key CREXXRAG_SELF=\"$1\" \"$1\" --access control job run \"$2\" --count 2 --poll-ms 20 --max-polls 200; printf '%s' $? >\"$5\" ) >\"$3\" 2>\"$4\" &"
    admission-test "${CPRAG_NATIVE_APPLICATION}" "${job}" "${work}/run.out" "${work}/run.err" "${work}/run.status"
    WORKING_DIRECTORY "${work}" COMMAND_ERROR_IS_FATAL ANY)
await_file("${work}/server.out" "RESPONSE_HELD")
set(reached FALSE)
foreach(poll RANGE 1 100)
    sql(peer "SELECT count(*) FROM attempts WHERE outcome IN('cancelled','failed','dead_letter');")
    if(peer GREATER 0)
        set(reached TRUE)
        break()
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
endforeach()
cli(waiting --format json job status "${job}")
sql(held "SELECT (SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM attempts WHERE outcome IN('failed','dead_letter'))||':'||(SELECT count(*) FROM job_events WHERE event_type='worker-replacement');")
# Always release before testing acceptance, including against the red baseline.
execute_process(COMMAND /bin/sh -c "printf R >\"$1\"" admission-release "${work}/release.fifo"
    TIMEOUT 5 COMMAND_ERROR_IS_FATAL ANY)
await_file("${work}/run.status" "[0-9]")
file(READ "${work}/run.status" run_status)
sql(final "SELECT (SELECT state FROM jobs)||':'||(SELECT count(*) FROM provider_runs)||':'||(SELECT count(*) FROM job_items WHERE state='processed')||':'||(SELECT count(*) FROM attempts WHERE outcome<>'cancelled')||':'||(SELECT count(*) FROM job_events WHERE event_type='worker-replacement')||':'||(SELECT count(*) FROM runtime_instances WHERE state='failed')||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost) FROM jobs);")
sql(receipts "SELECT (SELECT count(*) FROM job_events WHERE event_type='provider-response')||':'||(SELECT count(*) FROM job_events WHERE event_type GLOB 'reservation-open:*')||':'||(SELECT count(*) FROM job_events WHERE event_type GLOB 'reservation-close:*');")
sql(policy_after "SELECT message FROM job_events WHERE event_type='budget-policy';")
file(WRITE "${work}/evidence.txt" "reached=${reached}\nheld=${held}\nwaiting=${waiting}\nexit=${run_status}\nfinal=${final}\nreceipts=${receipts}\n")
if(NOT reached OR NOT held STREQUAL "0:0:0" OR NOT run_status STREQUAL "0" OR
   NOT final STREQUAL "completed:4:4:4:0:0:0" OR NOT receipts STREQUAL "4:4:4" OR
   NOT policy_before STREQUAL policy_after OR NOT waiting MATCHES "waiting_reason.*waiting for provider capacity")
    if(NOT EXISTS "${work}/server.status")
        file(READ "${work}/server.pid" fixture_pid)
        execute_process(COMMAND /bin/kill -TERM "${fixture_pid}" RESULT_VARIABLE stopped ERROR_QUIET)
    endif()
    message(FATAL_ERROR "Native capacity acceptance failed; see ${work}/evidence.txt\nheld=${held} exit=${run_status} final=${final} receipts=${receipts}")
endif()
await_file("${work}/server.status" "0")
cli(done --format json job status "${job}")
if(NOT done MATCHES "\"waiting_reason\":\"\"")
    message(FATAL_ERROR "Completed job retained a stale capacity-wait reason: ${done}")
endif()
sql(integrity "SELECT count(*) FROM pragma_foreign_key_check;")
if(NOT integrity STREQUAL "0")
    message(FATAL_ERROR "Admission recovery broke foreign keys")
endif()
cli(verify --access diagnose library verify)
message(STATUS "Native admission: held peer, clean workers, unchanged allowance, four exact settlements")
