# Persisted closed-window recovery through the public native CLI. SQL creates
# the historic five-failure shape; retry, planning and execution are public.
foreach(required CPRAG_NATIVE_APPLICATION CPRAG_LOOPBACK CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(sqlite_cli sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
foreach(item RANGE 1 5)
    file(WRITE "${CPRAG_WORK_DIR}/source/${item}.txt"
        "Document ${item}. BillingService depends on CustomerDatabase.\n")
endforeach()
set(CPRAG_FIXTURE_PORT 19046)
set(successful 5)
set(task_links 10)
set(historic_calls 5)
if(CPRAG_HOLDS)
    set(CPRAG_FIXTURE_PORT 19047)
    set(successful 3)
    set(task_links 8)
    set(historic_calls 7)
endif()
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
file(READ "${CPRAG_CONFIG_TEMPLATE}" config)
string(CONFIGURE "${config}" config @ONLY)
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 100" config "${config}")
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 100" config "${config}")
string(REPLACE "provider.gemini-embed.max_attempts = 1" "provider.gemini-embed.max_attempts = 3" config "${config}")
string(APPEND config "\nmaintenance.mode = automatic\nmaintenance.window_seconds = 120\nmaintenance.maximum_attempts = 3\nmaintenance.batch_items = 8\n")
file(WRITE "${CPRAG_WORK_DIR}/recovery.conf" "${config}")
set(library "${CPRAG_WORK_DIR}/library")
set(cli "${CMAKE_COMMAND}" -E env "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
    "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "${CPRAG_NATIVE_APPLICATION}"
    --library "${library}" --config-file "${CPRAG_WORK_DIR}/recovery.conf"
    --profile it-architecture-profile --format json --progress plain)
function(run_cli)
    execute_process(COMMAND ${cli} ${ARGN} RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 120)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\nstatus=${status}\n${output}${errors}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Lifecycle command failed: ${ARGN}\n${output}${errors}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()
function(query output sql)
    execute_process(COMMAND "${sqlite_cli}" -cmd ".timeout 5000" "${library}/library.sqlite" "${sql}"
        RESULT_VARIABLE status OUTPUT_VARIABLE value ERROR_VARIABLE errors OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Lifecycle SQL: ${sql}\n${errors}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()
function(assert_sql sql expected)
    query(value "${sql}")
    if(NOT value STREQUAL "${expected}")
        message(FATAL_ERROR "Lifecycle assertion: ${sql}\nExpected ${expected}; got ${value}")
    endif()
endfunction()
function(await_file path pattern)
    foreach(poll RANGE 1 500)
        if(EXISTS "${path}")
            file(READ "${path}" content)
            if(content MATCHES "${pattern}")
                return()
            endif()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
    endforeach()
    message(FATAL_ERROR "Lifecycle rendezvous missing: ${path} ${pattern}")
endfunction()
function(apply_window)
    run_cli(--access plan maintain plan --embeddings-only --minutes 2)
    string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
    string(JSON digest GET "${last_output}" records 0 fields digest)
    run_cli(--access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
    string(JSON id GET "${last_output}" records 0 fields job_id)
    set(window_job "${id}" PARENT_SCOPE)
endfunction()
run_cli(--access admin library init)
run_cli(--access plan ingest plan --source-set architecture-docs)
string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
string(JSON digest GET "${last_output}" records 0 fields digest)
run_cli(--access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON ingestion GET "${last_output}" records 0 fields job_id)
run_cli(--access control job pause "${ingestion}")
apply_window()
set(closed_job "${window_job}")
assert_sql("SELECT count(*) FROM job_items WHERE job_id='${closed_job}' AND item_type='embedding';" "5")
# Preserve real planner inputs and policy, then represent five previously paid
# quota failures. Each identity retains one call under the explicit ceiling 3.
query(unused "BEGIN IMMEDIATE;
INSERT INTO provider_runs(provider_run_id,config_snapshot_id,provider_id,model,request_hash,outcome,started_at,completed_at,cost_microunits)
 SELECT 'historic-'||item_id,j.config_snapshot_id,json_extract(i.input_json,'$.provider_id'),json_extract(i.input_json,'$.model'),input_hash,'failed','historic','historic',0 FROM job_items i JOIN jobs j USING(job_id) WHERE j.job_id='${closed_job}';
UPDATE job_items SET state='dead_letter',fence=1 WHERE job_id='${closed_job}';
INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,provider_run_id,started_at,completed_at)
 SELECT 'historic-'||item_id,item_id,'historic-worker',1,input_hash,'quota-rejected','dead_letter','historic-'||item_id,'historic','historic' FROM job_items WHERE job_id='${closed_job}';
INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at)
 SELECT job_id,item_id,'historic-'||item_id,'fixture-history','retain original failure','historic' FROM job_items WHERE job_id='${closed_job}';
UPDATE maintenance_tasks SET state='failed' WHERE task_id IN(SELECT task_id FROM maintenance_task_items WHERE window_id IN(SELECT window_id FROM maintenance_windows WHERE job_id='${closed_job}'));
UPDATE maintenance_windows SET state='complete',closed_epoch=1,deadline_epoch=1 WHERE job_id='${closed_job}';
UPDATE jobs SET state='completed' WHERE job_id='${closed_job}'; COMMIT;")
if(CPRAG_HOLDS)
    query(limit_item "SELECT item_id FROM job_items WHERE job_id='${closed_job}' ORDER BY item_id LIMIT 1;")
    query(unknown_item "SELECT item_id FROM job_items WHERE job_id='${closed_job}' ORDER BY item_id LIMIT 1 OFFSET 1;")
    foreach(attempt RANGE 2 3)
        query(unused "INSERT INTO provider_runs(provider_run_id,config_snapshot_id,provider_id,model,request_hash,outcome,started_at,completed_at,cost_microunits) SELECT 'ceiling-${attempt}',config_snapshot_id,provider_id,model,request_hash,'failed','historic-ceiling','historic-ceiling',0 FROM provider_runs WHERE provider_run_id='historic-${limit_item}'; INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,provider_run_id,started_at,completed_at) SELECT 'ceiling-${attempt}',item_id,'historic-worker',${attempt},input_hash,'quota-rejected','dead_letter','ceiling-${attempt}','historic-ceiling','historic-ceiling' FROM job_items WHERE item_id='${limit_item}';")
    endforeach()
    query(unused "UPDATE job_items SET fence=3 WHERE item_id='${limit_item}'; UPDATE maintenance_tasks SET attempt_count=3 WHERE task_id=(SELECT task_id FROM maintenance_task_items WHERE item_id='${limit_item}'); INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at) VALUES('${closed_job}','${unknown_item}','historic-${unknown_item}','provider-intent','{}','historic');")
endif()
set(history_sql "SELECT json_group_array(json(record)) FROM(SELECT json_object('item_id',i.item_id,'input',i.input_json,'input_hash',i.input_hash,'item_state',i.state,'fence',i.fence,'attempt_id',a.attempt_id,'attempt_input',a.input_hash,'attempt_outcome',a.outcome,'validation',a.validation_state,'worker',a.worker_id,'run',p.provider_run_id,'outcome',p.outcome,'input_tokens',p.input_tokens,'output_tokens',p.output_tokens,'cost',p.cost_microunits,'duration',p.duration_ms,'recovery',p.recovery_json) AS record FROM job_items i JOIN attempts a ON a.item_id=i.item_id JOIN provider_runs p ON p.provider_run_id=a.provider_run_id WHERE i.job_id='${closed_job}' ORDER BY a.attempt_id);")
query(history_before "${history_sql}")
query(policy_before "SELECT message FROM job_events WHERE job_id='${closed_job}' AND event_type='budget-policy';")
query(items "SELECT item_id FROM job_items WHERE job_id='${closed_job}' ORDER BY item_id;")
string(REPLACE "\n" ";" items "${items}")
foreach(item IN LISTS items)
    run_cli(--access control job retry "${closed_job}" --item "${item}" --reason quota-resolved)
    string(JSON request GET "${last_output}" records 0 fields retry_request_id)
    query(task "SELECT task_id FROM maintenance_task_items WHERE item_id='${item}';")
    # Each command is a fresh native process: durable identity survives restart.
    run_cli(--access control maintain retry "${task}" --reason duplicate)
    string(JSON duplicate GET "${last_output}" records 0 fields retry_request_id)
    if(NOT request STREQUAL duplicate)
        message(FATAL_ERROR "Item/task retry did not reuse the durable request")
    endif()
endforeach()
assert_sql("SELECT count(*) FROM retry_requests WHERE state='pending';" "5")
assert_sql("SELECT count(*) FROM job_items WHERE job_id='${closed_job}' AND state='dead_letter';" "5")
assert_sql("SELECT state||':'||deadline_epoch FROM maintenance_windows WHERE job_id='${closed_job}';" "complete:1")
run_cli(--access read job status "${closed_job}")
if(NOT last_output MATCHES "retry_pending.*5" OR (NOT CPRAG_HOLDS AND NOT last_output MATCHES "closed-window"))
    message(FATAL_ERROR "Job status omitted durable pending retry/hold: ${last_output}")
endif()
# Acceptance never depends on internal task, parent or window state. Retain
# the same pending request throughout; these state fixtures do not execute.
foreach(task_state IN ITEMS pending dispatched failed unresolved review superseded resolved)
    query(unused "INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) VALUES('task:matrix-${task_state}','matrix','chunk','matrix-${task_state}','matrix','matrix','{}','state acceptance','${task_state}',0,0,0);")
    run_cli(--access control maintain retry "task:matrix-${task_state}" --reason state-matrix)
endforeach()
query(unused "UPDATE maintenance_tasks SET state='failed' WHERE task_id='${task}';")
foreach(parent_state IN ITEMS queued running paused cancel_requested cancelled completed completed_with_errors)
    query(unused "UPDATE jobs SET state='${parent_state}' WHERE job_id='${closed_job}';")
    run_cli(--access control maintain retry "${task}" --reason parent-matrix)
endforeach()
query(unused "UPDATE jobs SET state='completed' WHERE job_id='${closed_job}';")
foreach(window_state IN ITEMS active paused cancelled complete budget-exhausted deadline)
    query(unused "UPDATE maintenance_windows SET state='${window_state}' WHERE job_id='${closed_job}';")
    run_cli(--access control maintain retry "${task}" --reason window-matrix)
endforeach()
query(unused "UPDATE maintenance_windows SET state='complete' WHERE job_id='${closed_job}';")
assert_sql("SELECT count(*) FROM retry_requests WHERE task_id NOT LIKE 'task:matrix-%';" "5")
assert_sql("SELECT count(*) FROM provider_runs;" "${historic_calls}")
if(CPRAG_HOLDS)
    assert_sql("SELECT disposition FROM retry_requests WHERE task_id=(SELECT task_id FROM maintenance_task_items WHERE item_id='${limit_item}');" "attempt-limit")
    assert_sql("SELECT disposition FROM retry_requests WHERE task_id=(SELECT task_id FROM maintenance_task_items WHERE item_id='${unknown_item}');" "provider-outcome-uncertain")
endif()
# A new reviewed window owns execution; it cannot reset the old deadline,
# original job allowance, item fence or attempt history.
apply_window()
set(recovery_job "${window_job}")
assert_sql("SELECT count(*) FROM job_items WHERE job_id='${recovery_job}' AND state='queued';" "${successful}")
execute_process(COMMAND mkfifo "${CPRAG_WORK_DIR}/release.fifo" COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND /bin/sh -c
    "( \"$1\" \"$2\" ${successful} product-hold-response \"$3\" & fixture_pid=$!; printf '%s' \"$fixture_pid\" >\"$7\"; wait \"$fixture_pid\"; printf '%s' $? >\"$6\" ) >\"$4\" 2>\"$5\" &"
    lifecycle "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}" "${CPRAG_WORK_DIR}/release.fifo"
    "${CPRAG_WORK_DIR}/server.out" "${CPRAG_WORK_DIR}/server.err" "${CPRAG_WORK_DIR}/server.status" "${CPRAG_WORK_DIR}/server.pid")
await_file("${CPRAG_WORK_DIR}/server.out" "READY ${CPRAG_FIXTURE_PORT}")
execute_process(COMMAND /bin/sh -c
    "( CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key CREXXRAG_SELF=\"$1\" \"$1\" --library \"$2\" --config-file \"$3\" --profile it-architecture-profile --access control job run \"$4\" --count 2 --poll-ms 20 --max-polls 300; printf '%s' $? >\"$7\" ) >\"$5\" 2>\"$6\" &"
    lifecycle "${CPRAG_NATIVE_APPLICATION}" "${library}" "${CPRAG_WORK_DIR}/recovery.conf" "${recovery_job}"
    "${CPRAG_WORK_DIR}/run.out" "${CPRAG_WORK_DIR}/run.err" "${CPRAG_WORK_DIR}/run.status")
await_file("${CPRAG_WORK_DIR}/server.out" "RESPONSE_HELD")
query(live_task "SELECT m.task_id FROM maintenance_task_items m JOIN job_items i USING(item_id) WHERE i.job_id='${recovery_job}' AND i.state='running' ORDER BY i.item_id LIMIT 1;")
run_cli(--access control maintain retry "${live_task}" --reason live-owner)
query(held "SELECT (SELECT count(*) FROM retry_requests WHERE task_id NOT LIKE 'task:matrix-%')||':'||(SELECT count(*) FROM maintenance_task_items)||':'||(SELECT count(*) FROM attempts WHERE started_at='historic');")
# Release the fixture before asserting, including on a red implementation.
execute_process(COMMAND /bin/sh -c "printf R >\"$1\"" lifecycle-release "${CPRAG_WORK_DIR}/release.fifo" TIMEOUT 5)
await_file("${CPRAG_WORK_DIR}/run.status" "[0-9]")
file(READ "${CPRAG_WORK_DIR}/run.status" run_status)
if(NOT held STREQUAL "5:${task_links}:5" OR NOT run_status STREQUAL "0")
    message(FATAL_ERROR "Live retry duplicated ownership or recovery failed: held=${held} exit=${run_status}")
endif()
await_file("${CPRAG_WORK_DIR}/server.status" "0")
assert_sql("SELECT count(*) FROM revision_chunk_embeddings WHERE visible_to_generation IS NULL;" "${successful}")
assert_sql("SELECT count(*) FROM provider_runs;" "10")
assert_sql("SELECT count(*) FROM retry_requests WHERE state='completed' AND task_id NOT LIKE 'task:matrix-%';" "${successful}")
assert_sql("SELECT count(*) FROM attempts WHERE started_at='historic' AND outcome='dead_letter' AND validation_state='quota-rejected' AND fence=1;" "5")
assert_sql("SELECT count(*) FROM job_events WHERE event_type='fixture-history' AND message='retain original failure';" "5")
assert_sql("SELECT state FROM jobs WHERE job_id='${ingestion}';" "paused")
assert_sql("SELECT count(*) FROM job_items WHERE job_id='${closed_job}' AND state='dead_letter';" "5")
assert_sql("SELECT state||':'||deadline_epoch FROM maintenance_windows WHERE job_id='${closed_job}';" "complete:1")
query(policy_after "SELECT message FROM job_events WHERE job_id='${closed_job}' AND event_type='budget-policy';")
query(history_after "${history_sql}")
if(NOT history_before STREQUAL history_after)
    message(FATAL_ERROR "Recovery changed retained item/attempt/provider history or usage")
endif()
if(NOT policy_before STREQUAL policy_after)
    message(FATAL_ERROR "Recovery changed the source allowance")
endif()
run_cli(--access control maintain retry "${live_task}" --reason already-covered)
run_cli(--access read maintain inspect "${live_task}")
if(NOT last_output MATCHES "already-complete")
    message(FATAL_ERROR "Covered retry omitted its no-call disposition: ${last_output}")
endif()
assert_sql("SELECT count(*) FROM provider_runs;" "10")
if(CPRAG_HOLDS)
    apply_window()
    run_cli(--access control worker start --count 2 --job "${window_job}" --poll-ms 20)
    assert_sql("SELECT count(*) FROM provider_runs;" "10")
    assert_sql("SELECT count(*) FROM retry_requests WHERE state='pending' AND disposition IN('attempt-limit','provider-outcome-uncertain') AND task_id NOT LIKE 'task:matrix-%';" "2")
    assert_sql("SELECT count(*) FROM maintenance_task_items;" "8")
endif()
assert_sql("SELECT sum(reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns) FROM jobs;" "0")
assert_sql("PRAGMA integrity_check;" "ok")
assert_sql("PRAGMA foreign_key_check;" "")
run_cli(--access diagnose library verify)
message(STATUS "LIFECYCLE_RECOVERY_OK failures=5 calls=${successful} history=preserved requests=durable live-owner=deduplicated")
