# Small isolated native journeys: no real credentials, network, or controller.
foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CODEX_FIXTURE CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(sqlite_cli sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
function(cli)
    execute_process(COMMAND ${command} ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20)
    file(APPEND "${cell}/commands.log" "${ARGN}\n${status}\n${output}${errors}\n")
    if(NOT "${status}" MATCHES "^[0-9]+$")
        message(FATAL_ERROR "Observation command did not terminate: ${status}")
    endif()
    set(out "${output}" PARENT_SCOPE)
    set(code "${status}" PARENT_SCOPE)
endfunction()
function(sql query)
    execute_process(COMMAND "${sqlite_cli}" "${cell}/library/library.sqlite" "${query}" OUTPUT_VARIABLE result OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    set(value "${result}" PARENT_SCOPE)
endfunction()
foreach(case auth slow malformed timeout disconnect)
    set(cell "${CPRAG_WORK_DIR}/${case}")
    file(MAKE_DIRECTORY "${cell}/source")
    file(WRITE "${cell}/source/source.txt" "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase.\n")
    set(CPRAG_FIXTURE_SOURCE "${cell}/source")
    set(CPRAG_FIXTURE_GLOSSARY "${cell}/glossary.tsv")
    set(CPRAG_FIXTURE_PORT 1)
    file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\nconcept\tBillingService\tapplication-component\nconcept\tCustomerDatabase\tdata-store\n")
    configure_file("${CPRAG_CONFIG_TEMPLATE}" "${cell}/crexxrag.conf" @ONLY)
    if(case STREQUAL "timeout")
        file(READ "${cell}/crexxrag.conf" config)
        string(REPLACE "timeout_ms = 10000" "timeout_ms = 1000" config "${config}")
        file(WRITE "${cell}/crexxrag.conf" "${config}")
    endif()
    file(WRITE "${cell}/codex.sh" "#!/bin/sh\nexec /bin/sh '${CPRAG_CODEX_FIXTURE}' \"\$@\"\n")
    file(CHMOD "${cell}/codex.sh" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    set(command "${CMAKE_COMMAND}" -E env "CREXXRAG_CODEX=${cell}/codex.sh" "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}"
        "CREXXRAG_CODEX_FIXTURE_MODE=extraction" "CREXXRAG_CODEX_FIXTURE_FAILURE=observation-${case}"
        "CREXXRAG_CODEX_FIXTURE_LOG=${cell}/methods.log" "${CPRAG_NATIVE_APPLICATION}"
        --library "${cell}/library" --config-file "${cell}/crexxrag.conf" --profile it-architecture-profile --format json)
    cli(--access admin library init)
    cli(--access plan ingest plan --source-set architecture-docs)
    string(JSON plan GET "${out}" records 0 fields canonical_plan)
    string(JSON digest GET "${out}" records 0 fields digest)
    cli(--access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
    string(JSON job GET "${out}" records 0 fields job_id)
    sql("UPDATE job_items SET priority=200 WHERE item_type='claim-extraction'; UPDATE job_items SET retry_at=unixepoch()+3600 WHERE item_type='embedding'; SELECT item_id FROM job_items WHERE item_type='claim-extraction';")
    set(item "${value}")
    cli(--access control worker run --once --job "${job}")
    cli(--access read job inspect "${item}" --section validation)
    string(JSON validation GET "${out}" records 0 fields text)
    if(case STREQUAL "auth")
        if(NOT validation MATCHES "authentication" OR NOT validation MATCHES "session expired")
            message(FATAL_ERROR "Authentication failure was not distinguishable: ${validation}")
        endif()
        sql("SELECT count(*) FROM provider_runs;")
        if(NOT value STREQUAL "0")
            message(FATAL_ERROR "Failed authentication invented a provider call")
        endif()
        cli(--access read job status "${job}" --diagnostics)
        string(JSON report GET "${out}" records 0 fields diagnostics)
        string(JSON category GET "${report}" errors 0 category)
        if(NOT category STREQUAL "authentication")
            message(FATAL_ERROR "Summary omitted authentication failure before a call was submitted")
        endif()
    else()
        cli(--access read job inspect "${item}" --section request)
        string(JSON request GET "${out}" records 0 fields text)
        if(NOT request MATCHES "BillingService" OR NOT request MATCHES "reasoning_effort")
            message(FATAL_ERROR "Submitted Codex request was not inspectable")
        endif()
        cli(--access read job inspect "${item}" --section response)
        string(JSON response GET "${out}" records 0 fields text)
        if(case STREQUAL "timeout" OR case STREQUAL "disconnect")
            if(NOT validation MATCHES "confirmed Codex turn interrupted")
                message(FATAL_ERROR "Missing terminal observation: ${validation}")
            endif()
            set(category transport)
            set(min_duration 200)
            if(case STREQUAL "timeout")
                set(category timeout)
                set(min_duration 900)
                if(NOT validation MATCHES "timed out|deadline")
                    message(FATAL_ERROR "Original timeout lost during reconciliation: ${validation}")
                endif()
            elseif(NOT validation MATCHES "closed stdout")
                message(FATAL_ERROR "Original disconnect lost during reconciliation: ${validation}")
            endif()
            cli(--access read job inspect "${item}" --section timing)
            string(JSON timing GET "${out}" records 0 fields text)
            string(JSON duration GET "${timing}" provider_duration_ms)
            string(JSON elapsed GET "${timing}" provider_elapsed_ms)
            if(elapsed LESS min_duration OR elapsed GREATER duration)
                message(FATAL_ERROR "Provider elapsed and admission wait were not separated: ${timing}")
            endif()
            if(duration LESS min_duration OR duration GREATER 15000)
                message(FATAL_ERROR "Interrupted call duration lost: ${duration}")
            endif()
            cli(--access read job items "${job}" --error "${category}")
            string(JSON selected GET "${out}" records 0 fields id)
            if(NOT selected STREQUAL item)
                message(FATAL_ERROR "Reconciled cause cannot be found by ${category}")
            endif()
            string(JSON complete GET "${timing}" usage_complete)
            if(NOT complete EQUAL 0)
                message(FATAL_ERROR "Timing inspection hid incomplete usage: ${timing}")
            endif()
            sql("SELECT count(*) FROM job_events WHERE event_type='provider-observed' AND json_extract(message,'$.usage_complete')=0;")
            if(NOT value STREQUAL "1")
                message(FATAL_ERROR "Interrupted call invented complete usage")
            endif()
            sql("SELECT reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns FROM jobs;")
            if(NOT value STREQUAL "0")
                message(FATAL_ERROR "Confirmed interruption retained a reservation")
            endif()
        elseif(case STREQUAL "slow")
            if(NOT response MATCHES "BillingService")
                message(FATAL_ERROR "Slow successful response lost output")
            endif()
            cli(--access read job inspect "${item}" --section timing)
            string(JSON timing GET "${out}" records 0 fields text)
            string(JSON duration GET "${timing}" provider_duration_ms)
            if(duration LESS 200 OR duration GREATER 15000)
                message(FATAL_ERROR "Slow response duration was not measured: ${duration}")
            endif()
        elseif(NOT response MATCHES "broken original output" OR NOT response MATCHES "structured_validation")
            message(FATAL_ERROR "Rejected Codex text was not retained: ${response}")
        endif()
        file(READ "${cell}/methods.log" methods)
        string(REGEX MATCHALL "turn/start" calls "${methods}")
        list(LENGTH calls count)
        if(NOT count EQUAL 1)
            message(FATAL_ERROR "Read inspection repeated a provider call")
        endif()
    endif()
endforeach()
message(STATUS "Authentication, slow success and malformed response are distinguishable without extra calls")
