# Synthetic rows deliberately put unrelated records before the selected subject.
# This catches filtering after pagination and verifies operator reads without SQL.
foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_FIXTURE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
set(library "${CPRAG_WORK_DIR}/library")
set(base "${CPRAG_NATIVE_APPLICATION}" --library "${library}" --config-file "${CPRAG_CONFIG_FIXTURE}"
    --profile it-architecture-profile --format json)
execute_process(COMMAND ${base} --access admin library init
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Diagnostic fixture init failed: ${out}${err}")
endif()
find_program(CREXXRAG_SQLITE3 sqlite3 REQUIRED)
set(database "${library}/library.sqlite")
set(seed [=[
PRAGMA foreign_keys=ON;
INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at)
SELECT j.id,j.id,'{}',c.config_snapshot_id,'completed',1000,0,0,0,0,'2026-09-12','2026-09-12'
FROM (SELECT 'job-noise' id UNION ALL SELECT 'job-target' UNION ALL SELECT 'job-empty') j CROSS JOIN config_snapshots c;
WITH RECURSIVE seq(n) AS(SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n<103), groups(prefix,job) AS(VALUES('a','job-noise'),('z','job-target'))
INSERT INTO job_items(item_id,job_id,item_type,state,priority,worker_id,fence,idempotency_key,input_hash,input_json,created_at,updated_at)
SELECT prefix||'-item-'||printf('%03d',n),job,'claim-extraction','dead_letter',1,'worker-fixture',3,prefix||'-key-'||n,'input-digest','SECRET_RAW_INPUT_MUST_NOT_BE_RETURNED','2026-09-12','2026-09-12' FROM seq CROSS JOIN groups;
INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,started_at,completed_at)
SELECT 'attempt-'||item_id,item_id,worker_id,fence,input_hash,'rejected','failed',created_at,updated_at FROM job_items;
INSERT INTO concepts(concept_id,canonical_label,concept_type,lifecycle_state,visible_from_generation)
VALUES('concept-noise','Noise','application-component','active',(SELECT published_generation FROM library_meta)),('concept-target','Turray','application-component','active',(SELECT published_generation FROM library_meta)),('concept-successor','Turray successor','application-component','active',(SELECT published_generation FROM library_meta)),('concept-homonym','Turray','application-component','active',(SELECT published_generation FROM library_meta)),('concept-unicode','Dùn Èideann''s','application-component','active',(SELECT published_generation FROM library_meta));
WITH RECURSIVE seq(n) AS(SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n<75)
INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch)
SELECT 'a-task-'||printf('%03d',n),'fixture','concept','concept-noise','evidence-'||n,'policy','{}','noise','pending',1,1,1 FROM seq;
WITH seq(n) AS(VALUES(1),(2),(3))
INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch)
SELECT 'z-task-'||n,'fixture','concept','concept-target','evidence-'||n,'policy','{}','target','pending',1,1,1 FROM seq;
INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch)
VALUES('z-task-homonym','fixture','concept','concept-homonym','evidence','policy','{}','homonym','pending',1,1,1),('z-task-unicode','fixture','concept','concept-unicode','evidence','policy','{}','Unicode','pending',1,1,1);
INSERT INTO maintenance_workflows(workflow_id,origin_task_id,kind,parent_concept_id,successors_json,state,created_generation,created_epoch,updated_epoch)
VALUES('workflow-1','z-task-1','split','concept-target','[{"concept_id":"concept-successor"}]','migrating',(SELECT published_generation FROM library_meta),1,1),('workflow-2','z-task-2','split','concept-target','[]','waiting',(SELECT published_generation FROM library_meta),1,1),('workflow-3','z-task-homonym','split','concept-homonym','[]','waiting',(SELECT published_generation FROM library_meta),1,1),('workflow-4','z-task-unicode','split','concept-unicode','[]','waiting',(SELECT published_generation FROM library_meta),1,1);
UPDATE maintenance_tasks SET workflow_id='workflow-1' WHERE task_id='z-task-3';
-- Distinguish an ordinary live submitted call from an interrupted held one.
UPDATE jobs SET state='running' WHERE job_id='job-noise';
UPDATE job_items SET state='running',lease_until=unixepoch()+300 WHERE item_id='a-item-001';
UPDATE attempts SET outcome='running',validation_state='pending',completed_at=NULL WHERE item_id='a-item-001';
INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at)
SELECT job_id,item_id,'attempt-'||item_id,'provider-intent','{}','2026-09-12' FROM job_items WHERE item_id IN('a-item-001','a-item-002','a-item-003');
INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at)
VALUES('job-noise','a-item-003','attempt-a-item-003','provider-response','{}','2026-09-12');
-- Held outcomes beyond the first hundred ordinary failures must be selectable
-- directly, and a matching receipt must remove the hold from selection.
INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at)
SELECT job_id,item_id,'attempt-'||item_id,'provider-intent','{}','2026-09-14' FROM job_items WHERE item_id IN('z-item-101','z-item-102','z-item-103');
INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at)
VALUES('job-target','z-item-101','attempt-z-item-101','provider-response','{}','2026-09-14');
WITH RECURSIVE seq(n) AS(SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n<125)
INSERT INTO reviews(review_id,review_type,subject_id,state,proposal_json,created_at)
SELECT 'review-'||printf('%03d',n),'external-proposal','proposal-'||n,'pending','{}','2026-09-14' FROM seq;
WITH RECURSIVE seq(n) AS(SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n<125)
INSERT INTO sources(source_id,connector_type,stable_key,lifecycle_state,observed_uri,observed_title,visible_from_generation)
SELECT 'source-'||printf('%03d',n),'folder:fixture','file-'||n,'active','file:fixture-'||n,'Fixture '||n,(SELECT published_generation FROM library_meta) FROM seq;
]=])
file(WRITE "${CPRAG_WORK_DIR}/seed.sql" "${seed}")
execute_process(COMMAND "${CREXXRAG_SQLITE3}" -bail "${database}" INPUT_FILE "${CPRAG_WORK_DIR}/seed.sql"
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Diagnostic fixture data failed: ${out}${err}")
endif()
execute_process(COMMAND "${CREXXRAG_SQLITE3}" -readonly "${database}" .dump OUTPUT_VARIABLE before)
function(read_command expected)
    execute_process(COMMAND ${base} --access read ${ARGN}
        WORKING_DIRECTORY "${CPRAG_WORK_DIR}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    if(NOT result EQUAL expected OR out MATCHES "SECRET_RAW_INPUT_MUST_NOT_BE_RETURNED")
        string(SUBSTRING "${out}${err}" 0 1600 detail)
        message(FATAL_ERROR "Operator read failed (${ARGN}): ${detail}")
    endif()
    set(response "${out}" PARENT_SCOPE)
endfunction()
# Existing positive control is required before checking the missing interface.
read_command(0 job status job-target)
# Exact show must find records beyond every list page. The first record is
# a positive control; missing keys must retain the normal not-found result.
foreach(kind IN ITEMS review source)
    read_command(0 ${kind} show ${kind}-001)
    read_command(0 ${kind} show ${kind}-125)
    string(JSON shown GET "${response}" records 0 fields identity)
    string(JSON shown_count LENGTH "${response}" records)
    if(NOT shown STREQUAL "${kind}-125" OR NOT shown_count EQUAL 1)
        message(FATAL_ERROR "Exact ${kind} lookup returned unrelated rows or pagination: ${response}")
    endif()
    read_command(5 ${kind} show ${kind}-missing)
endforeach()
# A live call is still unresolved, but is not a reconciliation hold. Preserve
# the old total while exposing its disjoint active/held parts; matched receipts
# must disappear from all three counts. Reads may not change any outcome.
read_command(0 job items job-noise --state running)
string(JSON active_detail GET "${response}" records 0 fields detail)
string(JSON active_action GET "${active_detail}" recovery next_action)
if(NOT active_action MATCHES "worker status" OR active_action MATCHES "job reconcile")
    message(FATAL_ERROR "Live submitted work wrongly recommends reconciliation: ${active_action}")
endif()
read_command(0 job status job-noise)
string(JSON unresolved GET "${response}" records 0 fields uncertain_items)
string(JSON active GET "${response}" records 0 fields active_unsettled_items)
string(JSON held GET "${response}" records 0 fields held_uncertain_items)
if(NOT unresolved EQUAL 2 OR NOT active EQUAL 1 OR NOT held EQUAL 1)
    message(FATAL_ERROR "Live/held uncertainty counts overlap, lose outcomes or include a matched receipt")
endif()
# Select uncertainty using the same live/held split as status, before pagination.
read_command(0 job items job-target --uncertainty held --limit 1)
string(JSON selected GET "${response}" records 0 fields id)
string(JSON cursor GET "${response}" records 1 fields next_cursor)
if(NOT selected STREQUAL "z-item-102" OR NOT cursor STREQUAL "z-item-102")
    message(FATAL_ERROR "Held outcome filter ran after pagination or included unrelated failures: ${response}")
endif()
read_command(0 job items job-target --uncertainty held --cursor "${cursor}")
string(JSON count LENGTH "${response}" records)
string(JSON selected GET "${response}" records 0 fields id)
if(NOT count EQUAL 1 OR NOT selected STREQUAL "z-item-103")
    message(FATAL_ERROR "Held outcome continuation lost or duplicated a record: ${response}")
endif()
foreach(mode IN ITEMS active held)
    read_command(0 job items job-noise --uncertainty ${mode})
    string(JSON count LENGTH "${response}" records)
    string(JSON selected GET "${response}" records 0 fields id)
    if("${mode}" STREQUAL "active")
        set(expected a-item-001)
    else()
        set(expected a-item-002)
    endif()
    if(NOT count EQUAL 1 OR NOT selected STREQUAL expected)
        message(FATAL_ERROR "Uncertainty filter disagrees with independent status totals: ${response}")
    endif()
endforeach()
read_command(0 job items job-noise --uncertainty all)
string(JSON count LENGTH "${response}" records)
if(NOT count EQUAL 2)
    message(FATAL_ERROR "Uncertainty filter included matched receipts or omitted unresolved calls")
endif()
read_command(0 job items job-noise --uncertainty held --state running)
string(JSON count LENGTH "${response}" records)
if(NOT count EQUAL 0)
    message(FATAL_ERROR "State and uncertainty filters were not intersected")
endif()
read_command(0 job items job-empty --uncertainty held)
string(JSON count LENGTH "${response}" records)
if(NOT count EQUAL 0)
    message(FATAL_ERROR "Empty job produced held outcomes")
endif()
read_command(2 job items job-target --uncertainty unknown)
read_command(2 job attempts job-target --uncertainty held)
# Empty, malformed and missing input remains safe to inspect. Public totals
# group by actual operation/source, with no hidden denominator or raw payload.
read_command(0 job progress job-target)
string(JSON detail GET "${response}" records 0 fields detail)
string(JSON total GET "${detail}" total)
string(JSON failed GET "${detail}" dead_letter)
if(NOT total EQUAL 103 OR NOT failed EQUAL 103)
    message(FATAL_ERROR "Public progress lost failed items or its denominator")
endif()
execute_process(COMMAND "${CREXXRAG_SQLITE3}" -readonly "${database}"
    "EXPLAIN QUERY PLAN SELECT count(*) FROM job_items i WHERE i.job_id='job-target' AND EXISTS(SELECT 1 FROM job_events u WHERE u.item_id=i.item_id AND u.event_type IN('provider-intent','provider-outcome-uncertain') AND NOT EXISTS(SELECT 1 FROM job_events r WHERE r.attempt_id=u.attempt_id AND r.event_type='provider-response'));"
    OUTPUT_VARIABLE uncertainty_plan RESULT_VARIABLE plan_status)
if(NOT plan_status EQUAL 0 OR uncertainty_plan MATCHES "SCAN u")
    message(FATAL_ERROR "Routine uncertainty status scans the entire event ledger per item: ${uncertainty_plan}")
endif()
read_command(2 maintain tasks task-a task-b)
read_command(0 job items job-target --state dead_letter --limit 100)
string(JSON count LENGTH "${response}" records)
string(JSON cursor GET "${response}" records 100 fields next_cursor)
if(NOT count EQUAL 101 OR NOT cursor STREQUAL "z-item-100")
    message(FATAL_ERROR "Job filter/pagination dropped or mixed rows: ${response}")
endif()
read_command(0 job items job-target --state dead_letter --limit 100 --cursor "${cursor}")
string(JSON count LENGTH "${response}" records)
if(NOT count EQUAL 3)
    message(FATAL_ERROR "Job item continuation lost rows: ${response}")
endif()
read_command(0 job attempts job-target --item z-item-103)
string(JSON count LENGTH "${response}" records)
string(JSON id GET "${response}" records 0 fields id)
if(NOT count EQUAL 1 OR NOT id STREQUAL "attempt-z-item-103")
    message(FATAL_ERROR "Attempt lookup lost job/item ownership: ${response}")
endif()
read_command(0 job attempts job-target --limit 100)
string(JSON cursor GET "${response}" records 100 fields next_cursor)
if(NOT cursor STREQUAL "attempt-z-item-100")
    message(FATAL_ERROR "Attempt page was filtered after pagination: ${response}")
endif()
read_command(0 maintain tasks --subject concept-target --limit 2)
string(JSON cursor GET "${response}" records 2 fields next_cursor)
if(NOT cursor STREQUAL "z-task-2")
    message(FATAL_ERROR "Task subject filter was not applied before pagination: ${response}")
endif()
read_command(0 maintain tasks --subject concept-target --workflow workflow-1)
string(JSON count LENGTH "${response}" records)
string(JSON id GET "${response}" records 0 fields id)
if(NOT count EQUAL 2 OR NOT id STREQUAL "z-task-3")
    message(FATAL_ERROR "Task filters were not intersected: ${response}")
endif()
read_command(0 maintain workflows --subject concept-target --limit 1)
string(JSON cursor GET "${response}" records 1 fields next_cursor)
if(NOT cursor STREQUAL "workflow-1")
    message(FATAL_ERROR "Workflow parent lookup failed: ${response}")
endif()
read_command(0 maintain workflows --subject concept-successor)
string(JSON count LENGTH "${response}" records)
string(JSON id GET "${response}" records 0 fields id)
if(NOT count EQUAL 1 OR NOT id STREQUAL "workflow-1")
    message(FATAL_ERROR "Workflow successor lookup failed: ${response}")
endif()
# Name-based discovery must retain separate homonymous concepts/workflows.
read_command(0 maintain workflows --concept Turray)
string(JSON count LENGTH "${response}" records)
if(NOT count EQUAL 3)
    message(FATAL_ERROR "Named migration lookup lost a homonym: ${response}")
endif()
read_command(0 maintain tasks --concept Turray)
string(JSON count LENGTH "${response}" records)
if(NOT count EQUAL 5)
    message(FATAL_ERROR "Named task lookup lost a homonym: ${response}")
endif()
read_command(0 maintain workflows --concept "Dùn Èideann's")
string(JSON count LENGTH "${response}" records)
string(JSON id GET "${response}" records 0 fields id)
if(NOT count EQUAL 1 OR NOT id STREQUAL "workflow-4")
    message(FATAL_ERROR "Unicode or quoted concept label lookup changed: ${response}")
endif()
read_command(0 job items job-empty)
string(JSON count LENGTH "${response}" records)
if(NOT count EQUAL 0)
    message(FATAL_ERROR "Empty existing job is not an empty page: ${response}")
endif()
read_command(5 job items job-missing)
read_command(5 job items "job-target' OR 1=1--")
read_command(2 job items job-target --limit 101)
read_command(2 job attempts job-target --limit 9223372036854775808)
read_command(2 maintain workflows --limit 0)
read_command(2 maintain tasks --subject concept-target --unexpected value)
read_command(0 job items job-target --limit 2)
string(JSON expected_records_0 GET "${response}" records)
read_command(0 job attempts job-target --item z-item-103)
string(JSON expected_records_1 GET "${response}" records)
read_command(0 maintain tasks --subject concept-target --limit 2)
string(JSON expected_records_2 GET "${response}" records)
read_command(0 maintain workflows --concept Turray)
string(JSON expected_records_3 GET "${response}" records)
read_command(0 job items job-target --uncertainty held --limit 1)
string(JSON expected_held_records GET "${response}" records)
set(requests [=[
{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"rag_job_items","arguments":{"id":"job-target","limit":2}}}
{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"rag_job_attempts","arguments":{"id":"job-target","item":"z-item-103"}}}
{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"rag_task_list","arguments":{"subject":"concept-target","limit":2}}}
{"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"rag_workflow_list","arguments":{"concept":"Turray"}}}
{"jsonrpc":"2.0","id":5,"method":"tools/call","params":{"name":"rag_job_items","arguments":{"id":"job-target","unexpected":"value"}}}
{"jsonrpc":"2.0","id":6,"method":"tools/call","params":{"name":"rag_workflow_list","arguments":{"concept":"\u0000"}}}
{"jsonrpc":"2.0","id":7,"method":"tools/call","params":{"name":"rag_job_items","arguments":{"id":"job-target","uncertainty":"held","limit":1}}}
]=])
file(WRITE "${CPRAG_WORK_DIR}/requests.jsonl" "${requests}")
execute_process(COMMAND ${base} --access read serve mcp INPUT_FILE "${CPRAG_WORK_DIR}/requests.jsonl"
    OUTPUT_FILE "${CPRAG_WORK_DIR}/responses.jsonl" ERROR_VARIABLE err RESULT_VARIABLE result TIMEOUT 30)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Diagnostic MCP session failed: ${err}")
endif()
file(STRINGS "${CPRAG_WORK_DIR}/responses.jsonl" responses)
list(LENGTH responses count)
if(NOT count EQUAL 7)
    message(FATAL_ERROR "Diagnostic MCP response count changed")
endif()
foreach(index RANGE 0 3)
    list(GET responses ${index} response)
    string(JSON is_error GET "${response}" result isError)
    if(is_error)
        message(FATAL_ERROR "MCP diagnostic failed: ${response}")
    endif()
    string(JSON actual_records GET "${response}" result structuredContent records)
    if(NOT actual_records STREQUAL expected_records_${index})
        message(FATAL_ERROR "CLI and MCP diagnostic records differ for route ${index}")
    endif()
endforeach()
list(GET responses 4 response)
string(JSON code GET "${response}" error code)
if(NOT code EQUAL -32602)
    message(FATAL_ERROR "Unknown diagnostic argument was accepted")
endif()
list(GET responses 5 response)
string(JSON code GET "${response}" result structuredContent exit_code)
if(NOT code EQUAL 2)
    message(FATAL_ERROR "NUL in diagnostic filter did not return usage")
endif()
list(GET responses 6 response)
string(JSON actual_held_records GET "${response}" result structuredContent records)
if(NOT actual_held_records STREQUAL expected_held_records)
    message(FATAL_ERROR "CLI/MCP held-outcome selection differs: ${response}")
endif()
execute_process(COMMAND "${CREXXRAG_SQLITE3}" -readonly "${database}" .dump OUTPUT_VARIABLE after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Read-only operator diagnostics changed the library")
endif()
message(STATUS "Operator diagnostics preserve job/subject ownership, bounded pages, strict arguments and zero-write CLI/MCP equivalence")
