foreach(required_var CPRAG_RXC CPRAG_RXAS CPRAG_RXLINK CPRAG_RXVME CPRAG_CREXX_BIN_DIR CPRAG_MODULE CPRAG_SOURCE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/CpragLinkCrexx.cmake")
if("$ENV{GEMINI_API_KEY}" STREQUAL "")
    message(FATAL_ERROR "GEMINI_API_KEY is unavailable")
endif()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
set(module_base "${CPRAG_WORK_DIR}/provider_boundary")
set(program "${CPRAG_WORK_DIR}/gemini-canary")
set(program_import_path "${CPRAG_WORK_DIR};${CPRAG_CREXX_BIN_DIR}")
execute_process(COMMAND "${CPRAG_RXC}" -i "${program_import_path}" --import-rxas -o "${module_base}" "${CPRAG_MODULE}" OUTPUT_VARIABLE module_rxc_out ERROR_VARIABLE module_rxc_err RESULT_VARIABLE module_rxc_result)
if(NOT module_rxc_result EQUAL 0)
    message(FATAL_ERROR "Canary provider module compile failed:\n${module_rxc_out}\n${module_rxc_err}")
endif()
execute_process(COMMAND "${CPRAG_RXAS}" -o "${module_base}" "${module_base}" OUTPUT_VARIABLE module_rxas_out ERROR_VARIABLE module_rxas_err RESULT_VARIABLE module_rxas_result)
if(NOT module_rxas_result EQUAL 0)
    message(FATAL_ERROR "Canary provider module assembly failed:\n${module_rxas_out}\n${module_rxas_err}")
endif()
execute_process(COMMAND "${CPRAG_RXC}" -i "${program_import_path}" --import-rxas -o "${program}" "${CPRAG_SOURCE}" OUTPUT_VARIABLE rxc_out ERROR_VARIABLE rxc_err RESULT_VARIABLE rxc_result)
if(NOT rxc_result EQUAL 0)
    message(FATAL_ERROR "Canary compile failed:\n${rxc_out}\n${rxc_err}")
endif()
execute_process(COMMAND "${CPRAG_RXAS}" -o "${program}" "${program}" OUTPUT_VARIABLE rxas_out ERROR_VARIABLE rxas_err RESULT_VARIABLE rxas_result)
if(NOT rxas_result EQUAL 0)
    message(FATAL_ERROR "Canary assembly failed:\n${rxas_out}\n${rxas_err}")
endif()
set(linked_program "${CPRAG_WORK_DIR}/gemini-canary-linked")
cprag_link_crexx("${linked_program}" "P1A Gemini canary"
    "${program}.rxbin"
    "${module_base}.rxbin"
    "${CPRAG_CREXX_BIN_DIR}/rxfnsg.rxbin"
    "${CPRAG_CREXX_BIN_DIR}/classlib.rxbin"
    "${CPRAG_CREXX_BIN_DIR}/library.rxbin")
execute_process(COMMAND "${CPRAG_RXVME}" -l "${program_import_path}" "${linked_program}.rxbin" OUTPUT_VARIABLE vm_out ERROR_VARIABLE vm_err RESULT_VARIABLE vm_result TIMEOUT 75)
file(WRITE "${CPRAG_WORK_DIR}/canary-result.txt" "provider module rxc:\n${module_rxc_out}${module_rxc_err}\nprovider module rxas:\n${module_rxas_out}${module_rxas_err}\ncanary rxc:\n${rxc_out}${rxc_err}\ncanary rxas:\n${rxas_out}${rxas_err}\nrxvme:\n${vm_out}${vm_err}\nresult=${vm_result}\n")
if(NOT vm_result EQUAL 0 OR NOT vm_out MATCHES "P1A_GEMINI_CANARY status=ok")
    message(FATAL_ERROR "Gemini canary failed (${vm_result}):\n${vm_out}\n${vm_err}")
endif()
message(STATUS "${vm_out}")
