if(NOT DEFINED CPRAG_EVIDENCE OR NOT EXISTS "${CPRAG_EVIDENCE}")
    message(FATAL_ERROR "Retained Gemini canary evidence is missing")
endif()
file(READ "${CPRAG_EVIDENCE}" evidence)
foreach(required "status=ok" "generation_match=1" "embedding_dimensions=8" "gemini-3.5-flash" "gemini-embedding-001" "credential_retained=no")
    string(FIND "${evidence}" "${required}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Gemini canary evidence omitted ${required}")
    endif()
endforeach()
message(STATUS "Retained Gemini generation/embedding canary evidence is complete")
