foreach(required_var CPRAG_RXC CPRAG_RXAS CPRAG_RXVME CPRAG_RXBVM CPRAG_CREXX_BIN_DIR CPRAG_PLUGIN_DIR CPRAG_STORE CPRAG_LIFECYCLE CPRAG_CLAIMS CPRAG_EVIDENCE CPRAG_CODEC CPRAG_VECTOR_SEARCH CPRAG_SOURCE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
set(base_import "${CPRAG_PLUGIN_DIR};${CPRAG_CREXX_BIN_DIR}")
set(program_import "${CPRAG_WORK_DIR};${base_import}")
set(report "${CPRAG_WORK_DIR}/commands-and-output.txt")
file(WRITE "${report}" "store=${CPRAG_STORE}\nlifecycle=${CPRAG_LIFECYCLE}\nclaims=${CPRAG_CLAIMS}\nevidence=${CPRAG_EVIDENCE}\ncodec=${CPRAG_CODEC}\nvector_search=${CPRAG_VECTOR_SEARCH}\nsource=${CPRAG_SOURCE}\ndatabase=scratch-per-cell\nproduction_schema=0\n")
function(compile_crexx source output imports mode_flag label)
    execute_process(COMMAND "${CPRAG_RXC}" ${mode_flag} -i "${imports}" -o "${output}" "${source}" OUTPUT_VARIABLE compile_out ERROR_VARIABLE compile_err RESULT_VARIABLE compile_result)
    if(NOT compile_result EQUAL 0)
        message(FATAL_ERROR "${label} compile failed:\n${compile_out}\n${compile_err}")
    endif()
    execute_process(COMMAND "${CPRAG_RXAS}" ${mode_flag} -o "${output}" "${output}" OUTPUT_VARIABLE assemble_out ERROR_VARIABLE assemble_err RESULT_VARIABLE assemble_result)
    if(NOT assemble_result EQUAL 0)
        message(FATAL_ERROR "${label} assembly failed:\n${assemble_out}\n${assemble_err}")
    endif()
    file(APPEND "${report}" "${label} compile:\n${compile_out}${compile_err}${label} assemble:\n${assemble_out}${assemble_err}\n")
endfunction()
foreach(mode IN ITEMS noopt opt)
    set(mode_flag)
    if(mode STREQUAL "noopt")
        set(mode_flag -n)
    endif()
    compile_crexx("${CPRAG_STORE}" "${CPRAG_WORK_DIR}/source_store" "${base_import}" "${mode_flag}" "${mode} source store")
    compile_crexx("${CPRAG_LIFECYCLE}" "${CPRAG_WORK_DIR}/source_lifecycle" "${program_import}" "${mode_flag}" "${mode} lifecycle")
    compile_crexx("${CPRAG_CLAIMS}" "${CPRAG_WORK_DIR}/claim_store" "${program_import}" "${mode_flag}" "${mode} claims")
    compile_crexx("${CPRAG_EVIDENCE}" "${CPRAG_WORK_DIR}/evidence_packet" "${program_import}" "${mode_flag}" "${mode} evidence")
    compile_crexx("${CPRAG_CODEC}" "${CPRAG_WORK_DIR}/vector_codec" "${base_import}" "${mode_flag}" "${mode} codec")
    compile_crexx("${CPRAG_VECTOR_SEARCH}" "${CPRAG_WORK_DIR}/vector_search" "${base_import}" "${mode_flag}" "${mode} vector search")
    compile_crexx("${CPRAG_SOURCE}" "${CPRAG_WORK_DIR}/program-${mode}" "${program_import}" "${mode_flag}" "${mode} test")
    foreach(runtime_name IN ITEMS rxvme rxbvm)
        if(runtime_name STREQUAL "rxvme")
            set(runtime "${CPRAG_RXVME}")
        else()
            set(runtime "${CPRAG_RXBVM}")
        endif()
        set(cell "${mode}-${runtime_name}")
        set(database "${CPRAG_WORK_DIR}/${cell}.sqlite")
        execute_process(COMMAND "${runtime}" -l "${program_import}" "${CPRAG_WORK_DIR}/program-${mode}" source_store source_lifecycle claim_store evidence_packet vector_codec vector_search rx_sqlite_boundary library -a "${database}" "${cell}" OUTPUT_VARIABLE vm_out ERROR_VARIABLE vm_err RESULT_VARIABLE vm_result)
        if(NOT vm_result EQUAL 0 OR NOT vm_out MATCHES "P1_ALG_04_OK cell=${cell} lexical_passages=1 accepted_claims=1 normalized_supports=1 ambiguities=1 ambiguity_candidates=2 vector_leads=1 vector_is_fact=0 direction=subject-to-object limitation=explicit")
            message(FATAL_ERROR "${cell} failed (${vm_result}):\n${vm_out}\n${vm_err}")
        endif()
        file(APPEND "${report}" "${cell}:\n${vm_out}${vm_err}\n")
    endforeach()
endforeach()
message(STATUS "P1-ALG-04 passed typed multi-kind evidence assembly on rxvme/rxbvm")
