foreach(required_var CPRAG_RXC CPRAG_RXAS CPRAG_RXVME CPRAG_RXBVM CPRAG_CREXX_BIN_DIR CPRAG_PLUGIN_DIR CPRAG_STORE CPRAG_LIFECYCLE CPRAG_CLAIMS CPRAG_EVIDENCE CPRAG_SOURCE CPRAG_ORACLE CPRAG_GOLDEN CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/CpragProcessMetrics.cmake")
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
set(base_import "${CPRAG_PLUGIN_DIR};${CPRAG_CREXX_BIN_DIR}")
set(program_import "${CPRAG_WORK_DIR};${base_import}")
set(report "${CPRAG_WORK_DIR}/commands-and-output.txt")

execute_process(COMMAND "${CPRAG_TIME_EXECUTABLE}" ${CPRAG_TIME_RESOURCE_ARGS} "${CPRAG_ORACLE}" OUTPUT_VARIABLE oracle_out ERROR_VARIABLE oracle_err RESULT_VARIABLE oracle_result)
if(NOT oracle_result EQUAL 0)
    message(FATAL_ERROR "Native semantic oracle failed (${oracle_result}):\n${oracle_out}\n${oracle_err}")
endif()
file(READ "${CPRAG_GOLDEN}" golden)
if(NOT oracle_out STREQUAL golden)
    message(FATAL_ERROR "Native semantic oracle differs from retained golden")
endif()
string(REGEX MATCHALL "\"record\"" oracle_records "${oracle_out}")
list(LENGTH oracle_records oracle_record_count)
if(NOT oracle_record_count EQUAL 9)
    message(FATAL_ERROR "Expected 9 native semantic records, got ${oracle_record_count}")
endif()
cprag_extract_peak_rss("${oracle_err}" oracle_rss)
file(WRITE "${CPRAG_WORK_DIR}/native-oracle.jsonl" "${oracle_out}")
file(WRITE "${report}" "native_oracle=${CPRAG_ORACLE}\ngolden=${CPRAG_GOLDEN}\nnative_records=${oracle_record_count}\nnative_peak_rss_bytes=${oracle_rss}\nsource=${CPRAG_SOURCE}\ndatabase=scratch-per-cell\nproduction_schema=0\n")

function(compile_crexx source output imports mode_flag label)
    execute_process(COMMAND "${CPRAG_RXC}" ${mode_flag} -i "${imports}" -o "${output}" "${source}" OUTPUT_VARIABLE compile_out ERROR_VARIABLE compile_err RESULT_VARIABLE compile_result)
    if(NOT compile_result EQUAL 0)
        message(FATAL_ERROR "${label} compile failed:\n${compile_out}\n${compile_err}")
    endif()
    execute_process(COMMAND "${CPRAG_RXAS}" ${mode_flag} -o "${output}" "${output}" OUTPUT_VARIABLE assemble_out ERROR_VARIABLE assemble_err RESULT_VARIABLE assemble_result)
    if(NOT assemble_result EQUAL 0)
        message(FATAL_ERROR "${label} assembly failed:\n${assemble_out}\n${assemble_err}")
    endif()
    file(APPEND "${report}" "${label} compile:\n${compile_out}${compile_err}${label} assemble:\n${assemble_out}${assemble_err}\n")
endfunction()
foreach(mode IN ITEMS noopt opt)
    set(mode_flag)
    if(mode STREQUAL "noopt")
        set(mode_flag -n)
    endif()
    compile_crexx("${CPRAG_STORE}" "${CPRAG_WORK_DIR}/source_store" "${base_import}" "${mode_flag}" "${mode} source store")
    compile_crexx("${CPRAG_LIFECYCLE}" "${CPRAG_WORK_DIR}/source_lifecycle" "${program_import}" "${mode_flag}" "${mode} lifecycle")
    compile_crexx("${CPRAG_CLAIMS}" "${CPRAG_WORK_DIR}/claim_store" "${program_import}" "${mode_flag}" "${mode} claims")
    compile_crexx("${CPRAG_EVIDENCE}" "${CPRAG_WORK_DIR}/evidence_packet" "${program_import}" "${mode_flag}" "${mode} evidence")
    compile_crexx("${CPRAG_SOURCE}" "${CPRAG_WORK_DIR}/program-${mode}" "${program_import}" "${mode_flag}" "${mode} test")
    foreach(runtime_name IN ITEMS rxvme rxbvm)
        if(runtime_name STREQUAL "rxvme")
            set(runtime "${CPRAG_RXVME}")
        else()
            set(runtime "${CPRAG_RXBVM}")
        endif()
        set(cell "${mode}-${runtime_name}")
        set(database "${CPRAG_WORK_DIR}/${cell}.sqlite")
        execute_process(COMMAND "${CPRAG_TIME_EXECUTABLE}" ${CPRAG_TIME_RESOURCE_ARGS} "${runtime}" -l "${program_import}" "${CPRAG_WORK_DIR}/program-${mode}" source_store source_lifecycle claim_store evidence_packet rx_sqlite_boundary library -a "${database}" "${cell}" OUTPUT_VARIABLE vm_out ERROR_VARIABLE vm_err RESULT_VARIABLE vm_result)
        if(NOT vm_result EQUAL 0 OR NOT vm_out MATCHES "P1_ALG_05_OK cell=${cell} native_records=9 deterministic_chunking=1 lexical_sources=2,1 identical_writes=0 paragraph_reuse=1 direction=forward accepted_claim=1 exact_support=1 ambiguity=explicit vector_is_fact=0 retracted_claim=1 algorithm_2000_us=[0-9]+ threshold_us=10000 checksum=[0-9]+")
            message(FATAL_ERROR "${cell} failed (${vm_result}):\n${vm_out}\n${vm_err}")
        endif()
        string(REGEX MATCH "algorithm_2000_us=([0-9]+)" algorithm_match "${vm_out}")
        set(algorithm_us "${CMAKE_MATCH_1}")
        if(algorithm_match STREQUAL "")
            message(FATAL_ERROR "${cell} omitted algorithm timing: ${vm_out}")
        endif()
        set(profile_trigger "retained")
        if(algorithm_us GREATER 10000)
            set(profile_trigger "crossed")
        endif()
        cprag_extract_peak_rss("${vm_err}" vm_rss)
        file(APPEND "${report}" "${cell}:\n${vm_out}profile_trigger=${profile_trigger}\nprocess_peak_rss_bytes=${vm_rss}\n${vm_err}\n")
        file(WRITE "${CPRAG_WORK_DIR}/${cell}-metrics.txt" "${vm_out}profile_trigger=${profile_trigger}\nprocess_peak_rss_bytes=${vm_rss}\n")
    endforeach()
endforeach()
message(STATUS "P1-ALG-05 passed native-golden semantic parity and recorded both-VM profile evidence")
