foreach(required_var CPRAG_RXC CPRAG_RXAS CPRAG_RXLINK CPRAG_RXVME CPRAG_RXBVM CPRAG_CREXX_BIN_DIR CPRAG_MODULE CPRAG_SOURCE CPRAG_LOOPBACK CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/CpragLinkCrexx.cmake")
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
set(module_base "${CPRAG_WORK_DIR}/provider_boundary")
set(program "${CPRAG_WORK_DIR}/provider-boundary-test")
set(port 18991)
set(program_import_path "${CPRAG_WORK_DIR};${CPRAG_CREXX_BIN_DIR}")

execute_process(COMMAND "${CPRAG_RXC}" -i "${CPRAG_CREXX_BIN_DIR}" --import-rxas -o "${module_base}" "${CPRAG_MODULE}" OUTPUT_VARIABLE module_rxc_out ERROR_VARIABLE module_rxc_err RESULT_VARIABLE module_rxc_result)
if(NOT module_rxc_result EQUAL 0)
    message(FATAL_ERROR "Provider module compile failed:\n${module_rxc_out}\n${module_rxc_err}")
endif()
execute_process(COMMAND "${CPRAG_RXAS}" -o "${module_base}" "${module_base}" OUTPUT_VARIABLE module_rxas_out ERROR_VARIABLE module_rxas_err RESULT_VARIABLE module_rxas_result)
if(NOT module_rxas_result EQUAL 0)
    message(FATAL_ERROR "Provider module assembly failed:\n${module_rxas_out}\n${module_rxas_err}")
endif()
execute_process(COMMAND "${CPRAG_RXC}" -i "${program_import_path}" --import-rxas -o "${program}" "${CPRAG_SOURCE}" OUTPUT_VARIABLE rxc_out ERROR_VARIABLE rxc_err RESULT_VARIABLE rxc_result)
if(NOT rxc_result EQUAL 0)
    message(FATAL_ERROR "Provider test compile failed:\n${rxc_out}\n${rxc_err}")
endif()
execute_process(COMMAND "${CPRAG_RXAS}" -o "${program}" "${program}" OUTPUT_VARIABLE rxas_out ERROR_VARIABLE rxas_err RESULT_VARIABLE rxas_result)
if(NOT rxas_result EQUAL 0)
    message(FATAL_ERROR "Provider test assembly failed:\n${rxas_out}\n${rxas_err}")
endif()
set(linked_program "${CPRAG_WORK_DIR}/provider-boundary-linked")
cprag_link_crexx("${linked_program}" "P1A provider boundary"
    "${program}.rxbin"
    "${module_base}.rxbin"
    "${CPRAG_CREXX_BIN_DIR}/rxfnsg.rxbin"
    "${CPRAG_CREXX_BIN_DIR}/classlib.rxbin"
    "${CPRAG_CREXX_BIN_DIR}/library.rxbin")

set(provider_out "${CPRAG_WORK_DIR}/loopback.out")
set(provider_err "${CPRAG_WORK_DIR}/loopback.err")
execute_process(COMMAND /bin/sh -c "\"$1\" \"$2\" 10 >\"$3\" 2>\"$4\" &" p1a-provider "${CPRAG_LOOPBACK}" "${port}" "${provider_out}" "${provider_err}" RESULT_VARIABLE start_result)
if(NOT start_result EQUAL 0)
    message(FATAL_ERROR "Could not start P1A provider loopback")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.2)
file(WRITE "${CPRAG_WORK_DIR}/commands-and-output.txt"
    "provider module rxc:\n${module_rxc_out}${module_rxc_err}\nprovider module rxas:\n${module_rxas_out}${module_rxas_err}\ntest rxc:\n${rxc_out}${rxc_err}\ntest rxas:\n${rxas_out}${rxas_err}\n")

foreach(runtime_name IN ITEMS rxvme rxbvm)
    if(runtime_name STREQUAL "rxvme")
        set(runtime "${CPRAG_RXVME}")
    else()
        set(runtime "${CPRAG_RXBVM}")
    endif()
    execute_process(COMMAND "${runtime}" -l "${program_import_path}" "${linked_program}.rxbin" -a "${port}" OUTPUT_VARIABLE vm_out ERROR_VARIABLE vm_err RESULT_VARIABLE vm_result)
    file(APPEND "${CPRAG_WORK_DIR}/commands-and-output.txt"
        "${runtime_name}: ${runtime} -l ${program_import_path} ${linked_program}.rxbin -a ${port}\n${vm_out}${vm_err}\nresult=${vm_result}\n")
    if(NOT vm_result EQUAL 0 OR NOT vm_out MATCHES "P1A_LLM_OK")
        message(FATAL_ERROR "${runtime_name} provider boundary failed (${vm_result}):\n${vm_out}\n${vm_err}")
    endif()
endforeach()

execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.4)
file(READ "${provider_out}" loopback_out)
file(READ "${provider_err}" loopback_err)
file(APPEND "${CPRAG_WORK_DIR}/commands-and-output.txt" "loopback:\n${loopback_out}${loopback_err}\n")
if(NOT loopback_out MATCHES "READY ${port}")
    message(FATAL_ERROR "Loopback provider readiness missing:\n${loopback_out}\n${loopback_err}")
endif()
message(STATUS "P1A provider boundary passed rxvme/rxbvm with production rxjson and no rx_socket module argument")
