foreach(required_var CPRAG_RXC CPRAG_RXAS CPRAG_RXVME CPRAG_RXBVM CPRAG_CREXX_BIN_DIR CPRAG_PLUGIN_DIR CPRAG_MODULE CPRAG_FAULTS CPRAG_SOURCE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
set(base_import "${CPRAG_PLUGIN_DIR};${CPRAG_CREXX_BIN_DIR}")
set(program_import "${CPRAG_WORK_DIR};${base_import}")
set(report "${CPRAG_WORK_DIR}/commands-and-output.txt")
file(WRITE "${report}" "module=${CPRAG_MODULE}\nfaults=${CPRAG_FAULTS}\nsource=${CPRAG_SOURCE}\ndatabase=scratch-per-cell\nproduction_schema=0\nforced_exit_codes=71,72,73,74\n")
function(compile_crexx source output imports mode_flag label)
    execute_process(COMMAND "${CPRAG_RXC}" ${mode_flag} -i "${imports}" -o "${output}" "${source}" OUTPUT_VARIABLE compile_out ERROR_VARIABLE compile_err RESULT_VARIABLE compile_result)
    if(NOT compile_result EQUAL 0)
        message(FATAL_ERROR "${label} compile failed:\n${compile_out}\n${compile_err}")
    endif()
    execute_process(COMMAND "${CPRAG_RXAS}" ${mode_flag} -o "${output}" "${output}" OUTPUT_VARIABLE assemble_out ERROR_VARIABLE assemble_err RESULT_VARIABLE assemble_result)
    if(NOT assemble_result EQUAL 0)
        message(FATAL_ERROR "${label} assembly failed:\n${assemble_out}\n${assemble_err}")
    endif()
    file(APPEND "${report}" "${label} compile:\n${compile_out}${compile_err}${label} assemble:\n${assemble_out}${assemble_err}\n")
endfunction()
function(run_stage runtime program database cell stage expected_result expected_pattern)
    execute_process(COMMAND "${runtime}" -l "${program_import}" "${program}" job_queue job_faults rx_sqlite_boundary library -a "${stage}" "${database}" "${cell}" OUTPUT_VARIABLE stage_out ERROR_VARIABLE stage_err RESULT_VARIABLE stage_result)
    if(NOT stage_result EQUAL expected_result OR NOT stage_out MATCHES "${expected_pattern}")
        message(FATAL_ERROR "${cell} ${stage} failed (${stage_result}, expected ${expected_result}):\n${stage_out}\n${stage_err}")
    endif()
    file(APPEND "${report}" "${cell} ${stage}:\n${stage_out}${stage_err}result=${stage_result}\n")
endfunction()
foreach(mode IN ITEMS noopt opt)
    set(mode_flag)
    if(mode STREQUAL "noopt")
        set(mode_flag -n)
    endif()
    compile_crexx("${CPRAG_MODULE}" "${CPRAG_WORK_DIR}/job_queue" "${base_import}" "${mode_flag}" "${mode} job queue")
    compile_crexx("${CPRAG_FAULTS}" "${CPRAG_WORK_DIR}/job_faults" "${base_import}" "${mode_flag}" "${mode} fault injection")
    compile_crexx("${CPRAG_SOURCE}" "${CPRAG_WORK_DIR}/program-${mode}" "${program_import}" "${mode_flag}" "${mode} scenario")
    foreach(runtime_name IN ITEMS rxvme rxbvm)
        if(runtime_name STREQUAL "rxvme")
            set(runtime "${CPRAG_RXVME}")
        else()
            set(runtime "${CPRAG_RXBVM}")
        endif()
        set(cell "${mode}-${runtime_name}")
        set(database "${CPRAG_WORK_DIR}/${cell}.sqlite")
        set(program "${CPRAG_WORK_DIR}/program-${mode}")
        run_stage("${runtime}" "${program}" "${database}" "${cell}" init 0 "stage=init state=queued items=4")
        run_stage("${runtime}" "${program}" "${database}" "${cell}" crash-before-call 71 "forced=1 fence=1")
        run_stage("${runtime}" "${program}" "${database}" "${cell}" recover-before-call 0 "fence=2 stale_rejected=1")
        run_stage("${runtime}" "${program}" "${database}" "${cell}" crash-after-call 72 "forced=1 fence=3 provider_calls=1")
        run_stage("${runtime}" "${program}" "${database}" "${cell}" recover-after-call 0 "fence=4 repeated_provider_call=1")
        run_stage("${runtime}" "${program}" "${database}" "${cell}" crash-during-promotion 73 "forced=1 fence=5 transaction_open=1")
        run_stage("${runtime}" "${program}" "${database}" "${cell}" recover-during-promotion 0 "fence=6 uncommitted_support_rolled_back=1")
        run_stage("${runtime}" "${program}" "${database}" "${cell}" crash-after-promotion 74 "forced=1 fence=7 promotion_committed=1")
        run_stage("${runtime}" "${program}" "${database}" "${cell}" recover-after-promotion 0 "P1_JOB_02_OK cell=${cell} forced_boundaries=before-call,after-call,during-promotion,after-promotion fences=7 attempts=7 expired_attempts=3 succeeded_attempts=4 stale_rejected=1 uncommitted_rollback=1 committed_replay=idempotent supports=4 duplicate_support=0 maximum_provider_replay=1")
    endforeach()
endforeach()
message(STATUS "P1-JOB-02 passed four forced-termination boundaries and duplicate-free recovery on rxvme/rxbvm")
