foreach(required_var CPRAG_RXC CPRAG_RXAS CPRAG_RXVME CPRAG_RXBVM CPRAG_CREXX_BIN_DIR CPRAG_PLUGIN_DIR CPRAG_QUEUE CPRAG_BUDGET CPRAG_SOURCE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
set(base_import "${CPRAG_PLUGIN_DIR};${CPRAG_CREXX_BIN_DIR}")
set(program_import "${CPRAG_WORK_DIR};${base_import}")
set(report "${CPRAG_WORK_DIR}/commands-and-output.txt")
file(WRITE "${report}" "queue=${CPRAG_QUEUE}\nbudget=${CPRAG_BUDGET}\nsource=${CPRAG_SOURCE}\ndatabase=scratch-per-cell\nproduction_schema=0\nprovider=deterministic-pure-work\n")
function(compile_crexx source output imports mode_flag label)
    execute_process(COMMAND "${CPRAG_RXC}" ${mode_flag} -i "${imports}" -o "${output}" "${source}" OUTPUT_VARIABLE compile_out ERROR_VARIABLE compile_err RESULT_VARIABLE compile_result)
    if(NOT compile_result EQUAL 0)
        message(FATAL_ERROR "${label} compile failed:\n${compile_out}\n${compile_err}")
    endif()
    execute_process(COMMAND "${CPRAG_RXAS}" ${mode_flag} -o "${output}" "${output}" OUTPUT_VARIABLE assemble_out ERROR_VARIABLE assemble_err RESULT_VARIABLE assemble_result)
    if(NOT assemble_result EQUAL 0)
        message(FATAL_ERROR "${label} assembly failed:\n${assemble_out}\n${assemble_err}")
    endif()
    file(APPEND "${report}" "${label} compile:\n${compile_out}${compile_err}${label} assemble:\n${assemble_out}${assemble_err}\n")
endfunction()
foreach(mode IN ITEMS noopt opt)
    set(mode_flag)
    if(mode STREQUAL "noopt")
        set(mode_flag -n)
    endif()
    compile_crexx("${CPRAG_QUEUE}" "${CPRAG_WORK_DIR}/job_queue" "${base_import}" "${mode_flag}" "${mode} job queue")
    compile_crexx("${CPRAG_BUDGET}" "${CPRAG_WORK_DIR}/job_budget" "${program_import}" "${mode_flag}" "${mode} job budget")
    compile_crexx("${CPRAG_SOURCE}" "${CPRAG_WORK_DIR}/program-${mode}" "${program_import}" "${mode_flag}" "${mode} test")
    foreach(runtime_name IN ITEMS rxvme rxbvm)
        if(runtime_name STREQUAL "rxvme")
            set(runtime "${CPRAG_RXVME}")
        else()
            set(runtime "${CPRAG_RXBVM}")
        endif()
        set(cell "${mode}-${runtime_name}")
        set(database "${CPRAG_WORK_DIR}/${cell}.sqlite")
        execute_process(COMMAND "${runtime}" -l "${program_import}" "${CPRAG_WORK_DIR}/program-${mode}" job_queue job_budget rx_sqlite_boundary library -a "${database}" "${cell}" OUTPUT_VARIABLE vm_out ERROR_VARIABLE vm_err RESULT_VARIABLE vm_result)
        if(NOT vm_result EQUAL 0 OR NOT vm_out MATCHES "P1_JOB_03_OK cell=${cell} item_ceiling=2 item_denial=-10 call_ceiling=2 call_denial=-11 token_denial=-12 cost_denial=-13 time_denial=-14 per_call_cap_denial=-15 inflight_denial=-16 calls_actual=2 tokens_reserved=0 tokens_actual=130 cost_reserved=0 cost_actual=26 time_reserved_ms=0 time_actual_ms=650 max_inflight_calls=1 max_inflight_tokens=100 max_inflight_cost=20 max_inflight_time_ms=500 denied_writes=0")
            message(FATAL_ERROR "${cell} failed (${vm_result}):\n${vm_out}\n${vm_err}")
        endif()
        file(APPEND "${report}" "${cell}:\n${vm_out}${vm_err}\n")
    endforeach()
endforeach()
message(STATUS "P1-JOB-03 passed hard ceilings, reservations, and actual-usage settlement on rxvme/rxbvm")
