foreach(required_var CPRAG_ROOT CPRAG_HASHES CPRAG_THRESHOLDS CPRAG_PROTOCOL CPRAG_NATIVE_RESULTS CPRAG_RXVME_RESULTS CPRAG_RXBVM_RESULTS)
    if(NOT DEFINED ${required_var})
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()

file(STRINGS "${CPRAG_HASHES}" hash_lines)
list(POP_FRONT hash_lines hash_header)
list(LENGTH hash_lines hash_count)
if(NOT hash_count EQUAL 19)
    message(FATAL_ERROR "Expected 19 frozen artifact hashes, found ${hash_count}")
endif()
foreach(line IN LISTS hash_lines)
    string(REPLACE "\t" ";" fields "${line}")
    list(LENGTH fields field_count)
    if(NOT field_count EQUAL 2)
        message(FATAL_ERROR "Malformed hash row: ${line}")
    endif()
    list(GET fields 0 expected)
    list(GET fields 1 relative_path)
    set(path "${CPRAG_ROOT}/${relative_path}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Frozen artifact is missing: ${relative_path}")
    endif()
    file(SHA256 "${path}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Frozen artifact hash mismatch: ${relative_path}\nexpected ${expected}\nactual   ${actual}")
    endif()
endforeach()

file(READ "${CPRAG_THRESHOLDS}" thresholds)
string(JSON schema ERROR_VARIABLE threshold_error GET "${thresholds}" schema)
string(JSON case_min GET "${thresholds}" quality case_min_points)
string(JSON suite_min GET "${thresholds}" quality suite_min_fraction)
string(JSON packet_max GET "${thresholds}" context evidence_packet_max_bytes)
string(JSON provider_max GET "${thresholds}" latency_us loopback_provider_wait_25ms_max_each_vm)
string(JSON vm_memory_max GET "${thresholds}" memory_bytes crexx_vm_process_peak_max_each)
if(threshold_error OR NOT schema STREQUAL "crexx-rag-gate0-thresholds-v1"
        OR case_min LESS 1 OR suite_min LESS 0.5 OR packet_max LESS 1024
        OR provider_max LESS 25000 OR vm_memory_max LESS 1048576)
    message(FATAL_ERROR "Gate-0 threshold manifest is invalid")
endif()

file(READ "${CPRAG_PROTOCOL}" protocol)
foreach(required "opaque labels" "does not receive the rubric" "13/16" "85%" "90%" "third blinded" "Reveal implementation labels only after")
    if(NOT protocol MATCHES "${required}")
        message(FATAL_ERROR "Answer-evaluation protocol omitted: ${required}")
    endif()
endforeach()

foreach(result_file "${CPRAG_NATIVE_RESULTS}" "${CPRAG_RXVME_RESULTS}" "${CPRAG_RXBVM_RESULTS}")
    file(READ "${result_file}" results)
    if(results MATCHES ",error" OR NOT results MATCHES ",ok")
        message(FATAL_ERROR "Raw benchmark result is not successful: ${result_file}\n${results}")
    endif()
endforeach()

message(STATUS "Gate-0 protocol valid: hashes=19; quality=13/16 and 85%; packet<=65536; benchmark rows successful")
