foreach(required_var CPRAG_SCOTLAND CPRAG_IT_QUESTIONS CPRAG_IT_JUDGEMENTS CPRAG_RUBRIC CPRAG_PASSAGE_MAP)
    if(NOT DEFINED ${required_var})
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()

foreach(required_file "${CPRAG_SCOTLAND}" "${CPRAG_IT_QUESTIONS}" "${CPRAG_IT_JUDGEMENTS}" "${CPRAG_RUBRIC}" "${CPRAG_PASSAGE_MAP}")
    if(NOT EXISTS "${required_file}")
        message(FATAL_ERROR "Required judgement file is missing: ${required_file}")
    endif()
endforeach()

file(STRINGS "${CPRAG_SCOTLAND}" scotland_lines)
list(LENGTH scotland_lines scotland_count)
if(NOT scotland_count EQUAL 5)
    message(FATAL_ERROR "Expected 5 Scotland-shaped judgement cases, found ${scotland_count}")
endif()

set(scotland_ids "")
foreach(line IN LISTS scotland_lines)
    string(JSON case_id ERROR_VARIABLE json_error GET "${line}" case_id)
    if(json_error)
        message(FATAL_ERROR "Invalid Scotland judgement JSON: ${json_error}\n${line}")
    endif()
    string(JSON question GET "${line}" question)
    string(JSON judgement_count LENGTH "${line}" judgements)
    string(JSON graph_rule GET "${line}" graph_rule)
    string(JSON required_gap GET "${line}" required_gap)
    if(question STREQUAL "" OR graph_rule STREQUAL "" OR required_gap STREQUAL "" OR judgement_count LESS 3)
        message(FATAL_ERROR "Incomplete Scotland judgement case: ${case_id}")
    endif()
    list(APPEND scotland_ids "${case_id}")
endforeach()

file(STRINGS "${CPRAG_IT_QUESTIONS}" question_lines)
file(STRINGS "${CPRAG_IT_JUDGEMENTS}" judgement_lines)
list(LENGTH question_lines question_count)
list(LENGTH judgement_lines judgement_count)
if(NOT question_count EQUAL 4 OR NOT judgement_count EQUAL 4)
    message(FATAL_ERROR "Expected 4 held-out questions and 4 held-out answer judgements")
endif()

set(question_ids "")
foreach(line IN LISTS question_lines)
    string(JSON case_id ERROR_VARIABLE json_error GET "${line}" case_id)
    string(JSON question GET "${line}" question)
    if(json_error OR question STREQUAL "")
        message(FATAL_ERROR "Invalid held-out question JSON: ${line}")
    endif()
    list(APPEND question_ids "${case_id}")
endforeach()

set(judgement_ids "")
foreach(line IN LISTS judgement_lines)
    string(JSON case_id ERROR_VARIABLE json_error GET "${line}" case_id)
    string(JSON item_count LENGTH "${line}" judgements)
    string(JSON graph_rule GET "${line}" graph_rule)
    string(JSON required_gap GET "${line}" required_gap)
    if(json_error OR graph_rule STREQUAL "" OR required_gap STREQUAL "" OR item_count LESS 2)
        message(FATAL_ERROR "Invalid held-out judgement JSON: ${line}")
    endif()
    list(APPEND judgement_ids "${case_id}")
endforeach()
if(NOT question_ids STREQUAL judgement_ids)
    message(FATAL_ERROR "Blinded question ids do not match answer-key ids: ${question_ids} versus ${judgement_ids}")
endif()

file(STRINGS "${CPRAG_PASSAGE_MAP}" passage_lines)
list(LENGTH passage_lines passage_line_count)
if(NOT passage_line_count EQUAL 15)
    message(FATAL_ERROR "Expected header plus 14 passage mappings, found ${passage_line_count}")
endif()

message(STATUS "Phase-0 judgements valid: Scotland=${scotland_count}; held-out=${judgement_count}; passage-mappings=14")
