foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_FIXTURE CPRAG_LOCK_FIXTURE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}" "${CPRAG_WORK_DIR}/replacement")
set(policy "${CPRAG_WORK_DIR}/crexxrag.conf")
file(READ "${CPRAG_CONFIG_FIXTURE}" original)
string(PREPEND original "# Preserve this operator comment.\n")
file(WRITE "${policy}" "${original}")
set(base "${CPRAG_NATIVE_APPLICATION}" --config-file "${policy}" --profile it-architecture-profile
    --library "${CPRAG_WORK_DIR}/library" --format json)
function(cli expected)
    execute_process(COMMAND ${base} ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    if(NOT result EQUAL expected)
        message(FATAL_ERROR "Policy command failed (${ARGN}): ${result} ${out}${err}")
    endif()
    string(JSON code ERROR_VARIABLE failure GET "${out}" exit_code)
    if(failure OR NOT code EQUAL expected)
        message(FATAL_ERROR "Policy result does not match process exit: ${out}")
    endif()
    set(response "${out}" PARENT_SCOPE)
endfunction()
function(unchanged expected)
    file(SHA256 "${policy}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Refused policy edit changed original bytes")
    endif()
endfunction()
# Confirm the existing parser/identity control before the new interface test.
cli(0 config check)
file(SHA256 "${policy}" initial)
cli(0 config show)
string(JSON shown GET "${response}" records 0 fields sha256)
string(JSON valid GET "${response}" records 0 fields valid)
if(NOT shown STREQUAL initial OR NOT valid OR EXISTS "${CPRAG_WORK_DIR}/library" OR EXISTS "${policy}.edit-lock.sqlite")
    message(FATAL_ERROR "Policy inspection lost identity or created mutable state: ${response}")
endif()
cli(0 --access admin library init)
find_program(CREXXRAG_SQLITE3 sqlite3 REQUIRED)
execute_process(COMMAND "${CREXXRAG_SQLITE3}" -readonly "${CPRAG_WORK_DIR}/library/library.sqlite" .dump OUTPUT_VARIABLE database_before)
cli(4 config set --key worker.max_restarts --value 1 --expect-sha256 "${initial}")
unchanged("${initial}")
cli(2 --access admin config set --key worker.max_restarts --value 1 --expect-sha256 bad)
cli(2 --access admin config set --key worker.max_restarts --value 1)
cli(2 config show --unexpected x)
cli(2 --access admin config set extra --key worker.max_restarts --value 1 --expect-sha256 "${initial}")
cli(2 --access admin config set --key worker.max_restarts --value 1 --value 2 --expect-sha256 "${initial}")
cli(3 --access admin config set --key worker.max_restarts --value 11 --expect-sha256 "${initial}")
cli(3 --access admin config set --key unknown.rule --value x --expect-sha256 "${initial}")
cli(3 --access admin config set --key profiles --value missing-profile --expect-sha256 "${initial}")
cli(2 --access admin config set --key role.answerer.system_prompt --value "first\nconfig.id = injected" --expect-sha256 "${initial}")
cli(3 --access admin config set --key provider.gemini-generate.credential --value literal-policy-secret --expect-sha256 "${initial}")
if(response MATCHES "literal-policy-secret")
    message(FATAL_ERROR "Rejected credential value leaked in policy error")
endif()
unchanged("${initial}")
string(REPEAT 0 64 stale)
cli(6 --access admin config set --key worker.max_restarts --value 1 --expect-sha256 "${stale}")
unchanged("${initial}")
cli(0 --access admin config set --key role.answerer.system_prompt --value "Operator answer objective." --expect-sha256 "${initial}")
file(SHA256 "${policy}" current)
string(JSON returned GET "${response}" records 0 fields sha256)
if(NOT returned STREQUAL current OR current STREQUAL initial)
    message(FATAL_ERROR "Updated policy hash was not returned")
endif()
cli(0 config prompt --role answerer)
string(JSON prompt GET "${response}" records 0 fields configured_objective)
if(NOT prompt STREQUAL "Operator answer objective.")
    message(FATAL_ERROR "Updated objective was not loaded: ${response}")
endif()
file(READ "${policy}" updated)
if(NOT updated MATCHES "# Preserve this operator comment." OR NOT updated MATCHES "worker.processes = 1")
    message(FATAL_ERROR "Single-key edit changed unrelated policy lines")
endif()
# A no-op has an exact byte identity and does not invalidate another review.
cli(0 --access admin config set --key role.answerer.system_prompt --value "Operator answer objective." --expect-sha256 "${current}")
unchanged("${current}")
string(JSON changed GET "${response}" records 0 fields changed)
if(changed)
    message(FATAL_ERROR "Identical edit was reported as a change")
endif()
file(WRITE "${CPRAG_WORK_DIR}/answer.txt" "Destination-relative prompt.\nSecond line.")
file(WRITE "${CPRAG_WORK_DIR}/replacement/answer.txt" "WRONG_INPUT_DIRECTORY")
cli(0 --access admin config set --key role.answerer.system_prompt_file --value ./answer.txt --expect-sha256 "${current}")
file(SHA256 "${policy}" current)
file(READ "${policy}" prompt_file_policy)
if(prompt_file_policy MATCHES "\nrole.answerer.system_prompt =")
    message(FATAL_ERROR "Prompt-file edit retained the competing inline prompt")
endif()
cli(0 config prompt --role answerer)
string(JSON prompt GET "${response}" records 0 fields configured_objective)
if(NOT prompt STREQUAL "Destination-relative prompt.\nSecond line.")
    message(FATAL_ERROR "Relative prompt file was not loaded")
endif()
file(WRITE "${CPRAG_WORK_DIR}/replacement/policy.conf" "${prompt_file_policy}")
file(WRITE "${CPRAG_WORK_DIR}/replacement/invalid.conf" "format = broken\n")
cli(3 --access admin config replace --input "${CPRAG_WORK_DIR}/replacement/invalid.conf" --expect-sha256 "${current}")
cli(3 --access admin config set --key role.answerer.system_prompt_file --value ./missing-prompt.txt --expect-sha256 "${current}")
unchanged("${current}")
# Invalid current policy remains addressable and repairable.
file(WRITE "${policy}" "format = broken\n")
file(SHA256 "${policy}" broken)
cli(0 config show)
string(JSON valid GET "${response}" records 0 fields valid)
string(JSON actual GET "${response}" records 0 fields sha256)
if(valid OR NOT actual STREQUAL broken)
    message(FATAL_ERROR "Invalid policy inspection did not expose its exact repair hash")
endif()
cli(3 --access admin config set --key config.id --value repaired --expect-sha256 "${broken}")
unchanged("${broken}")
cli(0 --access admin config replace --input "${CPRAG_WORK_DIR}/replacement/policy.conf" --expect-sha256 "${broken}")
cli(0 config prompt --role answerer)
string(JSON prompt GET "${response}" records 0 fields configured_objective)
if(NOT prompt STREQUAL "Destination-relative prompt.\nSecond line.")
    message(FATAL_ERROR "Replacement resolved paths against the input directory")
endif()
file(SHA256 "${policy}" current)
# The inverse prompt switch is one edit too.
cli(0 --access admin config set --key role.answerer.system_prompt --value "Inline again." --expect-sha256 "${current}")
file(READ "${policy}" updated)
if(updated MATCHES "role.answerer.system_prompt_file =")
    message(FATAL_ERROR "Inline edit retained the competing prompt-file setting")
endif()
file(SHA256 "${policy}" current)
# One MCP process must observe its own edit on the next call.
file(WRITE "${CPRAG_WORK_DIR}/requests.jsonl"
    "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_config_set\",\"arguments\":{\"key\":\"role.answerer.system_prompt\",\"value\":\"MCP updated objective.\",\"expect_sha256\":\"${current}\"}}}\n"
    "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_config_prompt\",\"arguments\":{\"role\":\"answerer\"}}}\n")
execute_process(COMMAND ${base} --access admin serve mcp INPUT_FILE "${CPRAG_WORK_DIR}/requests.jsonl"
    OUTPUT_FILE "${CPRAG_WORK_DIR}/responses.jsonl" RESULT_VARIABLE result ERROR_VARIABLE err TIMEOUT 30)
file(STRINGS "${CPRAG_WORK_DIR}/responses.jsonl" responses)
list(LENGTH responses count)
if(NOT result EQUAL 0 OR NOT count EQUAL 2)
    message(FATAL_ERROR "Policy-edit MCP session failed: ${err}")
endif()
list(GET responses 0 first)
list(GET responses 1 second)
string(JSON code GET "${first}" result structuredContent exit_code)
string(JSON prompt GET "${second}" result structuredContent records 0 fields configured_objective)
if(NOT code EQUAL 0 OR NOT prompt STREQUAL "MCP updated objective.")
    message(FATAL_ERROR "MCP retained stale policy after edit: ${responses}")
endif()
file(SHA256 "${policy}" current)
# Replacing policy may remove the session's profile; it must not retain a stale registry.
file(READ "${policy}" active_text)
string(REPLACE "profiles = generic-profile,it-architecture-profile" "profiles = generic-profile" removed_profile "${active_text}")
string(REPLACE "config.id = google-gemini" "config.id = replacement-policy" removed_profile "${removed_profile}")
file(WRITE "${CPRAG_WORK_DIR}/replacement/profile-change.conf" "${removed_profile}")
file(WRITE "${CPRAG_WORK_DIR}/requests.jsonl"
    "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_config_replace\",\"arguments\":{\"input\":\"${CPRAG_WORK_DIR}/replacement/profile-change.conf\",\"expect_sha256\":\"${current}\"}}}\n"
    "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_config_check\",\"arguments\":{}}}\n"
    "{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_config_show\",\"arguments\":{}}}\n")
execute_process(COMMAND ${base} --access admin serve mcp INPUT_FILE "${CPRAG_WORK_DIR}/requests.jsonl"
    OUTPUT_FILE "${CPRAG_WORK_DIR}/responses.jsonl" RESULT_VARIABLE result ERROR_VARIABLE err TIMEOUT 30)
file(STRINGS "${CPRAG_WORK_DIR}/responses.jsonl" responses)
list(GET responses 0 first)
list(GET responses 1 second)
list(GET responses 2 third)
string(JSON code GET "${first}" result structuredContent exit_code)
string(JSON absent_profile GET "${second}" result structuredContent exit_code)
string(JSON identity GET "${third}" result structuredContent records 0 fields config_id)
if(NOT result EQUAL 0 OR NOT code EQUAL 0 OR NOT absent_profile EQUAL 5 OR NOT identity STREQUAL "replacement-policy")
    message(FATAL_ERROR "MCP reused a stale registry/profile: ${responses}${err}")
endif()
# A new server can also start with a broken file and expose its repair commands.
file(WRITE "${policy}" "format = broken\n")
file(SHA256 "${policy}" broken)
file(WRITE "${CPRAG_WORK_DIR}/requests.jsonl"
    "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_config_show\",\"arguments\":{}}}\n"
    "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_config_replace\",\"arguments\":{\"input\":\"${CPRAG_WORK_DIR}/replacement/policy.conf\",\"expect_sha256\":\"${broken}\"}}}\n"
    "{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_config_prompt\",\"arguments\":{\"role\":\"answerer\"}}}\n")
execute_process(COMMAND ${base} --access admin serve mcp INPUT_FILE "${CPRAG_WORK_DIR}/requests.jsonl"
    OUTPUT_FILE "${CPRAG_WORK_DIR}/responses.jsonl" RESULT_VARIABLE result ERROR_VARIABLE err TIMEOUT 30)
file(STRINGS "${CPRAG_WORK_DIR}/responses.jsonl" responses)
list(LENGTH responses count)
if(NOT result EQUAL 0 OR NOT count EQUAL 3)
    message(FATAL_ERROR "MCP cannot start to repair invalid policy: ${responses}${err}")
endif()
list(GET responses 0 first)
list(GET responses 1 second)
list(GET responses 2 third)
string(JSON valid GET "${first}" result structuredContent records 0 fields valid)
string(JSON code GET "${second}" result structuredContent exit_code)
string(JSON prompt GET "${third}" result structuredContent records 0 fields configured_objective)
if(valid OR NOT code EQUAL 0 OR NOT prompt STREQUAL "Destination-relative prompt.\nSecond line.")
    message(FATAL_ERROR "MCP did not repair and reload the selected policy: ${responses}")
endif()
file(SHA256 "${policy}" current)
# Hold a real cross-process SQLite lock, prove refusal, kill its owner, then retry.
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    "TEST_SQLITE=${CREXXRAG_SQLITE3}" "TEST_LOCK=${policy}.edit-lock.sqlite"
    "TEST_FIFO=${CPRAG_WORK_DIR}/lock.fifo" "TEST_READY=${CPRAG_WORK_DIR}/lock.ready"
    "TEST_NATIVE=${CPRAG_NATIVE_APPLICATION}" "TEST_POLICY=${policy}" "TEST_HASH=${current}"
    "TEST_BUSY=${CPRAG_WORK_DIR}/busy.json" /bin/sh "${CPRAG_LOCK_FIXTURE}"
    RESULT_VARIABLE lock_result OUTPUT_VARIABLE lock_out ERROR_VARIABLE lock_err TIMEOUT 30)
if(NOT lock_result EQUAL 0)
    message(FATAL_ERROR "Policy lock/crash fixture failed: ${lock_out}${lock_err}")
endif()
unchanged("${current}")
file(WRITE "${policy}.edit-orphan.tmp" "unpublished orphan bytes")
cli(0 --access admin config set --key worker.max_restarts --value 1 --expect-sha256 "${current}")
file(SHA256 "${policy}" current)
# A literal true is a setting value, not a bare enabling flag.
cli(0 --access admin config set --key role.answerer.system_prompt --value true --expect-sha256 "${current}")
cli(0 config prompt --role answerer)
string(JSON literal_true GET "${response}" records 0 fields configured_objective)
if(NOT literal_true STREQUAL "true")
    message(FATAL_ERROR "Literal true setting was not preserved")
endif()
file(SHA256 "${policy}" current)
# Explicit resolution objective remains editable under the same policy owner.
cli(0 --access admin config set --key maintenance.resolution_prompt --value "Resolve only the supplied task evidence." --expect-sha256 "${current}")
cli(0 config prompt --role resolution)
string(JSON prompt GET "${response}" records 0 fields configured_objective)
if(NOT prompt STREQUAL "Resolve only the supplied task evidence.")
    message(FATAL_ERROR "Resolution objective did not follow the policy edit")
endif()
execute_process(COMMAND "${CREXXRAG_SQLITE3}" -readonly "${CPRAG_WORK_DIR}/library/library.sqlite" .dump OUTPUT_VARIABLE database_after)
if(NOT database_before STREQUAL database_after)
    message(FATAL_ERROR "Policy-file edits changed library jobs, configuration history or provider usage")
endif()
# Bootstrap selection creates one policy entry point, with no library required.
set(bootstrap "${CPRAG_WORK_DIR}/replacement/new.conf")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --config-file "${bootstrap}" --format json config show
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
string(JSON exists GET "${out}" records 0 fields exists)
if(NOT result EQUAL 0 OR exists)
    message(FATAL_ERROR "Missing policy cannot be inspected for bootstrap: ${out}${err}")
endif()
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --config-file "${bootstrap}" --access admin --format json
    config replace --input "${CPRAG_CONFIG_FIXTURE}" --expect-sha256 missing RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result EQUAL 0 OR NOT EXISTS "${bootstrap}")
    message(FATAL_ERROR "Policy bootstrap failed: ${out}${err}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env "CREXXRAG_CONFIG="
    "${CPRAG_NATIVE_APPLICATION}" --format json config show
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
string(JSON selected GET "${out}" records 0 fields path)
if(NOT result EQUAL 0 OR NOT selected STREQUAL policy)
    message(FATAL_ERROR "Local default did not select the single policy file: ${out}${err}")
endif()
# A publication I/O failure cannot invent the missing parent or publish bytes.
set(unavailable "${CPRAG_WORK_DIR}/absent-parent/crexxrag.conf")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --config-file "${unavailable}" --format json --access admin
    config replace --input "${CPRAG_CONFIG_FIXTURE}" --expect-sha256 missing
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
string(JSON failure_code GET "${out}" exit_code)
if(NOT result EQUAL 1 OR NOT failure_code EQUAL 1 OR EXISTS "${unavailable}" OR EXISTS "${CPRAG_WORK_DIR}/absent-parent")
    message(FATAL_ERROR "Failed policy publication changed the destination: ${out}${err}")
endif()
message(STATUS "Policy file edits preserve validation, optimistic concurrency, prompt ownership, MCP freshness and library history; killed lock owner does not block retry")
