set(contract_work "${CPRAG_WORK_DIR}")
file(REMOVE_RECURSE "${contract_work}")
file(MAKE_DIRECTORY "${contract_work}/requests")
set(ENV{CREXXRAG_FIXTURE_CAPTURE_DIR} "${contract_work}/requests")
set(CPRAG_WORK_DIR "${contract_work}/ingestion")
set(CPRAG_CONFIG_TEMPLATE "${CPRAG_INGESTION_TEMPLATE}")
include("${CMAKE_CURRENT_LIST_DIR}/GeminiIngestion.cmake")
set(CPRAG_WORK_DIR "${contract_work}/query")
set(CPRAG_CONFIG_TEMPLATE "${CPRAG_QUERY_TEMPLATE}")
include("${CMAKE_CURRENT_LIST_DIR}/GeminiQuery.cmake")
set(CPRAG_WORK_DIR "${contract_work}/resolution")
set(CPRAG_CONFIG_TEMPLATE "${CPRAG_INGESTION_TEMPLATE}")
set(CPRAG_CASES valid correction)
include("${CMAKE_CURRENT_LIST_DIR}/DurableBacklogProvider.cmake")
unset(ENV{CREXXRAG_FIXTURE_CAPTURE_DIR})

file(GLOB requests "${contract_work}/requests/*.json")
set(contracts)
set(corrections 0)
foreach(path IN LISTS requests)
    file(READ "${path}" request)
    string(JSON schema ERROR_VARIABLE missing GET "${request}" generationConfig responseJsonSchema)
    if(missing)
        continue()
    endif()
    string(JSON system GET "${request}" systemInstruction parts 0 text)
    string(SHA256 system_hash "${system}")
    string(SHA256 schema_hash "${schema}")
    list(APPEND contracts "${system_hash} ${schema_hash}")
    string(JSON count LENGTH "${request}" contents)
    if(count GREATER 1)
        math(EXPR last "${count} - 1")
        string(JSON feedback GET "${request}" contents ${last} parts 0 text)
        if(feedback MATCHES "^Citation correction ")
            if(NOT count EQUAL 3 OR NOT feedback MATCHES "Check every citation against the original input")
                message(FATAL_ERROR "Correction message history changed")
            endif()
            string(JSON previous_role GET "${request}" contents 1 role)
            if(NOT previous_role STREQUAL "model")
                message(FATAL_ERROR "Correction lost the previous response")
            endif()
            math(EXPR corrections "${corrections}+1")
        endif()
    endif()
endforeach()
list(REMOVE_DUPLICATES contracts)
list(SORT contracts)
list(JOIN contracts "\n" observed)
file(WRITE "${contract_work}/observed-contracts.txt" "${observed}\n")
if(corrections LESS 1)
    message(FATAL_ERROR "No real correction request was observed")
endif()
file(READ "${CPRAG_EXPECTED_CONTRACTS}" expected)
if(NOT "${observed}\n" STREQUAL expected)
    message(FATAL_ERROR "Effective system prompts or response schemas changed; inspect ${contract_work}/observed-contracts.txt")
endif()
message(STATUS "Effective extraction, resolution, answer/report prompts and schemas match the captured baseline; correction history preserved")
