file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
set(cli "${CPRAG_NATIVE_APPLICATION}" --config-file "${CPRAG_CONFIG_FIXTURE}"
    --profile it-architecture-profile --access read --format json)
execute_process(COMMAND ${cli} config check RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Positive configuration control failed: ${out}${err}")
endif()
foreach(role IN ITEMS extractor resolution answerer advisory)
    execute_process(COMMAND ${cli} config prompt --role "${role}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Effective prompt inspection failed for ${role}: ${out}${err}")
    endif()
    string(JSON system GET "${out}" records 0 fields system_prompt)
    string(JSON schema GET "${out}" records 0 fields response_schema)
    string(JSON digest GET "${out}" records 0 fields system_prompt_sha256)
    string(SHA256 expected "${system}")
    string(JSON schema_type GET "${schema}" type)
    if(NOT expected STREQUAL digest OR NOT schema_type STREQUAL "object")
        message(FATAL_ERROR "Prompt text, digest and schema disagree")
    endif()
    if(role STREQUAL "extractor" AND NOT system MATCHES "Source quotation rules:")
        message(FATAL_ERROR "Inspection exposes only the configurable objective")
    endif()
endforeach()
execute_process(COMMAND ${cli} config prompt --role unknown
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result EQUAL 2)
    message(FATAL_ERROR "Unknown prompt role did not return usage")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/ProjectContract.cmake")
