# REG-01: public contract tests; every library is disposable and no worker runs.
foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR CPRAG_CASE)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(sqlite_cli sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
set(CPRAG_FIXTURE_PORT 9)
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
configure_file("${CPRAG_CONFIG_TEMPLATE}" "${CPRAG_WORK_DIR}/crexxrag.conf" @ONLY)
if(CPRAG_CASE MATCHES "^retrieval")
    file(READ "${CPRAG_WORK_DIR}/crexxrag.conf" config)
    string(REPLACE "budget.item_limit = 2" "budget.item_limit = 20" config "${config}")
    string(REPLACE "budget.model_calls = 2" "budget.model_calls = 20" config "${config}")
    file(WRITE "${CPRAG_WORK_DIR}/crexxrag.conf" "${config}")
endif()
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
set(cli "${CMAKE_COMMAND}" -E env --unset=CPRAG_FIXTURE_GEMINI_KEY
    "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}" "NO_COLOR=1"
    "${CPRAG_NATIVE_APPLICATION}" --progress plain)
file(SHA256 "${CPRAG_NATIVE_APPLICATION}" artifact_hash)
file(WRITE "${CPRAG_WORK_DIR}/artifact.txt" "native_sha256=${artifact_hash}\ncase=${CPRAG_CASE}\n")

function(sql query expected)
    execute_process(COMMAND "${sqlite_cli}" -cmd ".timeout 5000" "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors
        OUTPUT_STRIP_TRAILING_WHITESPACE TIMEOUT 20)
    if(NOT status EQUAL 0 OR NOT output STREQUAL "${expected}")
        message(FATAL_ERROR "SQL fixture/assertion failed: ${query}\nExpected ${expected}; got ${output}\n${errors}")
    endif()
endfunction()

function(call_cli format)
    execute_process(COMMAND ${cli} --format "${format}" ${ARGN}
        WORKING_DIRECTORY "${CPRAG_WORK_DIR}" RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "CLI ${format} ${ARGN}\nexit=${status}\n${output}${errors}\n")
    set(last_status "${status}" PARENT_SCOPE)
    set(last_output "${output}" PARENT_SCOPE)
    set(last_error "${errors}" PARENT_SCOPE)
endfunction()

function(call_mcp tool arguments access)
    string(REPLACE "\n" "" arguments "${arguments}")
    file(WRITE "${CPRAG_WORK_DIR}/request.jsonl"
        "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{}}\n"
        "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"${tool}\",\"arguments\":${arguments}}}\n")
    execute_process(COMMAND ${cli} --access "${access}" serve mcp
        WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/request.jsonl"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "MCP ${tool} ${arguments}\nexit=${status}\n${output}${errors}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "MCP process failed: ${status}\n${output}${errors}")
    endif()
    # Parse each response by ID, rather than accepting a success from another call.
    file(WRITE "${CPRAG_WORK_DIR}/response.jsonl" "${output}")
    file(STRINGS "${CPRAG_WORK_DIR}/response.jsonl" responses ENCODING UTF-8)
    set(found 0)
    foreach(response IN LISTS responses)
        string(JSON id GET "${response}" id)
        if(id EQUAL 2)
            math(EXPR found "${found}+1")
            string(JSON result ERROR_VARIABLE parse_error GET "${response}" result structuredContent)
            if(parse_error)
                string(JSON status GET "${response}" error code)
                string(JSON errors GET "${response}" error message)
                set(result "")
            else()
                string(JSON status GET "${result}" exit_code)
            endif()
        endif()
    endforeach()
    if(NOT found EQUAL 1)
        message(FATAL_ERROR "MCP did not return exactly one response for ID 2")
    endif()
    set(last_status "${status}" PARENT_SCOPE)
    set(last_output "${result}" PARENT_SCOPE)
    set(last_error "${errors}" PARENT_SCOPE)
endfunction()

macro(require_status expected)
    if(NOT "${last_status}" STREQUAL "${expected}")
        message(FATAL_ERROR "Expected exit ${expected}, got ${last_status}: ${last_output}${last_error}")
    endif()
endmacro()

macro(require_json expected)
    string(JSON actual GET "${last_output}" ${ARGN})
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "${ARGN}: expected ${expected}, got ${actual}")
    endif()
endmacro()

# These are ordinary failing assertions, never WILL_FAIL or a skipped test.
# Recognize a known diagnosis only after the positive control has succeeded.
macro(expect_repaired issue known_message)
    if(NOT "${last_status}" STREQUAL "0")
        if(NOT "${last_output}${last_error}" MATCHES "${known_message}")
            message(FATAL_ERROR "Unexpected failure in ${issue}: ${last_status}: ${last_output}${last_error}")
        endif()
        list(APPEND defects "${issue}: ${surface}: ${known_message}")
    endif()
endmacro()

call_cli(json --access admin library init)
require_status(0)
set(defects)

if(CPRAG_CASE MATCHES "^page")
    # Ordered identities allow an independent complete-set check at every page size.
    sql("WITH RECURSIVE n(i) AS (VALUES(0) UNION ALL SELECT i+1 FROM n WHERE i<100) INSERT INTO reviews(review_id,review_type,subject_id,state,proposal_json,created_at) SELECT printf('review-%03d',i),'maintenance-external',printf('subject-%03d',i),'pending','{}','fixture' FROM n;" "")
    foreach(surface IN ITEMS json ndjson human mcp)
        if(surface STREQUAL "mcp")
            call_mcp(rag_review_list "{\"limit\":99}" read,plan)
        else()
            call_cli("${surface}" --access read review list --limit 99)
        endif()
        require_status(0)
        if(surface STREQUAL "json" OR surface STREQUAL "mcp")
            require_json(review-000 records 0 fields identity)
            require_json(review-098 records 98 fields identity)
            require_json(review-098 records 99 fields next_cursor)
        elseif(NOT last_output MATCHES "review-098" OR NOT last_output MATCHES "review-000")
            message(FATAL_ERROR "${surface} positive control omitted boundary identities")
        endif()
        if(CPRAG_CASE STREQUAL "page_max")
            if(surface STREQUAL "mcp")
                call_mcp(rag_review_list "{\"limit\":100}" read,plan)
            else()
                call_cli("${surface}" --access read review list --limit 100)
            endif()
            expect_repaired(RAG-UX-02 "result exceeds the 100-record rendering bound")
            if(last_status EQUAL 0)
                if(surface STREQUAL "json" OR surface STREQUAL "mcp")
                    require_json(review-099 records 99 fields identity)
                    require_json(review-099 records 100 fields next_cursor)
                elseif(NOT last_output MATCHES "review-099")
                    message(FATAL_ERROR "${surface}: successful maximum page omitted its last row")
                endif()
            endif()
        endif()
    endforeach()
    if(CPRAG_CASE STREQUAL "pages")
        foreach(limit IN ITEMS 1 20 99 100)
            set(cursor "")
            set(seen 0)
            foreach(page RANGE 0 101)
                set(cursor_option)
                if(NOT cursor STREQUAL "")
                    set(cursor_option --cursor "${cursor}")
                endif()
                call_cli(json --access read review list --limit "${limit}" ${cursor_option})
                require_status(0)
                string(JSON count LENGTH "${last_output}" records)
                set(cursor "")
                if(count GREATER 0)
                    math(EXPR end "${count}-1")
                    foreach(row RANGE 0 ${end})
                        string(JSON kind GET "${last_output}" records ${row} kind)
                        if(kind STREQUAL "page")
                            string(JSON cursor GET "${last_output}" records ${row} fields next_cursor)
                        else()
                            string(JSON identity GET "${last_output}" records ${row} fields identity)
                            string(REGEX REPLACE "^review-0*" "" ordinal "${identity}")
                            if(ordinal STREQUAL "")
                                set(ordinal 0)
                            endif()
                            if(NOT ordinal EQUAL seen)
                                message(FATAL_ERROR "limit=${limit}: missing, repeated or unordered row ${identity}; wanted ${seen}")
                            endif()
                            math(EXPR seen "${seen}+1")
                        endif()
                    endforeach()
                endif()
                if(cursor STREQUAL "")
                    break()
                endif()
            endforeach()
            if(NOT seen EQUAL 101 OR NOT cursor STREQUAL "")
                message(FATAL_ERROR "limit=${limit}: traversal failed to terminate with all 101 reviews")
            endif()
        endforeach()
        call_cli(json --access read review list --cursor review-100 --limit 100)
        require_status(0)
        string(JSON empty_count LENGTH "${last_output}" records)
        if(NOT empty_count EQUAL 0)
            message(FATAL_ERROR "An exhausted cursor should return an empty final page")
        endif()
        foreach(limit IN ITEMS 0 101 9223372036854775808)
            call_cli(json --access read review list --limit "${limit}")
            require_status(2)
            require_json(2 exit_code)
        endforeach()
    endif()
    sql("SELECT count(*)||':'||(SELECT count(*) FROM provider_runs) FROM reviews;" "101:0")
elseif(CPRAG_CASE STREQUAL "reset_retries")
    include("${CMAKE_CURRENT_LIST_DIR}/JobRetryReset.cmake")
elseif(CPRAG_CASE STREQUAL "large_job" OR CPRAG_CASE STREQUAL "plan_detail")
    # Valid JSON, with lengths straddling the generic field bound. The plan
    # renderer has a larger bound; job.list serializes it under 'value'.
    sql("INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at) SELECT 'large-job','large-plan','{}',config_snapshot_id,'completed',1,1,128,64,0,'fixture','fixture' FROM config_snapshots LIMIT 1;" "")
    foreach(surface IN ITEMS json ndjson human mcp)
        sql("UPDATE jobs SET canonical_plan=json_object('padding',replace(hex(zeroblob(65521)),'00','x')); SELECT length(canonical_plan) FROM jobs;" "65535")
        if(surface STREQUAL "mcp")
            call_mcp(rag_job_list "{\"limit\":1}" read)
        else()
            call_cli("${surface}" --access read job list --limit 1)
        endif()
        require_status(0)
        string(LENGTH "${last_output}" list_bytes)
        if(list_bytes GREATER 8192 OR last_output MATCHES "xxxxxxxxxxxxxxxx")
            message(FATAL_ERROR "Job list contains plan body on ${surface}: ${list_bytes} bytes")
        endif()
        sql("UPDATE jobs SET canonical_plan=json_object('padding',replace(hex(zeroblob(65522)),'00','x')); SELECT length(canonical_plan) FROM jobs;" "65536")
        if(surface STREQUAL "mcp")
            call_mcp(rag_job_list "{\"limit\":1}" read)
        else()
            call_cli("${surface}" --access read job list --limit 1)
        endif()
        expect_repaired(RAG-UX-02 "string field is too long")
        if(last_status EQUAL 0 AND (surface STREQUAL "json" OR surface STREQUAL "mcp"))
            require_json(large-job records 0 fields identity)
        endif()
    endforeach()
    if(CPRAG_CASE STREQUAL "plan_detail")
        # The copied-corpus defect involved a plan larger than a megabyte.
        sql("UPDATE jobs SET canonical_plan=json_object('padding',replace(hex(zeroblob(1500000)),'00','x'));" "")
        call_cli(json --access read job list --limit 1)
        require_status(0)
        require_json(OFF records 0 fields value_complete)
        call_cli(json --access read job plan large-job --cursor 1500004 --limit 8192)
        require_status(0)
        require_json("xxxxxxxx\"}" records 0 fields text)
        require_json("" records 0 fields next_cursor)
        # Multi-byte payload exceeds both the character and byte field bounds.
        # A second small job must remain discoverable in the same page.
        sql("UPDATE jobs SET canonical_plan=json_object('padding',replace(hex(zeroblob(17000)),'00','東京é'));" "")
        execute_process(COMMAND "${sqlite_cli}" "${database}" "SELECT canonical_plan FROM jobs WHERE job_id='large-job';"
            OUTPUT_VARIABLE expected OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE status)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "Cannot read retained plan oracle")
        endif()
        string(SHA256 expected_hash "${expected}")
        sql("UPDATE jobs SET plan_digest='${expected_hash}' WHERE job_id='large-job'; INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at) SELECT 'small-job','small-plan','{}',config_snapshot_id,'completed',1,1,128,64,0,'fixture','fixture' FROM config_snapshots LIMIT 1;" "")
        execute_process(COMMAND "${sqlite_cli}" "${database}" .dump OUTPUT_VARIABLE before)
        call_cli(json --access read job list --limit 100)
        require_status(0)
        require_json(large-job records 0 fields identity)
        require_json(OFF records 0 fields value_complete)
        require_json(job.plan records 0 fields detail_operation)
        require_json("" records 0 fields value)
        require_json(small-job records 1 fields identity)
        require_json(OFF records 1 fields value_complete)
        require_json("" records 1 fields value)
        foreach(surface IN ITEMS json mcp)
            set(offset 0)
            set(assembled "")
            foreach(page RANGE 0 100)
                if(surface STREQUAL "mcp")
                    call_mcp(rag_job_plan "{\"id\":\"large-job\",\"cursor\":\"${offset}\",\"limit\":8192}" read)
                else()
                    call_cli(json --access read job plan large-job --cursor "${offset}" --limit 8192)
                endif()
                require_status(0)
                require_json("${expected_hash}" records 0 fields plan_digest)
                require_json("${offset}" records 0 fields text_offset)
                require_json(unicode-characters records 0 fields cursor_unit)
                string(JSON chunk GET "${last_output}" records 0 fields text)
                string(JSON cursor GET "${last_output}" records 0 fields next_cursor)
                string(APPEND assembled "${chunk}")
                if(cursor STREQUAL "")
                    break()
                endif()
                if(NOT cursor GREATER offset)
                    message(FATAL_ERROR "Plan cursor did not advance")
                endif()
                set(offset "${cursor}")
            endforeach()
            string(SHA256 actual_hash "${assembled}")
            if(NOT actual_hash STREQUAL expected_hash)
                message(FATAL_ERROR "${surface}: plan round trip changed, omitted or repeated text")
            endif()
        endforeach()
        foreach(surface IN ITEMS human ndjson)
            call_cli("${surface}" --access read job plan large-job --limit 7)
            require_status(0)
        endforeach()
        foreach(limit IN ITEMS 0 8193 9223372036854775808)
            call_cli(json --access read job plan large-job --limit "${limit}")
            require_status(2)
        endforeach()
        foreach(cursor IN ITEMS -1 999999999 9223372036854775808)
            call_cli(json --access read job plan large-job --cursor "${cursor}")
            require_status(2)
        endforeach()
        call_cli(json --access plan job plan missing-job)
        require_status(5)
        call_cli(json --access read job plan small-job --cursor 2)
        require_status(0)
        require_json("" records 0 fields text)
        require_json("" records 0 fields next_cursor)
        call_cli(json --access read job plan small-job --cursor 3)
        require_status(2)
        call_mcp(rag_job_plan "{\"id\":\"small-job\",\"extra\":true}" read)
        if(last_status EQUAL 0)
            message(FATAL_ERROR "MCP accepted an unknown plan argument")
        endif()
        execute_process(COMMAND "${sqlite_cli}" "${database}" .dump OUTPUT_VARIABLE after)
        if(NOT before STREQUAL after)
            message(FATAL_ERROR "Read-only plan paging changed SQLite")
        endif()
        sql("SELECT count(*) FROM provider_runs;" "0")
    endif()
elseif(CPRAG_CASE MATCHES "^retrieval")
    include("${CMAKE_CURRENT_LIST_DIR}/LexicalRegression.cmake")
elseif(CPRAG_CASE STREQUAL "retry" OR CPRAG_CASE STREQUAL "closed_retry")
    # Retained history plus five failures models the OPS-002 terminal-parent
    # shape. SQL constructs the fixture; all recovery actions use public commands.
    foreach(parent IN ITEMS eligible closed)
        sql("INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at) SELECT '${parent}','${parent}-plan','{}',config_snapshot_id,'completed_with_errors',5,10,8192,1024,1000000,'fixture','fixture' FROM config_snapshots LIMIT 1; WITH RECURSIVE n(i) AS(VALUES(1) UNION ALL SELECT i+1 FROM n WHERE i<5) INSERT INTO job_items(item_id,job_id,item_type,state,priority,fence,idempotency_key,input_hash,input_json,created_at,updated_at) SELECT '${parent}-'||i,'${parent}','embedding','dead_letter',1,3,'${parent}-key-'||i,'original-hash','{}','fixture','fixture' FROM n; INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,started_at,completed_at) SELECT item_id||'-attempt',item_id,'original-worker',3,input_hash,'quota-rejected','dead_letter','fixture','fixture' FROM job_items WHERE job_id='${parent}'; INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at) SELECT '${parent}',item_id,attempt_id,'fixture-history','preserve this diagnostic','fixture' FROM attempts WHERE item_id LIKE '${parent}-%';" "")
    endforeach()
    sql("INSERT INTO maintenance_runs(run_id,expected_generation,config_snapshot_id,mode,state,plan_digest,canonical_plan,created_at) SELECT 'closed-run',published_generation,(SELECT config_snapshot_id FROM jobs WHERE job_id='closed'),'automatic','incomplete','closed-window-plan','{}','fixture' FROM library_meta; INSERT INTO maintenance_windows(window_id,run_id,job_id,state,deadline_epoch,policy_json,policy_fingerprint,created_epoch,closed_epoch) VALUES('closed-window','closed-run','closed','complete',1,'{}','fixture-policy',0,1); INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,attempt_count,created_epoch,updated_epoch) SELECT item_id||'-task','embedding','chunk',item_id,'fixture-evidence','fixture-policy','{}','Retry missing coverage','failed',1,3,0,0 FROM job_items WHERE job_id='closed'; INSERT INTO maintenance_task_items(item_id,task_id,window_id,attempt_number) SELECT item_id,item_id||'-task','closed-window',3 FROM job_items WHERE job_id='closed'; UPDATE jobs SET state='completed' WHERE job_id='closed';" "")
    sql("INSERT INTO job_events(job_id,event_type,message,occurred_at) VALUES('eligible','budget-policy','{\"maximum_attempts\":3}','fixture');" "")
    call_cli(json --access read job retry eligible --item eligible-1 --reason regression)
    require_status(4)
    sql("SELECT count(*) FROM job_items WHERE job_id='eligible' AND state='dead_letter';" "5")
    foreach(item RANGE 1 5)
        call_cli(json --access control job retry eligible --item "eligible-${item}" --reason regression)
        require_status(0)
        require_json(1 records 0 fields items_retried)
    endforeach()
    # Repeated submission is successful and reuses one durable request.
    call_cli(json --access control job retry eligible --item eligible-1 --reason regression)
    require_status(0)
    require_json(0 records 0 fields items_retried)
    call_mcp(rag_job_retry "{\"id\":\"eligible\",\"item\":\"eligible-1\",\"reason\":\"duplicate\"}" control)
    require_status(0)
    require_json(0 records 0 fields retry_accepted)
    sql("SELECT state||':'||(SELECT count(*) FROM job_items WHERE job_id='eligible' AND state='queued')||':'||(SELECT count(*) FROM job_events WHERE job_id='eligible' AND event_type='operator-retry') FROM jobs WHERE job_id='eligible';" "queued:5:5")
    if(CPRAG_CASE STREQUAL "closed_retry")
        set(surface cli)
        call_cli(json --access control job retry closed --item closed-1 --reason regression)
        expect_repaired(RAG-OPS-002 "job is not eligible for dead-letter retry")
        if(last_status EQUAL 0)
            require_json(1 records 0 fields items_retried)
            sql("SELECT state FROM job_items WHERE item_id='closed-1';" "dead_letter")
            sql("SELECT count(*) FROM retry_requests WHERE task_id='closed-1-task' AND state='pending';" "1")
            sql("SELECT state||':'||deadline_epoch FROM maintenance_windows WHERE job_id='closed';" "complete:1")
        endif()
        call_mcp(rag_task_retry "{\"id\":\"closed-1-task\",\"reason\":\"duplicate\"}" control)
        require_status(0)
        require_json(0 records 0 fields retry_accepted)
        call_mcp(rag_task_retry "{\"id\":\"closed-1-task\"}" read)
        if(last_status EQUAL 0)
            message(FATAL_ERROR "Read-only MCP accepted a retry write")
        endif()
        # Replay has its own positive control with the same input/config and
        # different parent state. A bad replay fixture must never count as a
        # successful reproduction of the closed-parent defect.
        foreach(parent IN ITEMS replay-closed replay-eligible)
            sql("INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at) SELECT '${parent}','${parent}-plan',canonical_plan,config_snapshot_id,'completed',item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at FROM jobs WHERE job_id='closed'; INSERT INTO job_items(item_id,job_id,item_type,state,priority,idempotency_key,input_hash,input_json,created_at,updated_at) VALUES('${parent}-item','${parent}','embedding','dead_letter',1,'${parent}-key','original-hash','{}','fixture','fixture');" "")
        endforeach()
        sql("UPDATE job_items SET input_json=json_object('text','Synthetic embedding input') WHERE job_id IN('replay-closed','replay-eligible');" "")
        sql("UPDATE jobs SET state='completed_with_errors' WHERE job_id='replay-eligible';" "")
        call_cli(json --access control job replay replay-eligible --reason regression)
        require_status(0)
        require_json(1 records 0 fields items_replayed)
        sql("SELECT count(*) FROM job_replay_items WHERE source_item_id='replay-eligible-item';" "1")
        call_cli(json --access control job replay replay-closed --reason regression)
        expect_repaired(RAG-OPS-002 "source job must be terminal with explicit dead letters")
        if(last_status EQUAL 0)
            require_json(1 records 0 fields items_replayed)
            sql("SELECT count(*) FROM job_replay_items m JOIN job_items i ON i.item_id=m.replay_item_id WHERE m.source_item_id='replay-closed-item' AND i.state='queued';" "1")
        endif()
        call_cli(json --access control job replay replay-closed --reason duplicate)
        if(last_status EQUAL 0)
            message(FATAL_ERROR "Replay duplicated its active descendant")
        endif()
        sql("SELECT count(*) FROM job_replay_items WHERE source_item_id='replay-closed-item';" "1")
        call_cli(json --access control job retry replay-closed --item replay-closed-item --reason source-duplicate)
        require_status(0)
        require_json(existing-work records 0 fields retry_disposition)
        sql("UPDATE job_items SET state='processed' WHERE item_id IN(SELECT replay_item_id FROM job_replay_items WHERE source_item_id='replay-closed-item');" "")
        call_cli(json --access control job retry replay-closed --item replay-closed-item --reason covered-descendant)
        require_status(0)
        require_json(already-complete records 0 fields retry_disposition)
        call_cli(json --access control job replay replay-closed --reason covered-descendant)
        if(last_status EQUAL 0)
            message(FATAL_ERROR "Replay ignored its completed descendant")
        endif()
        sql("SELECT count(*) FROM job_replay_items WHERE source_item_id='replay-closed-item';" "1")
        sql("SELECT state FROM job_items WHERE item_id='replay-closed-item';" "dead_letter")
    endif()
    sql("SELECT count(*) FROM attempts WHERE outcome='dead_letter' AND fence=3 AND input_hash='original-hash' AND validation_state='quota-rejected';" "10")
    sql("SELECT count(*) FROM job_events WHERE event_type='fixture-history' AND message='preserve this diagnostic';" "10")
    sql("SELECT count(*) FROM provider_runs;" "0")
    sql("SELECT sum(reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns) FROM jobs;" "0")
else()
    message(FATAL_ERROR "Unknown public regression case: ${CPRAG_CASE}")
endif()

sql("PRAGMA integrity_check;" "ok")
sql("PRAGMA foreign_key_check;" "")
if(defects)
    list(JOIN defects "\n" failures)
    file(WRITE "${CPRAG_WORK_DIR}/acceptance-failures.txt" "${failures}\n")
    message(FATAL_ERROR "Acceptance remains unmet after passing positive controls:\n${failures}")
endif()
message(STATUS "PUBLIC_REGRESSION_OK case=${CPRAG_CASE} native_sha256=${artifact_hash}")
