# One operator journey: new source policy beside old work, stable stop, completion.
foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_FIXTURE CPRAG_WORK_DIR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} required")
  endif()
endforeach()
find_program(sqlite sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/new-source")
file(WRITE "${CPRAG_WORK_DIR}/new-source/document.txt" "BillingService depends on CustomerDatabase.\n")
file(READ "${CPRAG_CONFIG_FIXTURE}" config)
get_filename_component(config_path "${CPRAG_CONFIG_FIXTURE}" REALPATH)
get_filename_component(config_dir "${config_path}" DIRECTORY)
string(REPLACE "source.architecture-docs.root = ./source-docs" "source.architecture-docs.root = ${config_dir}/source-docs" config "${config}")
file(WRITE "${CPRAG_WORK_DIR}/old.conf" "${config}")
file(APPEND "${CPRAG_WORK_DIR}/new.conf" "${config}\nsource.smoke.connector = folder\nsource.smoke.root = ${CPRAG_WORK_DIR}/new-source\nsource.smoke.include = **/*.txt\nsource.smoke.stable_key = relative-path\nsource.smoke.privacy = public\nsource.smoke.retain_raw_artifact = true\n")
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
function(sql query output)
  execute_process(COMMAND "${sqlite}" -bail "${database}" "${query}" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT code EQUAL 0)
    message(FATAL_ERROR "Rule fixture SQL failed: ${err}")
  endif()
  set(${output} "${out}" PARENT_SCOPE)
endfunction()
function(run policy)
  execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --library "${CPRAG_WORK_DIR}/library" --config-file "${CPRAG_WORK_DIR}/${policy}.conf" --profile it-architecture-profile --format json ${ARGN} RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
  file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${policy}: ${ARGN}\nexit=${code}\n${out}${err}\n")
  set(last_code "${code}" PARENT_SCOPE)
  set(last_out "${out}" PARENT_SCOPE)
endfunction()
function(expect actual expected label)
  if(NOT "${actual}" STREQUAL "${expected}")
    message(SEND_ERROR "${label}: expected '${expected}', got '${actual}'")
  endif()
endfunction()
run(old --access admin library init)
if(NOT last_code EQUAL 0)
  message(FATAL_ERROR "Rule fixture init failed: ${last_out}")
endif()
sql("PRAGMA foreign_keys=ON; INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at) SELECT id,id,'{}',config_snapshot_id,state,10,0,0,0,0,'fixture','fixture' FROM (SELECT 'old' id,'completed_with_errors' state UNION ALL SELECT 'peer','queued') CROSS JOIN config_snapshots; INSERT INTO job_items(item_id,job_id,item_type,state,priority,idempotency_key,input_hash,input_json,created_at,updated_at) SELECT job_id||'-item',job_id,'embedding',CASE job_id WHEN 'peer' THEN 'queued' ELSE 'dead_letter' END,1,job_id,'input','{}','fixture','fixture' FROM jobs; INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,started_at,completed_at) VALUES('old-attempt','old-item','old-worker',1,'input','missing receipt','dead_letter','fixture','fixture'); INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at) VALUES('old','old-item','old-attempt','provider-intent','{}','fixture'); INSERT INTO maintenance_runs(run_id,expected_generation,config_snapshot_id,mode,state,plan_digest,canonical_plan,created_at) SELECT 'old',1,config_snapshot_id,'automatic','incomplete','old','{}','fixture' FROM jobs WHERE job_id='old'; INSERT INTO maintenance_windows(window_id,run_id,job_id,state,deadline_epoch,policy_json,policy_fingerprint,created_epoch,closed_epoch) VALUES('old','old','old','complete',1,'{}','policy',1,2); INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) VALUES('resolved-task','embedding-repair:fixture','chunk','fixture','input','policy','{}','fixture','resolved',1,1,1); INSERT INTO maintenance_task_items(item_id,task_id,window_id,attempt_number) VALUES('old-item','resolved-task','old',1);" ignored)
execute_process(COMMAND "${sqlite}" -readonly "${database}" "SELECT * FROM attempts; SELECT job_id,item_id,attempt_id,event_type,message,occurred_at FROM job_events WHERE item_id IS NOT NULL;" OUTPUT_VARIABLE history_before COMMAND_ERROR_IS_FATAL ANY)
run(new --access plan config plan --reason "Add a source without settling historical work")
string(JSON plan GET "${last_out}" records 0 fields canonical_plan)
string(JSON digest GET "${last_out}" records 0 fields digest)
run(old --access control job cancel old --reason "Already stopped work needs no recovery")
expect("${last_code}" 0 "stop historical work")
sql("SELECT state FROM jobs WHERE job_id='old';" stopped)
execute_process(COMMAND "${sqlite}" -readonly "${database}" .dump OUTPUT_VARIABLE stopped_dump COMMAND_ERROR_IS_FATAL ANY)
run(old --access control job cancel old --reason "Repeat stop")
execute_process(COMMAND "${sqlite}" -readonly "${database}" .dump OUTPUT_VARIABLE repeated_dump COMMAND_ERROR_IS_FATAL ANY)
if(NOT repeated_dump STREQUAL stopped_dump)
  message(SEND_ERROR "repeated stop is not a no-op")
endif()
run(old --access read job status old)
string(JSON projected GET "${last_out}" records 0 fields state)
expect("${projected}" "${stopped}" "stopped parent agrees with public state")
run(old --access diagnose job items old --state dead_letter)
if(NOT last_code EQUAL 0)
  message(FATAL_ERROR "Item diagnostic command invalid: ${last_out}")
endif()
string(JSON detail GET "${last_out}" records 0 fields detail)
string(JSON disposition GET "${detail}" recovery task_policy disposition)
string(JSON action GET "${detail}" recovery next_action)
expect("${disposition}" already-complete "completed task wins over historical uncertainty")
if(action MATCHES "job reconcile")
  message(SEND_ERROR "Completed Gemini task must not demand Codex reconciliation")
endif()
run(new --access admin config apply --plan-json "${plan}" --expect-digest "${digest}")
expect("${last_code}" 0 "source policy applies despite queued and historical work")
if(last_code EQUAL 0)
  sql("SELECT count(*) FROM jobs WHERE config_snapshot_id=(SELECT current_config_snapshot_id FROM library_config_state);" rebound)
  expect("${rebound}" 0 "old job snapshots remain unchanged")
  run(new --access plan ingest plan --source-set smoke)
  expect("${last_code}" 0 "new document can be planned")
  string(JSON ingest_plan GET "${last_out}" records 0 fields canonical_plan)
  string(JSON ingest_digest GET "${last_out}" records 0 fields digest)
  run(new --access ingest ingest apply --plan-json "${ingest_plan}" --expect-digest "${ingest_digest}")
  expect("${last_code}" 0 "new document can be imported without providers")
  sql("SELECT count(*) FROM sources; SELECT count(*) FROM job_items WHERE job_id NOT IN('old','peer');" imported)
  expect("${imported}" "1\n2" "only new document queues extraction and embedding")
endif()
execute_process(COMMAND "${sqlite}" -readonly "${database}" "SELECT * FROM attempts; SELECT job_id,item_id,attempt_id,event_type,message,occurred_at FROM job_events WHERE item_id IS NOT NULL;" OUTPUT_VARIABLE history_after COMMAND_ERROR_IS_FATAL ANY)
expect("${history_after}" "${history_before}" "original attempts and missing receipt remain history")
sql("SELECT count(*) FROM provider_runs; PRAGMA integrity_check; SELECT count(*) FROM pragma_foreign_key_check;" integrity)
expect("${integrity}" "0\nok\n0" "zero calls and intact database")
message(STATUS "RULE_SIMPLIFICATION_JOURNEY_FINISHED; failed expectations remain ordinary failures")
