# Public regressions for the two status defects found in the Scottish smoke.
# Fixtures use scratch SQLite only; failed expectations remain ordinary failures.
foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_FIXTURE CPRAG_WORK_DIR CPRAG_CASE)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
if(NOT CPRAG_CASE MATCHES "^(stale_workers|terminal_state)$")
    message(FATAL_ERROR "Unknown smoke status case")
endif()
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}")
find_program(sqlite sqlite3 REQUIRED)
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
set(base "${CPRAG_NATIVE_APPLICATION}" --library "${CPRAG_WORK_DIR}/library"
    --config-file "${CPRAG_CONFIG_FIXTURE}" --profile it-architecture-profile --format json)
execute_process(COMMAND ${base} --access admin library init RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT code EQUAL 0)
    message(FATAL_ERROR "Smoke status init failed: ${out}${err}")
endif()
function(sql query output)
    execute_process(COMMAND "${sqlite}" -bail "${database}" "${query}"
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "Smoke status seed/read failed: ${err}")
    endif()
    set(${output} "${out}" PARENT_SCOPE)
endfunction()
function(read_cli output)
    execute_process(COMMAND ${base} --access read ${ARGN}
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\n${out}${err}\n")
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "Smoke status public read failed: ${ARGN}: ${out}${err}")
    endif()
    set(${output} "${out}" PARENT_SCOPE)
endfunction()
function(read_mcp output tool arguments)
    file(WRITE "${CPRAG_WORK_DIR}/request.jsonl"
        "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"${tool}\",\"arguments\":${arguments}}}\n")
    execute_process(COMMAND ${base} --access read serve mcp INPUT_FILE "${CPRAG_WORK_DIR}/request.jsonl"
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "MCP ${tool}\n${out}${err}\n")
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "Smoke status MCP process failed: ${err}")
    endif()
    string(JSON parsed GET "${out}" result structuredContent)
    string(JSON code GET "${parsed}" exit_code)
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "Smoke status MCP read failed: ${out}")
    endif()
    set(${output} "${parsed}" PARENT_SCOPE)
endfunction()
function(record_field output response kind key)
    string(JSON count LENGTH "${response}" records)
    math(EXPR last "${count}-1")
    foreach(index RANGE 0 ${last})
        string(JSON actual_kind GET "${response}" records ${index} kind)
        if(actual_kind STREQUAL kind)
            string(JSON value GET "${response}" records ${index} fields ${key})
            set(${output} "${value}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "Missing ${kind}.${key} in public response")
endfunction()
function(expect actual expected label)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(SEND_ERROR "${label}: expected '${expected}', got '${actual}'")
    endif()
endfunction()
function(control actual expected label)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "POSITIVE_CONTROL_FAILED ${label}: ${actual}, expected ${expected}")
    endif()
endfunction()
sql("PRAGMA foreign_keys=ON; INSERT INTO jobs(job_id,plan_digest,canonical_plan,config_snapshot_id,state,item_budget,model_call_budget,input_token_budget,output_token_budget,cost_budget,created_at,updated_at) SELECT id,id,'{}',config_snapshot_id,state,10,0,0,0,0,'fixture','fixture' FROM (SELECT 'target' id,'paused' state UNION ALL SELECT 'running','running' UNION ALL SELECT 'paused','paused' UNION ALL SELECT 'unknown','paused' UNION ALL SELECT 'completed','completed') CROSS JOIN config_snapshots; INSERT INTO job_items(item_id,job_id,item_type,state,priority,idempotency_key,input_hash,input_json,created_at,updated_at) SELECT job_id||'-item',job_id,'claim-extraction',CASE job_id WHEN 'running' THEN 'queued' WHEN 'completed' THEN 'processed' ELSE 'dead_letter' END,1,job_id,'input','{}','fixture','fixture' FROM jobs;" ignored)
if(CPRAG_CASE STREQUAL "stale_workers")
    # The test runner is a known live PID; a synchronously waited shell is a
    # known exited PID. No long-lived dummy process or guessed PID is needed.
    execute_process(COMMAND /bin/sh -c "echo \"$PPID\"" OUTPUT_VARIABLE live_pid OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    execute_process(COMMAND /bin/sh -c "echo \"$$\"" OUTPUT_VARIABLE dead_pid OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    cmake_host_system_information(RESULT host QUERY HOSTNAME)
    sql("INSERT INTO runtime_instances(instance_id,kind,parent_instance_id,host_id,pid,process_start_token,executable_identity,mode,job_filter,state,started_at,heartbeat_at) VALUES('live-controller','controller',NULL,'${host}',${live_pid},'live','fixture','wait','running','running',unixepoch(),unixepoch()),('live-worker','worker','live-controller','${host}',${live_pid},'live','fixture','follow','running','idle',unixepoch(),unixepoch()),('stale-live-controller','controller',NULL,'${host}',${live_pid},'live','fixture','wait','paused','running',1,1),('stale-live-worker','worker','stale-live-controller','${host}',${live_pid},'live','fixture','follow','paused','idle',1,1),('dead-controller','controller',NULL,'${host}',${dead_pid},'dead','fixture','wait','target','failed',1,1),('stale-worker','worker','dead-controller','${host}',${dead_pid},'dead','fixture','follow','target','idle',1,1); INSERT INTO job_events(job_id,event_type,message,occurred_at) VALUES('running','worker-supervision',json_object('controller','live-controller','configured_workers',1,'max_restarts',2,'window_seconds',3600),'fixture'),('paused','worker-supervision',json_object('controller','stale-live-controller','configured_workers',1,'max_restarts',2,'window_seconds',3600),'fixture'),('target','worker-supervision',json_object('controller','dead-controller','configured_workers',1,'max_restarts',2,'window_seconds',3600),'fixture');" ignored)
    sql("INSERT INTO runtime_instances(instance_id,kind,parent_instance_id,host_id,pid,process_start_token,executable_identity,mode,job_filter,state,started_at,heartbeat_at) VALUES('remote-worker','worker',NULL,'another-host',${live_pid},'remote','fixture','follow','unknown','idle',1,1),('reserved-worker','worker',NULL,'${host}',0,'','fixture','follow','unknown','starting',1,1);" ignored)
else()
    sql("PRAGMA foreign_keys=ON; INSERT INTO maintenance_runs(run_id,expected_generation,config_snapshot_id,mode,state,plan_digest,canonical_plan,created_at) SELECT job_id,g.published_generation,j.config_snapshot_id,'automatic','incomplete',job_id,'{}','fixture' FROM jobs j CROSS JOIN library_meta g WHERE job_id IN('target','unknown'); INSERT INTO maintenance_windows(window_id,run_id,job_id,state,deadline_epoch,policy_json,policy_fingerprint,created_epoch,closed_epoch) SELECT job_id,job_id,job_id,'deadline',1,'{}','policy',1,2 FROM jobs WHERE job_id IN('target','unknown'); INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,started_at,completed_at) VALUES('unknown-attempt','unknown-item','old-worker',1,'input','pending','failed','fixture','fixture'); INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at) VALUES('unknown','unknown-item','unknown-attempt','provider-intent','{}','fixture');" ignored)
endif()
sql("PRAGMA integrity_check; SELECT count(*) FROM pragma_foreign_key_check;" integrity)
control("${integrity}" "ok\n0" "fixture integrity")
sql("SELECT count(*) FROM provider_runs;" calls)
control("${calls}" "0" "no model calls")
execute_process(COMMAND "${sqlite}" -readonly "${database}" .dump OUTPUT_VARIABLE before COMMAND_ERROR_IS_FATAL ANY)
if(CPRAG_CASE STREQUAL "stale_workers")
    read_cli(response worker status live-worker)
    record_field(alive "${response}" runtime-process pid_check)
    control("${alive}" "alive" "launch-domain PID visibility")
    read_cli(response worker status stale-worker)
    record_field(missing "${response}" runtime-process pid_check)
    control("${missing}" "missing" "exited worker independently confirmed")
    read_cli(response job status running)
    record_field(live "${response}" job-status worker_live_workers)
    control("${live}" "1" "healthy registered worker retained")
    read_cli(response worker status stale-live-worker)
    record_field(alive "${response}" runtime-process pid_check)
    control("${alive}" "alive" "old heartbeat does not prove process death")
    read_cli(response job status paused)
    record_field(live "${response}" job-status worker_live_workers)
    control("${live}" "1" "confirmed live process with old heartbeat retained")
    read_cli(response job status completed)
    record_field(empty "${response}" job-status worker_live_workers)
    control("${empty}" "0" "empty group")
    message(STATUS "SMOKE_STATUS_CONTROLS_OK: live, stale-but-alive, confirmed exited, empty group")
    read_cli(response job status unknown)
    record_field(actual "${response}" job-status worker_live_workers)
    expect("${actual}" "0" "unverified remote/reserved workers are not confirmed live")
    string(JSON actual ERROR_VARIABLE missing GET "${response}" records 0 fields worker_unverified_workers)
    expect("${actual}" "2" "unverified worker ownership is visible")
    read_cli(response job status target)
    record_field(actual "${response}" job-status worker_live_workers)
    expect("${actual}" "0" "RAG-SMK-004 CLI counts stale exited worker as live")
    read_mcp(response rag_job_status "{\"id\":\"target\"}")
    record_field(actual "${response}" job-status worker_live_workers)
    expect("${actual}" "0" "RAG-SMK-004 MCP counts stale exited worker as live")
else()
    foreach(job IN ITEMS running paused unknown completed)
        set(expected "${job}")
        if(job STREQUAL "unknown")
            set(expected completed_with_errors)
        endif()
        read_cli(response job status "${job}")
        record_field(actual "${response}" job-status state)
        control("${actual}" "${expected}" "${job} state")
    endforeach()
    message(STATUS "SMOKE_STATUS_CONTROLS_OK: running, operator pause, unknown outcome, complete")
    foreach(surface IN ITEMS cli mcp)
        if(surface STREQUAL "cli")
            read_cli(response job status target)
        else()
            read_mcp(response rag_job_status "{\"id\":\"target\"}")
        endif()
        record_field(actual "${response}" job-status state)
        control("${actual}" "completed_with_errors" "drained deadline job outcome")
        if(surface STREQUAL "cli")
            read_cli(response job list --limit 20)
        else()
            read_mcp(response rag_job_list "{\"limit\":20}")
        endif()
        string(JSON count LENGTH "${response}" records)
        control("${count}" "5" "all five job-list controls present")
        math(EXPR last "${count}-1")
        set(found 0)
        foreach(index RANGE 0 ${last})
            string(JSON id GET "${response}" records ${index} fields identity)
            if(id STREQUAL "target")
                set(found 1)
                string(JSON actual GET "${response}" records ${index} fields state)
                expect("${actual}" "completed_with_errors" "RAG-SMK-005 ${surface} list contradicts drained job status")
            else()
                set(expected "${id}")
                if(id STREQUAL "unknown")
                    set(expected completed_with_errors)
                endif()
                string(JSON actual GET "${response}" records ${index} fields state)
                control("${actual}" "${expected}" "${surface} list preserves ${id} control")
            endif()
        endforeach()
        control("${found}" "1" "target present in job list")
        if(surface STREQUAL "cli")
            read_cli(response library report --top 1)
        else()
            read_mcp(response rag_library_report "{\"top\":1,\"narrative\":\"off\"}")
        endif()
        record_field(actual "${response}" maintenance-backlog active_jobs)
        expect("${actual}" "2" "${surface} report counts running and intentional pause, not drained history")
    endforeach()
endif()
execute_process(COMMAND "${sqlite}" -readonly "${database}" .dump OUTPUT_VARIABLE after COMMAND_ERROR_IS_FATAL ANY)
control("${after}" "${before}" "public diagnostics are read-only")
message(STATUS "SMOKE_STATUS_READ_ONLY_OK: ${CPRAG_CASE}; any errors above remain failures")
