foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(sqlite sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
set(CPRAG_FIXTURE_PORT 1)
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
string(REPEAT "A historical passage contains source evidence for ordinary retrieval.\n" 100 body)
file(WRITE "${CPRAG_FIXTURE_SOURCE}/target.txt" "${body}")
file(WRITE "${CPRAG_FIXTURE_SOURCE}/old.txt" "An older historical passage.\n")
configure_file("${CPRAG_CONFIG_TEMPLATE}" "${CPRAG_WORK_DIR}/crexxrag.conf" @ONLY)
file(READ "${CPRAG_WORK_DIR}/crexxrag.conf" config)
string(REPLACE "discovery.mode = all" "discovery.mode = maintenance" config "${config}")
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 100" config "${config}")
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 100" config "${config}")
string(REPLACE "budget.input_tokens = 8192" "budget.input_tokens = 1000000" config "${config}")
file(WRITE "${CPRAG_WORK_DIR}/crexxrag.conf" "${config}\nmaintenance.mode = automatic\nmaintenance.batch_items = 2\n")
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
function(cli expected)
    execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --format json ${ARGN}
        WORKING_DIRECTORY "${CPRAG_WORK_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\n${out}${err}\n")
    if(NOT status EQUAL expected)
        message(FATAL_ERROR "Source maintenance command failed (expected ${expected}, got ${status}): ${out}${err}")
    endif()
    set(response "${out}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${sqlite}" -bail "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Source maintenance fixture failed: ${err}")
    endif()
    set(${output} "${out}" PARENT_SCOPE)
endfunction()
function(getplan)
    string(JSON plan GET "${response}" records 0 fields canonical_plan)
    string(JSON digest GET "${response}" records 0 fields digest)
    set(plan "${plan}" PARENT_SCOPE)
    set(digest "${digest}" PARENT_SCOPE)
endfunction()
cli(0 init)
cli(0 --access plan ingest plan --source-set architecture-docs)
getplan()
cli(0 --access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
sql(source "SELECT source_id FROM sources WHERE stable_key='target.txt';")
sql(chunks "SELECT count(*) FROM revision_chunks WHERE revision_id=(SELECT current_revision_id FROM sources WHERE source_id='${source}');")
if(chunks LESS 3)
    message(FATAL_ERROR "Fixture needs more source chunks than a dispatch wave")
endif()
# A late-sorting new source must not sit behind an old corpus census prefix.
sql(seeded "WITH RECURSIVE n(x) AS(SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<8) INSERT INTO revision_chunks(revision_chunk_id,revision_id,ordinal,normalized_start,normalized_end,content_id,continuity_key,parser_version,evidence_class,visible_from_generation) SELECT '000-old-'||x,r.revision_id,100+x,0,10,r.content_id,'old-'||x,'fixture','direct',r.visible_from_generation FROM n CROSS JOIN revision_chunks r WHERE r.revision_id=(SELECT current_revision_id FROM sources WHERE stable_key='old.txt') AND r.ordinal=1; UPDATE job_items SET state='processed' WHERE state='queued'; UPDATE jobs SET state='completed';")
# Existing unscoped plan/apply and old high-ranked work are the positive control.
cli(0 --access plan maintain plan)
getplan()
string(JSON policy GET "${plan}" action window_policy)
string(JSON knowledge GET "${policy}" knowledge_policy)
string(JSON profile GET "${policy}" embedding_profile)
string(JSON dimension GET "${policy}" embedding_dimension)
sql(seeded "INSERT OR IGNORE INTO embedding_profiles(embedding_profile_id,provider_id,model,dimension,input_envelope_fingerprint,created_at) VALUES('${profile}','fixture','fixture',${dimension},'fixture','fixture'); INSERT INTO embeddings(embedding_id,input_digest,embedding_profile_id,vector,dimension,created_at) SELECT 'fixture-'||revision_chunk_id,'fixture-'||revision_chunk_id,'${profile}',zeroblob(${dimension}*8),${dimension},'fixture' FROM revision_chunks; INSERT INTO revision_chunk_embeddings SELECT revision_chunk_id,'fixture-'||revision_chunk_id,visible_from_generation,NULL FROM revision_chunks; INSERT INTO concepts(concept_id,canonical_label,concept_type,lifecycle_state,visible_from_generation) VALUES('old-concept','Old','concept','active',(SELECT published_generation FROM library_meta)); INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) VALUES('old-ranked-task','identity-review','concept','old-concept','fixture','${knowledge}','{}','Old catalogue question','pending',960000,1,1);")
cli(0 --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON old_job GET "${response}" records 0 fields job_id)
# Dispatch now refreshes legacy/stale packets before freezing provider input.
# The old question may therefore be represented by its fresh linked successor;
# preserve the subject, kind, priority and selected job in this ordering control.
sql(control "SELECT count(*) FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id JOIN maintenance_tasks t ON t.task_id=m.task_id WHERE (t.task_id='old-ranked-task' OR t.parent_task_id='old-ranked-task') AND t.subject_id='old-concept' AND t.kind='identity-review' AND t.priority=960000 AND json_extract(t.evidence_json,'$.subject.id')='old-concept' AND i.job_id='${old_job}' AND i.state='queued';")
if(NOT control EQUAL 1)
    message(FATAL_ERROR "Unscoped positive control did not select older high-ranked work")
endif()
sql(old_task "SELECT m.task_id FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id JOIN maintenance_tasks t ON t.task_id=m.task_id WHERE (t.task_id='old-ranked-task' OR t.parent_task_id='old-ranked-task') AND t.subject_id='old-concept' AND i.job_id='${old_job}' AND i.state='queued';")
cli(0 --access control job pause "${old_job}")
# Reapplying ticks the paused window through its normal closure, without workers.
cli(0 --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
sql(before ".dump")
cli(0 --access plan maintain plan --source "${source}")
getplan()
string(JSON policy GET "${plan}" action window_policy)
string(JSON frozen_source GET "${policy}" source_id)
string(JSON scoped_knowledge GET "${policy}" knowledge_policy)
string(JSON preview GET "${response}" records 1 fields maintenance_plan)
string(JSON census_source GET "${preview}" source_id)
if(NOT frozen_source STREQUAL source OR NOT census_source STREQUAL source OR NOT scoped_knowledge STREQUAL knowledge)
    message(FATAL_ERROR "Source selection must be frozen in plan and window, without changing knowledge identity")
endif()
sql(after ".dump")
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Source maintenance planning mutated the library")
endif()
set(scoped_plan "${plan}")
set(scoped_digest "${digest}")
cli(0 --access plan maintain plan --phase identity --cohort-limit 1)
getplan()
string(JSON cohort_policy GET "${plan}" action window_policy)
string(JSON cohort_phase GET "${cohort_policy}" phase)
string(JSON cohort_count LENGTH "${cohort_policy}" phase_cohort)
string(JSON cohort_first GET "${cohort_policy}" phase_cohort 0)
if(NOT cohort_phase STREQUAL "identity" OR NOT cohort_count EQUAL 1 OR NOT cohort_first STREQUAL "old-concept")
    message(FATAL_ERROR "Identity phase did not freeze the selected logical concept cohort")
endif()
set(phase_plan "${plan}")
set(phase_digest "${digest}")
# A selected identity cohort can stop at activation before its first census.
# The pre-existing old-concept task is outside this one-subject cohort.
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/pre-scan-expiry")
file(COPY "${CPRAG_WORK_DIR}/library" DESTINATION "${CPRAG_WORK_DIR}/pre-scan-expiry")
set(expired_library "${CPRAG_WORK_DIR}/pre-scan-expiry/library")
set(database "${expired_library}/library.sqlite")
sql(seeded "INSERT INTO concepts(concept_id,canonical_label,concept_type,lifecycle_state,visible_from_generation) VALUES('000-unscanned','Unscanned','concept','active',(SELECT published_generation FROM library_meta));")
sql(expired_until "SELECT strftime('%Y-%m-%dT%H:%M:%SZ','now','+14 seconds');")
cli(0 --library "${expired_library}" --access plan maintain plan --phase identity --cohort-limit 1 --until "${expired_until}")
getplan()
string(JSON expired_policy GET "${plan}" action window_policy)
string(JSON expired_subject GET "${expired_policy}" phase_cohort 0)
string(JSON expired_denominator GET "${expired_policy}" phase_denominator)
if(NOT expired_subject STREQUAL "000-unscanned" OR NOT expired_denominator EQUAL 1)
    message(FATAL_ERROR "Pre-scan expiry did not freeze its nonempty identity cohort")
endif()
cli(0 --library "${expired_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON expired_job GET "${response}" records 0 fields job_id)
sql(expired_facts "SELECT w.state||':'||r.state||':'||(SELECT count(*) FROM maintenance_tasks WHERE kind='identity-review' AND subject_id='000-unscanned')||':'||(SELECT count(*) FROM maintenance_scan_cursors c WHERE c.kind='identity-review' AND c.scan_token=w.window_id||':'||(SELECT published_generation FROM library_meta)||':'||(SELECT count(*) FROM provider_runs) AND c.completed=1)||':'||(SELECT count(*) FROM provider_runs) FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${expired_job}';")
if(NOT expired_facts STREQUAL "deadline:incomplete:0:0:0")
    message(FATAL_ERROR "Pre-scan expiry claimed selected resolution or failed its source controls: ${expired_facts}")
endif()
cli(0 --library "${expired_library}" --access read maintain status)
string(JSON expired_summary GET "${response}" records 0 fields backlog)
string(JSON expired_selected GET "${expired_summary}" selected_work_resolved)
string(JSON expired_termination GET "${expired_summary}" termination)
string(JSON expired_closed GET "${expired_summary}" closed_epoch)
string(JSON expired_quiet GET "${expired_summary}" closed_for_no_runnable_work)
if(expired_selected OR NOT expired_termination STREQUAL "stopped:deadline" OR
   expired_quiet OR NOT expired_closed GREATER 0)
    message(FATAL_ERROR "Public status claimed an unscanned selected cohort resolved: ${expired_summary}")
endif()
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
file(WRITE "${CPRAG_WORK_DIR}/phase-mcp.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_maintain_plan\",\"arguments\":{\"phase\":\"identity\",\"cohort_limit\":1}}}\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --access read,plan --format json serve mcp
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/phase-mcp.jsonl"
    RESULT_VARIABLE phase_mcp_status OUTPUT_VARIABLE phase_mcp_out ERROR_VARIABLE phase_mcp_err TIMEOUT 30)
if(NOT phase_mcp_status EQUAL 0)
    message(FATAL_ERROR "Phase MCP request failed: ${phase_mcp_out}${phase_mcp_err}")
endif()
string(JSON response GET "${phase_mcp_out}" result structuredContent)
getplan()
string(JSON mcp_policy GET "${plan}" action window_policy)
string(JSON mcp_phase GET "${mcp_policy}" phase)
string(JSON mcp_count LENGTH "${mcp_policy}" phase_cohort)
string(JSON mcp_first GET "${mcp_policy}" phase_cohort 0)
if(NOT mcp_phase STREQUAL "identity" OR NOT mcp_count EQUAL 1 OR NOT mcp_first STREQUAL cohort_first)
    message(FATAL_ERROR "MCP and CLI froze different identity cohorts")
endif()
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/phase-cohort")
file(COPY "${CPRAG_WORK_DIR}/library" DESTINATION "${CPRAG_WORK_DIR}/phase-cohort")
set(phase_library "${CPRAG_WORK_DIR}/phase-cohort/library")
set(database "${phase_library}/library.sqlite")
string(JSON phase_knowledge GET "${cohort_policy}" knowledge_policy)
sql(seeded "INSERT INTO concepts(concept_id,canonical_label,concept_type,lifecycle_state,visible_from_generation) VALUES('higher-priority-concept','Other','concept','active',(SELECT published_generation FROM library_meta)); INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) VALUES('higher-priority-task','identity-review','concept','higher-priority-concept','fixture','${phase_knowledge}','{}','Unrelated high-priority question','pending',1000000,1,1);")
cli(0 --library "${phase_library}" --access curate maintain apply --plan-json "${phase_plan}" --expect-digest "${phase_digest}")
string(JSON phase_job GET "${response}" records 0 fields job_id)
sql(phase_selected "SELECT group_concat(DISTINCT t.subject_id) FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id JOIN maintenance_tasks t ON t.task_id=m.task_id WHERE i.job_id='${phase_job}' AND i.state='queued';")
if(NOT phase_selected STREQUAL "old-concept")
    message(FATAL_ERROR "Frozen identity cohort was displaced by unrelated higher-priority work: ${phase_selected}")
endif()
cli(0 --library "${phase_library}" --access control job continue "${phase_job}" --prepare)
sql(phase_retained "SELECT json_extract(policy_json,'$.phase')||':'||json_extract(policy_json,'$.phase_denominator')||':'||json_extract(policy_json,'$.phase_cohort[0]') FROM maintenance_windows WHERE job_id='${phase_job}';")
sql(phase_continued "SELECT count(*)||':'||coalesce(group_concat(DISTINCT t.subject_id),'') FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id JOIN maintenance_tasks t ON t.task_id=m.task_id WHERE i.job_id='${phase_job}' AND i.state IN('queued','running');")
if(NOT phase_retained STREQUAL "identity:1:old-concept" OR NOT phase_continued STREQUAL "1:old-concept")
    message(FATAL_ERROR "Identity cohort changed across supported continuation: ${phase_retained}, ${phase_continued}")
endif()
# A previously settled selected question with unchanged evidence gives a
# nonempty cohort whose current census can finish without another provider call.
cli(0 --library "${phase_library}" --access control job pause "${phase_job}")
cli(0 --library "${phase_library}" --access curate maintain apply --plan-json "${phase_plan}" --expect-digest "${phase_digest}")
sql(settled_phase_task "SELECT m.task_id FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id JOIN maintenance_tasks t ON t.task_id=m.task_id WHERE i.job_id='${phase_job}' AND t.kind='identity-review' AND t.subject_id='old-concept' LIMIT 1;")
if(settled_phase_task STREQUAL "")
    message(FATAL_ERROR "Fully scanned positive control has no selected task")
endif()
sql(seeded "UPDATE maintenance_tasks SET state='resolved' WHERE task_id='${settled_phase_task}';")
cli(0 --library "${phase_library}" --access plan maintain plan --phase identity --cohort-after higher-priority-concept --cohort-limit 1 --minutes 2)
getplan()
string(JSON settled_policy GET "${plan}" action window_policy)
string(JSON settled_subject GET "${settled_policy}" phase_cohort 0)
if(NOT settled_subject STREQUAL "old-concept")
    message(FATAL_ERROR "Fully scanned positive control changed the selected subject")
endif()
cli(0 --library "${phase_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON settled_job GET "${response}" records 0 fields job_id)
sql(settled_facts "SELECT w.state||':'||r.state||':'||(SELECT count(*) FROM maintenance_scan_cursors c WHERE c.kind IN('identity-review','settled-questions') AND c.scan_token=w.window_id||':'||(SELECT published_generation FROM library_meta)||':'||(SELECT count(*) FROM provider_runs) AND c.completed=1)||':'||(SELECT count(*) FROM provider_runs) FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${settled_job}';")
if(NOT settled_facts STREQUAL "complete:complete:2:0")
    message(FATAL_ERROR "Fully scanned selected identity cohort did not close quiescent: ${settled_facts}")
endif()
cli(0 --library "${phase_library}" --access read maintain status)
string(JSON settled_summary GET "${response}" records 0 fields backlog)
string(JSON settled_resolved GET "${settled_summary}" selected_work_resolved)
string(JSON settled_quiet GET "${settled_summary}" closed_for_no_runnable_work)
string(JSON settled_closed GET "${settled_summary}" closed_epoch)
if(NOT settled_resolved OR NOT settled_quiet OR NOT settled_closed GREATER 0)
    message(FATAL_ERROR "Fully scanned selected identity cohort did not report resolution: ${settled_summary}")
endif()
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/finish-cohort")
file(COPY "${CPRAG_WORK_DIR}/library" DESTINATION "${CPRAG_WORK_DIR}/finish-cohort")
set(finish_library "${CPRAG_WORK_DIR}/finish-cohort/library")
set(database "${finish_library}/library.sqlite")
sql(seeded "INSERT INTO reviews(review_id,review_type,subject_id,state,proposal_json,created_at) VALUES('finish-review-one','external-proposal','synthetic-proposal','pending','{}','fixture');")
cli(0 --library "${finish_library}" --access plan maintain plan --phase finish --cohort-limit 1)
getplan()
string(JSON finish_policy GET "${plan}" action window_policy)
string(JSON finish_count LENGTH "${finish_policy}" phase_cohort)
string(JSON finish_first GET "${finish_policy}" phase_cohort 0)
if(NOT finish_count EQUAL 1 OR NOT finish_first STREQUAL "finish-review-one")
    message(FATAL_ERROR "Finish phase omitted a selected pending proposal review")
endif()
cli(0 --library "${finish_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON finish_job GET "${response}" records 0 fields job_id)
sql(finish_state "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${finish_job}';")
if(NOT finish_state STREQUAL "complete:incomplete")
    message(FATAL_ERROR "Finish phase claimed closure while selected review remains pending: ${finish_state}")
endif()
# A selected workflow is unfinished even when its origin and dependent task
# versions have resolved. Its required review may be created after the cohort
# was frozen, so its ID need not be an original cohort member.
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/finish-workflow")
file(COPY "${CPRAG_WORK_DIR}/library" DESTINATION "${CPRAG_WORK_DIR}/finish-workflow")
set(workflow_library "${CPRAG_WORK_DIR}/finish-workflow/library")
set(database "${workflow_library}/library.sqlite")
sql(seeded "INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) VALUES('finish-origin','fixture','concept','old-concept','origin','${phase_knowledge}','{}','Origin','resolved',1,1,1); INSERT INTO maintenance_workflows(workflow_id,origin_task_id,kind,parent_concept_id,successors_json,state,created_generation,created_epoch,updated_epoch) VALUES('workflow:finish-hold','finish-origin','split','old-concept','[]','waiting',(SELECT published_generation FROM library_meta),1,1); INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,workflow_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) VALUES('finish-dependent','fixture','concept','old-concept','workflow:finish-hold','dependent','${phase_knowledge}','{}','Dependent','resolved',1,1,1); INSERT INTO reviews(review_id,review_type,subject_id,state,proposal_json,created_at) VALUES('zz-finish-required','maintenance-change','finish-dependent','pending','{}','fixture');")
sql(workflow_facts "SELECT (SELECT count(*) FROM maintenance_workflows WHERE workflow_id='workflow:finish-hold' AND state='waiting')||':'||(SELECT count(*) FROM reviews WHERE subject_id='finish-dependent' AND state='pending')||':'||(SELECT count(*) FROM maintenance_tasks WHERE task_id IN('finish-origin','finish-dependent') AND state='resolved');")
if(NOT workflow_facts STREQUAL "1:1:2")
    message(FATAL_ERROR "Finish-workflow source control is invalid: ${workflow_facts}")
endif()
cli(0 --library "${workflow_library}" --access plan maintain plan --phase finish --cohort-limit 1)
getplan()
string(JSON workflow_policy GET "${plan}" action window_policy)
string(JSON workflow_selected GET "${workflow_policy}" phase_cohort 0)
if(NOT workflow_selected STREQUAL "workflow:finish-hold")
    message(FATAL_ERROR "Finish workflow was not the exact selected cohort: ${workflow_selected}")
endif()
cli(0 --library "${workflow_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON workflow_job GET "${response}" records 0 fields job_id)
# The first bounded checkpoint visits the workflow; the next observes its
# settled cursor and closes the no-runnable-work window.
cli(0 --library "${workflow_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
sql(workflow_state "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${workflow_job}';")
if(NOT workflow_state STREQUAL "complete:incomplete")
    message(FATAL_ERROR "Finish phase claimed selected workflow and required review resolved: ${workflow_state}")
endif()
string(JSON workflow_summary GET "${response}" records 0 fields backlog)
foreach(field termination run_state closed_for_no_runnable_work selected_work_resolved
        phase_denominator phase_next_cursor phase_unseen_remainder workflows
        selected_pending_reviews provider_calls processed_items admission_deferrals
        applied_change_decisions)
    string(JSON workflow_${field} GET "${workflow_summary}" ${field})
endforeach()
if(NOT workflow_termination STREQUAL "no-runnable-work" OR NOT workflow_run_state STREQUAL "incomplete" OR
   NOT workflow_closed_for_no_runnable_work OR workflow_selected_work_resolved OR
   NOT workflow_phase_denominator EQUAL 1 OR NOT workflow_phase_next_cursor STREQUAL "workflow:finish-hold" OR
   NOT workflow_phase_unseen_remainder OR NOT workflow_workflows EQUAL 1 OR
   NOT workflow_selected_pending_reviews EQUAL 1 OR NOT workflow_provider_calls EQUAL 0 OR
   NOT workflow_processed_items EQUAL 0 OR NOT workflow_admission_deferrals EQUAL 0 OR
   NOT workflow_applied_change_decisions EQUAL 0)
    message(FATAL_ERROR "Finish status conflated closure, selected debt, unseen cohort or throughput: ${workflow_summary}")
endif()
set(database "${finish_library}/library.sqlite")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/graph-cohort")
file(COPY "${CPRAG_WORK_DIR}/library" DESTINATION "${CPRAG_WORK_DIR}/graph-cohort")
set(graph_library "${CPRAG_WORK_DIR}/graph-cohort/library")
set(database "${graph_library}/library.sqlite")
cli(0 --library "${graph_library}" --access plan maintain plan --phase graph --cohort-limit 1)
getplan()
string(JSON graph_policy GET "${plan}" action window_policy)
string(JSON graph_first GET "${graph_policy}" phase_cohort 0)
if(NOT graph_first STREQUAL "old-concept")
    message(FATAL_ERROR "Graph phase did not freeze the requested sparse concept")
endif()
cli(0 --library "${graph_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON graph_job GET "${response}" records 0 fields job_id)
sql(graph_selected "SELECT count(*) FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id JOIN maintenance_tasks t ON t.task_id=m.task_id WHERE i.job_id='${graph_job}' AND t.kind='sparse-node' AND t.subject_id='old-concept';")
if(NOT graph_selected EQUAL 1)
    message(FATAL_ERROR "Graph phase was displaced by unrelated identity or old backlog work")
endif()
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
cli(0 --access curate maintain apply --plan-json "${scoped_plan}" --expect-digest "${scoped_digest}")
string(JSON job GET "${response}" records 0 fields job_id)
sql(initial "SELECT count(*)||':'||coalesce(sum(i.item_type='improve-extraction' AND json_extract(i.input_json,'$.revision_chunk_id') IN(SELECT c.revision_chunk_id FROM revision_chunks c JOIN sources s ON s.current_revision_id=c.revision_id WHERE s.source_id='${source}')),0) FROM job_items i WHERE i.job_id='${job}';")
if(NOT initial STREQUAL "2:2")
    message(FATAL_ERROR "First scoped wave did not select new-source extraction before the old census prefix: ${initial}")
endif()
if(CPRAG_DEADLINE_TEST)
    include("${CMAKE_CURRENT_LIST_DIR}/JobDeadline.cmake")
    return()
endif()
# PC-01: ordinary completion of already-admitted items after the wall-clock
# window expires must not renew allowances or discover another work wave.
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/admitted-continuation")
file(COPY "${CPRAG_WORK_DIR}/library" DESTINATION "${CPRAG_WORK_DIR}/admitted-continuation")
set(admitted_library "${CPRAG_WORK_DIR}/admitted-continuation/library")
set(database "${admitted_library}/library.sqlite")
# Before expiry, existing ordinary preparation remains a passing control.
cli(0 --library "${admitted_library}" --access control job continue "${job}" --prepare)
sql(ordinary_limit "SELECT json_extract(policy_json,'$.item_limit') FROM maintenance_windows WHERE job_id='${job}';")
if(NOT ordinary_limit EQUAL 100)
    message(FATAL_ERROR "Pre-expiry continuation changed normal discovery allowance")
endif()
sql(expired "UPDATE jobs SET state='paused' WHERE job_id='${job}'; UPDATE maintenance_windows SET deadline_epoch=1 WHERE job_id='${job}';")
set(allowance_sql "SELECT item_budget||':'||model_call_budget||':'||input_token_budget||':'||output_token_budget||':'||cost_budget||':'||codex_turn_budget||':'||config_snapshot_id FROM jobs WHERE job_id='${job}';")
set(admitted_sql "SELECT item_id||':'||input_hash||':'||state||':'||fence FROM job_items WHERE job_id='${job}' ORDER BY item_id;")
sql(allowance_before "${allowance_sql}")
sql(admitted_before "${admitted_sql}")
sql(task_count_before "SELECT count(*) FROM maintenance_tasks;")
cli(0 --library "${admitted_library}" --access control job continue "${job}" --prepare)
sql(allowance_after "${allowance_sql}")
sql(admitted_after "${admitted_sql}")
sql(periods "SELECT count(*) FROM job_events WHERE job_id='${job}' AND event_type='allowance-period';")
sql(admitted_window "SELECT (deadline_epoch>unixepoch())||':'||json_extract(policy_json,'$.item_limit') FROM maintenance_windows WHERE job_id='${job}';")
if(NOT allowance_before STREQUAL allowance_after OR NOT admitted_before STREQUAL admitted_after OR
   NOT periods EQUAL 0 OR NOT admitted_window STREQUAL "1:2")
    message(FATAL_ERROR "Admitted continuation changed allowance/history or failed to bound its existing queue: ${admitted_window}")
endif()
sql(deadline_before "SELECT deadline_epoch||':'||policy_json FROM maintenance_windows WHERE job_id='${job}';")
cli(0 --library "${admitted_library}" --access control job continue "${job}" --prepare)
sql(deadline_after "SELECT deadline_epoch||':'||policy_json FROM maintenance_windows WHERE job_id='${job}';")
if(NOT deadline_before STREQUAL deadline_after)
    message(FATAL_ERROR "Repeated ordinary preparation renewed the completion period")
endif()
# Simulate successful settlement in this scratch-only owner test. More source
# chunks and higher-priority old work remain available but must not be admitted.
sql(settled "UPDATE job_items SET state='processed' WHERE job_id='${job}' AND state='queued';")
cli(0 --library "${admitted_library}" --access control job continue "${job}" --prepare)
sql(final_items "SELECT count(*)||':'||sum(state='processed') FROM job_items WHERE job_id='${job}';")
sql(task_count_after "SELECT count(*) FROM maintenance_tasks;")
sql(provider_calls "SELECT count(*) FROM provider_runs;")
if(NOT final_items STREQUAL "2:2" OR NOT task_count_before STREQUAL task_count_after OR NOT provider_calls EQUAL 0)
    message(FATAL_ERROR "Expired queued completion discovered/dispatched additional work")
endif()
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
# A retry request for older work cannot use this source window's allowance.
cli(0 --access control maintain retry "${old_task}" --reason "Continue after selected source")
sql(retry_scope "SELECT disposition FROM retry_requests WHERE task_id='${old_task}' ORDER BY created_epoch DESC LIMIT 1;")
if(NOT retry_scope STREQUAL "policy-mismatch")
    message(FATAL_ERROR "An unrelated retry became eligible in the source window: ${retry_scope}")
endif()
# Simulate settled workers only in this disposable fixture. Each apply invokes
# the existing checkpoint; no transport or real library is involved.
math(EXPR passes "${chunks}+3")
foreach(pass RANGE 1 ${passes})
    sql(settled "UPDATE job_items SET state='processed' WHERE job_id='${job}' AND state='queued';")
    cli(0 --access curate maintain apply --plan-json "${scoped_plan}" --expect-digest "${scoped_digest}")
endforeach()
sql(result "SELECT count(*)||':'||sum(i.item_type='improve-extraction') FROM job_items i WHERE i.job_id='${job}';")
sql(complete "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${job}';")
sql(represented "SELECT count(DISTINCT t.subject_id) FROM maintenance_tasks t JOIN revision_chunks c ON c.revision_chunk_id=t.subject_id JOIN sources s ON s.current_revision_id=c.revision_id WHERE s.source_id='${source}' AND t.kind='concept-review' AND t.state='resolved';")
sql(untouched "SELECT state FROM maintenance_tasks WHERE task_id='${old_task}';")
if(NOT result STREQUAL "${chunks}:${chunks}" OR NOT represented EQUAL chunks OR NOT complete STREQUAL "complete:complete" OR NOT untouched STREQUAL "pending")
    message(FATAL_ERROR "Source completion leaked old work, skipped chunks or reopened a completed task: ${result}, ${represented}, ${complete}, ${untouched}")
endif()
# Missing old-source embeddings cannot enter or prevent completion of a
# source-scoped embedding repair window.
sql(target_chunk "SELECT revision_chunk_id FROM revision_chunks WHERE revision_id=(SELECT current_revision_id FROM sources WHERE source_id='${source}') ORDER BY revision_chunk_id LIMIT 1;")
sql(deleted "DELETE FROM revision_chunk_embeddings WHERE revision_chunk_id='${target_chunk}' OR revision_chunk_id LIKE '000-old-%';")
cli(0 --access plan maintain plan --source "${source}" --embeddings-only --minutes 13)
getplan()
set(embedding_plan "${plan}")
set(embedding_digest "${digest}")
cli(0 --access curate maintain apply --plan-json "${embedding_plan}" --expect-digest "${embedding_digest}")
string(JSON embedding_job GET "${response}" records 0 fields job_id)
sql(embedding_wave "SELECT count(*)||':'||sum(item_type='embedding' AND json_extract(input_json,'$.revision_chunk_id')='${target_chunk}') FROM job_items WHERE job_id='${embedding_job}';")
if(NOT embedding_wave STREQUAL "1:1")
    message(FATAL_ERROR "Scoped embedding repair leaked unrelated missing vectors: ${embedding_wave}")
endif()
sql(restored "INSERT INTO revision_chunk_embeddings SELECT revision_chunk_id,'fixture-'||revision_chunk_id,visible_from_generation,NULL FROM revision_chunks WHERE revision_chunk_id='${target_chunk}'; UPDATE job_items SET state='processed' WHERE job_id='${embedding_job}' AND state='queued';")
cli(0 --access curate maintain apply --plan-json "${embedding_plan}" --expect-digest "${embedding_digest}")
string(JSON summary GET "${response}" records 0 fields backlog)
string(JSON missing GET "${summary}" embedding_missing)
string(JSON total GET "${summary}" embedding_total)
sql(embedding_complete "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${embedding_job}';")
if(NOT missing EQUAL 0 OR NOT total EQUAL chunks OR NOT embedding_complete STREQUAL "complete:complete")
    message(FATAL_ERROR "Scoped embedding coverage/completion used the full corpus: ${summary}")
endif()
# Existing holds retain their semantics within the selected source.
sql(holds "INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch,required_capability) VALUES('scope-advanced','alias-follow-up:advanced','chunk','${target_chunk}','fixture','${knowledge}','{}','Held','pending',999999,1,1,'advanced-reasoning'),('scope-review','alias-follow-up:review','chunk','${target_chunk}','fixture','${knowledge}','{}','Held','pending',999999,1,1,'standard'),('scope-waived','alias-follow-up:waived','chunk','${target_chunk}','fixture','${knowledge}','{}','Held','pending',999999,1,1,'standard'); INSERT INTO reviews(review_id,review_type,subject_id,state,proposal_json,created_at) VALUES('scope-review-record','maintenance','scope-review','pending','{}','fixture'); INSERT INTO maintenance_task_waivers(waiver_id,task_id,reason,state,created_epoch) VALUES('scope-waiver','scope-waived','Fixture retains uncertainty','active',1);")
cli(0 --access plan maintain plan --source "${source}" --minutes 14)
getplan()
set(held_plan "${plan}")
set(held_digest "${digest}")
foreach(pass RANGE 1 ${passes})
    cli(0 --access curate maintain apply --plan-json "${held_plan}" --expect-digest "${held_digest}")
endforeach()
string(JSON held_job GET "${response}" records 0 fields job_id)
sql(held_result "SELECT count(*) FROM job_items WHERE job_id='${held_job}';")
sql(held_pending "SELECT count(*) FROM maintenance_tasks WHERE task_id IN('scope-advanced','scope-review','scope-waived') AND state='pending';")
sql(held_complete "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${held_job}';")
if(NOT held_result EQUAL 0 OR NOT held_pending EQUAL 3 OR NOT held_complete STREQUAL "complete:incomplete")
    message(FATAL_ERROR "Source window bypassed a hold or claimed held work complete")
endif()
# The source restriction is part of the approved plan rather than an apply flag.
cli(2 --access curate maintain apply --source "${source}" --plan-json "${scoped_plan}" --expect-digest "${scoped_digest}")
cli(5 --access plan maintain plan --source source-missing)
cli(2 --access plan maintain plan --source "${source}" --enrich-provenance --input unused.json)
file(WRITE "${CPRAG_WORK_DIR}/reviewed.conf" "${config}\nmaintenance.mode = reviewed\n")
cli(2 --config-file "${CPRAG_WORK_DIR}/reviewed.conf" --access plan maintain plan --source "${source}")
# Guided human maintenance must forward the selector and show it before approval.
sql(before ".dump")
file(WRITE "${CPRAG_WORK_DIR}/decline.txt" "n\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" maintain "--source=${source}"
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/decline.txt"
    RESULT_VARIABLE guided_status OUTPUT_VARIABLE guided_out ERROR_VARIABLE guided_err TIMEOUT 30)
string(FIND "${guided_out}" "${source}" shown_source)
if(NOT guided_status EQUAL 9 OR shown_source LESS 0)
    message(FATAL_ERROR "Guided maintenance did not preview the selected source: ${guided_out}${guided_err}")
endif()
sql(after ".dump")
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Declining source maintenance changed the library")
endif()
# MCP receives the same selector through canonical command metadata.
file(WRITE "${CPRAG_WORK_DIR}/mcp.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_maintain_plan\",\"arguments\":{\"source\":\"${source}\"}}}\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --access read,plan --format json serve mcp
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/mcp.jsonl"
    RESULT_VARIABLE mcp_status OUTPUT_VARIABLE mcp_out ERROR_VARIABLE mcp_err TIMEOUT 30)
if(NOT mcp_status EQUAL 0)
    message(FATAL_ERROR "Source maintenance MCP request failed: ${mcp_out}${mcp_err}")
endif()
string(JSON response GET "${mcp_out}" result structuredContent)
getplan()
string(JSON policy GET "${plan}" action window_policy)
string(JSON mcp_source GET "${policy}" source_id)
if(NOT mcp_source STREQUAL source)
    message(FATAL_ERROR "MCP dropped the source selector")
endif()
file(WRITE "${CPRAG_WORK_DIR}/mcp.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_maintain_plan\",\"arguments\":{\"source\":\"${source}\",\"initial_extraction_only\":true}}}\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --access read,plan --format json serve mcp
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/mcp.jsonl"
    RESULT_VARIABLE mcp_status OUTPUT_VARIABLE mcp_out ERROR_VARIABLE mcp_err TIMEOUT 30)
if(NOT mcp_status EQUAL 0)
    message(FATAL_ERROR "First-pass MCP request failed: ${mcp_out}${mcp_err}")
endif()
string(JSON response GET "${mcp_out}" result structuredContent)
getplan()
string(JSON policy GET "${plan}" action window_policy)
string(JSON mcp_initial GET "${policy}" initial_extraction_only)
if(NOT mcp_initial EQUAL 1)
    message(FATAL_ERROR "MCP dropped the first-pass selector")
endif()
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" maintain "--source=${source}" --initial-extraction-only
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/decline.txt"
    RESULT_VARIABLE guided_status OUTPUT_VARIABLE guided_out ERROR_VARIABLE guided_err TIMEOUT 30)
string(FIND "${guided_out}" "First concept review for current chunks" shown_mode)
if(NOT guided_status EQUAL 9 OR shown_mode LESS 0)
    message(FATAL_ERROR "Guided maintenance did not preview the first-pass scope: ${guided_out}${guided_err}")
endif()
# A first-pass extraction window uses ingested current chunks but excludes
# alias follow-ups, embedding repair and chunks with an earlier review result.
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/initial-only")
file(COPY "${CPRAG_WORK_DIR}/library" DESTINATION "${CPRAG_WORK_DIR}/initial-only")
set(initial_library "${CPRAG_WORK_DIR}/initial-only/library")
set(database "${initial_library}/library.sqlite")
sql(seeded "INSERT INTO revision_chunks(revision_chunk_id,revision_id,ordinal,normalized_start,normalized_end,content_id,continuity_key,parser_version,evidence_class,visible_from_generation) SELECT 'initial-only-new',revision_id,10000,normalized_start,normalized_end,content_id,'initial-only-new',parser_version,evidence_class,visible_from_generation FROM revision_chunks WHERE revision_chunk_id='${target_chunk}'; INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) VALUES('initial-alias','alias-follow-up:fixture','chunk','initial-only-new','fixture','${knowledge}','{}','Alias follow-up','pending',999999,1,1);")
# Model retained successful discovery receipts for the older scratch items.
# Their processed flag alone must not establish first-pass completion.
sql(seeded "INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,output_hash,validation_state,outcome,started_at,completed_at) SELECT 'accepted-'||item_id,item_id,'fixture',1,input_hash,'accepted-empty','validated-discovery-batch','succeeded','fixture','fixture' FROM job_items WHERE item_type='improve-extraction' AND state='processed';")
cli(0 --library "${initial_library}" --access plan maintain plan --source "${source}" --minutes 5)
string(JSON ordinary_selection GET "${response}" records 1 fields selection)
if(NOT ordinary_selection MATCHES "initial-alias")
    message(FATAL_ERROR "Ordinary source maintenance no longer admits alias follow-up work: ${ordinary_selection}")
endif()
sql(before ".dump")
cli(0 --library "${initial_library}" --access plan maintain plan --source "${source}" --initial-extraction-only --minutes 5)
getplan()
string(JSON initial_policy GET "${plan}" action window_policy)
string(JSON initial_mode GET "${initial_policy}" initial_extraction_only)
string(JSON initial_source GET "${initial_policy}" source_id)
if(NOT initial_mode EQUAL 1 OR NOT initial_source STREQUAL source)
    message(FATAL_ERROR "First-pass scope was not frozen in the reviewed plan")
endif()
sql(after ".dump")
if(NOT before STREQUAL after)
    message(FATAL_ERROR "First-pass maintenance planning mutated the library")
endif()
set(initial_plan "${plan}")
set(initial_digest "${digest}")
cli(0 --library "${initial_library}" --access curate maintain apply --plan-json "${initial_plan}" --expect-digest "${initial_digest}")
string(JSON initial_job GET "${response}" records 0 fields job_id)
sql(first_wave "SELECT count(*)||':'||coalesce(sum(i.item_type='improve-extraction' AND json_extract(i.input_json,'$.revision_chunk_id')='initial-only-new'),0) FROM job_items i WHERE i.job_id='${initial_job}';")
sql(alias_wave "SELECT count(*) FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id WHERE m.task_id='initial-alias' AND i.job_id='${initial_job}';")
if(NOT first_wave STREQUAL "1:1" OR NOT alias_wave EQUAL 0)
    message(FATAL_ERROR "First-pass window admitted follow-ups, embeddings or already reviewed chunks: ${first_wave}, ${alias_wave}")
endif()
sql(initial_task "SELECT m.task_id FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id WHERE i.job_id='${initial_job}' AND json_extract(i.input_json,'$.revision_chunk_id')='initial-only-new';")
sql(seeded "INSERT INTO provider_runs(provider_run_id,config_snapshot_id,provider_id,model,request_hash,outcome,started_at) SELECT 'first-pass-control-run',config_snapshot_id,'fixture','fixture','fixture','completed','fixture' FROM jobs WHERE job_id='${initial_job}'; UPDATE job_items SET state='processed' WHERE job_id='${initial_job}' AND state='queued'; INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,output_hash,provider_run_id,validation_state,outcome,started_at,completed_at) SELECT 'first-pass-control',item_id,'fixture',1,input_hash,'control','first-pass-control-run','validated-maintenance-resolution','succeeded','fixture','fixture' FROM job_items WHERE job_id='${initial_job}'; INSERT INTO maintenance_decisions(decision_id,task_id,item_id,provider_run_id,response_json,grounding_json,disposition,created_epoch) SELECT 'first-pass-control','${initial_task}',item_id,'first-pass-control-run','{}','[]','extract:pending',unixepoch() FROM job_items WHERE job_id='${initial_job}';")
cli(0 --library "${initial_library}" --access curate maintain apply --plan-json "${initial_plan}" --expect-digest "${initial_digest}")
sql(first_complete "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${initial_job}';")
if(NOT first_complete STREQUAL "complete:incomplete")
    message(FATAL_ERROR "Intermediate extract control falsely completed first pass: ${first_complete}")
endif()
cli(0 --library "${initial_library}" --access read maintain tasks --source "${source}")
string(JSON source_detail GET "${response}" records 0 fields detail)
string(JSON first_missing GET "${source_detail}" incomplete_first_pass_chunks)
if(NOT first_missing EQUAL 1)
    message(FATAL_ERROR "Source status hid the intermediate-only first-pass chunk: ${source_detail}")
endif()
foreach(control IN ITEMS "search:pending" "read:pending" "defer:unresolved" "escalate:unresolved" "no-change:resolved")
    sql(seeded "UPDATE maintenance_decisions SET disposition='${control}' WHERE decision_id='first-pass-control';")
    cli(0 --library "${initial_library}" --access read maintain tasks --source "${source}")
    string(JSON control_detail GET "${response}" records 0 fields detail)
    string(JSON control_missing GET "${control_detail}" incomplete_first_pass_chunks)
    if(NOT control_missing EQUAL 1)
        message(FATAL_ERROR "Processed ${control} control was mistaken for accepted first extraction")
    endif()
endforeach()
sql(seeded "UPDATE maintenance_decisions SET disposition='extract:pending' WHERE decision_id='first-pass-control';")
sql(retry_hold "SELECT not_before_epoch>unixepoch() FROM maintenance_tasks WHERE task_id='${initial_task}';")
if(NOT retry_hold EQUAL 1)
    message(FATAL_ERROR "Intermediate control lost its bounded retry delay")
endif()
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/initial-reset")
file(COPY "${initial_library}" DESTINATION "${CPRAG_WORK_DIR}/initial-reset")
set(reset_library "${CPRAG_WORK_DIR}/initial-reset/library")
set(database "${reset_library}/library.sqlite")
cli(0 --library "${reset_library}" --access control maintain reset "${initial_task}")
string(JSON reset_task GET "${response}" records 0 fields task_id)
sql(reset_state "SELECT state||':'||attempt_count||':'||(not_before_epoch=0) FROM maintenance_tasks WHERE task_id='${reset_task}';")
sql(reset_receipts "SELECT count(*) FROM attempts WHERE attempt_id='first-pass-control';")
if(reset_task STREQUAL initial_task OR NOT reset_state STREQUAL "pending:0:1" OR NOT reset_receipts EQUAL 1)
    message(FATAL_ERROR "Explicit first-pass reset did not restore eligibility while preserving the earlier receipt: ${reset_task}, ${reset_state}, ${reset_receipts}")
endif()
cli(0 --library "${reset_library}" --access plan maintain plan --source "${source}" --initial-extraction-only --minutes 6)
getplan()
cli(0 --library "${reset_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON reset_job GET "${response}" records 0 fields job_id)
sql(reset_selected "SELECT count(*) FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id WHERE m.task_id='${reset_task}' AND i.job_id='${reset_job}' AND i.item_type='improve-extraction';")
if(NOT reset_selected EQUAL 1)
    message(FATAL_ERROR "Explicit reset did not restore first-pass dispatch eligibility")
endif()
set(database "${initial_library}/library.sqlite")
# Advance this disposable fixture past the retained retry delay; ordinary
# refresh above must not have cleared it or the paid attempt history.
sql(expired "UPDATE maintenance_tasks SET not_before_epoch=0 WHERE task_id='${initial_task}';")
cli(0 --library "${initial_library}" --access plan maintain plan --source "${source}" --initial-extraction-only --minutes 6)
getplan()
cli(0 --library "${initial_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON accepted_job GET "${response}" records 0 fields job_id)
sql(accepted_wave "SELECT count(*) FROM job_items WHERE job_id='${accepted_job}' AND item_type='improve-extraction' AND json_extract(input_json,'$.revision_chunk_id')='initial-only-new';")
if(NOT accepted_wave EQUAL 1)
    message(FATAL_ERROR "Intermediate first-pass control did not remain eligible: ${accepted_wave}")
endif()
sql(seeded "UPDATE job_items SET state='processed' WHERE job_id='${accepted_job}' AND state='queued'; INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,output_hash,validation_state,outcome,started_at,completed_at) SELECT 'first-pass-accepted',item_id,'fixture',1,input_hash,'accepted-empty','validated-discovery-batch','succeeded','fixture','fixture' FROM job_items WHERE job_id='${accepted_job}'; INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at) SELECT job_id,item_id,'first-pass-accepted','processed','{\"mentions\":0,\"relationships\":0,\"notes\":0}','fixture' FROM job_items WHERE job_id='${accepted_job}';")
cli(0 --library "${initial_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
sql(accepted_complete "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${accepted_job}';")
if(NOT accepted_complete STREQUAL "complete:complete")
    message(FATAL_ERROR "Accepted empty extraction did not complete first pass: ${accepted_complete}")
endif()
cli(0 --library "${initial_library}" --access read maintain tasks --source "${source}")
string(JSON source_detail GET "${response}" records 0 fields detail)
string(JSON accepted_missing GET "${source_detail}" incomplete_first_pass_chunks)
string(JSON accepted_empty GET "${source_detail}" accepted_empty_first_pass_chunks)
if(NOT accepted_missing EQUAL 0 OR NOT accepted_empty EQUAL 1)
    message(FATAL_ERROR "Source status missed retained accepted extraction: ${source_detail}")
endif()
cli(0 --library "${initial_library}" --access plan maintain plan --source "${source}" --initial-extraction-only --minutes 7)
getplan()
cli(0 --library "${initial_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON repeat_job GET "${response}" records 0 fields job_id)
sql(repeat_items "SELECT count(*) FROM job_items WHERE job_id='${repeat_job}';")
sql(calls "SELECT count(*) FROM provider_runs;")
if(NOT repeat_items EQUAL 0 OR NOT calls EQUAL 1)
    message(FATAL_ERROR "First-pass mode repeated a completed result or called a provider")
endif()
cli(2 --library "${initial_library}" --access plan maintain plan --initial-extraction-only)
cli(2 --library "${initial_library}" --access plan maintain plan --source "${source}" --initial-extraction-only --embeddings-only)
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
sql(restored "INSERT INTO revision_chunk_embeddings SELECT revision_chunk_id,'fixture-'||revision_chunk_id,visible_from_generation,NULL FROM revision_chunks WHERE revision_chunk_id LIKE '000-old-%';")
cli(0 --access plan maintain plan)
getplan()
cli(0 --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON resumed_job GET "${response}" records 0 fields job_id)
sql(resumed "SELECT count(*) FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id WHERE m.task_id='${old_task}' AND i.job_id='${resumed_job}' AND i.state='queued';")
sql(calls "SELECT count(*) FROM provider_runs;")
if(NOT resumed EQUAL 1 OR NOT calls EQUAL 0)
    message(FATAL_ERROR "Ordinary backlog did not resume or fixture called a provider")
endif()
# The public plan/apply route must preserve a real zero deadline. The fixture
# is empty and isolated, so no provider request can occur.
set(unlimited_root "${CPRAG_WORK_DIR}/unlimited")
file(MAKE_DIRECTORY "${unlimited_root}/source-docs")
file(READ "${CMAKE_CURRENT_LIST_DIR}/../crexx/application/config/google-gemini.conf" unlimited_config)
string(REPLACE "crexx-rag.config/3" "crexx-rag.config/4" unlimited_config "${unlimited_config}")
string(REPLACE "budget.minutes = 30" "budget.minutes = 0" unlimited_config "${unlimited_config}")
string(REPLACE "budget.item_limit = 100" "budget.item_limit = 0" unlimited_config "${unlimited_config}")
string(REPLACE "budget.model_calls = 50" "budget.model_calls = 0" unlimited_config "${unlimited_config}")
string(REPLACE "budget.input_tokens = 100000" "budget.input_tokens = 0" unlimited_config "${unlimited_config}")
string(REPLACE "budget.output_tokens = 50000" "budget.output_tokens = 0" unlimited_config "${unlimited_config}")
string(REPLACE "budget.cost_microunits = 2000000" "budget.cost_microunits = 0" unlimited_config "${unlimited_config}")
file(WRITE "${unlimited_root}/crexxrag.conf" "${unlimited_config}\nmaintenance.mode = automatic\nmaintenance.window_seconds = 0\n")
set(unlimited_library "${unlimited_root}/library")
cli(0 --config-file "${unlimited_root}/crexxrag.conf" --library "${unlimited_library}" --config google-gemini --profile generic-profile init)
sql(future_until "SELECT strftime('%Y-%m-%dT%H:%M:%SZ','now','+1 hour');")
cli(0 --config-file "${unlimited_root}/crexxrag.conf" --library "${unlimited_library}" --config google-gemini --profile generic-profile --access plan maintain plan --until "${future_until}")
getplan()
string(JSON finite_policy GET "${plan}" action window_policy)
string(JSON finite_timing GET "${finite_policy}" timing)
string(JSON finite_mode GET "${finite_timing}" mode)
string(JSON finite_deadline GET "${finite_timing}" deadline_epoch)
if(NOT finite_mode STREQUAL "until" OR finite_deadline EQUAL 0)
    message(FATAL_ERROR "Explicit finite deadline did not override the unlimited default")
endif()
file(WRITE "${unlimited_root}/mcp.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_maintain_plan\",\"arguments\":{\"minutes\":0}}}\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --config-file "${unlimited_root}/crexxrag.conf" --library "${unlimited_library}" --config google-gemini --profile generic-profile --access read,plan --format json serve mcp
    INPUT_FILE "${unlimited_root}/mcp.jsonl" RESULT_VARIABLE mcp_status OUTPUT_VARIABLE mcp_out ERROR_VARIABLE mcp_err TIMEOUT 30)
if(NOT mcp_status EQUAL 0)
    message(FATAL_ERROR "Unlimited MCP plan request failed: ${mcp_out}${mcp_err}")
endif()
string(JSON mcp_response GET "${mcp_out}" result structuredContent)
string(JSON mcp_plan GET "${mcp_response}" records 0 fields canonical_plan)
string(JSON mcp_policy GET "${mcp_plan}" action window_policy)
string(JSON mcp_timing GET "${mcp_policy}" timing)
string(JSON mcp_deadline GET "${mcp_timing}" deadline_epoch)
if(NOT mcp_deadline EQUAL 0)
    message(FATAL_ERROR "MCP minutes zero did not preserve the public unlimited deadline")
endif()
cli(0 --config-file "${unlimited_root}/crexxrag.conf" --library "${unlimited_library}" --config google-gemini --profile generic-profile --access plan maintain plan --minutes 0)
getplan()
string(JSON unlimited_policy GET "${plan}" action window_policy)
string(JSON unlimited_timing GET "${unlimited_policy}" timing)
string(JSON unlimited_deadline GET "${unlimited_timing}" deadline_epoch)
if(NOT unlimited_deadline EQUAL 0)
    message(FATAL_ERROR "Public unlimited maintenance plan invented a deadline")
endif()
cli(0 --config-file "${unlimited_root}/crexxrag.conf" --library "${unlimited_library}" --config google-gemini --profile generic-profile --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON unlimited_job GET "${response}" records 0 fields job_id)
cli(0 --config-file "${unlimited_root}/crexxrag.conf" --library "${unlimited_library}" --config google-gemini --profile generic-profile --access read job status "${unlimited_job}")
string(JSON unlimited_status_marker GET "${response}" records 0 fields zero_unlimited)
if(NOT unlimited_status_marker STREQUAL "ON")
    message(FATAL_ERROR "Public job status did not identify explicit zero-unlimited policy: ${response}")
endif()
set(database "${unlimited_library}/library.sqlite")
sql(seeded "UPDATE jobs SET reserved_cost=123,reserved_codex_turns=7 WHERE job_id='${unlimited_job}';")
cli(0 --config-file "${unlimited_root}/crexxrag.conf" --library "${unlimited_library}" --config google-gemini --profile generic-profile --access read job status "${unlimited_job}")
string(JSON allowance GET "${response}" records 0 fields allowance)
string(JSON reserved_cost GET "${allowance}" reserved_cost)
string(JSON reserved_turns GET "${allowance}" reserved_codex_turns)
if(NOT reserved_cost EQUAL 123 OR NOT reserved_turns EQUAL 7)
    message(FATAL_ERROR "Public allowance swapped or omitted distinct live reservations: ${allowance}")
endif()
sql(seeded "UPDATE jobs SET reserved_cost=0,reserved_codex_turns=0 WHERE job_id='${unlimited_job}';")
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
execute_process(COMMAND "${sqlite}" -bail "${unlimited_library}/library.sqlite" "SELECT deadline_epoch FROM maintenance_windows WHERE job_id='${unlimited_job}';" OUTPUT_VARIABLE unlimited_stored OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT unlimited_stored STREQUAL "0")
    message(FATAL_ERROR "Public unlimited maintenance apply skipped or changed the zero deadline: ${response}")
endif()
set(reviewed_root "${CPRAG_WORK_DIR}/reviewed-unlimited")
file(MAKE_DIRECTORY "${reviewed_root}/source-docs")
file(WRITE "${reviewed_root}/source-docs/evidence.txt" "A short synthetic source passage for embedding repair.\n")
file(WRITE "${reviewed_root}/crexxrag.conf" "${unlimited_config}\nmaintenance.mode = reviewed\n")
set(reviewed_library "${reviewed_root}/library")
cli(0 --config-file "${reviewed_root}/crexxrag.conf" --library "${reviewed_library}" --config google-gemini --profile generic-profile init)
cli(0 --config-file "${reviewed_root}/crexxrag.conf" --library "${reviewed_library}" --config google-gemini --profile generic-profile --access plan ingest plan --source-set architecture-docs)
getplan()
cli(0 --config-file "${reviewed_root}/crexxrag.conf" --library "${reviewed_library}" --config google-gemini --profile generic-profile --access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON reviewed_ingest_job GET "${response}" records 0 fields job_id)
execute_process(COMMAND "${sqlite}" -bail "${reviewed_library}/library.sqlite" "INSERT INTO job_items(item_id,job_id,item_type,state,priority,idempotency_key,input_hash,input_json,created_at,updated_at) SELECT 'reviewed-control-'||content_id,'${reviewed_ingest_job}','improve-extraction','processed',1,'reviewed-control-'||content_id,'fixture',json_object('content_id',content_id,'policy_version','surface-claim-v1','prompt_version','surface-prompt-v1'),'fixture','fixture' FROM revision_chunks; UPDATE job_items SET state='processed' WHERE job_id='${reviewed_ingest_job}' AND state='queued'; UPDATE jobs SET state='completed' WHERE job_id='${reviewed_ingest_job}';" RESULT_VARIABLE reviewed_seed_result)
if(NOT reviewed_seed_result EQUAL 0)
    message(FATAL_ERROR "Could not seed completed cognitive work for reviewed repair-only case")
endif()
cli(0 --config-file "${reviewed_root}/crexxrag.conf" --library "${reviewed_library}" --config google-gemini --profile generic-profile --access plan maintain plan)
getplan()
cli(0 --config-file "${reviewed_root}/crexxrag.conf" --library "${reviewed_library}" --config google-gemini --profile generic-profile --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON reviewed_job GET "${response}" records 0 fields job_id)
execute_process(COMMAND "${sqlite}" -bail "${reviewed_library}/library.sqlite" "SELECT count(*) FROM job_events WHERE job_id='${reviewed_job}' AND event_type='budget-policy' AND json_extract(message,'$.zero_unlimited')=1 AND json_extract(message,'$.time_budget_ms')=0 AND json_extract(message,'$.maximum_call_time_ms')>0;" OUTPUT_VARIABLE reviewed_policy OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT reviewed_policy STREQUAL "1")
    message(FATAL_ERROR "Reviewed embedding-only job did not retain bounded requests under unlimited aggregates: ${response}")
endif()
file(WRITE "${CPRAG_WORK_DIR}/result.txt" "Source-scoped automatic maintenance: unscoped rank control, frozen preview/window scope, selection before census page and dispatch wave, complete source coverage across checkpoints, source-local completion, old-work preservation/resumption, MCP parity, zero provider calls.\n")
