foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(sqlite sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
set(CPRAG_FIXTURE_PORT 1)
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
string(REPEAT "A historical passage contains source evidence for ordinary retrieval.\n" 100 body)
file(WRITE "${CPRAG_FIXTURE_SOURCE}/target.txt" "${body}")
file(WRITE "${CPRAG_FIXTURE_SOURCE}/other.txt" "An unrelated historical passage.\n")
configure_file("${CPRAG_CONFIG_TEMPLATE}" "${CPRAG_WORK_DIR}/crexxrag.conf" @ONLY)
file(READ "${CPRAG_WORK_DIR}/crexxrag.conf" config)
string(REPLACE "discovery.mode = all" "discovery.mode = maintenance" config "${config}")
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 100" config "${config}")
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 100" config "${config}")
string(REPLACE "budget.input_tokens = 8192" "budget.input_tokens = 1000000" config "${config}")
file(WRITE "${CPRAG_WORK_DIR}/crexxrag.conf" "${config}")
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
function(cli expected)
    execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --format json ${ARGN}
        WORKING_DIRECTORY "${CPRAG_WORK_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\n${out}${err}\n")
    if(NOT status EQUAL expected)
        message(FATAL_ERROR "Source backlog command failed: ${out}${err}")
    endif()
    set(response "${out}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${sqlite}" -bail "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Source backlog fixture failed: ${err}")
    endif()
    set(${output} "${out}" PARENT_SCOPE)
endfunction()
function(summary expected_chunks expected_discovered)
    string(JSON detail GET "${response}" records 0 fields detail)
    string(JSON chunks GET "${detail}" active_chunks)
    string(JSON discovered GET "${detail}" chunks_with_extraction_task)
    string(JSON unseen GET "${detail}" chunks_without_extraction_task)
    math(EXPR expected_unseen "${expected_chunks}-${expected_discovered}")
    if(NOT chunks EQUAL expected_chunks OR NOT discovered EQUAL expected_discovered OR NOT unseen EQUAL expected_unseen)
        message(FATAL_ERROR "Incorrect source backlog denominator: ${detail}")
    endif()
endfunction()
cli(0 init)
cli(0 --access plan ingest plan --source-set architecture-docs)
string(JSON plan GET "${response}" records 0 fields canonical_plan)
string(JSON digest GET "${response}" records 0 fields digest)
cli(0 --access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
sql(source "SELECT source_id FROM sources WHERE stable_key='target.txt';")
sql(chunks "SELECT count(*) FROM revision_chunks WHERE revision_id=(SELECT current_revision_id FROM sources WHERE source_id='${source}');")
if(chunks LESS 3)
    message(FATAL_ERROR "Fixture needs at least three distinct source chunks")
endif()
# Positive control before the missing public source filter.
cli(0 maintain tasks --limit 2)
cli(0 maintain tasks --source "${source}" --limit 2)
summary("${chunks}" 0)
sql(seeded "WITH seq(n) AS(SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n<75) INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) SELECT 'a-noise-'||n,'concept-review','chunk',(SELECT revision_chunk_id FROM revision_chunks WHERE revision_id=(SELECT current_revision_id FROM sources WHERE stable_key='other.txt') LIMIT 1),'noise-'||n,'policy','{}','noise','pending',1,1,1 FROM seq; INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) SELECT 'z-target-'||ordinal,'concept-review','chunk',revision_chunk_id,'evidence','policy','{}','target',CASE WHEN ordinal=1 THEN 'resolved' ELSE 'pending' END,600000,1,1 FROM revision_chunks WHERE revision_id=(SELECT current_revision_id FROM sources WHERE source_id='${source}') ORDER BY ordinal LIMIT 2; INSERT INTO sources(source_id,connector_type,stable_key,lifecycle_state,observed_uri,observed_title,visible_from_generation) VALUES('source-empty','folder:fixture','empty','active','file:empty','Empty',(SELECT published_generation FROM library_meta));")
sql(before ".dump")
cli(0 maintain tasks --source "${source}" --limit 1)
summary("${chunks}" 2)
string(JSON detail GET "${response}" records 0 fields detail)
string(JSON pending GET "${detail}" extraction_tasks_by_state pending)
string(JSON resolved GET "${detail}" extraction_tasks_by_state resolved)
string(JSON first GET "${response}" records 1 fields id)
if(NOT pending EQUAL 1 OR NOT resolved EQUAL 1 OR NOT first MATCHES "^z-target-")
    message(FATAL_ERROR "Source task filtering/counts failed: ${response}")
endif()
string(JSON cursor GET "${response}" records 2 fields next_cursor)
cli(0 maintain tasks --source "${source}" --cursor "${cursor}" --limit 1)
summary("${chunks}" 2)
string(JSON second GET "${response}" records 1 fields id)
if(second STREQUAL first OR NOT second MATCHES "^z-target-")
    message(FATAL_ERROR "Source cursor repeated or leaked an unrelated task")
endif()
file(WRITE "${CPRAG_WORK_DIR}/mcp.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_task_list\",\"arguments\":{\"source\":\"${source}\",\"limit\":1}}}\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --access read --format json serve mcp
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/mcp.jsonl"
    RESULT_VARIABLE mcp_status OUTPUT_VARIABLE mcp_out ERROR_VARIABLE mcp_err TIMEOUT 30)
if(NOT mcp_status EQUAL 0)
    message(FATAL_ERROR "Source backlog MCP request failed: ${mcp_out}${mcp_err}")
endif()
string(JSON response GET "${mcp_out}" result structuredContent)
summary("${chunks}" 2)
cli(0 maintain tasks --source source-empty)
summary(0 0)
cli(5 maintain tasks --source source-missing)
sql(after ".dump")
sql(calls "SELECT count(*) FROM provider_runs;")
if(NOT before STREQUAL after OR NOT calls EQUAL 0)
    message(FATAL_ERROR "Source backlog inspection mutated data or called a provider")
endif()
file(WRITE "${CPRAG_WORK_DIR}/result.txt" "Source backlog: undiscovered chunk denominator, indexed source filtering before pagination, per-state counts, cursor, empty/missing source, zero writes/provider calls.\n")
