foreach(required CPRAG_NATIVE_APPLICATION CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
find_program(sqlite sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
set(CPRAG_FIXTURE_PORT 1)
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
string(REPEAT "A historical passage contains source evidence for ordinary retrieval.\n" 100 body)
file(WRITE "${CPRAG_FIXTURE_SOURCE}/target.txt" "${body}")
file(WRITE "${CPRAG_FIXTURE_SOURCE}/old.txt" "An older historical passage.\n")
configure_file("${CPRAG_CONFIG_TEMPLATE}" "${CPRAG_WORK_DIR}/crexxrag.conf" @ONLY)
file(READ "${CPRAG_WORK_DIR}/crexxrag.conf" config)
string(REPLACE "discovery.mode = all" "discovery.mode = maintenance" config "${config}")
string(REPLACE "budget.item_limit = 2" "budget.item_limit = 100" config "${config}")
string(REPLACE "budget.model_calls = 2" "budget.model_calls = 100" config "${config}")
string(REPLACE "budget.input_tokens = 8192" "budget.input_tokens = 1000000" config "${config}")
file(WRITE "${CPRAG_WORK_DIR}/crexxrag.conf" "${config}\nmaintenance.mode = automatic\nmaintenance.batch_items = 2\n")
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
function(cli expected)
    execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --format json ${ARGN}
        WORKING_DIRECTORY "${CPRAG_WORK_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    file(APPEND "${CPRAG_WORK_DIR}/commands.log" "${ARGN}\n${out}${err}\n")
    if(NOT status EQUAL expected)
        message(FATAL_ERROR "Source maintenance command failed (expected ${expected}, got ${status}): ${out}${err}")
    endif()
    set(response "${out}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${sqlite}" -bail "${database}" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Source maintenance fixture failed: ${err}")
    endif()
    set(${output} "${out}" PARENT_SCOPE)
endfunction()
function(getplan)
    string(JSON plan GET "${response}" records 0 fields canonical_plan)
    string(JSON digest GET "${response}" records 0 fields digest)
    set(plan "${plan}" PARENT_SCOPE)
    set(digest "${digest}" PARENT_SCOPE)
endfunction()
cli(0 init)
cli(0 --access plan ingest plan --source-set architecture-docs)
getplan()
cli(0 --access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
sql(source "SELECT source_id FROM sources WHERE stable_key='target.txt';")
sql(chunks "SELECT count(*) FROM revision_chunks WHERE revision_id=(SELECT current_revision_id FROM sources WHERE source_id='${source}');")
if(chunks LESS 3)
    message(FATAL_ERROR "Fixture needs more source chunks than a dispatch wave")
endif()
# A late-sorting new source must not sit behind an old corpus census prefix.
sql(seeded "WITH RECURSIVE n(x) AS(SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<8) INSERT INTO revision_chunks(revision_chunk_id,revision_id,ordinal,normalized_start,normalized_end,content_id,continuity_key,parser_version,evidence_class,visible_from_generation) SELECT '000-old-'||x,r.revision_id,100+x,0,10,r.content_id,'old-'||x,'fixture','direct',r.visible_from_generation FROM n CROSS JOIN revision_chunks r WHERE r.revision_id=(SELECT current_revision_id FROM sources WHERE stable_key='old.txt') AND r.ordinal=1; UPDATE job_items SET state='processed' WHERE state='queued'; UPDATE jobs SET state='completed';")
# Existing unscoped plan/apply and old high-ranked work are the positive control.
cli(0 --access plan maintain plan)
getplan()
string(JSON policy GET "${plan}" action window_policy)
string(JSON knowledge GET "${policy}" knowledge_policy)
string(JSON profile GET "${policy}" embedding_profile)
string(JSON dimension GET "${policy}" embedding_dimension)
sql(seeded "INSERT OR IGNORE INTO embedding_profiles(embedding_profile_id,provider_id,model,dimension,input_envelope_fingerprint,created_at) VALUES('${profile}','fixture','fixture',${dimension},'fixture','fixture'); INSERT INTO embeddings(embedding_id,input_digest,embedding_profile_id,vector,dimension,created_at) SELECT 'fixture-'||revision_chunk_id,'fixture-'||revision_chunk_id,'${profile}',zeroblob(${dimension}*8),${dimension},'fixture' FROM revision_chunks; INSERT INTO revision_chunk_embeddings SELECT revision_chunk_id,'fixture-'||revision_chunk_id,visible_from_generation,NULL FROM revision_chunks; INSERT INTO concepts(concept_id,canonical_label,concept_type,lifecycle_state,visible_from_generation) VALUES('old-concept','Old','concept','active',(SELECT published_generation FROM library_meta)); INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) VALUES('old-ranked-task','identity-review','concept','old-concept','fixture','${knowledge}','{}','Old catalogue question','pending',960000,1,1);")
cli(0 --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON old_job GET "${response}" records 0 fields job_id)
# Dispatch now refreshes legacy/stale packets before freezing provider input.
# The old question may therefore be represented by its fresh linked successor;
# preserve the subject, kind, priority and selected job in this ordering control.
sql(control "SELECT count(*) FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id JOIN maintenance_tasks t ON t.task_id=m.task_id WHERE (t.task_id='old-ranked-task' OR t.parent_task_id='old-ranked-task') AND t.subject_id='old-concept' AND t.kind='identity-review' AND t.priority=960000 AND json_extract(t.evidence_json,'$.subject.id')='old-concept' AND i.job_id='${old_job}' AND i.state='queued';")
if(NOT control EQUAL 1)
    message(FATAL_ERROR "Unscoped positive control did not select older high-ranked work")
endif()
sql(old_task "SELECT m.task_id FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id JOIN maintenance_tasks t ON t.task_id=m.task_id WHERE (t.task_id='old-ranked-task' OR t.parent_task_id='old-ranked-task') AND t.subject_id='old-concept' AND i.job_id='${old_job}' AND i.state='queued';")
cli(0 --access control job pause "${old_job}")
# Reapplying ticks the paused window through its normal closure, without workers.
cli(0 --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
sql(before ".dump")
cli(0 --access plan maintain plan --source "${source}")
getplan()
string(JSON policy GET "${plan}" action window_policy)
string(JSON frozen_source GET "${policy}" source_id)
string(JSON scoped_knowledge GET "${policy}" knowledge_policy)
string(JSON preview GET "${response}" records 1 fields maintenance_plan)
string(JSON census_source GET "${preview}" source_id)
if(NOT frozen_source STREQUAL source OR NOT census_source STREQUAL source OR NOT scoped_knowledge STREQUAL knowledge)
    message(FATAL_ERROR "Source selection must be frozen in plan and window, without changing knowledge identity")
endif()
sql(after ".dump")
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Source maintenance planning mutated the library")
endif()
set(scoped_plan "${plan}")
set(scoped_digest "${digest}")
cli(0 --access curate maintain apply --plan-json "${scoped_plan}" --expect-digest "${scoped_digest}")
string(JSON job GET "${response}" records 0 fields job_id)
sql(initial "SELECT count(*)||':'||coalesce(sum(i.item_type='improve-extraction' AND json_extract(i.input_json,'$.revision_chunk_id') IN(SELECT c.revision_chunk_id FROM revision_chunks c JOIN sources s ON s.current_revision_id=c.revision_id WHERE s.source_id='${source}')),0) FROM job_items i WHERE i.job_id='${job}';")
if(NOT initial STREQUAL "2:2")
    message(FATAL_ERROR "First scoped wave did not select new-source extraction before the old census prefix: ${initial}")
endif()
if(CPRAG_DEADLINE_TEST)
    include("${CMAKE_CURRENT_LIST_DIR}/JobDeadline.cmake")
    return()
endif()
# PC-01: ordinary completion of already-admitted items after the wall-clock
# window expires must not renew allowances or discover another work wave.
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/admitted-continuation")
file(COPY "${CPRAG_WORK_DIR}/library" DESTINATION "${CPRAG_WORK_DIR}/admitted-continuation")
set(admitted_library "${CPRAG_WORK_DIR}/admitted-continuation/library")
set(database "${admitted_library}/library.sqlite")
# Before expiry, existing ordinary preparation remains a passing control.
cli(0 --library "${admitted_library}" --access control job continue "${job}" --prepare)
sql(ordinary_limit "SELECT json_extract(policy_json,'$.item_limit') FROM maintenance_windows WHERE job_id='${job}';")
if(NOT ordinary_limit EQUAL 100)
    message(FATAL_ERROR "Pre-expiry continuation changed normal discovery allowance")
endif()
sql(expired "UPDATE jobs SET state='paused' WHERE job_id='${job}'; UPDATE maintenance_windows SET deadline_epoch=1 WHERE job_id='${job}';")
set(allowance_sql "SELECT item_budget||':'||model_call_budget||':'||input_token_budget||':'||output_token_budget||':'||cost_budget||':'||codex_turn_budget||':'||config_snapshot_id FROM jobs WHERE job_id='${job}';")
set(admitted_sql "SELECT item_id||':'||input_hash||':'||state||':'||fence FROM job_items WHERE job_id='${job}' ORDER BY item_id;")
sql(allowance_before "${allowance_sql}")
sql(admitted_before "${admitted_sql}")
sql(task_count_before "SELECT count(*) FROM maintenance_tasks;")
cli(0 --library "${admitted_library}" --access control job continue "${job}" --prepare)
sql(allowance_after "${allowance_sql}")
sql(admitted_after "${admitted_sql}")
sql(periods "SELECT count(*) FROM job_events WHERE job_id='${job}' AND event_type='allowance-period';")
sql(admitted_window "SELECT (deadline_epoch>unixepoch())||':'||json_extract(policy_json,'$.item_limit') FROM maintenance_windows WHERE job_id='${job}';")
if(NOT allowance_before STREQUAL allowance_after OR NOT admitted_before STREQUAL admitted_after OR
   NOT periods EQUAL 0 OR NOT admitted_window STREQUAL "1:2")
    message(FATAL_ERROR "Admitted continuation changed allowance/history or failed to bound its existing queue: ${admitted_window}")
endif()
sql(deadline_before "SELECT deadline_epoch||':'||policy_json FROM maintenance_windows WHERE job_id='${job}';")
cli(0 --library "${admitted_library}" --access control job continue "${job}" --prepare)
sql(deadline_after "SELECT deadline_epoch||':'||policy_json FROM maintenance_windows WHERE job_id='${job}';")
if(NOT deadline_before STREQUAL deadline_after)
    message(FATAL_ERROR "Repeated ordinary preparation renewed the completion period")
endif()
# Simulate successful settlement in this scratch-only owner test. More source
# chunks and higher-priority old work remain available but must not be admitted.
sql(settled "UPDATE job_items SET state='processed' WHERE job_id='${job}' AND state='queued';")
cli(0 --library "${admitted_library}" --access control job continue "${job}" --prepare)
sql(final_items "SELECT count(*)||':'||sum(state='processed') FROM job_items WHERE job_id='${job}';")
sql(task_count_after "SELECT count(*) FROM maintenance_tasks;")
sql(provider_calls "SELECT count(*) FROM provider_runs;")
if(NOT final_items STREQUAL "2:2" OR NOT task_count_before STREQUAL task_count_after OR NOT provider_calls EQUAL 0)
    message(FATAL_ERROR "Expired queued completion discovered/dispatched additional work")
endif()
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
# A retry request for older work cannot use this source window's allowance.
cli(0 --access control maintain retry "${old_task}" --reason "Continue after selected source")
sql(retry_scope "SELECT disposition FROM retry_requests WHERE task_id='${old_task}' ORDER BY created_epoch DESC LIMIT 1;")
if(NOT retry_scope STREQUAL "policy-mismatch")
    message(FATAL_ERROR "An unrelated retry became eligible in the source window: ${retry_scope}")
endif()
# Simulate settled workers only in this disposable fixture. Each apply invokes
# the existing checkpoint; no transport or real library is involved.
math(EXPR passes "${chunks}+3")
foreach(pass RANGE 1 ${passes})
    sql(settled "UPDATE job_items SET state='processed' WHERE job_id='${job}' AND state='queued';")
    cli(0 --access curate maintain apply --plan-json "${scoped_plan}" --expect-digest "${scoped_digest}")
endforeach()
sql(result "SELECT count(*)||':'||sum(i.item_type='improve-extraction') FROM job_items i WHERE i.job_id='${job}';")
sql(complete "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${job}';")
sql(represented "SELECT count(DISTINCT t.subject_id) FROM maintenance_tasks t JOIN revision_chunks c ON c.revision_chunk_id=t.subject_id JOIN sources s ON s.current_revision_id=c.revision_id WHERE s.source_id='${source}' AND t.kind='concept-review' AND t.state='resolved';")
sql(untouched "SELECT state FROM maintenance_tasks WHERE task_id='${old_task}';")
if(NOT result STREQUAL "${chunks}:${chunks}" OR NOT represented EQUAL chunks OR NOT complete STREQUAL "complete:complete" OR NOT untouched STREQUAL "pending")
    message(FATAL_ERROR "Source completion leaked old work, skipped chunks or reopened a completed task: ${result}, ${represented}, ${complete}, ${untouched}")
endif()
# Missing old-source embeddings cannot enter or prevent completion of a
# source-scoped embedding repair window.
sql(target_chunk "SELECT revision_chunk_id FROM revision_chunks WHERE revision_id=(SELECT current_revision_id FROM sources WHERE source_id='${source}') ORDER BY revision_chunk_id LIMIT 1;")
sql(deleted "DELETE FROM revision_chunk_embeddings WHERE revision_chunk_id='${target_chunk}' OR revision_chunk_id LIKE '000-old-%';")
cli(0 --access plan maintain plan --source "${source}" --embeddings-only --minutes 13)
getplan()
set(embedding_plan "${plan}")
set(embedding_digest "${digest}")
cli(0 --access curate maintain apply --plan-json "${embedding_plan}" --expect-digest "${embedding_digest}")
string(JSON embedding_job GET "${response}" records 0 fields job_id)
sql(embedding_wave "SELECT count(*)||':'||sum(item_type='embedding' AND json_extract(input_json,'$.revision_chunk_id')='${target_chunk}') FROM job_items WHERE job_id='${embedding_job}';")
if(NOT embedding_wave STREQUAL "1:1")
    message(FATAL_ERROR "Scoped embedding repair leaked unrelated missing vectors: ${embedding_wave}")
endif()
sql(restored "INSERT INTO revision_chunk_embeddings SELECT revision_chunk_id,'fixture-'||revision_chunk_id,visible_from_generation,NULL FROM revision_chunks WHERE revision_chunk_id='${target_chunk}'; UPDATE job_items SET state='processed' WHERE job_id='${embedding_job}' AND state='queued';")
cli(0 --access curate maintain apply --plan-json "${embedding_plan}" --expect-digest "${embedding_digest}")
string(JSON summary GET "${response}" records 0 fields backlog)
string(JSON missing GET "${summary}" embedding_missing)
string(JSON total GET "${summary}" embedding_total)
sql(embedding_complete "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${embedding_job}';")
if(NOT missing EQUAL 0 OR NOT total EQUAL chunks OR NOT embedding_complete STREQUAL "complete:complete")
    message(FATAL_ERROR "Scoped embedding coverage/completion used the full corpus: ${summary}")
endif()
# Existing holds retain their semantics within the selected source.
sql(holds "INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch,required_capability) VALUES('scope-advanced','alias-follow-up:advanced','chunk','${target_chunk}','fixture','${knowledge}','{}','Held','pending',999999,1,1,'advanced-reasoning'),('scope-review','alias-follow-up:review','chunk','${target_chunk}','fixture','${knowledge}','{}','Held','pending',999999,1,1,'standard'),('scope-waived','alias-follow-up:waived','chunk','${target_chunk}','fixture','${knowledge}','{}','Held','pending',999999,1,1,'standard'); INSERT INTO reviews(review_id,review_type,subject_id,state,proposal_json,created_at) VALUES('scope-review-record','maintenance','scope-review','pending','{}','fixture'); INSERT INTO maintenance_task_waivers(waiver_id,task_id,reason,state,created_epoch) VALUES('scope-waiver','scope-waived','Fixture retains uncertainty','active',1);")
cli(0 --access plan maintain plan --source "${source}" --minutes 14)
getplan()
set(held_plan "${plan}")
set(held_digest "${digest}")
foreach(pass RANGE 1 ${passes})
    cli(0 --access curate maintain apply --plan-json "${held_plan}" --expect-digest "${held_digest}")
endforeach()
string(JSON held_job GET "${response}" records 0 fields job_id)
sql(held_result "SELECT count(*) FROM job_items WHERE job_id='${held_job}';")
sql(held_pending "SELECT count(*) FROM maintenance_tasks WHERE task_id IN('scope-advanced','scope-review','scope-waived') AND state='pending';")
sql(held_complete "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${held_job}';")
if(NOT held_result EQUAL 0 OR NOT held_pending EQUAL 3 OR NOT held_complete STREQUAL "complete:incomplete")
    message(FATAL_ERROR "Source window bypassed a hold or claimed held work complete")
endif()
# The source restriction is part of the approved plan rather than an apply flag.
cli(2 --access curate maintain apply --source "${source}" --plan-json "${scoped_plan}" --expect-digest "${scoped_digest}")
cli(5 --access plan maintain plan --source source-missing)
cli(2 --access plan maintain plan --source "${source}" --enrich-provenance --input unused.json)
file(WRITE "${CPRAG_WORK_DIR}/reviewed.conf" "${config}\nmaintenance.mode = reviewed\n")
cli(2 --config-file "${CPRAG_WORK_DIR}/reviewed.conf" --access plan maintain plan --source "${source}")
# Guided human maintenance must forward the selector and show it before approval.
sql(before ".dump")
file(WRITE "${CPRAG_WORK_DIR}/decline.txt" "n\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" maintain "--source=${source}"
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/decline.txt"
    RESULT_VARIABLE guided_status OUTPUT_VARIABLE guided_out ERROR_VARIABLE guided_err TIMEOUT 30)
string(FIND "${guided_out}" "${source}" shown_source)
if(NOT guided_status EQUAL 9 OR shown_source LESS 0)
    message(FATAL_ERROR "Guided maintenance did not preview the selected source: ${guided_out}${guided_err}")
endif()
sql(after ".dump")
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Declining source maintenance changed the library")
endif()
# MCP receives the same selector through canonical command metadata.
file(WRITE "${CPRAG_WORK_DIR}/mcp.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_maintain_plan\",\"arguments\":{\"source\":\"${source}\"}}}\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --access read,plan --format json serve mcp
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/mcp.jsonl"
    RESULT_VARIABLE mcp_status OUTPUT_VARIABLE mcp_out ERROR_VARIABLE mcp_err TIMEOUT 30)
if(NOT mcp_status EQUAL 0)
    message(FATAL_ERROR "Source maintenance MCP request failed: ${mcp_out}${mcp_err}")
endif()
string(JSON response GET "${mcp_out}" result structuredContent)
getplan()
string(JSON policy GET "${plan}" action window_policy)
string(JSON mcp_source GET "${policy}" source_id)
if(NOT mcp_source STREQUAL source)
    message(FATAL_ERROR "MCP dropped the source selector")
endif()
file(WRITE "${CPRAG_WORK_DIR}/mcp.jsonl" "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"rag_maintain_plan\",\"arguments\":{\"source\":\"${source}\",\"initial_extraction_only\":true}}}\n")
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" --access read,plan --format json serve mcp
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/mcp.jsonl"
    RESULT_VARIABLE mcp_status OUTPUT_VARIABLE mcp_out ERROR_VARIABLE mcp_err TIMEOUT 30)
if(NOT mcp_status EQUAL 0)
    message(FATAL_ERROR "First-pass MCP request failed: ${mcp_out}${mcp_err}")
endif()
string(JSON response GET "${mcp_out}" result structuredContent)
getplan()
string(JSON policy GET "${plan}" action window_policy)
string(JSON mcp_initial GET "${policy}" initial_extraction_only)
if(NOT mcp_initial EQUAL 1)
    message(FATAL_ERROR "MCP dropped the first-pass selector")
endif()
execute_process(COMMAND "${CPRAG_NATIVE_APPLICATION}" maintain "--source=${source}" --initial-extraction-only
    WORKING_DIRECTORY "${CPRAG_WORK_DIR}" INPUT_FILE "${CPRAG_WORK_DIR}/decline.txt"
    RESULT_VARIABLE guided_status OUTPUT_VARIABLE guided_out ERROR_VARIABLE guided_err TIMEOUT 30)
string(FIND "${guided_out}" "First concept review for current chunks" shown_mode)
if(NOT guided_status EQUAL 9 OR shown_mode LESS 0)
    message(FATAL_ERROR "Guided maintenance did not preview the first-pass scope: ${guided_out}${guided_err}")
endif()
# A first-pass extraction window uses ingested current chunks but excludes
# alias follow-ups, embedding repair and chunks with an earlier review result.
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/initial-only")
file(COPY "${CPRAG_WORK_DIR}/library" DESTINATION "${CPRAG_WORK_DIR}/initial-only")
set(initial_library "${CPRAG_WORK_DIR}/initial-only/library")
set(database "${initial_library}/library.sqlite")
sql(seeded "INSERT INTO revision_chunks(revision_chunk_id,revision_id,ordinal,normalized_start,normalized_end,content_id,continuity_key,parser_version,evidence_class,visible_from_generation) SELECT 'initial-only-new',revision_id,10000,normalized_start,normalized_end,content_id,'initial-only-new',parser_version,evidence_class,visible_from_generation FROM revision_chunks WHERE revision_chunk_id='${target_chunk}'; INSERT INTO maintenance_tasks(task_id,kind,subject_type,subject_id,evidence_fingerprint,policy_fingerprint,evidence_json,question,state,priority,created_epoch,updated_epoch) VALUES('initial-alias','alias-follow-up:fixture','chunk','initial-only-new','fixture','${knowledge}','{}','Alias follow-up','pending',999999,1,1);")
cli(0 --library "${initial_library}" --access plan maintain plan --source "${source}" --minutes 5)
string(JSON ordinary_selection GET "${response}" records 1 fields selection)
if(NOT ordinary_selection MATCHES "initial-alias")
    message(FATAL_ERROR "Ordinary source maintenance no longer admits alias follow-up work: ${ordinary_selection}")
endif()
sql(before ".dump")
cli(0 --library "${initial_library}" --access plan maintain plan --source "${source}" --initial-extraction-only --minutes 5)
getplan()
string(JSON initial_policy GET "${plan}" action window_policy)
string(JSON initial_mode GET "${initial_policy}" initial_extraction_only)
string(JSON initial_source GET "${initial_policy}" source_id)
if(NOT initial_mode EQUAL 1 OR NOT initial_source STREQUAL source)
    message(FATAL_ERROR "First-pass scope was not frozen in the reviewed plan")
endif()
sql(after ".dump")
if(NOT before STREQUAL after)
    message(FATAL_ERROR "First-pass maintenance planning mutated the library")
endif()
set(initial_plan "${plan}")
set(initial_digest "${digest}")
cli(0 --library "${initial_library}" --access curate maintain apply --plan-json "${initial_plan}" --expect-digest "${initial_digest}")
string(JSON initial_job GET "${response}" records 0 fields job_id)
sql(first_wave "SELECT count(*)||':'||coalesce(sum(i.item_type='improve-extraction' AND json_extract(i.input_json,'$.revision_chunk_id')='initial-only-new'),0) FROM job_items i WHERE i.job_id='${initial_job}';")
sql(alias_wave "SELECT count(*) FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id WHERE m.task_id='initial-alias' AND i.job_id='${initial_job}';")
if(NOT first_wave STREQUAL "1:1" OR NOT alias_wave EQUAL 0)
    message(FATAL_ERROR "First-pass window admitted follow-ups, embeddings or already reviewed chunks: ${first_wave}, ${alias_wave}")
endif()
sql(settled "UPDATE job_items SET state='processed' WHERE job_id='${initial_job}' AND state='queued';")
cli(0 --library "${initial_library}" --access curate maintain apply --plan-json "${initial_plan}" --expect-digest "${initial_digest}")
sql(first_complete "SELECT w.state||':'||r.state FROM maintenance_windows w JOIN maintenance_runs r ON r.run_id=w.run_id WHERE w.job_id='${initial_job}';")
if(NOT first_complete STREQUAL "complete:complete")
    message(FATAL_ERROR "First-pass window did not close after the selected result: ${first_complete}")
endif()
cli(0 --library "${initial_library}" --access plan maintain plan --source "${source}" --initial-extraction-only --minutes 6)
getplan()
cli(0 --library "${initial_library}" --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON repeat_job GET "${response}" records 0 fields job_id)
sql(repeat_items "SELECT count(*) FROM job_items WHERE job_id='${repeat_job}';")
sql(calls "SELECT count(*) FROM provider_runs;")
if(NOT repeat_items EQUAL 0 OR NOT calls EQUAL 0)
    message(FATAL_ERROR "First-pass mode repeated a completed result or called a provider")
endif()
cli(2 --library "${initial_library}" --access plan maintain plan --initial-extraction-only)
cli(2 --library "${initial_library}" --access plan maintain plan --source "${source}" --initial-extraction-only --embeddings-only)
set(database "${CPRAG_WORK_DIR}/library/library.sqlite")
sql(restored "INSERT INTO revision_chunk_embeddings SELECT revision_chunk_id,'fixture-'||revision_chunk_id,visible_from_generation,NULL FROM revision_chunks WHERE revision_chunk_id LIKE '000-old-%';")
cli(0 --access plan maintain plan)
getplan()
cli(0 --access curate maintain apply --plan-json "${plan}" --expect-digest "${digest}")
string(JSON resumed_job GET "${response}" records 0 fields job_id)
sql(resumed "SELECT count(*) FROM maintenance_task_items m JOIN job_items i ON i.item_id=m.item_id WHERE m.task_id='${old_task}' AND i.job_id='${resumed_job}' AND i.state='queued';")
sql(calls "SELECT count(*) FROM provider_runs;")
if(NOT resumed EQUAL 1 OR NOT calls EQUAL 0)
    message(FATAL_ERROR "Ordinary backlog did not resume or fixture called a provider")
endif()
file(WRITE "${CPRAG_WORK_DIR}/result.txt" "Source-scoped automatic maintenance: unscoped rank control, frozen preview/window scope, selection before census page and dispatch wave, complete source coverage across checkpoints, source-local completion, old-work preservation/resumption, MCP parity, zero provider calls.\n")
