# Public Test 2 acceptance: durable results survive optional housekeeping and
# worker-finalization faults; the same command repairs only unfinished indexing.
find_program(sqlite_cli sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
function(call_cli)
    execute_process(COMMAND ${cli} ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 45)
    file(APPEND "${cell}/commands.log" "${ARGN}\nstatus=${status}\n${output}${errors}\n")
    set(last_status "${status}" PARENT_SCOPE)
    set(last_output "${output}" PARENT_SCOPE)
endfunction()
function(run_cli)
    call_cli(${ARGN})
    if(NOT last_status EQUAL 0)
        message(FATAL_ERROR "Test 2 setup failed: ${ARGN}\n${last_output}")
    endif()
    set(last_output "${last_output}" PARENT_SCOPE)
endfunction()
function(sql output query)
    execute_process(COMMAND "${sqlite_cli}" -cmd ".timeout 5000" "${library}/library.sqlite" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE result ERROR_VARIABLE errors OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Test 2 SQL failed: ${errors}")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
function(expect actual expected label)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(SEND_ERROR "${case}: ${label}: expected '${expected}', got '${actual}'")
    endif()
endfunction()
set(cases normal optional-refresh optional-delete worker-exit)
if(DEFINED CPRAG_CASE)
    set(cases "${CPRAG_CASE}")
endif()
foreach(case IN LISTS cases)
    set(cell "${CPRAG_WORK_DIR}/${case}")
    set(library "${cell}/library")
    set(CPRAG_FIXTURE_SOURCE "${cell}/source")
    file(MAKE_DIRECTORY "${CPRAG_FIXTURE_SOURCE}")
    foreach(n RANGE 1 2)
        file(WRITE "${CPRAG_FIXTURE_SOURCE}/${n}.txt" "BillingService depends on CustomerDatabase.\nAgain, BillingService depends on CustomerDatabase. Document ${n}.\n")
    endforeach()
    set(CPRAG_FIXTURE_GLOSSARY "${cell}/glossary.tsv")
    file(WRITE "${CPRAG_FIXTURE_GLOSSARY}" "format\tcrexx-rag.glossary/1\n")
    set(CPRAG_FIXTURE_PORT 19053)
    file(READ "${CPRAG_CONFIG_TEMPLATE}" config)
    string(CONFIGURE "${config}" config @ONLY)
    string(REPLACE "budget.item_limit = 2" "budget.item_limit = 4" config "${config}")
    string(REPLACE "budget.model_calls = 2" "budget.model_calls = 4" config "${config}")
    string(REPLACE "budget.codex_turns = 1" "budget.codex_turns = 2" config "${config}")
    string(REPLACE "budget.output_tokens = 1024" "budget.output_tokens = 8192" config "${config}")
    string(REPLACE "budget.input_tokens = 65536" "budget.input_tokens = 131072" config "${config}")
    string(APPEND config "\nworker.max_restarts = 0\n")
    file(WRITE "${cell}/test.conf" "${config}")
    file(WRITE "${cell}/codex.sh" "#!/bin/sh\nexec /bin/sh '${CPRAG_CODEX_FIXTURE}' \"\$@\"\n")
    file(CHMOD "${cell}/codex.sh" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    set(worker_executable "${CPRAG_NATIVE_APPLICATION}")
    if(case STREQUAL "worker-exit")
        # Execute the real worker to completion, then give its controller an
        # unsuccessful OS-process completion. No product test hook is needed.
        set(worker_executable "${cell}/worker-exit.sh")
        file(WRITE "${worker_executable}" "#!/bin/sh\n'${CPRAG_NATIVE_APPLICATION}' \"\$@\"\nresult=\$?\nif [ \"\$result\" -eq 0 ] && [ ! -e '${cell}/failed-once' ]; then : >'${cell}/failed-once'; exit 75; fi\nexit \"\$result\"\n")
        file(CHMOD "${worker_executable}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    endif()
    set(cli "${CMAKE_COMMAND}" -E env "CPRAG_FIXTURE_GEMINI_KEY=synthetic-product-gemini-key"
        "CREXXRAG_CODEX=${cell}/codex.sh" "CREXXRAG_CODEX_FIXTURE_MODE=extraction"
        "CREXXRAG_CODEX_FIXTURE_FAILURE=${case}" "CREXXRAG_CODEX_FIXTURE_LOG=${cell}/methods.log"
        "CREXXRAG_SELF=${worker_executable}" "${CPRAG_NATIVE_APPLICATION}"
        --library "${library}" --config-file "${cell}/test.conf"
        --profile it-architecture-profile --format json --progress plain)
    run_cli(--access admin library init)
    run_cli(--access plan ingest plan --source-set architecture-docs)
    string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
    string(JSON digest GET "${last_output}" records 0 fields digest)
    run_cli(--access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
    string(JSON job GET "${last_output}" records 0 fields job_id)
    # Embeddings first so every injected failure can test successful publication.
    sql(ignored "UPDATE job_items SET priority=CASE item_type WHEN 'embedding' THEN 200 ELSE 100 END;")
    execute_process(COMMAND /bin/sh -c
        "( \"$1\" \"$2\" 2 product-ingestion; printf '%s' $? >\"$5\" ) >\"$3\" 2>\"$4\" &"
        test2-completion "${CPRAG_LOOPBACK}" "${CPRAG_FIXTURE_PORT}" "${cell}/server.out" "${cell}/server.err" "${cell}/server.status")
    set(ready FALSE)
    foreach(poll RANGE 1 200)
        if(EXISTS "${cell}/server.out")
            file(READ "${cell}/server.out" output)
            if(output MATCHES "READY ${CPRAG_FIXTURE_PORT}")
                set(ready TRUE)
                break()
            endif()
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.02)
    endforeach()
    if(NOT ready)
        message(FATAL_ERROR "Test 2 fixture not ready")
    endif()
    call_cli(--access control job run "${job}" --count 1 --poll-ms 20)
    set(expected 0)
    if(case STREQUAL "worker-exit")
        set(expected 8)
    endif()
    expect("${last_status}" "${expected}" "job outcome separates required work from optional cleanup")
    sql(state "SELECT (SELECT count(*) FROM job_items WHERE state='processed')||':'||(SELECT count(*) FROM provider_runs WHERE outcome='succeeded')||':'||(SELECT count(*) FROM vector_generations WHERE state='published' AND row_count=2)||':'||(SELECT sum(reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns) FROM jobs);")
    expect("${state}" "4:4:1:0" "completed work, index and settled usage")
    sql(before "SELECT * FROM attempts ORDER BY attempt_id; SELECT * FROM provider_runs ORDER BY provider_run_id;")
    call_cli(--access control job run "${job}" --count 1 --poll-ms 20)
    expect("${last_status}" "0" "ordinary completion retry")
    sql(after "SELECT * FROM attempts ORDER BY attempt_id; SELECT * FROM provider_runs ORDER BY provider_run_id;")
    expect("${after}" "${before}" "retry preserves receipts and makes no calls")
    call_cli(--access diagnose library verify)
    expect("${last_status}" "0" "integrity")
    file(READ "${cell}/server.status" server_status)
    expect("${server_status}" "0" "two embedding calls")
endforeach()
