# Native, zero-network recovery gates using the managed-process protocol fixture.
foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_CODEX_FIXTURE CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(sqlite_cli sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
file(WRITE "${CPRAG_WORK_DIR}/source/architecture.txt"
    "BillingService depends on CustomerDatabase.\n"
    "Again, BillingService depends on CustomerDatabase.\n"
    "Bill-\ningService depends on CustomerDatabase.\n")
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_PORT 1)
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}"
    "format\tcrexx-rag.glossary/1\n"
    "concept\tBillingService\tapplication-component\tBilling Service\n"
    "concept\tCustomerDatabase\tdata-store\tCustomer DB\n")
file(READ "${CPRAG_CONFIG_TEMPLATE}" config)
string(CONFIGURE "${config}" config @ONLY)
string(REPLACE "provider.codex-extract.max_attempts = 2" "provider.codex-extract.max_attempts = 10" config "${config}")
string(APPEND config "\nworker.max_restarts = 2\nworker.restart_backoff_ms = 10\n")
file(WRITE "${CPRAG_WORK_DIR}/recovery.conf" "${config}")

function(run_cli expected)
    execute_process(COMMAND ${cli} ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 90)
    file(APPEND "${cell}/commands.log" "${ARGN}\nstatus=${status}\n${output}${errors}\n")
    if(NOT "${status}" MATCHES "^[0-9]+$")
        message(FATAL_ERROR "Recovery command did not terminate normally: ${status} ${errors}")
    endif()
    if(expected STREQUAL "ok" AND NOT status EQUAL 0)
        message(FATAL_ERROR "Recovery command failed: ${ARGN}\n${output}${errors}")
    elseif(expected STREQUAL "error" AND status EQUAL 0)
        message(FATAL_ERROR "Recovery command unexpectedly succeeded: ${ARGN}\n${output}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
    set(last_errors "${errors}" PARENT_SCOPE)
endfunction()

function(sql query expected)
    execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0 OR NOT output STREQUAL "${expected}")
        message(FATAL_ERROR "Recovery SQL assertion failed: ${query}\nExpected: ${expected}\nActual: ${output}\n${errors}")
    endif()
endfunction()

set(recovery_cases receipt-write preflight-once preflight-always preflight-disabled turn-disconnect admission-release citation-feedback citation-exhausted)
if(DEFINED CPRAG_CASE)
    set(recovery_cases "${CPRAG_CASE}")
endif()
foreach(case IN LISTS recovery_cases)
    set(cell "${CPRAG_WORK_DIR}/${case}")
    set(library "${cell}/library")
    file(MAKE_DIRECTORY "${cell}")
    set(wrapper "${cell}/codex-fixture.sh")
    file(WRITE "${wrapper}" "#!/bin/sh\nexec /bin/sh '${CPRAG_CODEX_FIXTURE}' \"\$@\"\n")
    file(CHMOD "${wrapper}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    set(failure_mode "${case}")
    set(case_config "${CPRAG_WORK_DIR}/recovery.conf")
    if(case STREQUAL "preflight-disabled")
        set(failure_mode preflight-always)
        string(REPLACE "worker.max_restarts = 2" "worker.max_restarts = 0" disabled_config "${config}")
        set(case_config "${cell}/recovery.conf")
        file(WRITE "${case_config}" "${disabled_config}")
    elseif(case MATCHES "^citation-" OR case STREQUAL "turn-disconnect")
        string(REPLACE "budget.codex_turns = 1" "budget.codex_turns = 2" correction_config "${config}")
        string(REPLACE "budget.output_tokens = 1024" "budget.output_tokens = 8192" correction_config "${correction_config}")
        set(case_config "${cell}/recovery.conf")
        file(WRITE "${case_config}" "${correction_config}")
    endif()
    set(cli "${CMAKE_COMMAND}" -E env
        "CREXXRAG_CODEX=${wrapper}" "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}"
        "CREXXRAG_CODEX_FIXTURE_MODE=extraction" "CREXXRAG_CODEX_FIXTURE_FAILURE=${failure_mode}"
        "CREXXRAG_CODEX_FIXTURE_ONCE=${cell}/failed-once"
        "CREXXRAG_CODEX_FIXTURE_LOG=${cell}/methods.log"
        "CREXXRAG_CODEX_FIXTURE_STATE_FILE=${cell}/external-state"
        "${CPRAG_NATIVE_APPLICATION}" --library "${library}"
        --config-file "${case_config}" --profile it-architecture-profile
        --format json --progress plain)
    run_cli(ok --access admin library init)
    run_cli(ok --access plan ingest plan --source-set architecture-docs)
    string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
    string(JSON digest GET "${last_output}" records 0 fields digest)
    run_cli(ok --access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
    string(JSON job GET "${last_output}" records 0 fields job_id)
    sql("UPDATE job_items SET priority=CASE item_type WHEN 'claim-extraction' THEN 200 ELSE 100 END,retry_at=CASE item_type WHEN 'embedding' THEN unixepoch()+3600 ELSE retry_at END;" "")
    if(case STREQUAL "admission-release")
        sql("CREATE TRIGGER fail_release BEFORE UPDATE ON provider_admissions WHEN NEW.outcome IN('succeeded','failed') BEGIN SELECT RAISE(ABORT,'injected admission release failure'); END;" "")
    endif()
    if(case STREQUAL "receipt-write")
        sql("CREATE TRIGGER reject_receipt BEFORE INSERT ON job_events WHEN NEW.event_type='provider-response' BEGIN SELECT RAISE(ABORT,'injected response persistence failure'); END;" "")
    endif()
    set(limit 0)
    set(expected error)
    if(case STREQUAL "preflight-once")
        set(limit 1)
        set(expected ok)
    elseif(case MATCHES "^citation-")
        set(limit 1)
        set(expected ok)
    elseif(case STREQUAL "admission-release")
        set(limit 1)
    endif()
    if(case STREQUAL "receipt-write")
        set(expected any)
        set(limit 1)
    endif()
    set(poll_limit 0)
    if(case STREQUAL "preflight-always")
        set(poll_limit 2000)
    endif()
    if(case STREQUAL "turn-disconnect")
        set(expected ok)
        set(poll_limit 10)
    endif()
    run_cli(${expected} --access control worker start --count 1 --job "${job}" --max-items "${limit}" --poll-ms 20 --max-polls "${poll_limit}")
    sql("SELECT count(*) FROM attempts WHERE outcome='running';" "0")
    sql("SELECT reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns FROM jobs;" "0")
    if(case STREQUAL "receipt-write")
        # Actual returned Codex output is durable before the event write fails.
        # It must survive, not be overwritten with a validation diagnostic.
        sql("SELECT count(*) FROM provider_runs WHERE outcome='completed-unsettled' AND json_extract(recovery_json,'$.content') LIKE '%BillingService%';" "1")
        sql("SELECT input_tokens||':'||output_tokens||':'||cost_microunits FROM provider_runs;" "20000:4:-1")
        sql("SELECT count(*) FROM job_events WHERE event_type='provider-response' OR event_type LIKE 'settlement-receipt:%';" "0")
        sql("SELECT count(DISTINCT attempt_id) FROM job_events WHERE event_type='provider-outcome-uncertain';" "1")
        sql("SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state='dead_letter';" "1")
        sql("SELECT count(*) FROM claims;" "0")
        execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite"
            "SELECT item_id FROM job_items WHERE item_type='claim-extraction';"
            OUTPUT_VARIABLE item OUTPUT_STRIP_TRAILING_WHITESPACE)
        sql("DROP TRIGGER reject_receipt;" "")
        # Automatic restart does not redo the missing response.
        run_cli(ok --access control job run "${job}" --max-polls 1 --poll-ms 20)
        sql("SELECT count(*) FROM attempts;" "1")
        run_cli(ok --access control job pause "${job}")
        run_cli(ok --access control job retry "${job}" --item "${item}" --reason "receipt store repaired")
        if(NOT last_output MATCHES "job-paused")
            message(FATAL_ERROR "Explicit retry did not respect the operator pause: ${last_output}")
        endif()
        file(WRITE "${cell}/external-state" "unavailable\n")
        run_cli(ok --access diagnose job reconcile "${job}" --item "${item}")
        string(JSON receipt_digest GET "${last_output}" records 0 fields digest)
        run_cli(ok --access control job reconcile "${job}" --item "${item}" --apply --expect-digest "${receipt_digest}")
        run_cli(ok --access control job reconcile "${job}" --item "${item}" --apply --expect-digest "${receipt_digest}")
        run_cli(ok --access control job run "${job}" --max-items 1 --poll-ms 20)
        sql("SELECT count(*) FROM provider_runs WHERE outcome='succeeded' AND input_tokens=20000 AND output_tokens=4;" "1")
        sql("SELECT count(*) FROM job_events WHERE event_type LIKE 'settlement-receipt:%';" "1")
        sql("SELECT count(*) FROM job_events WHERE event_type='provider-intent';" "1")
        sql("SELECT count(*) FROM claims;" "1")
        sql("SELECT count(*) FROM attempts a JOIN job_events e USING(attempt_id) WHERE e.event_type='provider-intent' AND a.outcome='expired' AND a.provider_run_id IS NOT NULL;" "1")
        sql("SELECT reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns FROM jobs;" "0")
        file(READ "${cell}/methods.log" methods)
        string(REGEX MATCHALL "turn/start" calls "${methods}")
        list(LENGTH calls call_count)
        if(NOT call_count EQUAL 1)
            message(FATAL_ERROR "Receipt recovery repeated generation: ${methods}")
        endif()
        continue()
    endif()
    if(case STREQUAL "preflight-once")
        if(NOT last_output MATCHES "\"workers_restarted\":1")
            message(FATAL_ERROR "Replacement was not reported: ${last_output}")
        endif()
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='succeeded';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='failed';" "0")
        sql("SELECT count(*) FROM attempts;" "2")
        sql("SELECT count(*) FROM job_items WHERE item_type='embedding' AND state='queued';" "1")
        # A stale heartbeat alone cannot revoke live PID or remote ownership.
        execute_process(COMMAND /bin/sh -c "echo \"$PPID\""
            OUTPUT_VARIABLE live_pid OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(NOT live_pid MATCHES "^[1-9][0-9]*$")
            message(FATAL_ERROR "Could not identify the live fixture controller")
        endif()
        sql("UPDATE runtime_instances SET pid=${live_pid},state='idle',heartbeat_at=unixepoch()-3600 WHERE kind='controller';" "")
        run_cli(ok --access control worker prune --stale-seconds 1)
        sql("SELECT count(*) FROM runtime_instances WHERE kind='controller';" "1")
        run_cli(error --access control job run "${job}" --max-polls 1)
        sql("SELECT count(*) FROM attempts;" "2")
        sql("UPDATE runtime_instances SET pid=99999999,host_id='remote-fixture-host' WHERE kind='controller';" "")
        run_cli(ok --access control worker prune --stale-seconds 1)
        sql("SELECT count(*) FROM runtime_instances WHERE kind='controller';" "1")
        sql("UPDATE runtime_instances SET state='stopped' WHERE kind='controller';" "")
        run_cli(ok --access control worker prune --stale-seconds 1)
        set(original_cli "${cli}")
        string(REPLACE "provider.codex-extract.model = default" "provider.codex-extract.model = incompatible-model" mismatch "${config}")
        file(WRITE "${cell}/mismatch.conf" "${mismatch}")
        string(REPLACE "${case_config}" "${cell}/mismatch.conf" cli "${original_cli}")
        run_cli(error --access control job run "${job}" --max-polls 1)
        sql("SELECT count(*) FROM attempts;" "2")
        sql("SELECT count(*) FROM runtime_instances;" "0")
        string(REPLACE "worker.processes = 1" "worker.processes = 2" count_config "${config}")
        file(WRITE "${cell}/count.conf" "${count_config}")
        string(REPLACE "${case_config}" "${cell}/count.conf" cli "${original_cli}")
        run_cli(ok --access control job run "${job}" --count 2 --max-polls 1 --poll-ms 20)
        sql("SELECT count(*) FROM attempts;" "2")
        sql("SELECT count(*) FROM provider_runs;" "1")
        set(cli "${original_cli}")
    elseif(case STREQUAL "preflight-always")
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "2")
        sql("SELECT count(*) FROM attempts;" "3")
        sql("SELECT count(*) FROM provider_runs;" "0")
        # A fresh controller respects the recent burst and shared cooldown;
        # its one bounded poll defers without another provider preflight.
        sql("DELETE FROM runtime_instances;" "")
        sql("UPDATE provider_cooldowns SET not_before_epoch=unixepoch()+3600 WHERE provider_id='codex-extract';" "")
        run_cli(ok --access control worker start --count 1 --job "${job}" --poll-ms 20 --max-polls 1)
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "2")
        sql("SELECT count(*) FROM attempts;" "4")
        sql("SELECT count(*) FROM provider_runs;" "0")
        sql("SELECT failure_count FROM provider_cooldowns WHERE provider_id='codex-extract';" "3")
    elseif(case MATCHES "^citation-")
        sql("SELECT count(*) FROM job_events WHERE event_type='citation-correction-requested' AND instr(message,'field=relationships[0].evidence_quote')>0 AND instr(message,'BillingService')>0 AND instr(message,'CustomerDatabase')>0;" "1")
        sql("INSERT INTO provider_cooldowns(provider_id,model,not_before_epoch,failure_count,updated_epoch) SELECT provider_id,model,unixepoch()+3600,1,unixepoch() FROM provider_runs LIMIT 1;" "")
        run_cli(ok --access control worker start --count 1 --job "${job}" --max-polls 1 --poll-ms 20)
        sql("SELECT count(*) FROM provider_runs;" "1")
        sql("SELECT state FROM job_items WHERE item_type='claim-extraction';" "queued")
        sql("SELECT count(*) FROM attempts WHERE outcome='cancelled';" "1")
        sql("DELETE FROM provider_cooldowns;" "")
        sql("UPDATE job_items SET retry_at=unixepoch() WHERE item_type='claim-extraction';" "")
        run_cli(ok --access control worker start --count 1 --job "${job}" --max-items 1 --poll-ms 20)
        set(expected_outcome correction-success)
        if(case STREQUAL "citation-exhausted")
            set(expected_outcome correction-failed)
        endif()
        run_cli(ok --access read job items "${job}" --outcome "${expected_outcome}")
        string(JSON selected GET "${last_output}" records 0 fields detail)
        string(JSON selected_item GET "${selected}" item_id)
        run_cli(ok --access read job attempts "${job}" --item "${selected_item}")
        string(JSON attempt_count LENGTH "${last_output}" records)
        if(NOT attempt_count EQUAL 3)
            message(FATAL_ERROR "Correction search lost original failure or uncalled deferral")
        endif()
        execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite"
            "SELECT attempt_id FROM job_events WHERE item_id='${selected_item}' AND event_type='provider-request' ORDER BY event_id DESC LIMIT 1;"
            OUTPUT_VARIABLE corrected_attempt OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        set(correction_input "")
        set(cursor 0)
        foreach(page RANGE 1 32)
            run_cli(ok --access read job inspect "${selected_item}" --attempt "${corrected_attempt}" --section request --cursor "${cursor}")
            string(JSON text GET "${last_output}" records 0 fields text)
            string(APPEND correction_input "${text}")
            string(JSON cursor GET "${last_output}" records 0 fields next_cursor)
            if(cursor STREQUAL "")
                break()
            endif()
        endforeach()
        if(NOT cursor STREQUAL "" OR NOT correction_input MATCHES "assistant" OR NOT correction_input MATCHES "field=relationships")
            message(FATAL_ERROR "Original correction input and validation feedback were not retained")
        endif()
        if(case STREQUAL "citation-exhausted")
            sql("SELECT count(*) FROM maintenance_tasks WHERE required_capability='advanced-reasoning' AND state='unresolved';" "1")
            sql("SELECT count(*) FROM job_events WHERE event_type='extraction-review-required';" "1")
            sql("SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state='dead_letter';" "1")
            sql("SELECT count(*) FROM provider_runs;" "2")
            # Ingestion already creates local candidates. Rejected provider
            # output must add neither provider discoveries nor typed claims.
            sql("SELECT count(*) FROM candidate_mentions WHERE extractor_version='provider-discovery-v2';" "0")
            sql("SELECT count(*) FROM claims;" "0")
            sql("SELECT count(*) FROM job_events WHERE event_type='citation-correction-requested' AND instr(message,'field=mentions[0].evidence_quote')>0 AND instr(message,'field=relationships[0].evidence_quote')>0;" "1")
            run_cli(ok --access read maintain tasks --capability advanced-reasoning)
            string(JSON task_detail GET "${last_output}" records 0 fields detail)
            string(JSON task_id GET "${task_detail}" task_id)
            run_cli(ok --access read job items --all --task "${task_id}")
            string(JSON original_item GET "${last_output}" records 0 fields id)
            if(NOT original_item STREQUAL selected_item)
                message(FATAL_ERROR "Advanced task does not link to its original failed extraction")
            endif()
            continue()
        endif()
        sql("SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state='processed';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='failed';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='succeeded';" "1")
        sql("SELECT count(*) FROM job_events WHERE event_type='citation-correction-requested';" "1")
        file(READ "${cell}/methods.log" methods)
        if(NOT methods MATCHES "correction-feedback-checked")
            message(FATAL_ERROR "Correction did not receive precise feedback")
        endif()
    elseif(case STREQUAL "preflight-disabled")
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "0")
        sql("SELECT count(*) FROM attempts;" "1")
        sql("SELECT count(*) FROM provider_runs;" "0")
    elseif(case STREQUAL "turn-disconnect")
        sql("SELECT state FROM jobs;" "running")
        sql("SELECT count(DISTINCT attempt_id) FROM job_events WHERE event_type='provider-outcome-uncertain';" "1")
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE external_turn_id='fixture-turn' AND outcome='running';" "1")
        sql("SELECT input_tokens||':'||output_tokens FROM provider_runs;" "7:2")
        # A later bounded launch leaves the same uncertain item held. Pause
        # explicitly before testing the operator's reviewed reconciliation.
        run_cli(ok --access control worker start --count 1 --job "${job}" --max-items 1 --poll-ms 20 --max-polls 5)
        run_cli(ok --access control job pause "${job}")
        sql("SELECT count(*) FROM provider_runs;" "1")
        execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite"
            "SELECT item_id FROM job_items WHERE item_type='claim-extraction';"
            OUTPUT_VARIABLE item OUTPUT_STRIP_TRAILING_WHITESPACE)
        # Inspection cannot cancel a turn, consume a generation, or mutate SQL.
        foreach(observed IN ITEMS inProgress missing unavailable wrong-thread)
            file(WRITE "${cell}/external-state" "${observed}\n")
            run_cli(ok --access diagnose job reconcile "${job}" --item "${item}")
            string(JSON held_digest GET "${last_output}" records 0 fields digest)
            run_cli(error --access control job reconcile "${job}" --item "${item}" --apply --expect-digest "${held_digest}")
            sql("SELECT count(*) FROM job_events WHERE event_type IN('provider-reconciled','provider-response');" "0")
            sql("SELECT state FROM jobs;" "paused")
        endforeach()
        set(held_library "${library}")
        set(held_cli "${cli}")
        # Reset must also reach exact-outcome reconciliation's paid-attempt
        # ceiling, without releasing the unknown outcome by itself.
        set(library "${cell}/reset-reconcile/library")
        file(MAKE_DIRECTORY "${cell}/reset-reconcile")
        file(COPY "${held_library}" DESTINATION "${cell}/reset-reconcile")
        string(REPLACE "${held_library}" "${library}" cli "${held_cli}")
        sql("WITH RECURSIVE n(i) AS(VALUES(1) UNION ALL SELECT i+1 FROM n WHERE i<9) INSERT INTO provider_runs(provider_run_id,config_snapshot_id,provider_id,model,request_hash,outcome,started_at,completed_at,cost_microunits) SELECT 'reset-prior-'||n.i,p.config_snapshot_id,p.provider_id,p.model,p.request_hash,'failed','historic','historic',0 FROM n CROSS JOIN provider_runs p; INSERT INTO attempts(attempt_id,item_id,worker_id,fence,input_hash,validation_state,outcome,provider_run_id,started_at,completed_at) SELECT p.provider_run_id,'${item}','prior-worker',0,'prior-input','timeout','failed',p.provider_run_id,'historic','historic' FROM provider_runs p WHERE p.provider_run_id LIKE 'reset-prior-%';" "")
        run_cli(ok --access control job reset-retries "${job}")
        sql("SELECT count(*) FROM provider_runs;" "10")
        sql("SELECT count(*) FROM job_events WHERE event_type='provider-reconciled';" "0")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='running';" "1")
        file(WRITE "${cell}/external-state" "interrupted\n")
        run_cli(ok --access diagnose job reconcile "${job}" --item "${item}")
        string(JSON reset_digest GET "${last_output}" records 0 fields digest)
        run_cli(ok --access control job reconcile "${job}" --item "${item}" --apply --expect-digest "${reset_digest}")
        sql("SELECT state FROM job_items WHERE item_id='${item}';" "queued")
        sql("SELECT count(*) FROM attempts;" "10")
        sql("SELECT count(*) FROM provider_runs;" "10")
        sql("SELECT sum(input_tokens)||':'||sum(output_tokens) FROM provider_runs;" "7:2")
        set(library "${held_library}")
        set(cli "${held_cli}")
        foreach(terminal IN ITEMS interrupted completed completed-local completed-receipt)
            set(library "${cell}/${terminal}/library")
            file(MAKE_DIRECTORY "${cell}/${terminal}")
            file(COPY "${held_library}" DESTINATION "${cell}/${terminal}")
            string(REPLACE "${held_library}" "${library}" cli "${held_cli}")
            if(terminal STREQUAL "completed-local")
                # Earlier crash boundary: raw output is durable, receipt is not.
                sql("ATTACH DATABASE '${cell}/completed/library/library.sqlite' AS prior; UPDATE provider_runs SET outcome='completed-unsettled',recovery_json=(SELECT json_object('request_id',json_extract(message,'$.request_id'),'content',json_extract(message,'$.content')) FROM prior.job_events WHERE event_type='provider-response'); DETACH DATABASE prior;" "")
            endif()
            if(terminal STREQUAL "completed-receipt")
                # Reproduce completion persisted before accounting: reuse a
                # product-created receipt, retaining its original finish field.
                sql("ATTACH DATABASE '${cell}/completed/library/library.sqlite' AS prior; INSERT INTO job_events(job_id,item_id,attempt_id,event_type,message,occurred_at) SELECT job_id,item_id,attempt_id,event_type,json_set(message,'$.finish','stop'),occurred_at FROM prior.job_events WHERE event_type='provider-response'; UPDATE provider_runs SET outcome='completed-unsettled',recovery_json=(SELECT json_object('request_id',json_extract(message,'$.request_id'),'content',json_extract(message,'$.content')) FROM job_events WHERE event_type='provider-response'); DETACH DATABASE prior;" "")
            endif()
            file(WRITE "${cell}/external-state" "${terminal}\n")
            run_cli(ok --access diagnose job reconcile "${job}" --item "${item}")
            string(JSON reconcile_digest GET "${last_output}" records 0 fields digest)
            set(original_reconcile_cli "${cli}")
            if(terminal STREQUAL "interrupted" OR terminal STREQUAL "completed")
                # Original-config inspection above is the positive control.
                # Later source and budget edits must not block observation of
                # an existing turn or replace its original attempt ceiling.
                string(REPLACE "source.architecture-docs.include = **/*.txt"
                    "source.architecture-docs.include = architecture.txt" changed_config "${correction_config}")
                string(REPLACE "budget.item_limit = 2" "budget.item_limit = 3" changed_config "${changed_config}")
                string(REPLACE "provider.codex-extract.max_attempts = 10"
                    "provider.codex-extract.max_attempts = 1" changed_config "${changed_config}")
                file(WRITE "${cell}/${terminal}/changed.conf" "${changed_config}")
                string(REPLACE "provider.codex-extract.model = default"
                    "provider.codex-extract.model = another-model" wrong_route_config "${changed_config}")
                file(WRITE "${cell}/${terminal}/wrong-route.conf" "${wrong_route_config}")
                string(REPLACE "${case_config}" "${cell}/${terminal}/wrong-route.conf" cli "${original_reconcile_cli}")
                run_cli(error --access diagnose job reconcile "${job}" --item "${item}")
                if(NOT last_output MATCHES "original Codex provider route")
                    message(FATAL_ERROR "Reconciliation lost its original provider identity check: ${last_output}")
                endif()
                string(REPLACE "${case_config}" "${cell}/${terminal}/changed.conf" cli "${original_reconcile_cli}")
                execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite" .dump OUTPUT_VARIABLE before_inspect)
                run_cli(ok --access diagnose job reconcile "${job}" --item "${item}")
                string(JSON changed_digest GET "${last_output}" records 0 fields digest)
                if(NOT changed_digest STREQUAL reconcile_digest)
                    message(FATAL_ERROR "Unrelated configuration changed the retained observation digest")
                endif()
                execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite" .dump OUTPUT_VARIABLE after_inspect)
                if(NOT before_inspect STREQUAL after_inspect)
                    message(FATAL_ERROR "Reconciliation inspection changed durable state")
                endif()
            endif()
            if(NOT terminal MATCHES "^completed-(receipt|local)$")
                file(WRITE "${cell}/external-state" "inProgress\n")
                run_cli(error --access control job reconcile "${job}" --item "${item}" --apply --expect-digest "${reconcile_digest}")
                file(WRITE "${cell}/external-state" "${terminal}\n")
            endif()
            # A transaction failure must leave neither half a receipt nor usage.
            sql("CREATE TRIGGER reject_reconciliation BEFORE UPDATE ON job_items BEGIN SELECT RAISE(ABORT,'injected reconciliation failure'); END;" "")
            run_cli(error --access control job reconcile "${job}" --item "${item}" --apply --expect-digest "${reconcile_digest}")
            if(terminal STREQUAL "completed-receipt")
                sql("SELECT count(*) FROM job_events WHERE event_type IN('provider-response','provider-reconciled');" "1")
                sql("SELECT outcome FROM provider_runs;" "completed-unsettled")
            elseif(terminal STREQUAL "completed-local")
                sql("SELECT count(*) FROM job_events WHERE event_type IN('provider-response','provider-reconciled');" "0")
                sql("SELECT outcome FROM provider_runs;" "completed-unsettled")
            else()
                sql("SELECT count(*) FROM job_events WHERE event_type IN('provider-response','provider-reconciled');" "0")
                sql("SELECT outcome FROM provider_runs;" "running")
            endif()
            sql("DROP TRIGGER reject_reconciliation;" "")
            run_cli(ok --access control job reconcile "${job}" --item "${item}" --apply --expect-digest "${reconcile_digest}")
            run_cli(ok --access control job reconcile "${job}" --item "${item}" --apply --expect-digest "${reconcile_digest}")
            sql("SELECT count(*) FROM job_events WHERE event_type='provider-reconciled' AND json_extract(message,'$.usage_complete')=0;" "1")
            sql("SELECT count(*) FROM job_events WHERE event_type LIKE 'settlement-receipt:%';" "1")
            sql("SELECT input_tokens||':'||output_tokens FROM provider_runs;" "7:2")
            sql("SELECT count(*) FROM provider_runs;" "1")
            sql("SELECT state FROM jobs;" "paused")
            sql("SELECT reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns FROM jobs;" "0")
            if(terminal STREQUAL "interrupted" OR terminal STREQUAL "completed")
                sql("SELECT json_extract(message,'$.maximum_attempts') FROM job_events WHERE event_type='budget-policy';" "10")
                sql("SELECT state FROM job_items WHERE item_id='${item}';" "queued")
                # Reconciliation compatibility does not permit generation or
                # validation under a changed request configuration.
                run_cli(error --access control job run "${job}" --max-items 1 --poll-ms 20)
                sql("SELECT count(*) FROM attempts;" "1")
                sql("SELECT count(*) FROM provider_runs;" "1")
                set(cli "${original_reconcile_cli}")
            endif()
            if(terminal MATCHES "^completed")
                run_cli(ok --access control job run "${job}" --max-items 1 --poll-ms 20)
                sql("SELECT count(*) FROM job_items WHERE item_id='${item}' AND state IN('processed','skipped');" "1")
                sql("SELECT count(*) FROM provider_runs;" "1")
                if(terminal STREQUAL "completed-receipt")
                    sql("SELECT json_extract(message,'$.finish') FROM job_events WHERE event_type='provider-response';" "stop")
                endif()
            else()
                # The original attempt and job budget remain; the second call
                # is fenced separately and its disconnect is held separately.
                run_cli(error --access control job run "${job}" --max-items 1 --poll-ms 20)
                sql("SELECT count(*) FROM provider_runs;" "2")
                sql("SELECT count(*) FROM attempts;" "2")
            endif()
        endforeach()
        file(READ "${cell}/methods.log" methods)
        if(methods MATCHES "turn/interrupt")
            message(FATAL_ERROR "Inspection cancelled external work")
        endif()
    else()
        sql("SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state='processed';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='succeeded';" "1")
        sql("SELECT count(*) FROM attempts WHERE outcome='dead_letter';" "0")
        if(NOT last_errors MATCHES "sqlite=19" OR NOT last_errors MATCHES "extended=1811" OR
           NOT last_errors MATCHES "injected admission release failure")
            message(FATAL_ERROR "SQLite release diagnostics were lost: ${last_errors}")
        endif()
    endif()
endforeach()
message(STATUS "Worker recovery passed: bounded replacement, durable ceiling, preserved batch limit, no phantom calls, uncertain-turn hold, and saved-response publication after admission failure")
