# Native, zero-network recovery gates using the managed-process protocol fixture.
foreach(required_var CPRAG_NATIVE_APPLICATION CPRAG_CODEX_FIXTURE CPRAG_CONFIG_TEMPLATE CPRAG_WORK_DIR)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()
find_program(sqlite_cli sqlite3 REQUIRED)
file(REMOVE_RECURSE "${CPRAG_WORK_DIR}")
file(MAKE_DIRECTORY "${CPRAG_WORK_DIR}/source")
file(WRITE "${CPRAG_WORK_DIR}/source/architecture.txt"
    "BillingService depends on CustomerDatabase.\n"
    "Again, BillingService depends on CustomerDatabase.\n")
set(CPRAG_FIXTURE_SOURCE "${CPRAG_WORK_DIR}/source")
set(CPRAG_FIXTURE_PORT 1)
set(CPRAG_FIXTURE_GLOSSARY "${CPRAG_WORK_DIR}/glossary.tsv")
file(WRITE "${CPRAG_FIXTURE_GLOSSARY}"
    "format\tcrexx-rag.glossary/1\n"
    "concept\tBillingService\tapplication-component\tBilling Service\n"
    "concept\tCustomerDatabase\tdata-store\tCustomer DB\n")
file(READ "${CPRAG_CONFIG_TEMPLATE}" config)
string(CONFIGURE "${config}" config @ONLY)
string(REPLACE "provider.codex-extract.max_attempts = 2" "provider.codex-extract.max_attempts = 10" config "${config}")
string(APPEND config "\nworker.max_restarts = 2\nworker.restart_backoff_ms = 10\n")
file(WRITE "${CPRAG_WORK_DIR}/recovery.conf" "${config}")

function(run_cli expected)
    execute_process(COMMAND ${cli} ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 45)
    file(APPEND "${cell}/commands.log" "${ARGN}\nstatus=${status}\n${output}${errors}\n")
    if(NOT "${status}" MATCHES "^[0-9]+$")
        message(FATAL_ERROR "Recovery command did not terminate normally: ${status} ${errors}")
    endif()
    if(expected STREQUAL "ok" AND NOT status EQUAL 0)
        message(FATAL_ERROR "Recovery command failed: ${ARGN}\n${output}${errors}")
    elseif(expected STREQUAL "error" AND status EQUAL 0)
        message(FATAL_ERROR "Recovery command unexpectedly succeeded: ${ARGN}\n${output}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
    set(last_errors "${errors}" PARENT_SCOPE)
endfunction()

function(sql query expected)
    execute_process(COMMAND "${sqlite_cli}" "${library}/library.sqlite" "${query}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT status EQUAL 0 OR NOT output STREQUAL "${expected}")
        message(FATAL_ERROR "Recovery SQL assertion failed: ${query}\nExpected: ${expected}\nActual: ${output}\n${errors}")
    endif()
endfunction()

foreach(case IN ITEMS preflight-once preflight-always preflight-disabled turn-disconnect admission-release citation-feedback)
    set(cell "${CPRAG_WORK_DIR}/${case}")
    set(library "${cell}/library")
    file(MAKE_DIRECTORY "${cell}")
    set(wrapper "${cell}/codex-fixture.sh")
    file(WRITE "${wrapper}" "#!/bin/sh\nexec /bin/sh '${CPRAG_CODEX_FIXTURE}' \"\$@\"\n")
    file(CHMOD "${wrapper}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    set(failure_mode "${case}")
    set(case_config "${CPRAG_WORK_DIR}/recovery.conf")
    if(case STREQUAL "preflight-disabled")
        set(failure_mode preflight-always)
        string(REPLACE "worker.max_restarts = 2" "worker.max_restarts = 0" disabled_config "${config}")
        set(case_config "${cell}/recovery.conf")
        file(WRITE "${case_config}" "${disabled_config}")
    elseif(case STREQUAL "citation-feedback")
        string(REPLACE "budget.codex_turns = 1" "budget.codex_turns = 2" correction_config "${config}")
        string(REPLACE "budget.output_tokens = 1024" "budget.output_tokens = 8192" correction_config "${correction_config}")
        set(case_config "${cell}/recovery.conf")
        file(WRITE "${case_config}" "${correction_config}")
    endif()
    set(cli "${CMAKE_COMMAND}" -E env
        "CREXXRAG_CODEX=${wrapper}" "CREXXRAG_SELF=${CPRAG_NATIVE_APPLICATION}"
        "CREXXRAG_CODEX_FIXTURE_MODE=extraction" "CREXXRAG_CODEX_FIXTURE_FAILURE=${failure_mode}"
        "CREXXRAG_CODEX_FIXTURE_ONCE=${cell}/failed-once"
        "CREXXRAG_CODEX_FIXTURE_LOG=${cell}/methods.log"
        "${CPRAG_NATIVE_APPLICATION}" --library "${library}"
        --config-file "${case_config}" --profile it-architecture-profile
        --format json --progress plain)
    run_cli(ok --access admin library init)
    run_cli(ok --access plan ingest plan --source-set architecture-docs)
    string(JSON plan GET "${last_output}" records 0 fields canonical_plan)
    string(JSON digest GET "${last_output}" records 0 fields digest)
    run_cli(ok --access ingest ingest apply --plan-json "${plan}" --expect-digest "${digest}")
    string(JSON job GET "${last_output}" records 0 fields job_id)
    sql("UPDATE job_items SET priority=CASE item_type WHEN 'claim-extraction' THEN 200 ELSE 100 END,retry_at=CASE item_type WHEN 'embedding' THEN unixepoch()+3600 ELSE retry_at END;" "")
    if(case STREQUAL "admission-release")
        sql("CREATE TRIGGER fail_release BEFORE UPDATE ON provider_admissions WHEN NEW.outcome IN('succeeded','failed') BEGIN SELECT RAISE(ABORT,'injected admission release failure'); END;" "")
    endif()
    set(limit 0)
    set(expected error)
    if(case STREQUAL "preflight-once")
        set(limit 2)
        set(expected ok)
    elseif(case STREQUAL "citation-feedback")
        set(limit 1)
        set(expected ok)
    elseif(case STREQUAL "admission-release")
        set(limit 1)
    endif()
    run_cli(${expected} --access control worker start --count 1 --job "${job}" --max-items "${limit}" --poll-ms 20)
    sql("SELECT count(*) FROM attempts WHERE outcome='running';" "0")
    sql("SELECT reserved_calls+reserved_tokens+reserved_cost+reserved_codex_turns FROM jobs;" "0")
    if(case STREQUAL "preflight-once")
        if(NOT last_output MATCHES "\"workers_restarted\":1")
            message(FATAL_ERROR "Replacement was not reported: ${last_output}")
        endif()
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='succeeded';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='failed';" "0")
        sql("SELECT count(*) FROM attempts;" "2")
        sql("SELECT count(*) FROM job_items WHERE item_type='embedding' AND state='queued';" "1")
    elseif(case STREQUAL "preflight-always")
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "2")
        sql("SELECT count(*) FROM attempts;" "3")
        sql("SELECT count(*) FROM provider_runs;" "0")
        # A new controller and pruned runtime history cannot reset the job ceiling.
        sql("DELETE FROM runtime_instances;" "")
        run_cli(error --access control worker start --count 1 --job "${job}" --poll-ms 20)
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "2")
        sql("SELECT count(*) FROM attempts;" "4")
    elseif(case STREQUAL "citation-feedback")
        sql("SELECT count(*) FROM job_events WHERE event_type='citation-correction-requested' AND instr(message,'field=relationships[0].evidence_quote')>0 AND instr(message,'BillingService')>0 AND instr(message,'CustomerDatabase')>0;" "1")
        run_cli(ok --access control worker start --count 1 --job "${job}" --max-items 1 --poll-ms 20)
        sql("SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state='processed';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='failed';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='succeeded';" "1")
        sql("SELECT count(*) FROM job_events WHERE event_type='citation-correction-requested';" "1")
        file(READ "${cell}/methods.log" methods)
        if(NOT methods MATCHES "correction-feedback-checked")
            message(FATAL_ERROR "Correction did not receive precise feedback")
        endif()
    elseif(case STREQUAL "preflight-disabled")
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "0")
        sql("SELECT count(*) FROM attempts;" "1")
        sql("SELECT count(*) FROM provider_runs;" "0")
    elseif(case STREQUAL "turn-disconnect")
        sql("SELECT state FROM jobs;" "paused")
        sql("SELECT count(*) FROM job_events WHERE event_type='provider-outcome-uncertain';" "1")
        sql("SELECT count(*) FROM job_events WHERE event_type='worker-replacement';" "0")
        sql("SELECT count(*) FROM provider_runs WHERE external_turn_id='fixture-turn' AND outcome='running';" "1")
        sql("SELECT input_tokens||':'||output_tokens FROM provider_runs;" "7:2")
        # This paused corpus has no embeddings to publish; the command reports
        # that existing readiness gap without retrying the uncertain turn.
        run_cli(error --access control worker start --count 1 --job "${job}" --max-items 1 --poll-ms 20)
        sql("SELECT count(*) FROM provider_runs;" "1")
    else()
        sql("SELECT count(*) FROM job_items WHERE item_type='claim-extraction' AND state='processed';" "1")
        sql("SELECT count(*) FROM provider_runs WHERE outcome='succeeded';" "1")
        sql("SELECT count(*) FROM attempts WHERE outcome='dead_letter';" "0")
        if(NOT last_errors MATCHES "sqlite=19" OR NOT last_errors MATCHES "extended=1811" OR
           NOT last_errors MATCHES "injected admission release failure")
            message(FATAL_ERROR "SQLite release diagnostics were lost: ${last_errors}")
        endif()
    endif()
endforeach()
message(STATUS "Worker recovery passed: bounded replacement, durable ceiling, preserved batch limit, no phantom calls, uncertain-turn hold, and saved-response publication after admission failure")
